networkx/networkx

- .travis.yml
- networkx/readwrite/nx_shp.py
- networkx/readwrite/tests/test_shp.py
Remove xrange and map to make nx_shp tests work with python3.
Fixes #1227 
All changes to test_shp.py are for python3. 
All changes to nx_shp.py are to take advantage of "new" gdal/ogr iterator functionality for loops.
> Python3 tests fixed for nx_shp.py

- networkx/drawing/nx_pylab.py
This is an initial support for large verbose node labels.
> allow bbox parameter in draw_networkx_labels

- doc/source/developer/gitwash/following_latest.rst
- doc/source/developer/gitwash/forking_hell.rst
- doc/source/developer/gitwash/git_links.inc
- doc/source/developer/gitwash/git_resources.rst
First I only wanted to update and correct the steps listed on http://networkx.github.io/documentation/latest/developer/gitwash/following_latest.html, but then I saw that many links on http://networkx.github.io/documentation/latest/developer/gitwash/git_resources.html are also outdated. So I decided to clean that page and soft-redirect visitors to https://help.github.com/articles/what-are-other-good-resources-for-learning-git-and-github/ instead of listing outdated links.
> Update Git docs

- networkx/readwrite/json_graph/node_link.py
- networkx/readwrite/json_graph/tests/test_node_link.py
**Previously**
The `graph` attribute dictionary was previously split into a list of key-value pairs. This resulted in a counter-intuitive JSON representation with a structure that is different from the original `graph`-dict. The only upside was the ability to use numerical keys in the dictionary which is are not supported by JSON. This enabled a mapping of the following form:
G = nx.Graph()
G.graph[1] = 'val'
json_graph.node_link_graph(json_graph.node_link_data(G))[1] # numerical key preserved
**Now**
With the new approach the JSON representation matches the python dict and the note in the docstring now explains the new behavior.
G = nx.Graph()
G.graph[1] = 'val'
json_graph.node_link_graph(json_graph.node_link_data(G))['1'] # JSON has string-keys only
This pull request is a follow up on …
> node-link repr. contains graph dict 'as is'

- networkx/classes/tests/test_timing.py
This comments out the nosetests for timing base classes. Due to variation in travis test times we are getting too many false fails.  Addresses #1323.
Uncomment to use locally with nosetests. Or run the test script manually "python test_timing.py".
> Comment out timing nosetests due to variation in travis test times.

- networkx/convert_matrix.py
- networkx/tests/test_convert_numpy.py
- networkx/tests/test_convert_scipy.py
Adds the `parallel` keyword argument to the from_numpy_matrix()
function. If the adjacency matrix has integer entries, this is set to
`True`, and the `create_using` keyword argument is an instance of
`MultiGraph`, then each positive integer entry in the adjacency matrix
is interpreted as the number of parallel edges, each with weight 1,
joining two vertices. Otherwise, if any of these conditions is not met,
the function behaves as it previously did: an integer entry is
interpreted as the weight of a single edge joining the two vertices.
This is a backwards compatible change.
> Allows from_numpy_matrix to create parallel edges

- .travis.yml
This expands travis coverage back to what wheel used to provide.
See #1313 for brief discussion.
It seems that a mixture of conda and pip gives the best coverage now.
This attempt provides:
- coverage/coveralls for 2.7 and 3.4
- dependent packages testing for 2.7, 3.2, 3.3, 3.4
- no dep testing for 2.7,3.2,3.3,3.4,pypy,pypy3,ipy
> Shift travis to miniconda and pip mixture

- networkx/convert_matrix.py
- networkx/tests/test_convert_numpy.py
- networkx/tests/test_convert_scipy.py
Previously in `from_scipy_sparse_matrix()` and `from_numpy_matrix()`, if
`create_using` were an undirected multigraph and the input matrix were
symmetric, the edge (u, v) and the edge (v, u) would be added
separately, thereby resulting in two parallel edges. This change makes
the function behave more intelligently: it now assumes that when the
input matrix is symmetric and `create_using` is undirected, the edge (u,
v) should be added only once.
> Don't add edges twice when converting from numpy or scipy

- networkx/linalg/graphmatrix.py
Added a line documenting the (typical but not always used) convention that entry i,j corresponds to an edge from i to j. I couldn't find this documented elsewhere, and it is not clear from reading the code in to_scipy_sparse_matrix
> added documentation

- networkx/algorithms/tests/test_boundary.py
Instead of taking the min of 100 random samples of k nodes,
we now take the min of all possible samples of k nodes.
There's only 10 nodes so it is still very fast.
> Remove randomness from test_petersen to avoid fails

- networkx/convert_matrix.py
- networkx/tests/test_convert_numpy.py
- networkx/tests/test_convert_scipy.py
Adds the `parallel_edges` keyword argument to the `from_numpy_matrix`
and `from_scipy_sparse_matrix`. This allows the user to specify whether
to interpret an integer matrix as parallel edges in a multigraph or
single weighted edges in a multigraph.
This restores the default behavior of these functions that was changed
by pull request #1305.
> Allows explicit conversion with parallel edges

- doc/source/tutorial/tutorial.rst
- networkx/classes/digraph.py
- networkx/classes/graph.py
- networkx/classes/multidigraph.py
- networkx/classes/multigraph.py
- networkx/classes/tests/test_graph.py
This is one feature for the 2.0 API as discussed in #1246 
It change G.edges in a backward compatible way. 
For G.edges(data=data)
If data is True, the whole data dictionary is returned for each edge.
If data is False, no data is returned.
Otherwise data is used as the attribute name of the edge data to return.
The code
```[ (u,v,edata['weight']) for u,v,edata in G.edges(data=True) ]```
can become (either works)
```G.edges(data='weight')```
The code
for n,nbrs in G.adjacency_iter():
for nbr,ddict in nbrs.items():
print (n,nbr,ddict.get('weight',1))
can become (either works)
```G.edges(data='weight', default=1)```
> Expand data keyword in G.edges and add default keyword

- networkx/drawing/__init__.py
- networkx/drawing/nx_pydot.py
- networkx/drawing/tests/test_pydot.py
pydotplus is a replacement for pydot that works on Python 3. This PR uses pydotplus if pydot isn't available. Tests pass for me (Python 3.4, Windows 64-bit).
> Support pydotplus as a (Python 3 compatible) replacement for pydot

- networkx/classes/__init__.py
- networkx/classes/ordered.py
- networkx/classes/tests/test_ordered.py
For doctests (and perhaps unit tests as well---for example, unit tests for `edge_dfs` could actually be written properly), it might make more sense to use ordered graphs. This PR provides such graphs as part of the `networkx` API.
> Ordered graphs

- .travis.yml
This is a temporary measure to hide travis failures in pypy due to ordering.
#1351 is discussing actual fixes.
> Allow Failures in pypy tests until we sort things out ;)

- doc/source/reference/generators.rst
- networkx/generators/bipartite.py
- networkx/generators/classic.py
- networkx/generators/tests/test_bipartite.py
- networkx/generators/tests/test_classic.py
This commit reimplements `complete_bipartite_graph` using a generator
expression instead of two nested for loops. Also adds the `bipartite`
node attribute (that was missing, as per #1375).
I've also moved the `complete_bipartite_graph` function from `classic.py`
to `bipartite.py`. I think it's better to have all bipartite generators
together.
The function `complete_bipartite_graph` is used by other functions, such as
`wheel_graph`, which was abusing the interface by passing -1 as the second
argument of `complete_bipartite_graph` (for `wheel_graph(0)`) and hoping to
get an empty graph with zero nodes. This is also fixed.
> Refactor complete_bipartite_graph. Fixes #1375.

- networkx/algorithms/components/strongly_connected.py
The "copy" keyword argument was incorrectly placed in the Returns
section of the docstring. This moves it to the correct location, under
Parameters.
> Fix docstring for strongly_connected_components

- networkx/drawing/nx_pydot.py
pydot_ng is a another pydot fork
URL: https://pypi.python.org/pypi/pydot-ng
> Add pydot_ng as a supported pydot lib

- doc/source/reference/algorithms.connectivity.rst
- doc/source/reference/credits.rst
- networkx/algorithms/__init__.py
- networkx/algorithms/connectivity/__init__.py
- networkx/algorithms/connectivity/kcutsets.py
- networkx/algorithms/connectivity/tests/test_kcutsets.py
This PR implements Kanevsky's algorithm for all minimum-size separating
node sets in an undirected graph as a generator of node sets.
The most tricky thing about the implementation is that for reusing the
residual network and the auxiliary graph for node connectivity (which
is key for speed) we have to keep removing and adding edges to them
instead of regenerating both each time we have to modify the input
graph (the algorithm prescrives to add an edge each time we find
a node cutset to avoid finding it again).
This PR uses almost as is a function from SAGE (see `compute_antichains`),
maybe we should ask permission to it's author to include it given that SAGE
is GPL and we are BSD?
> Add all minimum-size k node cutsets algorithm.

- doc/source/reference/api_2.0.rst
- networkx/algorithms/approximation/__init__.py
- networkx/algorithms/approximation/connectivity.py
- networkx/algorithms/approximation/tests/test_connectivity.py
This PR adds White and Newman's fast approximation algorithm for
finding node independent paths between two nodes. It finds them by
computing their shortest path using BFS, marking the nodes of the path
found as used and then searching other shortest paths excluding the
nodes marked as used until no more paths exist. It is not exact because
a shortest path could use nodes that, if the path were longer, may belong
to two different node independent paths. Thus it only guarantees an
strict lower bound on node connectivity.
This implementation uses a modified version of `bidirectional_shortest_path`
that accepts the extra parameter `exclude`, which is a container for nodes
already used in other paths that should be ignored.
> Add fast approximation for node connectivity.

- .travis.yml
- fixcoverage.py
E.g., https://coveralls.io/files/556354222
IIRC, this was broken for a long time before being fixed and now broken again.
EDIT: Or rather partially broken. Works for https://coveralls.io/files/556379931.
> Coveralls cannot load source files

- networkx/testing/utils.py
Before, providing an empty list to `assert_nodes_equal` caused an
error. By removing this line, the function now correctly returns
``True`` if provided with an empty input list.
> Removes unused variable

- networkx/classes/graph.py
This was probably an accidental commit after developing the error condition checking that follows.
> Remove sys.stdout.write() in Graph.nbunch_iter()/bunch_iter()

- doc/source/reference/api_2.0.rst
- networkx/generators/classic.py
- networkx/generators/tests/test_classic.py
This pull request adds a simple function for generating [circulant graphs](http://mathworld.wolfram.com/CirculantGraph.html), where every vertex is connected to those vertices with labels ±*j* of its own label, for all *j* in some set of 'jumps' *J*. A unit test is included which checks some common cases where well-known circulant graphs (such as the complete and cycle graphs) are generated.
> Add generator function for circulant graphs

- doc/source/reference/algorithms.minors.rst
- doc/source/reference/algorithms.rst
- doc/source/reference/credits.rst
- networkx/algorithms/__init__.py
- networkx/algorithms/minors.py
- networkx/algorithms/tests/test_minors.py
The quotient graph of a graph `G` with respect to an equivalence
relation `R` on the nodes of `G` is the graph whose vertex set is the
equivalence classes of `R` and where there is an edge joining class `c` to
class `d` if the vertices in `c` are adjacent to the vertices in `d`.
This commit places that function in a new module,
`networkx/algorithms/minors.py`, for functions related to graph minors.
This is a generalization of some other functions already in NetworkX. For example, the [condensation][1] of a graph can be expressed as a quotient graph under the appropriate node and edge relations. You can see an example of this in one of the unit tests.
[1]: https://networkx.github.io/documentation/latest/reference/generated/networkx.algorithms.components.strongly_connected.condensation.html# …
> Adds function for computing a quotient graph.

- doc/source/reference/algorithms.simple_paths.rst
- doc/source/reference/api_2.0.rst
- doc/source/reference/credits.rst
- networkx/algorithms/simple_paths.py
- networkx/algorithms/tests/test_simple_paths.py
This function is based on Yen's algorithm for finding k shortest paths.
It generates all simple paths between source and target starting from
the shortest one. See #762 and #793 for prior work on this and discussion.
This implementation is based on Andrey's work on #762. It generalizes his
approach there to the weighted case, as in Greg's implementation posted
on #793.
Regarding the discussion on #762 about how to do the filtering of nodes
and edges efficiently, this PR adds private modifications of the functions
`bidirectional_shortest_path` and `bidirectional_dijkstra` (that accept
containers with nodes and edges to exclude during the SP search) for its
exclusive use.
This still needs work, especially on documentation and tests. I'm pushing
it so we can have the discussion with the code …
> Add shortest_simple_paths function.

- networkx/algorithms/richclub.py
- networkx/generators/geometric.py
- networkx/utils/misc.py
Python 3.2 introduces the `itertools.accumulate()`. Before, we were
using less flexible custom code for performing the same task, in
`networkx.utils.misc.cumulative_sum`. This commit replaces calls to
`cumulative_sum` with calls to `itertools.accumulate()`.
Since we currently still support Python 2.7, this commit adds a fallback
equivalent definition of accumulate that matches the Python 3.2
implementation. Once support for Python 2.7 is dropped, all of this code
can be removed, and calls to `networkx.utils.accumulate()` can be
replaced by calls to `itertools.accumulate()`.
This will also affect pull request #1425; if one is merged, the other should be updated.
> Replaces cumulative_sum with accumulate.

- doc/gh-pages.py
- doc/gitwash_dumper.py
- doc/make_examples_rst.py
- doc/make_gallery.py
I am using networkx library to hold a syntantic analysis of python source code and I noticed that you had some deprecated python statements (print and except for Python:v2.5) that could be easily solve.
The new syntaxt shouldn't change anything of the library but mainly for the documentation
Hope it helps ;)
> bug - use of deprecated syntax (print and except) fixed

- doc/source/reference/generators.rst
- networkx/generators/community.py
The `community` module was previously undocumented. This commit adds
documentation for the functions in this module.
This fixes  #1471.
This commit also updates some of the documentation to fix some errors.
> Documents the networkx.generators.community module

- networkx/algorithms/centrality/betweenness.py
There's another issue that I couldn't fix. The first occurrence of `\sigma(s, t)` after the formula does not render correctly.
> Fixes formula for edge betweenness centrality

- networkx/convert_matrix.py
https://github.com/networkx/networkx/issues/1423
> Fix doc for from_numpy_matrix and to_numpy_matrix

- networkx/algorithms/tests/test_link_prediction.py
- networkx/classes/function.py
This simplifies the code in `nx.non_edges` for undirected networks a bit. Performance comparison:
Old version:
In [18]: G =nx.random_regular_graph(5, 2000, seed=1)
In [19]: %timeit list(nx.non_edges(G))
1 loops, best of 3: 2.52 s per loop
New version:
In [10]: G = nx.random_regular_graph(5, 2000, seed=1)
In [11]: %timeit list(nx.non_edges(G))
1 loops, best of 3: 812 ms per loop
Since it doesn't keep a set of 'seen' edges, it probably uses less RAM (though I haven't checked).
> Simplify and speed up nx.non_edges

- doc/source/reference/algorithms.minors.rst
- doc/source/reference/api_2.0.rst
- networkx/algorithms/minors.py
- networkx/algorithms/tests/test_minors.py
This implements vertex and edge contraction as functions that return new
graph objects with the specified vertices or edge contracted.
This fixes issue #1057 (by creating entirely new code that I agree to license under NetworkX's BSD license).
This pull request needs some attention though.
1. I'm not sure how node attributes should be handled. Currently the code stores them in a dictionary on the contracted edge. Should they be dropped completely? Accordingly, there's an unimplemented test there.
2. Currently the code keeps the first vertex argument and removes the second argument. Should both vertices be removed and a new vertex created? How should it be named?
This pull request complements pull request #1437: if one is merged, the other needs to be rebased and merged, since they both …
> Adds vertex and edge contraction functions.

- doc/source/reference/api_2.0.rst
- doc/source/reference/credits.rst
- networkx/convert_matrix.py
- networkx/tests/test_convert_pandas.py
First PR, so let me say that NetworkX has been very useful in the past. Thanks!
I was looking at the dev docs and was happy to see that there is some work being done to handle Pandas DataFrames as inputs for graph creation (from_pandas_dataframe). Unfortunately (for me), the source looks to be a very thin wrapper around from_numpy_matrix. This doesn't work for the DataFrames I create, which are sparse and not square (Example below). This PR modifies from_pandas_dataframe in a way that accepts non-square DFs. What I've done is to create a generator function that takes a DataFrame and returns an [ebunch](http://networkx.github.io/documentation/development/reference/glossary.html#term-ebunch). The generator is passed to the `add_edges_from` constructor. This works fine for all shapes of …
> Modify from_pandas_dataframe to accept non-square inputs 

- doc/source/reference/utils.rst
Pull request #1463 removed the `cumulative_sum` function. This commit removes the reference to it in the documentation.
> Removes reference to nonexistent function

- networkx/generators/line.py
Cleans formatting and syntax for the `networkx.generators.line`
module. Also moves discussion of self-loops from module-level to
function-level.
> Cleans documentation for generators.line.

- networkx/algorithms/centrality/tests/test_katz_centrality.py
There was a random failure on TravisCI recently:
https://travis-ci.org/networkx/networkx/jobs/58959952
```
======================================================================
ERROR: test_katz_centrality.TestKatzEigenvectorVKatz.test_eigenvector_v_katz_random
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/travis/miniconda/envs/test-environment/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
self.test(*self.arg)
File "/home/travis/miniconda/envs/test-environment/lib/python3.4/site-packages/networkx/algorithms/centrality/tests/test_katz_centrality.py", line 322, in test_eigenvector_v_katz_random
k = networkx.katz_centrality_numpy(G, 1.0/l)
File "<string>", line 2, in katz_centrality_numpy
File …
```
> Fix unit test for katz centrality.

- networkx/algorithms/assortativity/connectivity.py
Just a simple formatting fix and also some pep8 formatting.
BTW I was wondering how much of pep8 does networkx follows? I find a lot of pep8 errors in the codebase here and then. I was wondering if pep8 is compromised a little. I would love to get some feedback.
> average_degree_connectivity formatting fix.

- doc/source/reference/algorithms.shortest_paths.rst
- doc/source/reference/api_2.0.rst
- networkx/algorithms/shortest_paths/tests/test_weighted.py
- networkx/algorithms/shortest_paths/weighted.py
Johnson's algorithm is one more algorithm for the shortest paths.
This algorithm solves all pairs shortest paths, and may be faster than Floyd–Warshall on sparse graphs.
For this reason, this pull request adds __johnson()__ which implements the main algorithm.
The ___reweight_graph_johnson()__ and ___add_node_johnson()__ are parts of the algorithm.
> Adds Johnson's algorithm for computing all pairs shortest paths

- doc/source/reference/api_2.0.rst
- networkx/algorithms/connectivity/kcutsets.py
- networkx/algorithms/connectivity/tests/test_kcutsets.py
I merged #1391 in a bit of a rush to be able to push #1414. This PR is for finishing up the last details. So far it makes `all_node_cuts` use the recently exposed `nx.antichains` function from #1413, and adds `all_node_cuts` to `api_2.0.rst`.
I also want to investigate a bit more a failed test for non repeated cuts in the pypy Travis CI (which is allowed to fail):
https://travis-ci.org/networkx/networkx/jobs/55252872#L2829
I think that it does not have to do with hash randomization, as most of the other failures there. However I cannot reproduce it in my machine (pypy 2.2.1 linux 64bit). So I added a bit of debug to that test to try to see what is going on. Also we saw a strange frailure only one time in a `pypy3` environment in another test: `test_kcutsets.test_configuration_model`. I …
> all_node_cuts wrap up

- networkx/algorithms/bipartite/redundancy.py
- networkx/algorithms/bipartite/tests/test_redundancy.py
Cleans and updates the documentation for the
`networkx.algorithms.bipartite.redundancy` module, and creates a
corresponding test module.
Also simplifies the code for computing the node redundancy.
I did some (minimal) timing tests, and this appears to be about the same as the previous code.
> Cleans docs and simplifies bipartite.redundancy

- networkx/readwrite/nx_shp.py
- networkx/readwrite/tests/test_shp.py
I needed the segments of multi-segment line features to be added as edges, so I added a simplify parameter to read_shp (defaults to True so it's back compatible).  A caveat is that attributes associated with the feature are repeated for each segment.  Thought someone else might find this useful.
> parameterize simplification of line features in read_shp

- doc/source/reference/api_2.0.rst
- networkx/algorithms/components/attracting.py
- networkx/algorithms/components/biconnected.py
- networkx/algorithms/components/connected.py
- networkx/algorithms/components/strongly_connected.py
- networkx/algorithms/components/tests/test_attracting.py
- networkx/algorithms/components/tests/test_biconnected.py
- networkx/algorithms/components/tests/test_connected.py
- networkx/algorithms/components/tests/test_strongly_connected.py
- networkx/algorithms/components/tests/test_subgraph_copies.py
- networkx/algorithms/components/tests/test_weakly_connected.py
- networkx/algorithms/components/weakly_connected.py
- networkx/algorithms/cycles.py
Use a plain BFS to compute connected components instead of using the single source shortest path function. The latter also does a BFS but keeps track of the distances. This is only slightly faster (around 5% in my tests), but I think it's conceptually better. As @ysitu said, we have a tendency to abuse shortest paths functions for reachability.
This came out while working on #1414 and trying to speed up the set consolidation function, that uses connected_components.
Also, following @jfinkels example (great work!), I've cleaned up the `biconnected.py` docstrings and code, and improved the examples showing how to use `max` to get the largest [bi]connected component.
Another thing that I'm not sure if we should change now is that there is an inconsistency between `connected_components` and …
> Refactor connected components

- networkx/relabel.py
- networkx/tests/test_relabel.py
Fixes #1593 relabel_nodes(copy=False) bug removed an isolated node when relabeled to itself.
Fix is that any node relabeled to itself is simply skipped in the relabeling.
> Fixes issue #1539 Bug in relabel_nodes for isolated nodes

- doc/source/reference/algorithms.connectivity.rst
- doc/source/reference/api_1.10.rst
- networkx/algorithms/__init__.py
- networkx/algorithms/connectivity/__init__.py
- networkx/algorithms/connectivity/kcomponents.py
- networkx/algorithms/connectivity/tests/test_kcomponents.py
Add Moody and White algorithm for for identifying k-components in a graph,
which is based on Kanevsky's algorithm for finding all minimum-size node
cut-sets (implemented in `all_node_cuts` function #1391). This algorithm
consists in keep cutting a graph until we obtain either a complete or a
trivial graph.
`all_node_cuts` is doing most of the work here, the only tricky
implementation thing is the generation of partitions. The authors say that
``Nodes in a cutset belong to both sides of the induced cut.'', but an
induced cut can split a graph in more than two sides. Thus, after a cut,
we have to merge the node sets that (after adding the nodes in the cut set)
share at least k nodes.
I found out that this is very related to set consolidation. I've adapted a
nice function from …
> Add k-(node)-components algorithm.

- doc/source/reference/algorithms.approximation.rst
- doc/source/reference/api_1.10.rst
- examples/subclass/antigraph.py
- networkx/algorithms/approximation/__init__.py
- networkx/algorithms/approximation/kcomponents.py
- networkx/algorithms/approximation/tests/test_connectivity.py
- networkx/algorithms/approximation/tests/test_kcomponents.py
This is an approximation approach to compute the k-component structure
of a graph (#1414 is the exact, and slow, version of this). I wrote a
paper to explore this approach in detail, see http://arxiv.org/abs/1503.04476
The logic of the approximation algorithm for computing the `k`-component
structure is based on repeatedly applying simple and fast algorithms
for `k`-cores and biconnected components in order to narrow down the
number of pairs of nodes over which we have to compute White and Newman's
approximation algorithm for finding node independent paths (implemented at #1405).
More formally, this algorithm is based on Whitney's theorem, which states
an inclusion relation among node connectivity, edge connectivity, and
minimum degree for any graph G. This theorem implies that every …
> Add fast approximation for k-(node)-components.

- networkx/algorithms/approximation/dominating_set.py
- networkx/algorithms/approximation/tests/test_dominating_set.py
Before, the greedy algorithm for approximate dominating set chose each
node based on the sum of the weights in the closed neighborhood of the
node. Now it just uses the weight of the node. This fixes an issue that
causes, for example, the return value for a star graph to be all nodes
other than the center node.
Fixes issue #1527.
> Fixes approximate dominating set greedy choice.

- README.rst
- doc/make_examples_rst.py
- doc/make_gallery.py
- doc/requirements.txt
- doc/source/conf.py
This PR allows ReadTheDocs to build our documentation. They will be available here: https://networkx.readthedocs.org/en/latest/ once this is merged. After that, we will need to update networkx-website accordingly. There are also a number of places we need to cleanup the documentation, but that is another PR.
> Build documentation on ReadTheDocs

- networkx/classes/digraph.py
- networkx/classes/multidigraph.py
- networkx/classes/tests/test_digraph.py
- networkx/classes/tests/test_multidigraph.py
digraph.degree( iter([0]) ) doesn't work because the iterator is used twice. 
Bug introduced in 2010 during conversion for python3.
This PR also adds tests for this same bug.
> Fix bug for iterator input for digraph.degree

- .travis.yml
Turning off coverage for the pypy tests reduces time from 50 minutes to about 5 minutes.
> Turn off coverage for pypy travis tests

- networkx/readwrite/adjlist.py
- networkx/readwrite/multiline_adjlist.py
#1604 
Also fixes pep8 and uses the newer str.format.
> Docstring fix for adjlist and multiline_adjlist.

- networkx/algorithms/approximation/clique.py
- networkx/algorithms/approximation/tests/test_clique.py
Before, the maximum clique was chosen from a set of candidate cliques
according to the subset ordering on sets. This commit changes the code
to choose the maximum clique according to clique size.
This pull request supercedes #1531.
> Find maximum clique by cardinality.

- networkx/addons/__init__.py
- setup.py
This allows various addons to be installed for networkx inside `networkx.addons` namespace. We can discuss whether we have to take this in with `1.10` or `2.0`.
> Allow external packages to be installed in networkx.addons

- networkx/algorithms/dag.py
- networkx/algorithms/tests/test_dag.py
If G has edges with 'weight' attribute the edge data are used as weight values.
> dag_longest_path: Use edge weights

- networkx/algorithms/approximation/tests/test_kcomponents.py
See #1637 for debugging efforts. So far we cannot reproduce it locally.
> Remove a test that only fails sporadically on Travis for k_components approximation.

- networkx/algorithms/richclub.py
- networkx/classes/graph.py
- networkx/classes/multigraph.py
- networkx/classes/tests/test_graph.py
- networkx/classes/tests/test_multigraph.py
- networkx/convert_matrix.py
This PR updates the methods `nodes_with_selfloops`, `selfloop_edges`, `number_of_selfloops` in `network/classes/graph.py` and `network/classes/multigraph.py`. These functions now return an iterator instead of lists.
> Make selfloop methods return iterator instead of list in graph class

- networkx/addons/__init__.py
- setup.py
Reverts networkx/networkx#1595
This now deletes `networkx.addons` namespace and leaves users with the option to import the addons directly from their own packages, e.g. `nxmetis`, `nxlemon`, `nxmatplotlib`.
Flask recommends users to import addons from `flask.ext`, we could also do that. In that case we'll need changes in this PR.
As of now, I've not been able to think the difference between two, so it's all about the design and our choice.
> Revert "Allow external packages to be installed in networkx.addons"

- networkx/algorithms/approximation/tests/test_kcomponents.py
This algorithm is based on a node connectivity approximation that only
guarantees a lower bound for node connectivity. Even though some tests only
fail sporadically in Travis, and we cannot reproduce them, it's better to just
remove the problematic tests based on random graphs. Those tests were designed
for the exact implementation of the algorithm in `connectivity/kcomponents.py`.
> Remove some tests for k_components approximation.

- networkx/algorithms/approximation/ramsey.py
- networkx/algorithms/cluster.py
- networkx/algorithms/components/connected.py
- networkx/algorithms/connectivity/connectivity.py
- networkx/algorithms/connectivity/stoerwagner.py
- networkx/algorithms/dag.py
- networkx/algorithms/euler.py
- networkx/algorithms/flow/capacityscaling.py
- networkx/algorithms/flow/preflowpush.py
- networkx/algorithms/minors.py
- networkx/algorithms/tests/test_minors.py
- networkx/algorithms/tests/test_simple_paths.py
- networkx/generators/degree_seq.py
- networkx/utils/misc.py
- networkx/utils/rcm.py
As of the date of this commit, there is no way to get an arbitrary
element of an iterable like a set without modifying it (for example, as
in `set.pop()`). The `peek()` function is more readable than writing
next(iter(S))
whenever an arbitrary element of an iterable is required.
This commit also makes a couple of PEP8 changes, but not many.
> Use peek(S) instead of next(iter(S)).

- networkx/algorithms/approximation/tests/test_kcomponents.py
- networkx/release.py
Cherry pick the two commits that remove tests based on random graphs for k-components approximation to the v1.10 branch. Those tests were failing sporadically on Travis and we were not able to reproduce them outside Travis. Since this algorithm is an approximation, and the removed tests were designed for the exact implementation at `connectivity.kcomponents.py`, it is better to just remove them for the approximation version of the algorithm.
Is there any other change that we need to add to the v1.10 branch before releasing it?
> Release 1.10

- .travis.yml
Travis-CI still uses 6.x version of pip. However, pip 7.0.0 and later cache installed packages automatically in the form of wheels. Subsequent installs are therefore much faster which results in decrease of the total installation time.
> Upgrade pip for cache installation

- networkx/algorithms/coloring/greedy_coloring.py
- networkx/algorithms/coloring/tests/test_coloring.py
I like the new ``greedy_color()`` algorithm, but passing strategy functions directly is inconvenient. This PR adds the ability to specify strategies as strings, and is entirely backward-compatible.
Here is an example:
```python
>>> colors1 = nx.coloring.greedy_color(G, strategy=nx.coloring.strategy_connected_sequential)
>>> colors2 = nx.coloring.greedy_color(G, strategy='connected_sequential')
>>> colors1 == colors2
True
```
This also helps improve the inline documentation:
Old documentation:
```python
>>> help(nx.coloring.greedy_color)
...
greedy_color(G, strategy=<function networkx.algorithms.coloring.greedy_coloring.strategy_largest_first>, interchange=False)
...
```
New documentation:
```python
>>> help(nx.coloring.greedy_color)
...
greedy_color(G, strategy='largest_first', …
```
> ENH: allow greedy_color strategies to be specified as strings

- appveyor.yml
- appveyor/install.ps1
- appveyor/run_with_env.cmd
Fix #1650 
This PR adds necessary files for starting CI based builds over [AppVeyor](https://ci.appveyor.com). AppVeyor helps ensure that the code is *really* OS independent by testing it over a Windows based platform.
> Activate Appveyor-CI

- networkx/convert.py
- networkx/tests/test_convert.py
In convert.to_networkx_graph, we are overwriting instead of 
updating the node dict.  We just need to update the existing dict.
Fixes #1718
> to_networkx_graph needs .update() instead of new dict

- networkx/algorithms/centrality/eigenvector.py
- networkx/algorithms/centrality/tests/test_eigenvector_centrality.py
By computing eigenvectors with repeated multiplication by A+I
the spectrum is shifted so that the positive real eigenvalue
is dominant even for odd path graphs and others with multiple
dominant eigenvalues. Fixes #1704
> Eigenvector_centrality power method shifted to A+I

- networkx/algorithms/connectivity/tests/test_cuts.py
Replaces indexing with `arbitrary_element()` function.
This issue caused a build error in https://travis-ci.org/networkx/networkx/jobs/74853743, a build for pull request #1729.
> Don't use indexing to access elements of a set

- networkx/algorithms/operators/binary.py
- networkx/algorithms/operators/tests/test_binary.py
compose func merge edges data
e.g. R=compose(G,H)
G.edge = 2: {3: {'p_b': 1}
H.edge = 2: {3: {'s_b': 2}
R.edge = 2: {3: {'p_b': 1, 's_b': 2}
, but not for nodes
G.node = 3: {'p_b': 1}
H.node = 3: {'s_b': 2}
R.node = 3: {'s_b': 2} # 'p_b' missed
> merge data of G and H instead replace

- networkx/algorithms/dag.py
This change adds the node identifier to exception message produced when
a cycle is detected during a topological sort.
Signed-off-by: Eden G. Adogla <eden@edengrail.io>
> dag: add more information to exception message when cycle detected

- networkx/readwrite/nx_shp.py
- networkx/readwrite/tests/test_shp.py
Thought some other networkx might need this (there are definitely shapefiles out there with MultiLineStrings).  
I also added a geom_attrs param to disable appending the geometry as attributes of the edge (since I may edit the underlying nodes, this info can get out of sync).  
Tests for the new features are included.
> Needed MultiLineString support in reading Graph from shapefile

- doc/source/reference/algorithms.dag.rst
- networkx/algorithms/components/semiconnected.py
- networkx/algorithms/dag.py
- networkx/algorithms/tests/test_dag.py
- networkx/relabel.py
- networkx/utils/misc.py
Rewrote topolgical_sort as a generator:
* It no longer accepts reverse or nbunch arguments
* It is slightly faster.
Added lexicographical_topological_sort, which accepts a key.
Some tests for topological sort were removed because they relied on
CPython's particular dict element ordering.
Added utils from more_itertools:
* These were necessary for working with the new generators.
* "pairwise" is equavalent to zip(some_list, some_list[1:]) -- for generators.
* "consume" consumes an iterator.
> topolgical_sort, lexicographical_topological_sort

- networkx/generators/stochastic.py
- networkx/generators/tests/test_stochastic.py
This commit allows the `stochastic_graph` generator to operate on
`MultiDiGraph` instances. It also adds some missing unit tests.
> Makes stochastic_graph work for multigraphs.

- networkx/classes/graph.py
Instead of :
```
'dict' objects are unhashableTraceback (most recent call last):
File "<builtin>/app_main.py", line 75, in run_toplevel
File "mk_graph_file.py", line 34, in <module>
if d['weight'] > 3])
File "/usr/local/lib/pypy2.7/dist-packages/networkx/classes/graph.py", line 1488, in subgraph
for n in bunch:
File "/usr/local/lib/pypy2.7/dist-packages/networkx/classes/graph.py", line 1815, in bunch_iter
"Node %s in the sequence nbunch is not a valid node."%n)
TypeError: not all arguments converted during string formatting
```
You get:
```
'dict' objects are unhashableTraceback (most recent call last):
File "<builtin>/app_main.py", line 75, in run_toplevel
File "mk_graph_file.py", line 34, in <module>
if d['weight'] > 3])
File "/usr/local/lib/pypy2.7/dist-packages/networkx/classes/graph.p …
```
> Fix, now raise NetworkXError instead of TypeError

- doc/requirements.txt
The stable branch of sphinx has the one-line fix for autosummary.
So even though the release on pypi doesn't have it, we can get it from github.
Fixes #1796 without creating our own fork of sphinx.
When sphinx 1.4 comes out we can switch back to using the pypi version.
> Use sphinx stable branch via github on ReadTheDocs

- networkx/generators/degree_seq.py
Changes the error message when a degree sequence with an odd sum is
provided to the `configuration_model` function so that it indicates that
the user must provide a degree sequence with an even sum.
This fixes issue #1800.
> Clarifies error message in configuration_model

- networkx/algorithms/distance_measures.py
Changes the error message when an infinite path length is encountered so
that it is different based on whether the graph is directed or not.
Fixes issue #1803.
> Clarifies error message in eccentricity

- networkx/algorithms/tests/test_distance_measures.py
For #1820, this is to be first merged in `error-message-eccentricity` branch.
> add test for error message in eccentricity function

- networkx/readwrite/graphml.py
- networkx/readwrite/tests/test_graphml.py
Fixes #1487
This addresses the issue of the GraphML writer creating separate
attribute tags for named data with different numeric types.
This does everything in "one pass" by keeping the values it's encountered for a ```name``` **and** ```scope```, and generalizing at the end. Doing so is noted [here](https://github.com/networkx/networkx/compare/master...danlamanna:fix-graphml-properties-1487?expand=1#diff-aca9577a5a85cf350216d863b25cf1d6R271) and was a judgment call by me, let me know what you think.
> Allow GraphML to infer numeric types

- networkx/algorithms/isomorphism/matchhelpers.py
- networkx/algorithms/isomorphism/tests/test_match_helpers.py
a and b - nodes
they has attr: x, y, z
if a attr = {x:1, y: 1, z: 2}
and b attr = {x:1, y: 2, z: 2}
match return True. It's wrong.
> fix comparison error in categorical_node|edge_match.

- networkx/algorithms/cycles.py
This makes the doc describe the actual (and intended) behaviour.
> Update doc for find_cycle() to properly describe no-cycle behaviour. Fixes #1832.

- networkx/algorithms/approximation/clique.py
- networkx/algorithms/coloring/greedy_coloring.py
- networkx/algorithms/community/centrality.py
- networkx/algorithms/connectivity/kcutsets.py
- networkx/algorithms/richclub.py
- networkx/classes/graph.py
- networkx/classes/tests/test_graph.py
Adds the `with_data` keyword argument to the `Graph.copy()` method,
which specifies whether the graph, node, and edge data will be included
in the copy of the graph object.
This commit also updates algorithms that include a call to
`Graph.copy()` to use `with_data=False` if they really do not need a
copy of the data.
This should theoretically allow both our algorithms and user algorithms to save some memory when copies of large graphs are made.
> Allows copying a graph without attribute data.

- networkx/algorithms/bipartite/tests/test_edgelist.py
- networkx/algorithms/isolate.py
- networkx/algorithms/tests/test_isolate.py
- networkx/readwrite/tests/test_edgelist.py
This commit makes several changes to the `networkx.algorithms.isolate`
module. It
- updates and clarifies docstrings,
- makes PEP8 fixes,
- changes `isolates()` to return an iterator instead of a list,
- adds a `number_of_isolates()` function,
- adds a new unit test module, `test_isolate.py`.
With this new `number_of_isolates()` function, pull request #1831 could be simplified.
> Adds number_of_isolates function and updates docs.

- networkx/generators/classic.py
- networkx/generators/tests/test_classic.py
Previously, the `balanced_tree` generator function always returned a
path graph on two nodes instead of a path graph of the appropriate
length when provided a branching factor of one. This corrects that error
so the function now returns the path graph on `h + 1` nodes, where `h`
is the specified height of the tree, when the branching factor is one.
> Makes balanced unary tree generator return path.

- doc/source/reference/generators.rst
- networkx/algorithms/triads.py
- networkx/generators/__init__.py
- networkx/generators/tests/test_triads.py
- networkx/generators/triads.py
Previously, the `triad_graphs` function in the
`networkx.algorithms.triads` module, returned a dictionary containing a
graph representing each possible triad. This commit moves that function
to a new module, `networkx.generators.triads`, and adds previously
missing test code for that function. It also modifies the function to
return a single graph instead of a dictionary of graphs. The dictionary
can now be generated by the code
from networkx.algorithms.triads import TRIAD_NAMES
triad_graphs = {name: triad_graph(name) for name in TRIAD_NAMES}
This commit should improve test coverage.
> Moves triad_graph function to generators package.

- doc/source/reference/algorithms.wiener.rst
- networkx/algorithms/__init__.py
- networkx/algorithms/tests/test_vitality.py
- networkx/algorithms/tests/test_wiener.py
- networkx/algorithms/vitality.py
- networkx/algorithms/wiener.py
Previously, the closeness vitality function was using an incorrect
definition of the Wiener index, counting each orientation of a pair of
nodes in an undirected graph twice. This commit corrects the behavior of
the Wiener index function and therefore the closeness vitality function.
Correcting the Wiener index function also corrects another case for the
closeness vitality function: when removing a node causes a graph to
become disconnected. By definition, the closeness vitality of a node
whose removal causes the graph to become disconnected should be negative
infinity. This commit fixes the Wiener index function to return positive
infinity on a disconnected graph.
Furthermore, this commit improves the closeness vitality function so
that it does not mutate the graph in order to compute the …
> Fixes and extends Wiener index, vitality functions

- README.rst
A IRC channel has been made where discussion can be performed
about networkx, using the popular opensource freenode servers
so it might as well be mentioned in the README.rst so people
can find it as needed.
https://freenode.net/
> Add IRC channel to README.rst

- networkx/algorithms/tree/mst.py
- networkx/algorithms/tree/tests/test_mst.py
Before, the `minimum_spanning_edges()` function returned edges without
edge keys for multigraphs. This commit enables the user to choose to
return edge keys in addition to edges in a multigraph.
This can potentially be used in pull request #1538.
> Return minimum spanning edge keys for multigraphs

- networkx/algorithms/centrality/harmonic.py
If the graph has one or zero nodes, the overhead for calling the shortest-path algorithms will be small. This slight increase in overhead is worth the decrease in the complexity of the code.
> Removes unnecessary code in harmonic centrality.

- networkx/algorithms/clique.py
- networkx/algorithms/tests/test_clique.py
This commit makes several updates to networkx/algorithms/clique.py,
including
- removing some unnecessary arguments to the functions,
- updates documentation strings,
- removes the local `project_up` and `project_down` functions, which
were duplicating the bipartite projection functions
- sets the node attributes of the bipartite clique graph in the same way
as the bipartite generator functions (that is, setting the `bipartite`
node attribute to be 0 for the "top" nodes and 1 for the "bottom"
nodes).
Since the signature of these functions has changed, this is not a
backwards-compatible change.
> Cleans make_max_clique_graph, make_clique_bipartite

- networkx/algorithms/__init__.py
- networkx/algorithms/approximation/__init__.py
This submodule is not accessible when one imports networkX with `import networkx as nx`.
Is there a particular reason *not* to import this submodule with the rest of the package?
> Add approximation import

- doc/source/reference/generators.rst
- networkx/generators/random_graphs.py
- networkx/generators/tests/test_random_graphs.py
This adds a generator of random graphs with a specified kernel.   Random graphs based on kernels are designed to produce  graphs with the number of edges scaling linearly with the number of nodes. They are especially interesting because many graph properties can be analyzed.  See http://arxiv.org/abs/math/0504589
This algorithm is a fast way to sample random instances from this model.  A simple test and example to generate a G(n,p) graph using a kernel are provided.
The method is detailed in the (currently unpublished) paper, 'Fast generation of random kernel graphs', Aric Hagberg and Nathan Lemons, 2015.  I'll update the reference with (pre)publication info when available.
> Add random kernel graph generator

- networkx/classes/graph.py
- networkx/classes/tests/test_graph.py
This is now consistent with the behaviour of the data parameter of `G.edges()`. We can interact in the same way and get an iterator over (nodes, value of attribute) by `G.nodes(data='attribute')`.
``` python
>>> G = nx.Graph()
>>> G.add_nodes_from([0, 1 ,2])
>>> G.add_node(1, time='5pm')
>>> G.node[0]['foo'] = 'bar'
>>> list(G.nodes(data=True))
[(0, {'foo': 'bar'}), (1, {'time': '5pm'}), (2, {})]
>>> list(G.nodes(data='foo'))
[(0, 'bar'), (1, None), (2, None)]
>>> list(G.nodes(data='time'))
[(0, None), (1, '5pm'), (2, None)]
>>> list(G.nodes(data='time', default='Not Available'))
[(0, 'Not Available'), (1, '5pm'), (2, 'Not Available')]
```
> add option to view specific attributes in G.nodes()

- .gitignore
- doc/source/reference/credits.rst
- networkx/algorithms/shortest_paths/weighted.py
I found that the function dijkstra_path_length() run the function single_source_dijkstra_path_length() that does a one-to-all path length computation. Given that this function knows the target upfront, a one-to-once-found is more computationally efficient.
> Changed function dijkstra_path_length() to finish once target path length has been found

- .travis.yml
- networkx/drawing/nx_pydot.py
- networkx/drawing/tests/test_pydot.py
- change to "import pydotplus as pydot"; remove flexible import cruft
- remove encode("utf-8") in pydot_layout node names
- in tests: sort edges for undirected 2-tuples
- in travis.yml: pip install from tar.gz for python3.3 (pip couldn't find)
> Use pydotplus for all supported python versions

- networkx/algorithms/matching.py
- networkx/algorithms/tests/test_matching.py
1. Fixes [#1736](https://github.com/networkx/networkx/issues/1736)
2. Added test
Self Loops should not be included in maximal matching because it **contradictions** the definition  mentioned in documentation which is:-
A [matching](https://networkx.github.io/documentation/latest/reference/generated/networkx.algorithms.matching.maximal_matching.html) is a subset of edges in which **no node occurs more than once**.The cardinality of a matching is the number of matched edges.
> Exclude self-loops from maximal matching

- networkx/drawing/layout.py
- networkx/drawing/tests/test_layout.py
_rescale_layout was dividing by zero for single shells.
Add tests.
> Fix layout for single node graphs and shells

- networkx/generators/directed.py
By using true division, we can avoid casting to floats entirely.
As discussed in pull request #1877.
> Removes unnecessary cast to float.

- .travis.yml
- doc/source/reference/api_1.11.rst
- doc/source/reference/news.rst
- networkx/drawing/nx_pydot.py
- networkx/drawing/tests/test_pydot.py
Use pydotplus for all supported python versions
- change to "import pydotplus"; remove flexible import cruft
- remove encode("utf-8") in pydot_layout node names
- in tests: sort edges for undirected 2-tuples
- in travis.yml: pip install from tar.gz for python3.3 (pip couldn't find)
- use assert_graphs_equal in tests
- fix from_pydot to no longer create attributes 'name', 'graph', 'node' and 'edge' with value ''
> Use pydotplus for v1.11

- networkx/algorithms/bipartite/generators.py
- networkx/algorithms/bipartite/tests/test_generators.py
- networkx/generators/classic.py
- networkx/generators/geometric.py
- networkx/generators/tests/test_classic.py
- networkx/generators/tests/test_geometric.py
- networkx/utils/decorators.py
Create decorator ```@nodes_or_number(which_args)``` which replaces the arguments numbered by ```which_args``` with a 2-tuple ```(n_name, nodes)``` where ```n_name``` is the original argument value and ```nodes``` is the resulting list of nodes.  ```which_args``` can be a positive integer or a list of positive integers. The integers point to which argument includes the nodes. Keyword identity is not needed for any of the use_cases I have run into.
The reason for the 2-tuple is so that ```G.name``` can include the original call signature. Also, ```star_graph(9)``` has 10 nodes in it while ```star_graph(range(9))``` has 9 nodes. So that particular function needs to know how it was actually called. 
Implemented for ```empty_graph``` in first commit and then many others in the next two …
> Overload graph generators to allow nodes or numbers

- networkx/algorithms/approximation/ramsey.py
- networkx/algorithms/approximation/tests/test_clique.py
Before, the maximum clique and maximum independent set were chosen from
a collection of candidates according to the subset ordering on
sets. This commit changes the code to choose the maximum clique and
maximum independent set according to cardinality of the sets.
This pull request supercedes #1532.
There is a problem with this change: it affects one of the unit tests for the clique removal function. The unit test expects cliques to be of size greater than one, but now the function returns, among others, a clique of size one.
> Find max clique and independent set by cardinality

- networkx/generators/__init__.py
- networkx/generators/duplication.py
- networkx/generators/random_graphs.py
- networkx/generators/tests/test_duplication.py
- networkx/generators/tests/test_random_graphs.py
This commit adds the `partial_duplication_graph` generator function in a
new module `networkx.generators.duplication`. It also moves the
`duplication_divergence_graph` function from the `random_graphs` module
to the `duplication` module.
Fixes issue #1368.
> Adds partial_duplication_graph generator.

- networkx/algorithms/shortest_paths/generic.py
- networkx/algorithms/shortest_paths/tests/test_generic.py
This commit updates the `average_shortest_path_length` function to
return zero for the trivial graph (the graph with a single node).
This fixes issue #1960, if my understanding of Google's machine translation of the original Chinese text is correct.
> Returns 0 for average path length of trivial graph

- networkx/classes/graph.py
- networkx/classes/tests/test_graph.py
providing one style of shallow copies
with other styles described in the docstrings
Addresses #1916 and supercedes #1917 also related to #1876
> provides with_data options for shallow copies in G.copy

- networkx/testing/tests/test_utils.py
- networkx/testing/utils.py
Removes sorting requirement for nodes and edges in test for comparison.  This way builds dictionaries and compares the dictionaries.  Possibly not the most efficient way to do it but correct? Needs review @dschult?
Addresses #1911
> Remove sorting from assert_nodes_equal, assert_edges_equal

- networkx/generators/directed.py
- networkx/generators/tests/test_directed.py
This commit adds the `random_uniform_k_out_graph` generator to
complement the `random_k_out_graph` generator. The latter has
preferential attachment rules, while the former has uniform attachment.
This commit also makes PEP8 changes.
The random k-out graph generator was introduced in pull request #1316.
> Adds random uniform k-out generator

- networkx/algorithms/connectivity/cuts.py
Improved documentation for issue [#1859](https://github.com/networkx/networkx/issues/1859)
The minimum_edge_cut returns an empty set in case of weekly connected directed graph, which is theoretically correct but can be **confusing**  to a user, hence this addition to documentation explains this corner case.It also explain the case when disconnected graph is passed as input.
> Improving Documentation as per issue #1859

- networkx/readwrite/gml.py
gml.py doesn't use lib2to3 anymore, 
so lib2to3 isn't required anymore in networkx
so programs using networkx can be "compiled" using py2exe
see https://github.com/networkx/networkx/issues/1775
> removed requirement of lib2to3

- networkx/algorithms/richclub.py
- networkx/algorithms/shortest_paths/generic.py
- networkx/generators/directed.py
The richclub docstrings are a good candidate for pointing people to formatting choices in docstrings.
shortest_path/generic had some examples that didn't work, did pep8 on this one too--look at individual commits to avoid that it you need to.
added authors comment in generators/directed.
> Fix docstring formatting in richclub and generic

- networkx/algorithms/connectivity/cuts.py
A left over in the docstring from the last refactor made somewhat
not clear that the functions in cuts.py do not consider weights
and compute cuts in terms only of number of nodes or edges. Also
added a reference to `minimum_cut` for the users interested in
weighted edge cuts.
This PR fixes #1810
> Fix minimum_st_edge_cut documentation.

- networkx/algorithms/connectivity/kcutsets.py
- networkx/algorithms/connectivity/tests/test_kcutsets.py
This PR fixes #1875 . For cycle graphs and complete graphs all_node_cuts
was giving incorrect or incomplete results. The most tricky case is cycle
graphs because handling them as a part of the implementation of Kanevsky's
algorithm requires checks inside tight loops that would penalize the common
case.
Instead in this PR cycle and complete graphs are handled separately. It is
cheap to test if the input graph is any of both, and the solution of finding
all node cuts is a lot easier and faster than in the general case.
Also added tests for both cycle and complete graphs.
> Fix all_node_cuts corner cases: cycle and complete graphs.

- networkx/algorithms/bipartite/matching.py
- networkx/algorithms/bipartite/tests/test_matching.py
- networkx/algorithms/matching.py
- networkx/algorithms/tests/test_matching.py
Ref to #1927 
I contacted Prof. Eppstein. There, problem is with the input format. From [PADS/BipartiteMatching](http://www.ics.uci.edu/~eppstein/PADS/BipartiteMatching.py)'s documentation:
**The input format is a dictionary mapping members of U to lists of their neighbors in V.**
This PR solves this issue.
Along with it, I have implemented `is_max_cardinality_matching` and fixed some pep8 errors.
Will modify #1915's test cases soon.
> Corrected eppstein matching

- .travis.yml
- networkx/algorithms/bipartite/tests/test_edgelist.py
- networkx/algorithms/bipartite/tests/test_matrix.py
- networkx/algorithms/tests/test_dominating.py
- networkx/classes/tests/historical_tests.py
- networkx/classes/tests/test_graph.py
- networkx/readwrite/tests/test_adjlist.py
- networkx/readwrite/tests/test_edgelist.py
- networkx/readwrite/tests/test_gexf.py
- networkx/readwrite/tests/test_graph6.py
- networkx/readwrite/tests/test_graphml.py
- networkx/readwrite/tests/test_sparse6.py
- networkx/tests/test_convert_scipy.py
- networkx/tests/test_exceptions.py
- requirements.txt
This package makes nose report which test is being done in form: file.function
Without it the docstring of the test function is used and is not as helpful to find the problem.
I also switched installation of scikits-sparse from conda to pip because it is not being supported on conda anymore.  We still have a travis-ci issue with gdal/osgeo/ogr not being installed, but I'll try to figure that out in another pr.
> Nose ignore docstrings

- doc/Makefile
Probably the smallest pull-request ever. I edited the Makefile in the doc-directory to remove the contents of the folder source/static/examples instead of the folder itself when `make clean` is called, as was already the case with the other generated folders. I also use other types of file synchronization tools and it is difficult to exclude non-existent folders, or the exclusion gets deleted together with the deleted folder, hence it gets included again at the next make.
> Edited Doc Makefile

- networkx/algorithms/link_analysis/pagerank_alg.py
We are only after the largest value, so np.argmax is sufficient.
> Avoid unnecessary eigenval sort in pagerank_numpy

- doc/source/install.rst
> Fix a typo in install.rst

- networkx/algorithms/tests/test_dag.py
This commit adds a unit test to ensure that the `dag_longest_path`
function correctly handles graphs with unorderable nodes. It also cleans
some other unit tests and removes a duplicate test.
This tests for the bug reported in issue #1989.
> Adds unorderable nodes test for dag_longest_path.

- networkx/drawing/tests/test_agraph.py
- networkx/drawing/tests/test_layout.py
- networkx/drawing/tests/test_pydot.py
- networkx/drawing/tests/test_pylab.py
First, I wanted to remove the typo in `test_agraph.py` (intefaace). Then I saw that the list of `.add_edge()` can be collapsed to `.add_edges_from()`. I did the same in `test_pydot.py`, where I additionally entered `with open() as` statements. Finally, I ended up harmonizing all four test files: remove whitespaces around `=`, remove redundant newlines, collapse title to one-line.
> Improve drawing test scripts (typos, newlines, methods)

- networkx/algorithms/shortest_paths/astar.py
- networkx/algorithms/shortest_paths/tests/test_astar.py
This commit improves test coverage by 1. using the `not_implemented_for` decorator and 2. updating a unit test to ensure it runs correctly on both Python 2 and Python 3. This commit also simplifies the unit tests and applies PEP8 to make them more readable.
> Improves test coverage for A* shortest path.

- networkx/classes/digraph.py
- networkx/classes/graph.py
- networkx/classes/multidigraph.py
- networkx/classes/multigraph.py
The existing documentation on the Graph() constructor function says that it can only take "an edge list or a NetworkX graph object" as well as a few third-party formats. This isn't true, since the data is just passed to the to_networkx_graph() function, which can actually accept a wider variety of input formats - including dict of dicts and dict of lists.
> Fix Graph() docstring to reflect input flexibility

- networkx/readwrite/json_graph/node_link.py
- networkx/readwrite/json_graph/tests/test_node_link.py
This is related to issue #1951.
Changes: 
* Set default value of `id` to `name` and rename attribute key `id` to `name`
* Use `attrs` parameter to update `_attrs` such that default parameters don't need to be provided
* Add attribute key `link` with default value `links`
* Update docstrings (i.e. extend example, apply PEP8 and remove obsolete note)
* Apply PEP8 to `test_node_link.py`
Some questions remain:
1. Do we really need `make_str`? After all, it's just a wrapper and doesn't make things shorter. Removing it means to import one package less.
2. Should we get rid of all the blanks in the output? Especially for large graphs writing `{'source':0,'target':1}` instead of `{'source': 0, 'target': 1}` results in a good compression.
3. Should I remove `__author__` attribute according to …
> Generalize and improve docstrings of node_link.py

- networkx/convert_matrix.py
2 bugs:
1) to_numpy_matrix didn't respect integer types (and possilbly others) since a floating value np.nan is added to mark non-edges
2) to_pandas_dataframe missing dtype and order keywords
> Fix bug in dtype-valued matrices

- networkx/algorithms/components/strongly_connected.py
condensation(DiGraph()) currently crashes on line number_of_components = i + 1 with UnboundLocalError: local variable 'i' referenced before assignment
> UnboundLocalError if called with an empty graph

- doc/source/reference/algorithms.shortest_paths.rst
- networkx/algorithms/shortest_paths/tests/test_weighted.py
- networkx/algorithms/shortest_paths/weighted.py
I found that the bellman_ford function call and return parameters are different in design from Dijkstra's and the BFS in unweighted network. So I have standardized these functions to match said function calls and return parameters.
To do so, I have added all the _path() and _path_length() and single_source_ and all_pairs functions accordingly to that "standard". These all now call a private function _bellman_ford() that performs the actual magic. Furthermore, I added multiple predecessor values when multiple shortest paths exist, just like the Dijkstra function does. Finally, I deprecated (not yet removed in case somebody uses it) the function bellman_ford() with a warning and replaced it with bellman_ford_predecessor_and_distance(), since that is what it actually does.
I already updated …
> Standardized Bellman-Ford function calls

- doc/source/reference/algorithms.shortest_paths.rst
- networkx/algorithms/shortest_paths/tests/test_weighted.py
- networkx/algorithms/shortest_paths/weighted.py
This is a generalization of Dijkstra's algorithm that works for a set of
initial nodes instead of just a single initial node.
With this addition pull request #2037 can be implemented easily as follows:
```python
def groups(many_to_one):
one_to_many = defaultdict(set)
for v, k in many_to_one.items():
one_to_many[k].add(v)
return dict(one_to_many)
def voronoi_cells(G, center_nodes, weight='weight'):
paths = nx.multi_source_dijkstra_path(G, center_nodes, weight=weight)
nearest = {v: p[0] for v, p in paths.items()}
return groups(nearest)
> Adds multi-source Dijkstra's algorithm

- doc/source/reference/algorithms.rst
- doc/source/reference/algorithms.voronoi.rst
- doc/source/reference/utils.rst
- networkx/algorithms/__init__.py
- networkx/algorithms/community/asyn_lpa.py
- networkx/algorithms/tests/test_voronoi.py
- networkx/algorithms/voronoi.py
- networkx/utils/misc.py
- networkx/utils/tests/test_misc.py
This provides a new function, `voronoi_cells`, that computes the Voronoi partition of a graph with a given set of center nodes, with respect to the shortest-path distance metric.
This pull request uses the multi-source Dijkstra's algorithm from pull request #2073 and supercedes #2037.
The first commit refactors out a utility function, `groups()`, for "inverting" a many-to-one mapping which can be used in the `networkx.algorithms.community.asyn_lpa` module as well as in the `networkx.algorithms.voronoi` module.
> Adds Voronoi cells algorithm

- networkx/algorithms/approximation/tests/test_vertex_cover.py
- networkx/algorithms/approximation/vertex_cover.py
This commit removes the decorator that marked the approximate minimum
weighted vertex cover function as "not implemented" for directed graphs,
because it works for a reasonable definition of vertex cover in directed
graphs.
This also updates the documentation and tests.
This fixes issue #961.
> Support digraphs in approximate min vertex cover

- doc/source/reference/algorithms.matching.rst
- networkx/algorithms/matching.py
- networkx/algorithms/tests/test_matching.py
Previously the tests for maximal matchings were testing that a given set
of edges was an edge cover, *not* a matching. In addition, they were not
testing maximality of the matching. This updates the tests to correctly
test that the `maximal_matching()` function returns a valid maximal
matching.
As part of this fix, this commit also introduces two public functions,
`is_matching()` and `is_maximal_matching()`, which decide whether a
given set of edges is a valid matching or maximal matching,
respectively.
> Fixes tests for maximal matching.

- networkx/drawing/nx_pylab.py
This is my first contribution to a proper codebase, so any guidance would be great.
I've addressed issue #1199 regarding applying alphas to nodes in a similar manner to node colouring.
I haven't added any more tests, but have tested with some of the drawing examples, to make sure that they have the expected behaviour.
I haven't yet modified edges, since there is a lot more colour handling code in the `draw_networkx_edges` function.
> Apply alphas to individual nodes

- networkx/algorithms/isomorphism/__init__.py
- networkx/algorithms/isomorphism/temporalisomorphvf2.py
- networkx/algorithms/isomorphism/tests/test_temporalisomorphvf2.py
This feature is a directed and undirected extension to the DiGraphMatcher and GraphMatcher classes, respectively. The returned isomorphic embeddings capture temporal information in the graph, assuming the edges have a "date" or "datetime" attribute.
Both incorporate a temporal constraint: timedelta "d". All interactions adjacent to a node must happen within time "d" of each other. In the directed case, all incoming interactions must precede all outgoing interactions.
This work was part of my PhD research at University College Dublin. Citation: http://dl.acm.org/citation.cfm?id=2492586 Paper available on request.
> Code and tests for temporal VF2

- networkx/readwrite/gexf.py
- networkx/readwrite/graphml.py
- networkx/readwrite/tests/test_gexf.py
- networkx/readwrite/tests/test_graphml.py
Follow-up to pull request #971 - recommend extending ``convert_bool`` to include true/false support for literal 0/1 and the string variants.
1. [graphml.py:224](https://github.com/networkx/networkx/blob/7d9682a07dcae30acab3c4841e33d31f727a3fb2/networkx/readwrite/graphml.py#L224)
1. [gexf.py:215](https://github.com/networkx/networkx/blob/87764469941cfa52a5aefc1b1b381a614b484c8d/networkx/readwrite/gexf.py#L215)
E.g., in [graphml.py:224](https://github.com/networkx/networkx/blob/7d9682a07dcae30acab3c4841e33d31f727a3fb2/networkx/readwrite/graphml.py#L224):
Old:
```python
convert_bool={'true':True,'false':False,
'True': True, 'False': False}
```
New:
```python
convert_bool={'true':True,'false':False,
'True': True, 'False': False
'0': False, 0: False,
'1': True, 1: True}
```
For reference, the …
> extend convert_bool in gexf.py and graphml.py to all valid boolean 

- networkx/algorithms/centrality/degree_alg.py
Using `not_implemented_for()` from `networkx.utils.decorators` for `in_degree_centrality()` and `out_degree_centrality()`. Applying PEP8 (removing trailing whitespaces and adding missing whitespaces) and current top-of-the-module standards as well.
> Use not_implemented_for() for in_degree_centrality() and out_degree_centrality()

- networkx/algorithms/components/attracting.py
- networkx/algorithms/components/biconnected.py
- networkx/algorithms/components/connected.py
- networkx/algorithms/components/semiconnected.py
- networkx/algorithms/components/strongly_connected.py
- networkx/algorithms/components/weakly_connected.py
This is an attempt to fix #1176, which is about missing links to methods in other modules. Working on the docstrings, I added some references in text and added `raises` statements where they were missing.
Furthermore, I updated the tops of the modules to current standards and applied PEP8 in the code.
> See also-correction

- networkx/algorithms/assortativity/correlation.py
- networkx/algorithms/assortativity/mixing.py
The numeric mixing and assortativity algorithms only work for integers.
They could be implemented to work for floating point numbers too.
Fixes #1981
> Document integer-only numeric mixing

- doc/source/reference/algorithms.rst
- networkx/generators/geometric.py
- ```efficiency``` toc entry
- link to definition of metric had to move out of parameters section. (in generators/geometric.py)
> doc sphinx error removal

- networkx/algorithms/operators/binary.py
Fixes #1619 (doc changes only) while leaving #1654 to decide about whether edges
should have unique identifiers (UUID).
> Docs for compose now warn about MultiGraph edgekeys

- networkx/algorithms/flow/mincost.py
- networkx/algorithms/flow/networksimplex.py
Add a Notes section to functions that use network_simplex warning
users of the potential problems of using float edge weights. Also
mention the workaround of multiplying weights by a convenient constant
factor.
Fixes #2076
> Improve Notes section on simplex and friends docs.

- doc/source/reference/algorithms.flow.rst
- networkx/algorithms/connectivity/connectivity.py
- networkx/algorithms/connectivity/tests/test_connectivity.py
- networkx/algorithms/connectivity/tests/test_cuts.py
- networkx/algorithms/connectivity/tests/test_kcutsets.py
- networkx/algorithms/flow/__init__.py
- networkx/algorithms/flow/dinitz_alg.py
- networkx/algorithms/flow/maxflow.py
- networkx/algorithms/flow/tests/test_maxflow.py
- networkx/algorithms/flow/tests/test_maxflow_large_graph.py
This implementation is based on Cherkassky's approach (see section 4 of
this very nice paper [1]). That is, do not explicitly construct the layered
network, just compute the layer number or rank of each node in the BFS tree
up to distance = dist(s, t). Then in the DFS, just ignore both edges between
nodes of incompatible ranks and saturated edges.
I've implemented this algorithm with hopes of speed up flow based connectivity
algorithms. Turns out that Edmonds Karp algorithm clearly outperforms this one.
Although this one outperforms clearly Preflow-push and Short-augmenting-paths
for very sparse networks with skewed degree distributions. The paper suggest
other improvements not implemented here.
[1] Dinitz' Algorithm: The Original Version and Even's Version. …
> Add Dinitz' algorithm for maximum flow problems.

- networkx/algorithms/isomorphism/matchhelpers.py
- networkx/algorithms/isomorphism/tests/test_match_helpers.py
generic_multiedge_match can be used to compare multiedges with multiple attributes. For this, one can give it a list of attributes, list of default values and a list of operators to be used for comparison of pairs of single attributes. There was a bug which caused the operators to instead compare tuples of attributes. I fixed this.
As discussed in https://github.com/networkx/networkx/issues/2114, I then also simplified the method to only one case, independent of the number of attributes that ought to be compared.
> Bugfix for generic_multiedge_match (Issue #2114)

- networkx/readwrite/gml.py
- networkx/relabel.py
- networkx/tests/test_relabel.py
Fixes #2134
simplifies read_gml handling of "name" as well.
> Handle graph name attribute in relabel_nodes

- networkx/drawing/layout.py
- networkx/drawing/tests/test_layout.py
Incorrect generator expression syntax when evaluating the maximum of
the input pos dictionary. This bug only triggered when a pos dict
was passed as argument to fruchterman_reingold_layout. This commit
adds tests for this case.
Also added more tests for layouts, which are currently quite sparse.
When doing so I also found and fixed a bug in circular_layout
corner case (graph with only one node) that was using the old API
(expecting G.nodes() to be a list).
> Fix fruchterman reingold bug and add more tests to layouts.

- networkx/algorithms/centrality/eigenvector.py
- networkx/algorithms/centrality/katz.py
- networkx/algorithms/centrality/tests/test_eigenvector_centrality.py
- networkx/algorithms/centrality/tests/test_katz_centrality.py
- networkx/algorithms/community/community_generators.py
- networkx/algorithms/link_analysis/hits_alg.py
- networkx/algorithms/link_analysis/pagerank_alg.py
- networkx/algorithms/link_analysis/tests/test_pagerank.py
- networkx/exception.py
This commit adds two new exceptions, `ExceededMaxIterations` and its
subclass `PowerIterationFailedConvergence`, intended to be used by
algorithms that accept a `max_iter` keyword argument specifying the
maximum number of allowable iterations of a main loop. Several existing
algorithms have been modified to raise these more meaningful exceptions.
(This pull request was inspired by pull request #2142, and needs to be updated once that gets merged. Specifically, that pull request should be merged before this one.)
This pull request follows the suggestion of issue #1705 to remove the "NetworkX" prefix from exception names.
> Adds exception: failed power iteration convergence

- networkx/algorithms/link_analysis/hits_alg.py
- networkx/algorithms/link_analysis/tests/test_hits.py
Refactor HITS convergence iteration logic so that exception message correctly states the number of iterations - iterate while the number of iterations is less than or equal to `max_iter`. If convergence is achieved within `max_iter` iterations, break out of the loop. If convergence is not achieved within `max_iter` iterations, raise a networkx error.
Create test `test_hits_not_convergent` to test for non-convergence of HITS by setting `max_iter` to 0 - test passes when error is raised and test fails when error is not raised.
https://github.com/networkx/networkx/issues/2140
cc: @dschult
> Tweak iteration logic of HITS

- networkx/algorithms/link_analysis/pagerank_alg.py
- networkx/algorithms/link_analysis/tests/test_pagerank.py
Fix docstring for PageRank personalization vector - personalization vector must have at least one non-zero value (ie. personalization values for each node can be zero provided that at least one personalization value for one node is non-zero).
Add test for zero personalization vector.
Add test for at least one non-zero personalization value.
Fix `test_personalization` - set `alpha` to 0.85. If `alpha` is 0, personalization vector does not contribute to PageRank.
> Fix PageRank personalize docstring

- networkx/algorithms/traversal/depth_first_search.py
- networkx/algorithms/traversal/tests/test_dfs.py
Docstring for `dfs_tree` states that `source` parameter is optional,
None is a valid value for `source`, and other functions in the same
module default to source=None.  Set `source=None` default and test.
> Set default source=None for dfs_tree

- doc/source/tutorial/tutorial.rst
With version 1.10, `connected_components` returns a generator of sets of nodes. This PR updates the tutorial accordingly.
> Update `connected_components` example in tutorial

- doc/source/reference/algorithms.centrality.rst
- doc/source/reference/algorithms.dispersion.rst
- doc/source/reference/algorithms.rst
This is to fix #1397.
Basically, there are three types of centralities: Based on paths, neighbors and the entire network. Those based on paths are usually betweenness centralities, while those based on neighbors (degree centrality, eigenvector centrality, katz centrality). The latter category are usually called closeness centralities. I ordered all the centralities in `algorithms.centrality.rst` by category.
Furthermore I outsourced `dispersion` into a new file/page because it's not a centrality.
> Sort centralities together and outsource dispersion

- networkx/algorithms/flow/dinitz_alg.py
- networkx/algorithms/flow/tests/test_maxflow_large_graph.py
Reimplemented the DFS iteratively instead of recursively. This
speeds up the running time considerably, specially for problems
in which the paths between source and sink are long, such as big
and sparse networks (eg social networks). For dense networks, in
which the paths are typically short, the running time is very
simmilar to the recursive implementation.
The speed up in the running time makes now possible to use Dinitz'
algorithm for testing the large graphs in `test_maxflow_large_graph.py`.
Thus we are now using all flow algorithms in all flow tests.
> Refactor Dinitz' algorithm implementation.

- networkx/classes/digraph.py
- networkx/classes/graph.py
- networkx/classes/multidigraph.py
- networkx/classes/multigraph.py
- networkx/classes/ordered.py
- networkx/classes/tests/test_special.py
* Rename adjlist_dict_factory to adjlist_inner_dict_factory
* Split node_dict_factory into node_dict_factory (and add its doc) and adjlist_inner_dict_factory (its previously documented purpose).
Motivation: in an application I am writing, I set `node_dict_factory` to a pseudo-dict that notifies a certain class when nodes are added to the graph.
Unfortunately, `node_dict_factory` is also used to create the outer dict of the adjacency list, so I have no way to patch one and not the other.
> Add adjlist_outer_dict_factory.

- networkx/generators/directed.py
Fixed documentation of the scale free network generator: "conecgted" should be "connected".
> Typo in scale free network generator documentation

- doc/source/tutorial/tutorial.rst
This corrects a minor typo in an example in the tutorial.
> Example not working in tutorial

- networkx/algorithms/dag.py
- networkx/algorithms/tests/test_dag.py
The `dag_longest_path function` can raise an TypeError Exception when the nodes of the DiGraph passed to it aren't sortable (i.e. don't define the `__lt__` method). The algorithm creates a list of `(length, u)` tuples, where u is a node. It then runs the `max()` function on said list. Ordering of tuples is defined by comparing corresponding elements lexicographically. So if ever there's a case where two lengths are equal, the nodes will be compared a `TypeError: unorderable types` is raised. I suspect that this would occur for very frequently when using unsortable nodes considering how the algorithm works.
> don't assume nodes are sortable when running dag_longest_path

- networkx/algorithms/efficiency.py
- networkx/algorithms/tests/test_efficiency.py
This commit fixes a bug in the `local_efficiency()` function in which
the central node was being excluded from the computation of global
efficiency.
This fixes issue #2233.
> Use ego graph when computing local efficiency

- networkx/algorithms/centrality/harmonic.py
This commit changes the implementation of harmonic centrality to compute
single-source shortest path length in the body of a loop instead of
computing all-pairs shortest path lengths outside of the loop, in order
to make the implementation more memory efficient.
Fixes issue #2238.
> Make harmonic centrality more memory-efficient

- doc/source/reference/algorithms.dag.rst
- networkx/algorithms/dag.py
- networkx/algorithms/tests/test_dag.py
I've added an initial implementation of [transitive reduction](https://en.wikipedia.org/wiki/Transitive_reduction) in the dag.py algorithms. It's a standard operation on directed acyclic graphs, basically the opposite of the transitive closure which is already implemented there.
This is my first attempt at contributing to this library but I'd like to get more involved if possible. I've tried to follow the development workflow in the docs but any feedback is welcome and apologies on anything that's been overlooked.
James
> Added transitive_reduction in dag

- .travis.yml
- doc/requirements.txt
- doc/source/install.rst
- doc/source/tutorial/tutorial.rst
- examples/drawing/atlas.py
- examples/drawing/circular_tree.py
- examples/drawing/giant_component.py
- examples/drawing/lanl_routes.py
- examples/graph/atlas.py
- examples/pygraphviz/write_dotfile.py
- networkx/drawing/nx_pydot.py
- networkx/drawing/tests/test_pydot.py
- requirements.txt
This pull request refactors the `networkx.drawing.nx_pydot` submodule to support the well-maintained [`pydot`](https://github.com/erocarrera/pydot) project in lieu of the effectively dead [`pydotplus`](https://github.com/carlos-jenkins/pydotplus) fork, resolving [issue #2235](https://github.com/networkx/networkx/issues/2235) (_Abandon All pydotplus, Ye Who Graph Here_) and restoring basic sanity.
See #2235 for full-frontal details. A brute-force **tl;dr** follows:
* The last commit for [`pydotplus`](https://github.com/carlos-jenkins/pydotplus) was at **[December 8th, 2014](https://github.com/carlos-jenkins/pydotplus/commits/master?page=1)** – nearly two years ago. Long-standing open issues and pull requests remain unresolved. `pydotplus` is a face-rotting zombie.
* The last commit for …
> Make PyDot Support Great Again

- networkx/algorithms/centrality/katz.py
Consider the following code in `networkx/algorithms/centrality/katz.py` :
```python
A = nx.adj_matrix(G, nodelist=nodelist, weight=weight).todense().T
n = np.array(A).shape[0]
```
From the [numpy.array()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html) documentation, `np.array(A)` does make a copy in memory. Removing the call to `np.array() ` should work the same without using up extra memory just to see the shape of `A`.
> Unnecessary array copying in katz_centrality_numpy ?

- networkx/algorithms/coloring/greedy_coloring.py
Implementation used degree lists to track updates to the ever-shrinking graph.
This reduced time from O(|V|^2) to O(|V|+|E|). 
Because this was a replacement for the existing algorithm, instead of new functionality, no tests were added. This build passes all of the existing tests for smallest-last strategy.
> Switch to faster smallest-last algorithm implementation.

- networkx/algorithms/simple_paths.py
I suggested this example in a comment on issue #718. This commit adds it to the _Examples_ section of the docstring for `all_simple_paths`.
> Adds example for getting all simple edge paths

- networkx/algorithms/tree/branchings.py
The error message appears to have been copied from `maximum_spanning_arborescence` to `minimum_spanning_arborescence` as the latter incorrectly reports "No maximum spanning arborescence in G". Fixed.
> Correct error in minimum_spanning_arborescence

- networkx/algorithms/traversal/depth_first_search.py
- networkx/algorithms/traversal/tests/test_dfs.py
Previously, the `dfs_labeled_edges` function included yield statements
of the form
```
yield u, v, {'dir': 'nontree'}
```
This commit changes those statements to be
```
yield u, v, 'nontree'
```
This change is _not_ backwards-compatible: code that was previously like
``` python
for u, v, d in nx.dfs_labeled_edges(G):
if d['dir'] == 'forward':
...
```
needs to be changed now to
``` python
for u, v, d in nx.dfs_labeled_edges(G):
if d == 'forward':
...
```
> Yield string, not dict, in dfs_labeled_edges.

- doc/source/reference/generators.rst
- networkx/generators/classic.py
- networkx/generators/tests/test_classic.py
The Turan Graph generator does not appear in the docs (it was not in the generator.rst file).
This pr also removes some unnecessary type checking from the Turan Graph code and fixes its documentation to include the :math: tag. It also fixes some spacing issues to comply with PEP8.
> Turan docs

- networkx/algorithms/shortest_paths/weighted.py
https://github.com/networkx/networkx/issues/1345 and https://github.com/networkx/networkx/pull/1350
We can add node weight functionality by updating `_weight_function` to include `node_weight` as an argument 
@jfinkels @dschult @hagberg  Thoughts?
> add example of node weights

- networkx/convert_matrix.py
- networkx/tests/test_convert_numpy.py
This commit incorporates the change from pull request #1363, which makes the `to_numpy_matrix` code a little easier to understand (just create a matrix full of NaNs instead of adding a NaN to a matrix of zeros). However, the issue reported in that pull request was already fixed in pull request #2038. The current pull request adds the missing unit tests for those pull requests.
> Adds unit tests for using dtype with to_numpy_matrix

- doc/source/reference/algorithms.chains.rst
- doc/source/reference/algorithms.rst
- networkx/algorithms/__init__.py
- networkx/algorithms/chains.py
- networkx/algorithms/tests/test_chains.py
The chain decomposition is essentially the non-overlapping initial segments of the fundamental cycles of a DFS search tree, when cycles are read as a list of edges starting from the nontree edge. This function induces a very simple bridge-finding algorithm (every edge not in a chain is a bridge), which I will propose later if this function is satisfactory.
> Adds chain decomposition algorithm.

- networkx/generators/classic.py
- networkx/generators/tests/test_classic.py
This refactors the grid_graph() generator to accept both a tuple as well as a list argument for its dimension argument.
> Allow grid_graph generator to accept tuple dim argument

- networkx/generators/geometric.py
- networkx/generators/tests/test_geometric.py
Replace the existing random geometric graph generator with one
that uses a k-d tree to efficiently determine which nodes are
adjacent, so the algorithm is now `O(n)` instead of `O(n^2)`.
Use p-norm number as parameter instead of function. The
scipy KDTree requires a number instead of distance function.
> Use faster random geometric graph implementation.

- networkx/algorithms/community/tests/test_asyn_lpa.py
Alternate form of #2329 which should stop random test errors while leaving the test that came from the references.
> Allow community asyn_lpa test to have two answers

- doc/Makefile
- doc/source/download.rst
This addresses #2281
1. Fix (or remove) broken links to documentation files
2. Remove obsolete calls in `Makefile`
> Fix broken links and remove pdf files from Makefile

- doc/source/reference/algorithms.tree.rst
- doc/source/reference/generators.rst
- networkx/algorithms/__init__.py
- networkx/algorithms/traversal/breadth_first_search.py
- networkx/algorithms/tree/__init__.py
- networkx/algorithms/tree/coding.py
- networkx/algorithms/tree/operations.py
- networkx/algorithms/tree/tests/test_coding.py
- networkx/algorithms/tree/tests/test_operations.py
- networkx/generators/__init__.py
- networkx/generators/tests/test_tree.py
- networkx/generators/tree.py
This commit makes several additions. The main additions are two
encoding/decoding schemes for trees, the nested tuple and Prüfer
sequence schemes. These appear in a new module,
`networkx.algorithms.tree.coding`.
These encoding/decoding functions required implementing a function for
joining subtrees at a root node, which appears as the `join` function in
a new module, `networkx.algorithms.tree.operations`.
Finally, the encoding/decoding schemes suggest a simple implementation
for generating a uniformly random tree. The random tree generator first
generates a random Prüfer sequence, then converts that sequence to the
corresponding tree. This `random_tree` function appears in a new module,
`networkx.generators.tree`.
> Adds tree encoding and decoding functions.

- networkx/algorithms/centrality/subgraph_alg.py
scipy.linalg.expm was being used on a numpy matrix, which is known to be buggy. See scipy/scipy#5546.
> Fix for #2364

- networkx/algorithms/bipartite/__init__.py
- networkx/algorithms/bipartite/basic.py
- networkx/algorithms/bipartite/covering.py
- networkx/algorithms/bipartite/matching.py
- networkx/algorithms/bipartite/tests/test_basic.py
- networkx/algorithms/bipartite/tests/test_generators.py
- networkx/algorithms/bipartite/tests/test_matching.py
- networkx/exception.py
This pull request fixes #2127
When a disconnected graph is passed to `bipartite.sets` more than one
coloring solution is possible. This led to surprising results and hard
to diagnose bugs (see #2127) in algorithms that used `bipartite.sets`,
such as bipartite matching and friends. These algorithms now have a new
optional parameter that allows the user to specify the nodes in one of
the two bipartite sets, and thus allows to use disconnected graphs in
these algorithms without ambiguity.
I've added a new exception `AmbiguousSolution` in order to be more
explicit when we raise it. It might have more use cases beyond
`bipartite.sets`.
The changes in this pull request are backwards compatible for connected
graphs as the new parameter is optional. For disconnected graphs is not
backward …
> Raise an Exception for disconnected Graphs in bipartite.sets

- networkx/algorithms/bipartite/matching.py
- networkx/algorithms/bipartite/tests/test_matching.py
This PR fixes #2384.
Reimplement iteratively the inner function `_alternative_dfs` in
`_is_connected_by_alternating_path`. This function checks if nodes
in the graph are linked to target nodes by alternating paths, that
is, paths that alternate between matched and unmatched edges.
This PR also delegates to `_connected_by_alternating_paths`
computing the matched and unmatched edges because these are the same
for a given maximum matching and we do not need to recompute them
each time that we check if a node is linked to targets by an
alternating path.
I also changed the implementation of the computation of matched and
unmatched edges in order to avoid assuming orderable nodes.
Added a test with the example given in #2384 and another test with
unorderable nodes.
> Check alternating paths using iterative DFS in to_vertex_cover.

- networkx/drawing/nx_pylab.py
hold() has been removed from matplotlib  https://github.com/matplotlib/matplotlib/issues/3070, it will be `True` by default.
should we introduce our own `hold` logic which basically calls `plt.cla()` and `plt.clf()` when `hold=False`
@hagberg
> [Fixes #2342] remove calls to plt.hold(), deprecated in mpl2.0

- doc/source/reference/exceptions.rst
- networkx/algorithms/bipartite/__init__.py
- networkx/algorithms/bipartite/basic.py
- networkx/algorithms/bipartite/centrality.py
- networkx/algorithms/bipartite/cluster.py
- networkx/algorithms/bipartite/matching.py
- networkx/algorithms/bipartite/projection.py
This PR addresses #2400
Improve bipartite documentation by clarifying that the use of a node
attribute named `bipartite` with values 0 and 1 in order to
distinguish bipartite node sets is only a convention which is not
enforced in the source code. Also state explicitly that bipartite
functions do not check that the input graph is actually bipartite
nor than the container with a bipartite node set contains all nodes
from that bipartite node set.
Added links form all relevant function docstring to the module
level documentation where all this is explained.
Also added links to some custom exceptions to the generated
documentation that were missing.
> Improve bipartite documentation.

- networkx/readwrite/json_graph/node_link.py
- networkx/readwrite/json_graph/tests/test_node_link.py
Fix for issues #2328 and #2332.
Changes JSON node-link format to no longer export or import expecting links to be by node index. Instead, it expects node IDs like D3's current examples.
> Fix for issues #2328 and #2332

- .travis.yml
- networkx/algorithms/centrality/subgraph_alg.py
This PR fixes #2415 (well not really, but at least it doesn't kill the build for python 3.6 with optional dependencies).
This workaround still does not install gdal for python 3.6 but it doesn't kill the build, and gdal installation works for all other python versions. It seems that the problem is that conda for python 3.6 installs the latest version of gdal (2.1.3) which is not compatible with the package libgdal-dev provided by Travis version of Ubuntu.
Also more doctests fixes for python 3.6 at subgraph centrality.
> Workaround for gdal python3.6 at travis and more doctests fixes

- networkx/algorithms/operators/product.py
Since the implementation was only adding nodes as a byproduct of adding edges, it ended up dropping zero-degree nodes. This fixes things by initializing the result to contain all original nodes. Fixes #2454.
> Ensure nx.power preserves all original nodes

- networkx/algorithms/connectivity/connectivity.py
Rename the parameters u, v of local_edge_connectivity to s, t so they match their names in the documentation and are consistent with similar functions, such as local_node_connectivity.
> rename parameters to conform with the docstring and similar functions

- networkx/readwrite/gexf.py
I added a sentence describing that networkx does indeed write
attributes like visualization parameters, "viz", correctly according
to the GEXF schema.
I added an example setting the size color and layout positions of a
node which was tested to work in Gephi 8.0.2.
There was a few questions on stackoverflow and some promoting
work-around behavior because it was not evident in the documentation.
I will note that beyond viz there are other behaviors that are not
documented and the user would not know they are available without
actually reading through the code.
> added documentation for write_gexf viz attrs

- doc/source/tutorial/tutorial.rst
- networkx/classes/graph.py
Fixes #2271 
Could be made unnecessary if we move G.edge to G._edge and create read-only G.edge (see #2469)
> Make clear to NOT assign to G.edge[u] or G.edge[u][v]

- networkx/algorithms/cycles.py
- networkx/algorithms/tests/test_cycles.py
Fixes #2439 as well as #2323 and #2324.  The problem was when a node is discovered that had already been used as a source to no avail. Old version added it as a potential head to be explored. It should just ignore that edge.
> find_cycle.  Fixes #2323 and #2324 by fixing #2439

- networkx/algorithms/approximation/dominating_set.py
- networkx/algorithms/approximation/independent_set.py
- networkx/algorithms/approximation/matching.py
This changes some weird formatting in the documentation, mostly in the [`dominating_set` module docstring](http://networkx.readthedocs.io/en/latest/reference/algorithms.approximation.html#module-networkx.algorithms.approximation.dominating_set). But it also changes two links to Wikipedia that were missing the closing `)` in the link, for example [in `matching`](http://networkx.readthedocs.io/en/latest/reference/algorithms.approximation.html#graph-matching).
Preview:
> Fixes some minor documentation issues (approximation algorithm subpackage)

- networkx/classes/digraph.py
- networkx/classes/tests/test_digraph.py
I more or less implemented the suggested test and fix from #2442.  I changed the test from this
```
self.assertCountEqual(G.nodes(), G.reverse().nodes())
self.assertCountEqual(map(reversed, G.edges()), G.reverse().edges())
```
to
```
assert_items_equal(G.nodes(), G.reverse().nodes())
assert (y, x) in G.reverse().edges()
```
Let me know if you have a better idea.
> Ensure `digraph.reverse` respects hashable objects

- networkx/relabel.py
- networkx/tests/test_relabel.py
This fixes #2482 as suggested. @dschult 
I added a test, which failed with the previous code and passes with this commit.  Please let me know if I should provide additional tests.
I also made some minor pep8 modifications to the functions I touched. I noticed that both `networkx/relabel.py` and `networkx/tests/test_relabel.py` have additional pep8 violations.  When I edit a file (such as these two) for some other purpose, is it acceptable to take the opportunity to make those files pep8 compliant?  I don't think it is worth making a big deal about pep8 compliance, but I am happy to make things more standard as I go.  For instance, I am happy to make additional pep8 style fixes to this PR before you merge it.
If you don't need any additional tests and would prefer that I resist making …
> Ensure _relabel_copy() respects node order of OrderedGraphs

- doc/source/reference/algorithms.flow.rst
- networkx/algorithms/__init__.py
- networkx/algorithms/flow/__init__.py
- networkx/algorithms/flow/gomory_hu.py
- networkx/algorithms/flow/tests/test_gomory_hu.py
Thos PR addresses #2421.
A Gomory-Hu tree of an undirected graph with capacities is a
weighted tree that represents the minimum s-t cuts for all s-t
pairs in the graph.
It only requires `n-1` minimum cut computations instead of the
obvious `n(n-1)/2`. The tree represents all s-t cuts as the
minimum cut value among any pair of nodes is the minimum edge
weight in the shortest path between the two nodes in the
Gomory-Hu tree.
The Gomory-Hu tree also has the property that removing the
edge with the minimum weight in the shortest path between
any two nodes leaves two connected components that form
a partition of the nodes in G that defines the minimum s-t
cut.
> Add Gomory-Hu tree representation of undirected graphs.

- networkx/convert.py
- networkx/convert_matrix.py
- networkx/tests/test_convert.py
- networkx/tests/test_convert_pandas.py
Fixes #2111.
To make this clean, I decided to make `from_pandas_dataframe` only
require one argument by changing the signature from
```
def from_pandas_dataframe(df, source, target, edge_attr=None,
create_using=None):
```
to
```
def from_pandas_dataframe(df, source='source', target='target', edge_attr=None,
create_using=None):
```
I added additional tests and expanded a doctest.
I have a few minor cleanups I want to make before this is merged, but I would like to have feedback on the changes I made to the call signature (or anything else) first.
> Fix call to `from_pandas_dataframe` from `to_networkx_graph`

- networkx/drawing/layout.py
The current upstream implementation of the (non-sparse) Fruchterman-Reingold layout algorithm uses an explicit for-loop over spatial dimensions, and some nested transpose operations on 3D arrays. This branch replaces the for-loop with direct NumPy indexing operations, and replaces the nested transposes with np.einsum() operations which makes it clearer which axes are being summed when calculating the forces.
> Improved vectorization of Fruchterman-Reingold layout.

- networkx/algorithms/centrality/closeness.py
- networkx/algorithms/shortest_paths/tests/test_unweighted.py
- networkx/algorithms/shortest_paths/unweighted.py
Closeness centrality for a node u is calculated as C(u) = \frac{n - 1}{\sum_{v=1}^{n-1} d(v, u)}, that is the reciprocal of the sum of the shortest path distances from all n-1 other nodes to u, but in closeness_centrality method it is implemented as the reciprocal of the sum of the shortest path distances from u to all n-1 other nodes. For undirected graphs, using d(u,v) instead of d(v,u) is not a problem, but for directed graph it can produce totally different results. For this reason I have slightly modified the closeness centrality function, by using predecessors of a node instead of successors in case of undirected graph through the new method "single_target_shortest_path_length" added to the file _networkx/algorithms/shortest_paths/unweighted.py_: for the sake of completeness, I have …
> Fix closeness centrality for DiGraphs

- networkx/classes/tests/test_views.py
- networkx/classes/views.py
```G.nodes``` and ```G.edges``` objects now have methods ```keys/values/items/data``` where ```data``` allows you to extract a particular data attribute rather than the entire data dict.  I'm not sure that we need all of these methods. Even for dicts, the ```keys``` method seems superfluous. But ```keys/values/items``` come with the Mapping ABC class, and could theoretically be useful to someone.
Thoughts?
> Add method .data() on Nodeview and Edgeview

- networkx/readwrite/gml.py
Fixes #2383 
It looked to me like modifying the code to automatically detecting a multigraph was a bit involved.  Given the (hopefully) imminent release of networkx-2.0, I decided that adding a hint to the error message would be sufficient for now.
```
In [1]: import networkx as nx
In [2]: nx.read_gml('polblogs.gml')
---------------------------------------------------------------------------
NetworkXError                             Traceback (most recent call last)
<ipython-input-2-83bca7fece32> in <module>()
----> 1 nx.read_gml('polblogs.gml')
<decorator-gen-455> in read_gml(path, label, destringizer)
/home/jarrod/src/networkx/networkx/utils/decorators.pyc in _open_file(func, *args, **kwargs)
219         # Finally, we call the original function, making sure to close the fobj.
220 …
```
> Add hint to duplicated edge error

- networkx/readwrite/gml.py
- networkx/readwrite/tests/test_gml.py
Attempting to fix #2362. 
@dschult  I am not confident that my approach is correct.  Would you take a quick look and let me know if this seems like a reasonable start.  Should I add `and key != 'label'` to the blocks of code handling dicts and lists in `stringize` as well?  I wasn't sure how we should handle labels that were more complex than just ints, longs, and floats.
If this seems like the correct approach, the problem I am running into is that the `literal_stringizer` function takes the unicode string
```
u'This is "quoted" and this is a copyright: \xa9'
``` 
and converts it to the text string
```
'u\'This is "quoted" and this is a copyright: \\xa9\''
```
The function `escape` handles the unicode string correctly producing
```
'This is &#34;quoted&#34; and this is a copyright: …
```
> Ensure label in gml output is quoted

- networkx/drawing/nx_agraph.py
- networkx/drawing/tests/test_agraph.py
Fixes #2450  and adds some tests of same issue
Before, from_agraph put all graph attributes in G.graph['graph'].
Now graph attributes are put there and also updated into G.graph
> Make graph attributes work both to/from with agraph 

- networkx/classes/digraph.py
- networkx/classes/multigraph.py
- networkx/classes/tests/test_multidigraph.py
- networkx/classes/tests/test_multigraph.py
Can now do (u, v, d) or (u, v, k) with networkx deciding for k only when dict.update(d) raises an exception.  Basically if d is a dict or iterator of 2-tuples assume it is edge data. Otherwise assume it is a key.
> Allow more flexible multigraph add_edges_from options

- networkx/convert_matrix.py
- networkx/tests/test_convert_numpy.py
* to_numpy_array returns the graph adjacency matrix as a NumPy array
* from_numpy_array returns a graph from NumPy array
* Adapted tests for to_numpy_matrix and from_numpy_matrix, which all pass
Resolves #2479
> Add {to, from}_numpy_array functions, resolves #2479

- doc/source/reference/algorithms.bridges.rst
- networkx/algorithms/__init__.py
- networkx/algorithms/bridges.py
- networkx/algorithms/tests/test_bridges.py
This bridge-finding algorithm is implemented using the
`chain_decomposition` function.
This is an alternate implementation to the approach given in pull request #2273. The implementation there is basically
```python
for component in nx.biconnected_components(G):
if len(component) == 2:
yield tuple(component)
```
I find this implementation based on chain decomposition a bit less mysterious.
> Adds linear-time bridge-finding algorithm.

- networkx/generators/geometric.py
- networkx/generators/tests/test_geometric.py
Reversed calling order too, so non-keyword usage is the same, reducing
backward compatibility problems. Minor tweaks with docs and tests.
Added a Note to the doctsring to explain this switching of order.
Resolves #2310
> Switch parameters alpha and beta in waxman_graph

- doc/conf.py
Mark `parallel_betweenness` as a known failure
> Ensure `make html` doesn't fail build on exit

- doc/news.rst
- doc/release/api_1.11.rst
- doc/release/index.rst
- doc/tutorial.rst
- networkx/convert_matrix.py
- networkx/drawing/tests/test_agraph.py
Fix #2531.  Do we want some of 79550da?  Or should I remove the tests cases added in a35b7ea to ``networkx/drawing/tests/test_layout.py``?
I also left out the move to ``pydotplus`` as it appears abandoned and development on ``pydot`` continued.  But I am not familiar with either.
> Cherry pick missing commits

- RELEASE.rst
- doc/news.rst
- doc/release/contribs.py
- doc/release/release_dev.rst
- doc/release/release_template.rst
Am I missing anything obvious?  We can fine-tune this as we do the 2.0 release.
(I don't mention making a 2.0 branch as I don't think it is necessary.   Particularly, if we are releasing 2.1 soon after the 2.0 release.)
> Document release process

- doc/release/release_dev.rst
- networkx/algorithms/bipartite/basic.py
- networkx/algorithms/bipartite/generators.py
- networkx/algorithms/community/centrality.py
- networkx/algorithms/components/strongly_connected.py
- networkx/algorithms/flow/boykovkolmogorov.py
- networkx/algorithms/flow/gomory_hu.py
- networkx/algorithms/flow/tests/test_gomory_hu.py
- networkx/algorithms/flow/tests/test_maxflow.py
- networkx/algorithms/flow/tests/test_maxflow_large_graph.py
- networkx/algorithms/shortest_paths/astar.py
- networkx/algorithms/tests/test_simple_paths.py
- networkx/algorithms/tests/test_structuralholes.py
- networkx/classes/function.py
- networkx/classes/tests/test_function.py
- networkx/generators/geometric.py
- networkx/generators/lattice.py
- networkx/relabel.py
This is related to #2343:
- `set_node_attributes()` and `set_edge_attributes()` no longer throw KeyErrors when a key in the passed dict is not present in the graph
- `set_node_attributes()` and `set_edge_attributes()` both accept dictionary of dictionaries, conditional on parameters "values" and "name"
- parameter "name" now has a default value (`None`), and therefore parameter "name" now has to come last
- harmonized, corrected and extended documentation for `set_node_attributes()` and `set_edge_attributes()`
> Refactor set_node_attributes() and set_edge_attributes()

- networkx/classes/tests/test_function.py
- networkx/generators/classic.py
- networkx/generators/community.py
- networkx/generators/degree_seq.py
- networkx/generators/directed.py
- networkx/generators/duplication.py
- networkx/generators/geometric.py
- networkx/generators/joint_degree_seq.py
- networkx/generators/lattice.py
- networkx/generators/random_clustered.py
- networkx/generators/random_graphs.py
- networkx/generators/tests/test_classic.py
- networkx/readwrite/tests/test_gml.py
- networkx/testing/tests/test_utils.py
- networkx/tests/test_relabel.py
I left the names for atlas and small graphs as it seemed helpful in determining which graph was which. The other cases were sometimes incorrect or with incorrect parameter values (basically G.name doesn't always get updated when the graph gets updated).  So we'll put the user in charge of keeping it up-to-date.
Addresses #1906
> Remove automatic assignment of G.name from many generators

- networkx/__init__.py
- networkx/classes/__init__.py
- networkx/classes/filters.py
- networkx/classes/subgraph.py
- networkx/classes/tests/test_subgraph.py
Here SubGraph means a view restricting (or enhancing) a graph. 
Two filters are possible: ```node_filter``` and ```edge_filter```
```node_filter``` takes a ```node``` argument and returns True to keep the node.
```edge_filter``` takes two nodes as arguments (or for multigraph,
an additional key argument) and returns True to keep the edge.
This seems cleaner than the ```GraphView``` of #2512 and can hide nodes easily by building a filter function: ```lambda n: n not in hidden_nodes```, but can be much more involved.
def fish_nodes(n):
return 'fish' in G.nodes[n]
def red_edges(u,v):
return 'red' == G.edges[u, v]['color']
SG = nx.SubGraph(G, node_filter=fish_nodes, edge_filter=red_edges)
Related tickets include:
#2512 
#762
#1011
#793
#335
and there are probably many other places where this …
> SubGraph filter on nodes/edges

- doc/release/migration_guide_from_1.x_to_2.0.rst
I noticed that after PR #2553 the new set_edge_attributes and get_edge_attribute API broke my codebase. 
I didn't see any documentation about the new API in the migration from 1.x.x to 2.0 doc, so after finding a fix, I added a write-up describing it.
> [DOC] Added blurb about set_edge/node_attributes

- networkx/readwrite/graphml.py
- networkx/readwrite/tests/test_graphml.py
Before this commit, in order to write a multigraph to qraphml file, both `key` and `data` items of  edges(`G.edges(keys=True, data=True).items()`) were stored as `<data>` children of `<edge>` elements. This caused difference in edges of multigraphs with key and data attributes, before and after consequent write and reads of graphml. `test_preserve_multi_edge_data` was added to `test_graphml.py` to show this inconsistency.
This commit changes graphml reader and writer behavior to:
* read and write `key` of networkx edges only in `id` attribute of `<edge id="...">` elements of graphml.
* read and write `data` of networkx edges only in `<data></data>` elements of graphml.
Only in non-multigraphs, `id` attribute of `<edge id="...">` elements will be read into `data` of networkx edges, because …
> Graphml: consistent I/O for key and data attributes of edges in multi-graphs

- networkx/drawing/layout.py
- networkx/drawing/tests/test_layout.py
Fixes #2448 where a spring layout with a single initial position got a dimension size of 0 when there was only one initial value. 
My fix simply checks to see if the domain size is zero, and if it is, then it sets it to one. This also addresses the case if multiple nodes are all set to the same (0, 0) position. I added a corresponding test that replicates and tests for the original error.
> [FIX] fixed divide by zero error in spring_layout

- networkx/algorithms/minors.py
- networkx/algorithms/tests/test_minors.py
clean up docs, add tests, clarify multigraph treatment.
Found bug in ```assert_edges_equal``` for multiedge data comparison.
It doesn't seem to hav caused any errors elsewhere -- guess we don't tests multiedges this way often.
> contracted nodes multiedges

- networkx/algorithms/lowest_common_ancestors.py
- networkx/algorithms/tests/test_lowest_common_ancestors.py
I introduced a bug into lowest common ancestor about using undirected or multigraph. 
This PR adds tests for that bug and fixes it.
> Add tests, fix my bugs for NotImplemented code in lowest_common_ancestor

- networkx/algorithms/centrality/katz.py
Fixes #2307.
I made parallel changes to both ``katz_centrality`` and ``katz_centrality_numpy``.  In particular, I added the sentence
```
You can use ``max(nx.adjacency_spectrum(G))`` to get $\lambda_{\max}$ the largest
eigenvalue of the adjacency matrix.
```
after the sentence (in ``katz_centrality``)
```
The parameter ``alpha`` should be strictly less than the inverse of largest
eigenvalue of the adjacency matrix for the algorithm to converge.
```
and the sentence (in ``katz_centrality_numpy``)
```
The parameter ``alpha`` should be strictly less than the inverse of largest
eigenvalue of the adjacency matrix for there to be a solution.
```
You will also notice that I changed the inline math markup (e.g., ``:math:`\beta` `` became ``$\beta$``).  This uses the ``texext`` Sphinx extension, …
> WIP: Add note on how to estimate appropriate values for alpha

- doc/reference/convert.rst
- doc/release/release_dev.rst
- networkx/convert.py
- networkx/convert_matrix.py
- networkx/tests/test_convert.py
- networkx/tests/test_convert_numpy.py
- networkx/tests/test_convert_pandas.py
- networkx/tests/test_convert_scipy.py
Fixes #2464.
Some related commits:
52eb3d3: from_pandas_dataframe and to_pandas_dataframe were added to work with adjacency matrix.
f0c22dd: from_pandas_dataframe was changed to work with edge-lists, but to_pandas_dataframe was not changed.
> Create separate functions for df as edge-lists and adjacency matrices

- README.rst
- networkx/algorithms/centrality/harmonic.py
- networkx/algorithms/connectivity/stoerwagner.py
- networkx/algorithms/dag.py
- networkx/algorithms/distance_measures.py
- networkx/algorithms/shortest_paths/generic.py
- networkx/algorithms/shortest_paths/tests/test_generic.py
- networkx/algorithms/shortest_paths/tests/test_unweighted.py
- networkx/algorithms/shortest_paths/tests/test_weighted.py
- networkx/algorithms/shortest_paths/unweighted.py
- networkx/algorithms/shortest_paths/weighted.py
- networkx/algorithms/tests/test_lowest_common_ancestors.py
- networkx/algorithms/tests/test_threshold.py
This is a partial solution to #2510.  This commit only handles the following:
Changed to return a dict:
- multi_source_dijkstra_path_length
- single_source_bellman_ford_path_length
Changed to yield 2-tuples:
- all_pairs_shortest_path
changed to return dicts:
- single_source_shortest_path_length
- single_target_shortest_path_length
The following are in #2510:
Still need these to yield 2-tuples:
- all_pairs_dijkstra_path
- all_pairs_bellman_ford_path
Need to add this (and yield 2-tuple):
- all_pairs_dijkstra
> shortest_path return types as discussed for #2510

- networkx/release.py
It works when I make this change to release.py in
already installed v1.11 site-packages. It makes sense
that it would fix it for all future releases too.
Don't add the current directory to sys.path
and then removing it again in release.py. Just import version.
We can still play with sys.path in setup.py.  That gets run 
from the base directory. But release.py runs in the same directory as version.py
So this is the only change needed.
I'm writing all this out because I know very little about this code and I'm hoping to either justify it to myself, or give someone else enough info to tell me I'm wrong (or right).
Fixes #2546
> This seems to fix the shadow import for version

- .travis.yml
- tools/travis/osx_install.sh
Since Graphviz 2.40.1 from homebrew seems to have trouble with multiedges and it is not obvious how to get an older version of graphviz via homebrew, I put together this alternative where miniconda is used for the optional deps version of osx tests.
related to #2614
> Add miniconda osx test environment

- networkx/classes/digraph.py
- networkx/classes/function.py
- networkx/classes/graph.py
- networkx/classes/graphviews.py
- networkx/classes/multidigraph.py
- networkx/classes/multigraph.py
- networkx/classes/tests/test_function.py
- networkx/classes/tests/test_graphviews.py
Chains of views are view-of-view-of-view constructs. For subgraphs, if they get long (about 15 views) simple node/edge reporting slows to a crawl.
There could be times when we want the flexibility provided by short chains of subgraphs, but many common cases used in recursive algorithms should avoid chains. 
I have changes the base class method ```subgraph``` to short-cut chains. That is, when the subgraph method of a subgraph view is called, it constructs a subgraph view of the original graph rather than of itself. 
For people who want chains, the function ```nx.induced_subgraph(G, nodes)``` does not short-cut. I also considered ```edge_subgraph``` and ```restricted_view```, but short-cuts are harder to figure out from introspection. In the end I added documentation to describe options. …
> Unravel subgraph chains

- doc/release/migration_guide_from_1.x_to_2.0.rst
- networkx/classes/graph.py
- networkx/classes/tests/test_graph.py
This eases creating code that works for both v1 and v2.
It doesn't address the concerns of #2634 but it eases
the transition to v2.
What do people think about adding back the moved methods?
> Add deprecated methods for moved base class methods.

- doc/conf.py
- examples/drawing/plot_random_geometric_graph.py
- examples/drawing/plot_sampson.py
Some of the examples threw errors at me, when I tried to build the documentation locally.
There are still two more failures, one related to `mailbox.UnixMailbox` and one regarding a not-pickable function in `advances/plot_parallel_betweenness`.
I also changed the intersphinx links to `https` to avoid these warnings:
```
loading intersphinx inventory from http://docs.scipy.org/doc/numpy/objects.inv...
intersphinx inventory has moved: http://docs.scipy.org/doc/numpy/objects.inv -> https://docs.scipy.org/doc/numpy/objects.inv
loading intersphinx inventory from http://docs.python.org/objects.inv...
intersphinx inventory has moved: http://docs.python.org/objects.inv -> https://docs.python.org/2/objects.inv
```
Also is there some documentation on how one should build the documentation? It was a …
> Fix some examples for python 3 compatibility

- .gitignore
- .travis.yml
- doc/Makefile
- doc/conf.py
- requirements/doc.txt
- requirements/extras.txt
- tools/travis/before_install.sh
- tools/travis/build_docs.sh
- tools/travis/deploy-key.enc
- tools/travis/deploy_docs.sh
- tools/travis/linux_install.sh
- tools/travis/osx_install.sh
- tools/travis/script.sh
See
- https://travis-ci.org/networkx/networkx/builds/271948102
- https://networkx.github.io/dev-docs/
This PR accomplishes two main goals:
1. Travis-ci now tests that our documentation builds without error.
2. Travis-ci can now push the built docs to GitHub pages when a
build is triggered on the master branch.
I also changed the travis-ci tests so that we only install packages
when necessary and only generate a coverage report when it will
be uploaded via codecov.
This substantial speeds up the tests so that we are able to test more
things now (e.g., whether the docs build).
Generating the coverage reports, in particular, was costly (i.e., it roughly
doubled or tripled the time it takes the test suite to run).
I no longer test extra dependencies on 3.4 and 3.5 (since I suspect they
aren't …
> Refactor travis tests and deploy docs with travis

- networkx/classes/digraph.py
- networkx/classes/filters.py
- networkx/classes/graph.py
- networkx/classes/reportviews.py
- networkx/classes/tests/test_graphviews.py
- networkx/classes/tests/test_reportviews.py
Fixes #2652 
The EdgeViews have attributes that refer (without context) to graph methods like ```G.nbunch_iter``` and ```G._adj.items```.  Even worse, the EdgeDataViews store lambda functions on the ```_report``` attribute. In any case, these objects are thus not picklable. The graph would probably still be pickleable if it didn't use lazy properties to store the ```edges``` object. But the edge views would not be.  I decided it would be better to make them all pickleable rather than just fix the graph classes and then run into the same trouble later with the views.
I'm sure there are many methods to fix the pickles. The one I use here is to store enough context to recreate the troublesome attribute methods/iterators on Unpickling. That adds a couple of slots to the views which is not a …
> Add tests for pickle of each view and fix where needed

- networkx/readwrite/nx_shp.py
this unpacks the `attributes` dictionary in `read_shp()` so that `net.add_node()` works. `attributes` is unpacked into keyword arguments.
> unpacked dict to provide kwargs when creating nodes from shapefiles

- networkx/classes/coreviews.py
The show_nodes() filter creates a set from an iterable container.
However, FilterAtlas will always traverse the entire node set,
even though the set of nodes is available in this newly constructed
set.
This change dramatically speeds up node iteration when the subgraph
is much smaller than the graph.
I tested this with the following:
```
import time
GRAPH_SIZE=10000000
nodes = list(range(GRAPH_SIZE))
G = nx.Graph()
G.add_nodes_from(nodes)
SG = G.subgraph(nodes[:100])
t = time.clock()
node_list = list(SG)
elapsed = time.clock() - t
print('Time to make subgraph node list: {:.3f}'.format(elapsed))
```
Our use case in particular involved created lists of nodes from
connected component subgraphs of a large graph, which became
much slower when upgrading to 2.0. This …
> Improve subgraph node iteration

- networkx/readwrite/graphml.py
- networkx/readwrite/tests/test_graphml.py
Fixed a problem when reading graphml files where nodes that were part of groups would only be parsed if they were connected to non-grouped nodes via edges. This meant that unconnected nodes were not parsed, but also data any custom properties were not parsed for connected nodes, for example:
> Fixed problem parsing graphml with nodes in groups

- networkx/drawing/nx_pydot.py
This keyword argument is unused, because the value is overwritten in the function's body.
> rm arg `strict` from function `networkx.drawing.nx_pydot.to_pydot`

- examples/drawing/plot_spectral_grid.py
> Add example of spectral embedding of the grid graph

- requirements/README.md
The file `requirements/doc.txt` was recently added, and was not described in the README file of that directory.
> mention `doc.txt` in `requirements/README.md`

- networkx/algorithms/community/quality.py
- networkx/algorithms/community/tests/test_quality.py
inter_community_edges sometimes returned wrong answer when working with digraphs. This patch should also fix #2600.
> Fix for inter_community_edges

- networkx/algorithms/dag.py
- networkx/algorithms/tests/test_dag.py
Fix a bug in dag_longest_path that raises an exception when an empty
graph is given.
> Fix dag_longest_path bug

- networkx/algorithms/operators/binary.py
The doc string for union had a reference to "create_using" which is not an actual parameter.
> removed reference to create_using from union docs

- networkx/readwrite/nx_shp.py
- networkx/readwrite/tests/test_shp.py
Hi, This PR fixes some minor bugs in nx_shp:
- Updates read_shp to raise RuntimeError when file cant be open or read.
- Adds new keyword `strict` to read_shp and implements suggestion #2451 , read_shp now raises NetworkXError when feature lacks geometry and `strict=True`. Conversely `strict=False` can be used to silently ignore features without geometry.
- Adds small change to write_shp, should fix #2432 .
- Some new tests which check this updates.
Update:
Some builds were failing because of no ogr module. Fixed testcase which was causing problems.
> nx_shp fixes

- networkx/algorithms/cluster.py
removed the explicit conversion to a list from the cluster._triangles_and_degree_iter function.
> removed list conversion from _triangles_and_degree_iter

- networkx/algorithms/components/connected.py
`algorithms/components/connected.py` was littered with incorrect descriptions that we raise `NetworkXNotImplemented` for undirected graphs, when we meant to say directed.
> Correct when we raise NetworkXNotImplemented

- networkx/algorithms/components/strongly_connected.py
- networkx/algorithms/components/weakly_connected.py
I liked the documentation for weak connectivity <a href="https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.components.is_weakly_connected.html">here</a>, but there wasn't anything similar for strong connectivity.  Thought I might as well add it.
> Expand documentation regarding strong connectivity

- networkx/classes/function.py
- networkx/classes/tests/test_function.py
Fixes #2726 
If the given path (list of nodes) is of length one, `add_path` will add the first node.
> Fix #2726: ensure add_path to add the first node

- doc/tutorial.rst
Fix typo `furether` in networkx tutorial documentation
@dschult
> Fix 2763: Typo `furether` in networkx tutorial documentation

- networkx/linalg/algebraicconnectivity.py
- networkx/linalg/tests/test_algebraic_connectivity.py
- networkx/utils/decorators.py
- networkx/utils/tests/test_decorators.py
Addresses #2381 
There was a bug (default method didn't set method to 'pcg') that made the algorithm not converge consistently for any network which required more than one iteration to converge.  Even with the bug fixed, the algorithm doesn't always converge. The initial conditions are random, so restarting could work. I put in a check for non-convergence that simply raises a NetworkXError. The user would have to check this to restart with new random conditions.
It would be nice if we could make one of the other methods the default, but they have optional dependencies. Perhaps we would check if those optional dependencies are present and if so switch the default.
To be clear: the non-convergence is not a fault of the algorithm. That is apparently guaranteed to converge. But up to roundoff …
> Fix bug and add checks for non-convergent fiedler_vector

- doc/source/reference/readwrite.sparsegraph6.rst
- networkx/readwrite/graph6.py
- networkx/readwrite/sparse6.py
- networkx/readwrite/tests/test_graph6.py
- networkx/readwrite/tests/test_sparse6.py
This commit changes the implementation of the `write_graph6` function so
that it makes better use of iterators and writes directly to file
instead of buffering the entire encoding of the graph as a string in
memory before writing. This commit also removes the `generate_graph6`
function, since it's functionality can be simulated by using the
`write_graph6` function to write to a file.
Fixes issue #2295.
> Makes write_graph6 less memory-intensive.

- networkx/release.py
* Fix SOURCE_DATE_EPOCH ignored bug
Fix a bug in networkx/release.py that makes build
non-reproducible.
> Fix SOURCE_DATE_EPOCH ignored bug (#2735)

- networkx/drawing/nx_agraph.py
- networkx/drawing/tests/test_agraph.py
Avoid keyword/attribute clash for
nodes: n
edges: u,v
Fixes #1582
> Avoid keyword and attribute clash

- networkx/algorithms/covering.py
- networkx/algorithms/matching.py
- networkx/algorithms/tests/test_covering.py
- networkx/algorithms/tests/test_matching.py
Change return of max_weight_matching to be set of edges instead of dict of "mates".
Required changes in covering.py to adjust for this change.
The set of edges now does not return duplicates (e.g. only u,v and not v,u).
Fixes #1918
> max_weight_matching returns set of edges

- doc/reference/algorithms/connectivity.rst
- networkx/algorithms/__init__.py
- networkx/algorithms/connectivity/__init__.py
- networkx/algorithms/connectivity/disjoint_paths.py
- networkx/algorithms/connectivity/tests/test_disjoint_paths.py
This is a flow based implementation of edge and node disjoint paths. We compute
the maximum flow between source and target on an auxiliary directed
network. This auxiliary network is the same used in the flow based edge and
node connectivity algorithms. See `networkx.algorithms.connectivity.utils` for details.
The saturated edges in the residual network after running the maximum flow algorithm
correspond to edge or node disjoint paths between source and target in the original network.
This function handles both directed and undirected graphs, and can use all flow
algorithms from NetworkX flow package.
Related to the discussion in #2053
> Add flow based node and edge disjoint paths.

- networkx/readwrite/tests/test_sparse6.py
Use tempfile only to get a valid filename.
The contextmanager closes that file, making it
openable even in Windows. keep Appveyor from giving error.
Fixes #2777
> Change how sparse6 tests filenames

- .travis.yml
Looks like the latest Travis image change on OSX broke our testing system there.
This makes it work again by using the older xcode (7.3) instead of the new default (8.3) but even the version 9 code gives the same error so we will have to deal with this more seriously at some point.
> Switch to xcode 7.3 for osx_image in .travis.yml

- networkx/algorithms/bipartite/generators.py
fixes https://github.com/networkx/networkx/issues/2799
By right, the parameters to functions like complete_bipartite() need not be int, as long as they come from a correctly 
defined Integral type. This allows direct usage of Sagemath's Integers, for instance.
> use a generic Integral type for parameters check

- networkx/drawing/nx_pylab.py
This pull request targets to replace the thicker lines used to draw arcs (directed edges) used in the nx_pylab.py file with arrow heads.
The main idea is to replace the `matplotlib.collections.LineCollection` with a list of `matplotlib.patches.FancyArrowPatch`.
The implementation is a bit slower than the original, but adds some clarity when zooming on a a network, e.g. consider the following the network with N nodes and N*2 edges:
```
import matplotlib.pyplot as plt
G = nx.Digraph()
G = nx.generators.directed.random_uniform_k_out_graph(N, 2)
pos = nx.layout.spring_layout(G)
nx.draw_networkx(G, pos=pos, edge_color='g', arrowstyle='-|>')
plt.show()
```
For **N=100**, this normally draws:
With this pull request:
For **N=1000**
Zooming on the network gives:
With this …
> Digraph Arrows to fix #2757

- networkx/convert_matrix.py
- networkx/linalg/attrmatrix.py
https://github.com/numpy/numpy/blob/master/doc/release/1.14.0-notes.rst
This fixes a bunch of failures like:
```
File "/home/travis/venv/lib/python2.7/site-packages/networkx/convert_matrix.py", line 1053, in networkx.convert_matrix.to_numpy_array
Failed example:
A
Expected:
array([[ 1.]])
Got:
array([[1.]])
```
> WIP: Legacy array printing for NumPy 1.14+

- networkx/drawing/tests/test_pydot.py
I removed the check for "True" on P.write_raw because
now it returns None (nothing). We'll rely on exceptions
being raised is the write doesn't work. We actualy test
the written contents later by reading it in so should be OK.
> Fix Pydot tests so works with new version 1.2.4

- examples/drawing/plot_directed.py
This Pull request gives an example of usage of the newly added arrows heads for directed edges or arcs.
Is a simple plot where node sizes differ from node to node, and `arrowstyle` and `arrowsize` are different from default. It should output something like:
> Arrows as a plot example.

- tools/travis/build_docs.sh
See Legacy array printing for NumPy 1.14+ (#2810)
That fix worked for nose, but doesn't seem to work for sphinx.
> Temporarily disable sphinx doctests

- networkx/algorithms/components/attracting.py
- networkx/algorithms/components/biconnected.py
- networkx/algorithms/components/connected.py
- networkx/algorithms/components/strongly_connected.py
- networkx/algorithms/components/tests/test_attracting.py
- networkx/algorithms/components/tests/test_biconnected.py
- networkx/algorithms/components/tests/test_connected.py
- networkx/algorithms/components/tests/test_strongly_connected.py
- networkx/algorithms/components/tests/test_subgraph_copies.py
- networkx/algorithms/components/tests/test_weakly_connected.py
- networkx/algorithms/components/weakly_connected.py
- networkx/algorithms/shortest_paths/weighted.py
- networkx/convert_matrix.py
Resolves #1431 
Also added tests for null graphs to component functions and 
avoided creating lists of components when counting is sufficient.
> Deprecate component_subgraphs functions

- networkx/algorithms/approximation/tests/test_kcomponents.py
- networkx/algorithms/connectivity/tests/test_kcomponents.py
- networkx/algorithms/connectivity/tests/test_kcutsets.py
- networkx/algorithms/operators/all.py
- networkx/algorithms/operators/binary.py
- networkx/algorithms/operators/product.py
- networkx/algorithms/operators/unary.py
- networkx/classes/digraph.py
- networkx/classes/graph.py
- networkx/classes/multidigraph.py
- networkx/drawing/nx_agraph.py
- networkx/generators/geometric.py
- networkx/relabel.py
- networkx/tests/test_relabel.py
It's too hard to keep G.name consistently updated
throughout the codebase.  Let users do it.
This stops from deprecating G.name altogether, but
it is a first step toward that if we decide to go that route.
Fixes #2651
> Remove automatic processing of G.name attribute

- networkx/algorithms/efficiency.py
- networkx/algorithms/tests/test_efficiency.py
Local efficiency should be computed on the subgraphs induced by *neighbors* of each node (ref: **Efficient Behavior of Small-World Networks**, Latora et al) - however, the node itself should not be included in this subgraph. Hence, `center = False`.
Thanks to @dschult and Vlado S.
> Fixes issue #2710

- tools/travis/osx_install.sh
temporarily fixes #2852 
There's a problem with graphviz 2.40 that is fixed in the development version 2.41
Hopefully that will be released soon so that the latest version no longer gives the error.
This change just makes our tests use the old version. It doesn't make NetworkX work with v2.40.
> Pull back graphviz version on osx_install to v2.38

- networkx/classes/tests/test_special.py
Travis only has 2.7+ in the matrix.
> Removed a Python 2.6 fallback for OrderedDict in test_special.

- networkx/drawing/layout.py
Unlike the regular version of fruchterman reingold, the sparse version doesn't calculate temperature proportionality to domain size.
I propose to make the exact same calculation for t in the sparse version, too. If this calculation is not carried out, unsatisfying behavior is shown when plotting graphs with nodes with fixed, faraway position.
> t domain proportionality in _sparse_fruchterman

- networkx/algorithms/assortativity/tests/test_correlation.py
- networkx/algorithms/centrality/tests/test_eigenvector_centrality.py
- networkx/algorithms/connectivity/tests/test_connectivity.py
- networkx/classes/tests/historical_tests.py
- networkx/drawing/tests/test_agraph.py
- networkx/readwrite/tests/test_adjlist.py
Second iteration of this clean-up. I noticed also this duplicated attribute: 
```
numpy = 1  # nosetests attribute, use nosetests -a 'not numpy' to skip test
```
> Deleted tests that were hidden due to name clash.

- networkx/readwrite/gexf.py
- networkx/readwrite/tests/test_gexf.py
Hi,
I am sending a pull request which adds dynamic graph attribute `start`/`end` field into `node` element in gexf utils and tests that.
(Based on https://github.com/networkx/networkx/pull/1797)
> Add dynamic graph attribute start/end field into node element in gexf

- networkx/generators/line.py
Removed not_implemented_for decorator from line_graph function. See #2814 and #2880.
> Fix #2880: Allow line_graph to apply to multigraph

- doc/bibliography.rst
- examples/algorithms/plot_blockmodel.py
- networkx/algorithms/approximation/clique.py
- networkx/algorithms/bipartite/generators.py
- networkx/algorithms/bipartite/matching.py
- networkx/algorithms/centrality/current_flow_closeness.py
- networkx/algorithms/centrality/reaching.py
- networkx/algorithms/centrality/subgraph_alg.py
- networkx/algorithms/chains.py
- networkx/algorithms/clique.py
- networkx/algorithms/coloring/greedy_coloring.py
- networkx/algorithms/cuts.py
- networkx/algorithms/cycles.py
- networkx/algorithms/distance_measures.py
- networkx/algorithms/efficiency.py
- networkx/algorithms/link_prediction.py
- networkx/algorithms/tree/branchings.py
- networkx/algorithms/tree/coding.py
- networkx/generators/duplication.py
- networkx/generators/random_graphs.py
Hello!
The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). This PR implements that recommendation by changing all static DOI links to `https://doi.org/`, see diff.
If you agree and merge, I'll also update other repos, website, docu, etc. in the same manner.
Cheers :-)
> link DOIs to preferred resolver

- networkx/algorithms/shortest_paths/dense.py
- networkx/algorithms/shortest_paths/tests/test_dense.py
In this PR I have implemented a simple function to reconstruct the path from a node `source` to a node `target` with the result of executing: `floyd_warshall_predecessor_and_distance`
The code is being properly tested:
. Expected behavior
. Abnormal behavior: `source == target`
. KeyError exception (this test is optional)
> Floyd Warshall rebuild path

- networkx/algorithms/community/community_generators.py
> Corrects incorrect requirements for values of Tau1 and Tau2 in docs.

- networkx/algorithms/bipartite/matrix.py
- networkx/convert_matrix.py
From Scipy 1.1.0, `asformat` will throw a ValueError instead of an AttributeError if the format if not recognized. For backward compatibility, both are captured now.
> Fix compatibility issue with new version of scipy.

- setup.py
When we run 'networkx.test()', we need nose packages.
Turtorial from this web page
https://networkx.github.io/documentation/networkx-1.9.1/test.html.
so I add nose package to extras_require packages
> Update setup.py related Networkx test Error #2925

- networkx/algorithms/bipartite/generators.py
- networkx/algorithms/bipartite/tests/test_generators.py
Fix a bug when run bipartite configuration model with empty degree sequence.
> Allow bipartite configuration model for empty graph

- networkx/drawing/layout.py
- networkx/drawing/tests/test_layout.py
Add a simple layout for bipartite graph.
I also noticed that all the functions in layout.py used numpy but some checked if numpy is installed while others didn't. Shall we make them more consistent? Personally I don't think checking and raise a new error is necessary. If we remove all the checks we can bring up the code coverage a bit as well.
> Add bipartite layout

- networkx/algorithms/centrality/betweenness.py
- networkx/algorithms/centrality/tests/test_betweenness_centrality.py
This is my first ever attempt at fixing a bug. The issue #2709 came across as simpler than the rest. 
I changed the _rescale function to take endpoints as an input parameter. 
If endpoints is true: 
scale = 1/(n*(n-1))
else:
scale = 1/((n-1)*(n-2))
Please review
> Changed scaling factor in betweenness.py (#2709)

- networkx/generators/__init__.py
- networkx/generators/spectral_graph_forge.py
- networkx/generators/tests/test_spectral_graph_forge.py
Hi,
I am a PhD. student at the University of Trento, Italy and I would like to contribute to the NetworkX project adding a random graph generator algorithm that me and my co-authors have recently published in an international peer-reviewed conference.
This algorithm, called Spectral Graph Forge (SGF), computes the eigenvectors of a given graph adjacency matrix, filters them and build a random graph with a similar eigenstructure.
SGF has been proved to be particularly useful for synthesizing realistic social networks and it can also be used to anonymize graph sensitive data.
Our paper, L. Baldesi, C. T. Butts, A. Markopoulou, "Spectral Graph Forge: Graph Generation Targeting Modularity", [IEEE Infocom](http://infocom2018.ieee-infocom.org/), 2018, has a [pre-print …
> add Spectral Graph Forge generator

- CONTRIBUTORS.rst
- networkx/algorithms/tree/branchings.py
- networkx/algorithms/tree/tests/test_branchings.py
This pull request contains a patch to allow the `Edmonds` class to preserve the edge attributes of the source graph when working out an optimum.
The function is disabled by default, so all of the branching algorithms gain a new `preserve_attrs` keyword argument to enable it. Tests are added for both preserving and discarding attributes.
Feedback is welcome - I am happy to make changes. I am not sure exactly how this change will interract with the change in #2117 - looking at the diff there, this change is orthogonal, but I would guess it might cause merge conflicts.
> Preserve edge attributes when using branching algorithms

- doc/release/release_dev.rst
- networkx/classes/digraph.py
- networkx/classes/graph.py
- networkx/classes/multidigraph.py
- networkx/classes/multigraph.py
- networkx/classes/tests/test_coreviews.py
- networkx/classes/tests/test_graph.py
Graphs no longer have references to views.
Views still have references to the graph.
This should ease subclassing the base graph classes
because you don't have to worry about creating memory leaks.
Fixes #2915
> Remove circular references between graphs and views.

- networkx/algorithms/bipartite/tests/test_generators.py
Fixing by setting the seed of the random number generator
> Attempt to fix random test fail in bipartite.generators

- networkx/classes/coreviews.py
- networkx/classes/digraph.py
- networkx/classes/graph.py
- networkx/classes/multidigraph.py
- networkx/classes/multigraph.py
- networkx/classes/tests/test_coreviews.py
Check if induced node set is big or small to determine lookup method.
Also add subgraph docs to warn that building the subgraph from scratch
may be better and give alternate code to use for this.
Fixes #2887 
@gboeing :  This should help speed up the case when most nodes are in the subgraph.
> speedup of filters for induced subgraph

- networkx/generators/random_graphs.py
- requirements/extras.txt
- tools/travis/build_docs.sh
Fixes #3030.
I couldn't reproduce the nbconvert / libpng error.  But it looks like it may no longer be a problem.
However, a couple of days ago pyyaml 4.1 was released and it is breaking things.  I am going to merge this now, so that there is less ci noise.  I will look into the 4.1 issue soon.
> TravisCI fix

- doc/reference/classes/digraph.rst
- doc/reference/classes/graph.rst
- doc/reference/classes/multidigraph.rst
- doc/reference/classes/multigraph.rst
- doc/release/release_dev.rst
- networkx/classes/graph.py
- networkx/classes/tests/test_graph.py
Second part of #1393 : adding an update() method to the base classes.
Input parameters can be a graph or containers of edges and/or nodes.
As written this new method returns None like the `dict.update`.  Perhaps it should return the graph? That would allow `G.update(G1).update(G2).edges()` which some might think is/isn't a good thing.
I decided to exclude adjacency inputs for the update method because there are so many variations.
I include examples in the docstring for adjacency inputs.
> Add base class method `update`

- doc/release/release_dev.rst
- networkx/readwrite/graphml.py
- networkx/readwrite/tests/test_graphml.py
> Expand read/write_Graphml numeric type to support numpy numeric types

- networkx/generators/community.py
- networkx/generators/tests/test_community.py
This is fairly straightforward PR, I've implemented the classical "binomial" SBM in `generators/community.py`.
There's a sparse switch that will create edges by jumping ahead by a random number of  non-edges,
drawn from a geometric distribution. This is the default. In the dense case, I use a Bernoulli test on each edges.
Note that with this PR,  `random_partition_graph` could be refactored as a call to `stochastic_block_model` (as well as `gnp_random_graph` and other Erdos Renyi type graphs).
> Add stochastic block models to generators

- networkx/algorithms/clique.py
- networkx/algorithms/tests/test_clique.py
- empty graphs return 0
- graphs with at least one vertex and no cliques return 1
- add test cases for each
fixes https://github.com/networkx/networkx/issues/3050
> Fix graph_clique_number for clique-less graphs

- networkx/algorithms/dag.py
Speed up the ```transitive_reduction``` function which was repeatedly finding dfs of the same nodes.
This should improve its speed and scaling with number of nodes and edges.
Relates to #3032
> Speedup transitive_reduction

- networkx/drawing/layout.py
- networkx/drawing/tests/test_layout.py
Fix #3065 
`circular_layout()` now raises an exception when `dim < 2`.
Also, `kamada_kawai_layout()` now uses a uniformly-spaced linear layout when `dim < 2` and `pos` hasn't been specified, rather than passing a bad parameter value to `circular_layout()`.
> Bugfix for issue 3065

- networkx/drawing/nx_agraph.py
This works on some OS as is, but adding the b-flag in mode makes it work for all.
Fixes #3060
> add binary mode to open_file for view_pygraphviz.

- networkx/algorithms/centrality/degree_alg.py
- networkx/algorithms/centrality/tests/test_degree_centrality.py
1) Fixed a division by zero bug in the degree_centrality functions (division by zero was raised when len(G)==1), if there is one node in the graph it's centrality is set to 1.
2) Removed redundant dict initialization line.
> Degree centrality bug fix.

- CONTRIBUTORS.rst
- networkx/algorithms/operators/all.py
- networkx/algorithms/operators/tests/test_all.py
I raise a ValueError when any of the functions in all.py (i.e., union_all, disjoint_union_all, compose_all, and intersection_all) receives an empty list as an argument.
Fixes #2973.
> Raise ValueError when empty list is passed to functions in all.py, fixes #2973

- doc/reference/classes/digraph.rst
- doc/reference/classes/graph.rst
- doc/reference/classes/multidigraph.rst
- doc/reference/classes/multigraph.rst
- networkx/algorithms/clique.py
- networkx/algorithms/connectivity/edge_kcomponents.py
- networkx/algorithms/minors.py
- networkx/algorithms/operators/binary.py
- networkx/algorithms/operators/unary.py
- networkx/algorithms/tree/branchings.py
- networkx/algorithms/tree/mst.py
- networkx/classes/coreviews.py
- networkx/classes/digraph.py
- networkx/classes/function.py
- networkx/classes/graph.py
- networkx/classes/graphviews.py
- networkx/classes/multidigraph.py
- networkx/classes/multigraph.py
- networkx/classes/ordered.py
- networkx/classes/tests/test_graphviews.py
- networkx/classes/tests/test_subgraphviews.py
- networkx/drawing/tests/test_pydot.py
- networkx/generators/line.py
- networkx/relabel.py
Over the past year since the introduction of ```GraphView```s in NetworkX 2.0 there have been a number of issues with manipulating and/or expanding the class structure of Views relative to the graph classes themselves.  This PR is an attempt to simplify the "graph views" by converting them from classes to functions which create graph objects with the right data structure for views. This means ```G.__class__``` can again be used to instantiate an empty graph of the same (Di/Multi) type.
Perhaps more importantly, subclasses which extend the interface don't lose those extensions when using the ```G.copy``` or ```G.subgraph``` methods.
An additional benefit is that the interface is much smaller: e.g. one ```subgraph_view``` function replaces 4 classes.
Original PR does the following:
- add …
> Simplify the Graphview and SubGraphView system

- networkx/drawing/nx_agraph.py
- networkx/drawing/tests/test_agraph.py
> Stop pydot expansion of graph attributes upon repeated to_from

- networkx/algorithms/connectivity/kcutsets.py
- networkx/algorithms/connectivity/tests/test_kcutsets.py
Address #3025.
I made quite some changes to the original implementation and this probably need to be carefully reviewed.
The code correctly find much more cuts from `torrents_and_ferraro_graph` and doesn't need to deal with cycle graph separately. However it's also significantly slower than before, so I turned off a few tests for now.
I will explain a bit about the changes later and probably add more comments, but I'd like to get some feedback.
> Fix bugs in all_node_cuts, address #3025

- doc/reference/algorithms/centrality.rst
- networkx/algorithms/centrality/__init__.py
- networkx/algorithms/centrality/percolation.py
- networkx/algorithms/centrality/tests/test_percolation_centrality.py
Percolation centrality for a given node, at a given time, as the proportion of ‘percolated paths’ that go through that node. A ‘percolated path’ is a shortest path between a pair of nodes, where the source node is percolated (e.g., infected).
Ref. http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0053095
> Add percolation centrality

- doc/release/release_dev.rst
- networkx/algorithms/shortest_paths/tests/test_weighted.py
- networkx/algorithms/shortest_paths/weighted.py
This brings APIs closer to the same for interchangability.
Now an empty list is the pred value for any source nodes. (was [None] for bellman_ford)
Fixes #3094
> make bellman_ford use same pred dict sentinal value as dijkstra

- doc/release/release_dev.rst
- networkx/algorithms/shortest_paths/generic.py
- networkx/algorithms/shortest_paths/tests/test_generic.py
Addresses #2346 
This is one possible way to do this. I reworked some of the machinery to reduce conditional nesting, but there's still redundant code.
Some verbosity is inevitable - we're trying to value-dispatch on multiple parameters, which isn't usually elegant.
Another approach would be a more dramatic refactor in favor of a more functional style of passing functions around and closing them over values as needed. I've briefly sketched this out for myself, and I can share it in a gist if there's interest. My concern is that it would add complexity (at least for the casual reader) for somewhat questionable gain - how likely is it that the generic shortest-path functions will need to be extended similarly soon?
Finally: this module raises `NetworkXNoPath`, `NetworkXPointlessConcept`, …
> Add option to use Bellman-Ford in generic shortest-path functions

- networkx/drawing/layout.py
- networkx/drawing/tests/test_layout.py
> Removed internal use of deprecated np.matrix type.

- doc/reference/algorithms/index.rst
- doc/reference/algorithms/planarity.rst
- networkx/algorithms/__init__.py
- networkx/algorithms/planarity.py
- networkx/algorithms/tests/test_planarity.py
We implemented a planarity check based on the paper "The Left-Right Planarity Test"[1]
The code is able to certify the correctness of the result by giving a combinatorial embedding as a planarity certificate and Kuratowski subgraph as a counterexample. Our unit tests also verify that the certificates are correct.
We've encountered the following issues and would like your feedback regarding these:
- Recursion depth will be exceeded on larger graphs (10000 nodes).
- Fix would be to use a DFS visitor, but it needs to be more complex than the one already present in networkx
- We have worked on a fix, but it would make the code much harder to read.
- Workaround is the standard recursion depth adjustment.
- Runtime complexity of the planarity check is superlinear. Reasons:
- Sorting of a …
> LR planarity checking

- networkx/convert_matrix.py
- networkx/tests/test_convert_pandas.py
> In 'from_pandas_adjacency', use column names rather than column order.

- networkx/generators/directed.py
- networkx/generators/tests/test_directed.py
`scale_free_graph` generator has a restriction, that `alpha + beta + gamma` has to be equal to `1`.
However, while working with random graph parameters, it is often hard to satisfy this requirement, because   of the float representation.
Eg, this simple code doesn't work:
```python
from networkx import scale_free_graph
import numpy as np
np.random.seed(1)
t = np.random.random(3)
t = t / t.sum()
G = scale_free_graph(N, alpha=t[0], beta=t[1], gamma=t[2])
```
neither does that one
```python
from networkx import scale_free_graph
import numpy as np
np.random.seed(1)
t = np.random.random(3)
t = t / t.sum()
G = scale_free_graph(N, alpha=t[0], beta=t[1], gamma=(1 - t[0] - t[1]))
```
or that one
```python
from networkx import scale_free_graph
import numpy as np
t = np.random.dirichlet(np.ones(3, …
```
> Fix scale_free_graph restriction

- networkx/algorithms/shortest_paths/tests/test_weighted.py
- networkx/algorithms/shortest_paths/weighted.py
When negatively weighted edges are present, skipping nodes with longer distance than destination could miss better path. See example added in test case.
This should fix #3130.
> Handle negatively weighted edges in bellman-ford, fixes #3130

- doc/reference/algorithms/centrality.rst
- networkx/algorithms/centrality/__init__.py
- networkx/algorithms/centrality/second_order.py
- networkx/algorithms/centrality/second_order_centrality.py
- networkx/algorithms/centrality/tests/test_second_order_centrality.py
* Adds second_order_centrality module to networkx.algorithms.centrality package
Author implementation of "Second order centrality: Distributed assessment of nodes criticity in complex networks", Elsevier Computer Communications 34(5):619-628, 2011. Cited 96 times.
> Adding second order centrality algorithm to centrality/

- networkx/algorithms/cluster.py
- The documentation for `clustering` had `c_u = ... \sum_{uv}` but used `w` within the sum, so I think it was probably meant to be `c_u = ... \sum_{vw}`.
- The whole file used `` `...` `` instead ``:math:`...` `` for inline math, which meant it rendered as (semi-)raw LaTeX, 
Comparison showing both of these:
Rendered documentation at  https://huonw.github.io/networkx/reference/algorithms/clustering.html. Another comparison that's particularly heavy on inline math:
- old: https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.cluster.square_clustering.html#networkx.algorithms.cluster.square_clustering
- new: https://huonw.github.io/networkx/reference/algorithms/generated/networkx.algorithms.cluster.square_clustering.html#networkx.algorithms.cluste …
> Mathematics and rendering fixes to algorithms.cluster documentation

- networkx/algorithms/tree/mst.py
Fixes small typos in the max. spanning tree docstring.
> Copy/Paste Typo in Maximum Spanning Tree Docstring

- networkx/algorithms/approximation/steinertree.py
- networkx/algorithms/approximation/tests/test_steinertree.py
This makes the small change suggested in #3155 to error if `steiner_tree` is passed a `MultiGraph`.
> Steiner tree not implemented for MultiGraph, see #3155

- networkx/algorithms/simple_paths.py
- networkx/algorithms/tests/test_simple_paths.py
If one is looking to find all simple paths to multiple targets with out-degree 0, then emitting paths for a set of targets instead of each target separately improves big O algorithmic complexity by a factor of m, where m is the number of targets.
Further clarification: Because we are using an exhaustive depth-first search to find all paths to a target, all other targets will also be encountered during that search.  This PR changes the algorithm so that those paths are also emitted.  
One might not want to use the `targets` argument if any of the targets have out-degree > 0.
> Add targets argument to all_simple_paths

- networkx/algorithms/cycles.py
- networkx/algorithms/tests/test_cycles.py
Really appreciate your work on this wonderful lib. These are codes written by genius!
And, I found below example,
```
g = nx.DiGraph()
for i in range(10000):
g.add_edge(i, i + 1)
g.add_path([10005, 10007, 10005])
g.add_path([10014, 10016, 10014])
list(nx.simple_cycles(g))
```
runs surprisingly slow. 
After I look into this, I would like to make 2 changes.
In Johnson's paper,
>  Our definitions exclude graphs with loops (edges of the form (v, v)) and multiple edges between the same vertices. 
So I would like to remove self-cycle edges out. This reduces huge amount of time. If you really want to do this (to be back compatible, although not consistent with its raw paper def), it would still be faster to check it in advance within O(n) time (I would add it if needed). …
> Speed up simple_cycles

- networkx/readwrite/gml.py
- networkx/readwrite/tests/test_gml.py
This PR fixes issue #3184 in reading GML files, bringing the behavior in line with the documentation.
> Fix reading labels from gml files (#3184)

- networkx/algorithms/connectivity/tests/test_connectivity.py
- networkx/algorithms/connectivity/tests/test_cuts.py
- networkx/algorithms/connectivity/tests/test_kcomponents.py
- networkx/algorithms/connectivity/tests/test_kcutsets.py
This is an attempt to stop the tests from occasionally failing when random degree sequences take too many iterations to find a valid degree sequence. This PR sets a seed on the RNG for those tests making them deterministic.
> Make tests deterministic in connectivity/

- doc/reference/generators.rst
I added the dual-BA model in https://github.com/networkx/networkx/pull/3194, but I forgot to add it to the `docs`. I have added it here
> Added dual-BA to docs

- networkx/drawing/nx_pylab.py
* Switches default node color in draw_networkx_nodes() to #1f78b4 from the ColorBrewer colorblind-safe qualitative palette.
> Make default node color colorblind-safe, close #3233.

- networkx/algorithms/approximation/kcomponents.py
- networkx/algorithms/lowest_common_ancestors.py
- networkx/classes/coreviews.py
- networkx/classes/graph.py
- networkx/classes/reportviews.py
Importing Abstract Base Classes directly from the collections module is
deprecated in python 3.8 in favour of the collections.abc module.
Importing from collections is the only option on python 2.7, though.
This PR tries to import ABCs from collections.abc, and fallback to
collections in case of failure.
Fixes #3170
> Import ABCs from collections.abc

- networkx/algorithms/centrality/eigenvector.py
Precompute sum for the normalization of the initial vector.
Only make dict lookup if there are edge weights, otherweise dict lookups
are prevented.
These changes make the computation of the eigenvector centrality significantly faster if  edge weights are not used. In other cases it is a little bit faster (especially for larger networks) since there are $number_of_nodes fewer calls to the sum function.
Quick benchmarks:
current stable version: 
```
~> python3 -m timeit -n 10 -r 5 -s "import networkx as nx; g = nx.barabasi_albert_graph(1000, 10)" -u msec "x = nx.eigenvector_centrality(g)"
10 loops, best of 5: 298 msec per loop
```
this commit
```
~> python3 -m timeit -n 10 -r 5 -s "import networkx as nx; g = nx.barabasi_albert_graph(1000, 10)" -u msec "x = nx.eigenvector_centrality(g)"
10 …
```
> Improve execution time of eigenvector centrality.

- networkx/classes/digraph.py
- networkx/classes/function.py
Related to #3230
All the mentioned depredations were already fixed. I did find two more (if they're relevant)
> replace deprecated fresh_copy with __class__

- networkx/algorithms/approximation/clique.py
- networkx/algorithms/approximation/dominating_set.py
- networkx/algorithms/centrality/current_flow_betweenness.py
- networkx/algorithms/cluster.py
- networkx/algorithms/connectivity/connectivity.py
- networkx/algorithms/connectivity/stoerwagner.py
- networkx/algorithms/flow/preflowpush.py
- networkx/algorithms/flow/shortestaugmentingpath.py
- networkx/algorithms/reciprocity.py
- networkx/algorithms/shortest_paths/weighted.py
- networkx/generators/expanders.py
- networkx/generators/geometric.py
- networkx/generators/lattice.py
- networkx/generators/line.py
- networkx/linalg/modularitymatrix.py
Hello,
This is a little patch to fix warnings such as:
```python
networkx/networkx/algorithms/cluster.py:537: DeprecationWarning: invalid escape sequence \m
```
In one place, I had to shorten the output of a function to fix
```python
ValueError: line 31 of the docstring for networkx.algorithms.cluster.generalized_degree has inconsistent leading whitespace: '3: Counter({3: 4}), 4: Counter({3: 4})}'
```
Let me know if you are not OK with that :)
Signed-off-by: Mickaël Schoentgen <contact@tiger-222.fr>
> Fix several DeprecationWarning: invalid escape sequence

- networkx/tests/test_convert_pandas.py
Pandas accepts unhashables as DataFrame containers of keys as of 0.24.0 so we cant test that unhashables cause an exception.
Fixes #3298
> Pandas accepts unhashables

- networkx/drawing/nx_pylab.py
* Removes left and bottom ticks and tick labels for draw_networkx() and all related draw_networkx_*() functions.
> Remove ticks and tick labels from draw_networkx(), close #3254.

- networkx/algorithms/simple_paths.py
- networkx/algorithms/tests/test_simple_paths.py
Hey, I've recently use `simple_paths` function. I found https://github.com/networkx/networkx/pull/3074 which replaces `list` to `OrderedDict` speeds up it a lot. Thanks to that. But after that, I found https://github.com/networkx/networkx/pull/3138/ a little misleading.
In the doc, there is no warning about it when we pass in parameters as targets, those should be **out-degree 0**. Otherwise it may not return all_simple_paths as this function name indicates.
Actually, I noticed the added doc itself is likely a misuse.
```
>>> G = nx.complete_graph(4)
>>> for path in nx.all_simple_paths(G, source=0, target=[3, 2]):
...     print(path)
[0, 1, 2]
[0, 1, 3]
[0, 2]
[0, 3]
```
in this complete_graph, nodes [2, 3] are not out-degree 0. So the result paths miss some simple path like [0, 1, 2, 3], …
> Fix `simple_paths` targets parameter

- networkx/algorithms/shortest_paths/unweighted.py
Discovered a small copy-paste error in the error message for `single_target_shortest_path_length`.
Currently, if the node passed into `single_target_shortest_path_length` is not defined, it will throw an error that `source` is not defined. Replaced `source` with `target` since that is the variable defined for this function.
> Fixed error message for single_target_shortest_path_length

- .gitignore
- networkx/generators/harary_graph.py
- networkx/generators/tests/test_harary_graph.py
This pull request implements two generators for the Harary graph, which achieves the maximum node connectivity among all graphs of the same number of nodes and number of edges. The way of constructing Harary graph is described by the famous mathematician Frank Harary in his 1962 work "The Maximum Connectivity of a Graph." 
The two generators use different parameters to generate Harary graph. For more details about them, please refer to the comments for the code. Please review and feedback. Thank you.
> Add two generators for Harary graph

- networkx/drawing/nx_pylab.py
This is a cosmetic change to the `draw_networkx_edges()` to pass the `connectionstyle` parameter to `matplotlib.patches.FancyArrowPatch` to create curved arc of rounding radius `rad`. For example, connectionstyle='arc3,rad=0.2'.
The default is `None` which is ignored by `matplotlib.patches.FancyArrowPatch`
See :py:class: `matplotlib.patches.ConnectionStyle` and :py:class: `matplotlib.patches.FancyArrowPatch` for more info.
> WIP: add connectionstyle parameter

- networkx/algorithms/centrality/flow_matrix.py
There were two erroneous raise statements `raise("Implement solver")` in `algorithms/centrality/flow_matrix.py`. I've fixed these errors by raising the `nx.NetworkXError` exception but I'm not sure if this is the desirable behavior, perhaps raising a `Warning` would be more appropriate.
I work for Semmle and I noticed these issues with out LGTM code analyzer
https://lgtm.com/projects/g/networkx/networkx/alerts/?mode=tree&ruleFocus=3980085
> Fixed raise error in `algorithms/centrality/flow_matrix.py`

- networkx/algorithms/graphical.py
- networkx/algorithms/tests/test_graphical.py
Allow is_graphcial to work with numpy arrays and lists of floats that
have integer values
Fixes #3322
> Make is_graphical raise error for invalid input

- networkx/linalg/graphmatrix.py
- networkx/linalg/laplacianmatrix.py
- networkx/linalg/modularitymatrix.py
Very simple doc PR.
While prepping PR #3401 I noticed that the doc was missing see also links from the matrices definition to their equivalent in linalg.spectrum.
This fixes it.
On a side note:
There's a lot of doc inconsistencies in the linealg module BTW.
algebraicconnectivity.py and attrmatrix.py don't follow the standard at all.
> Add see also links to linalg.spectrum

- networkx/drawing/layout.py
- networkx/drawing/tests/test_layout.py
When fixed nodes are used in spring_layout() but positions are not assigned, the domain size variable ```dom_size``` is not given a value so Python raises an exception. 
This PR sets ```dom_size``` in all cases, and also changes the code to check that all fixed nodes are assigned positions in the input ```pos```.
> Fix spring_layout bug with fixed nodes

- doc/reference/linalg.rst
- networkx/linalg/__init__.py
- networkx/linalg/bethehessianmatrix.py
- networkx/linalg/spectrum.py
- networkx/linalg/tests/test_bethehessian.py
- networkx/linalg/tests/test_spectrum.py
The Bethe Hessian matrix or deformed Laplacian matrix generalizes the graph Laplacian.
It is great for clustering, and also for counting the number of communities in dense networks, see:
[Saade, Alaa, Florent Krzakala, and Lenka Zdeborová. "Spectral clustering of graphs with the bethe hessian." Advances in Neural Information Processing Systems. 2014.](https://arxiv.org/abs/1406.1880)
and
[Le, Can M., and Elizaveta Levina. "Estimating the number of communities in networks by spectral methods." arXiv preprint arXiv:1507.00827 (2015).](https://arxiv.org/abs/1507.00827).
This PR implements this family of matrices and its spectrum, for undirected networks, with tests and documentation.
> Add bethe hessian matrix

- networkx/drawing/nx_pylab.py
- networkx/drawing/tests/test_pylab.py
Both draw_networkx_nodes and draw_networkx_edges support RGB or RGBA tuples.
Fixes #3394
> Fix edge_color inconsistency with node_color and description.

- doc/reference/algorithms/centrality.rst
- networkx/algorithms/centrality/__init__.py
- networkx/algorithms/centrality/group.py
- networkx/algorithms/centrality/tests/test_group.py
- networkx/algorithms/centrality/tests/test_group_betweenness_centrality.py
Added group.py, a new module, to networkx.algorithms.centrality for group centrality computation functions. Added function for group betweenness centrality. Please do review the code and suggest any changes/improvements. Thanks.
(Future work: Adding functions for group closeness and group degree centralities)
Issue: #3388
> Adding module for group centrality measures

- networkx/algorithms/centrality/betweenness_subset.py
- networkx/algorithms/centrality/tests/test_betweenness_centrality_subset.py
This proposed changeset fixes a bug in the implementation of the `subset centrality betweeness`.
I believe that the existing implementation fails to take into account the case where a node lies on multiple shortest paths, and only accounts for the number of predecessors of those nodes.
This changeset adds a test case that illustrates the problem, along with a proposed fix. I also took the liberty of fixing what apperas to be a mistake in some tests fixtures names.
> Fix centrality betweeness subset

- networkx/algorithms/centrality/tests/test_betweenness_centrality_subset.py
Small typo, "etweenness" changed to "betweenness".
> Fixed typo in betweenness centrality subset test

- networkx/algorithms/components/semiconnected.py
- networkx/algorithms/dag.py
As previously discussed [here](https://github.com/networkx/networkx/issues/3446), I added an optional `topo_order` parameter to functions that rely on `topological_sort`so that users can provide their own topological order if they have already computed one.
I left the following two functions alone:
1. `has_cycle` in `dag.py`: if you call `has_cycle`, then either you haven't computed a topological order yet; or you already have, and in that case you already know the result that `has_cycle` would return.
1. `_relabel_inplace` from `relabel.py`: it did not seem like a sensible choice to me. I'm having trouble picturing a user wanting to provide a topological order there, but maybe it's just because I've never had a need for the function that calls it.
> Additional topo_order parameter for functions that rely on topological_sort

- networkx/algorithms/isomorphism/isomorphvf2.py
- networkx/algorithms/isomorphism/tests/test_isomorphvf2.py
It is now possible to search for subgraph monomorphisms by using `subgraph_is_monomorphic()` and `subgraph_monomorphisms_iter()` in the same way that `subgraph_is_isomorphic()` and `subgraph_isomorphisms_iter()` is used, respectively.
> Implemented subgraph monomorphism

- networkx/generators/degree_seq.py
Aims to fix issue #3450 by setting random seed value in the docstring test.
The seed has been sent to an `int` value of 42. Let me know if it should be changed to a random state or if any other change is required.
> Set seed in random_degree_sequence_graph docstring test

- networkx/drawing/nx_pylab.py
`matplotlib.cbook.iterable` is deprecated in matplotlib 3.1
See https://matplotlib.org/3.1.0/api/cbook_api.html#matplotlib.cbook.iterable
> Replace cb.iterable with np.iterable

- networkx/drawing/nx_pylab.py
Fix for issue raised in https://stackoverflow.com/questions/56496486/axes-disappear-after-drawing-networkx-graph-on-another-subplot
`plt.tick_params` operates on the currently active pyplot axes, which is not necessarily the one where the networkx graph resides in. 
This PR makes sure the axes `ax` is operated on. (`ax.tick_params`)
> Don't remove ticks of other pyplot axes

- doc/reference/algorithms/core.rst
- networkx/algorithms/core.py
- networkx/algorithms/tests/test_core.py
- networkx/drawing/nx_pylab.py
- networkx/readwrite/gml.py
The onion decomposition refines the k-core decomposition by providing information on the internal organization of each shell. This is a relatively new tool from network science, but I'm being increasingly more asked for the code and I thought the community might appreciate having it well integrated in networkx.
The extraction code takes the form of a single function which has been added to the `core` submodule (`algorithms/core.py`); its natural home in my opinion.
I added a test function to `algorithms/tests/test_core.py` which is similar to the one for the function `core_number`.
This is my first contribution to networkx; any feedback will be greatly appreciated.
> Adding onion decomposition

- networkx/algorithms/centrality/betweenness.py
Aims to fix issue #3432 by adding `@not_implemented_for('multigraph')` in `betweenness_centrality`. If the generalised shortest path functions should be used, or if the custom Dijkstra code should be modified rather than not implementing `betweenness_centrality` for multigraph, let me know. Thanks!
> No multigraphs for betweenness

- setup.cfg
version 2.3 dropped python2 support until py2 is actually deprecated we
shouldn't mark these wheels as universal
> Wheels are python 3 only

- networkx/drawing/nx_pylab.py
Replace collections.Iterable with collections.abc.Iterable to fix deprecation warning with Python 3.7:
"DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working"
> Fix deprecation warning with Python 3.7

- networkx/algorithms/traversal/depth_first_search.py
> Fix dfs_preorder_nodes docstring saying "edges" instead of "nodes"

- networkx/algorithms/dag.py
- networkx/algorithms/tests/test_dag.py
Add `NodeId` filed to the tuple for cases where two or more nodes have the same key. It causes a problem with the `heapq` object in `lexicographical_topological_sort` function.
> Fixes Issue #3493 - Bug in lexicographical_topological_sort()

- CONTRIBUTORS.rst
- doc/reference/algorithms/asteroidal.rst
- networkx/algorithms/__init__.py
- networkx/algorithms/asteroidal.py
- networkx/algorithms/tests/test_asteroidal.py
Dear all,
This is my first contribution to networkx and to any open-source project so bear with me. I have created a module called `asteroidal.py`which contains a method for recognition of AT-free graphs. I plan to implement more functionality for asteroidal recognition and some other graph recognitions which I have developed, but I try to keep my first pull request small.
`asteroidal.py` implements the method `is_at_free` which takes a graph and checks whether it contains any asteroidal triples or not, i.e. if it is AT-free or not. AT-free graphs is a graph class for which several classical NP-complete problems are solvable polynomial time, independent set and coloring (even list coloring) amongst them.
I have tried to set up sphinx locally to check what my docstrings would look like, …
> AT-free graph recognition

- .travis.yml
- networkx/algorithms/bipartite/projection.py
- networkx/algorithms/chordal.py
- networkx/algorithms/community/kclique.py
- networkx/algorithms/cycles.py
- networkx/algorithms/tests/test_clique.py
- networkx/algorithms/tests/test_covering.py
- networkx/algorithms/tests/test_cycles.py
- networkx/algorithms/tests/test_matching.py
- networkx/algorithms/tests/test_planar_drawing.py
I don't know why it was removed but PyPy3 now supports Python 3.5 and hopefully the next major PyPy version will support PyPy 3.6.
It's really important for me to know that this library is portable since I'm going to use it quite a bit.
> Restore checking PyPy3

- networkx/algorithms/shortest_paths/astar.py
- networkx/algorithms/shortest_paths/tests/test_astar.py
Fixes #3464.
The problem was that each node was allowed to be explored at most once, but sometimes, there are multiple paths through the same node, where the first one is not necessarily the best.  
I fixed it by removing the checks for whether a node was already explored and adding logic to prevent the overriding of starting node's parent. The latter is required because when returning a path, that is done by backtracking until the node's parent is `None`. Without the check, the parent of starting node could be overridden and the backtracking would never end.
The added test contains a smaller version of the graph, mentioned in issue #3464.
> Fix A* returning wrong solution

- CONTRIBUTORS.rst
- networkx/algorithms/bipartite/matching.py
- networkx/algorithms/bipartite/tests/test_matching.py
This provides an implementation of the minimum weight full matching problem, also known as the linear assignment problem, for complete bipartite graphs by deferring the calculation of the assignment to `scipy.optimize.linear_sum_assignment`.
This closes #3520; note that there, I referred to the matchings as "perfect"; since we also support bipartite graphs in which the two partitions have different cardinalities, "perfect" becomes a bit of a misnomer, so here we use term "full" instead; this follows the terminology used in Karp's *An algorithm to Solve the m x n Assignment Problem in Expected Time O(mn log n)* (doi:10.1002/net.3230100205).
I've marked the PR as "WIP" mainly because this is my first contribution, so I'm sure it has some rough edges. All suggestions for improvements are …
> Implement minimum weight full matching of bipartite graphs

- doc/reference/linalg.rst
- networkx/algorithms/dag.py
- networkx/algorithms/tests/test_dag.py
- networkx/algorithms/traversal/breadth_first_search.py
This is an improved algorithm for computing the transitive closure of a DAG using topological_sort (so an exception will be raised if the input graph is not a DAG): traverse vertices following a reverse topological order, and connect each vertex to its descendants at distance 2 as we go. The topological order guarantees that each successor v of a node u is connected to all descendants of u in the transitive closure, and therefore it is enough to connect u to nodes at distance 2 from u rather than attempting to explore all descendants.
The algorithm is probably folklore but I didn't find a reference in my books, feel free to add one if you can.
I also added a function to compute the descendants of a node at a fixed distance. `bfs_successors` worked just as well in my tests but resulted in …
> Faster transitive closure computation for DAGs

- networkx/readwrite/graphml.py
- networkx/readwrite/tests/test_graphml.py
If an attribute has different types on different nodes, it needs a separate key for each type. This has always worked fine when calling `write_graphml_xml`, but `write_graphml_lxml` wouldn't write all of the necessary `<key>` elements, which resulted in an invalid GraphML file. (I have added a test case that you can try out to see what I mean.) This patch fixes it so that the two functions produce the same output.
> Write mixed-type attributes correctly in write_graphml_lxml

- networkx/algorithms/community/label_propagation.py
- networkx/algorithms/community/tests/test_label_propagation.py
The old convergence test was inconsistent with the reference paper. It would stop only if each node has a single majority label among its neighbors. In a network like below, the bridge node will always have `best_labels` = 2 and the stopping condition will never be met.
This prevented convergence in many cases, including the karate_club_graph. 
Instead, according to the cited reference, a node should be satisfied if it has a majority label (either blue or red in the above example), even if there are multiple tied majority labels (two in the case above).
The algorithm is now consistent with the cited reference and is guaranteed to converge.
> Fixes bug in networkx.algorithms.community.label_propagation.asyn_lpa_communities

- networkx/readwrite/gml.py
- networkx/readwrite/tests/test_gml.py
According to the GML technical report, integers in GML must fit into a
signed 32-bit integer. Values outside this range have to be written as
strings instead.
> When exporting to GML, write non 32-bit numbers as strings.

- doc/reference/algorithms/bipartite.rst
- networkx/algorithms/bipartite/matching.py
In https://github.com/networkx/networkx/pull/3527 we added `nx.algorithms.bipartite.minimum_weight_full_matching`; this introduced a few issues in the reference documentation which we fix here:
- The function was missing from the general overview.
- The documentation itself had some rendering issues due to backslashes
not being properly escaped.
- The reference to Karp was not formatted properly.
> Fix a few documentation issues for the bipartite algorithm reference

- networkx/convert_matrix.py
Explicitly stated i.j convention in to_numpy_array() function for ready reference. This is important to mention AGAIN because in many texts/articles (including M E J Newman's book "Networks: An Introduction") the opposite convention is used! Ideally, this point should be prominently mentioned in the documentation wherever network information is converted to/from adjacency matrices.
> explicitly stated i.j convention in to_numpy_array

- networkx/algorithms/approximation/connectivity.py
Self references instead of referencing node_connectivity method.
> Fix typo in all_pairs_node_connectivity method's doctring in connectivity.py

- networkx/classes/graph.py
Some improvements in the docstrings of the three linked methods: order, number_of_nodes, and _len_.
> Fix and Improve multiple docstrings in graph.py

- doc/reference/drawing.rst
- networkx/drawing/layout.py
- networkx/drawing/tests/test_layout.py
New method in layout will arrange nodes of a graph in a spiral layout
with variable compactness. Nodes may be positioned with equal angles
(increasing separation further from center), or equidistant (decreasing
angle further from center)
> Add spiral layout for graph drawing

- networkx/generators/random_graphs.py
- networkx/generators/tests/test_random_graphs.py
It is now compatible with k==n scenario
additionally changed the unit tests for the same effect
This is my first pull request, relating to issue #3522
Please let me know if I need to make any changes!
> Handle k==n within the Watts-Strogatz graph generator

- .travis.yml
- networkx/readwrite/tests/test_gexf.py
This fixes the following errors:
```
======================================================================
FAIL: test_gexf.TestGEXF.test_edge_id_construct
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/travis/venv/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
self.test(*self.arg)
File "/home/travis/venv/lib/python3.8/site-packages/networkx/readwrite/tests/test_gexf.py", line 339, in test_edge_id_construct
assert_equal(expected, obtained)
AssertionError: '<gexf version="1.2" xmlns="http://www.gexf.net/[660 chars]exf>' != '<gexf xmlns="http://www.gexf.net/1.2draft" xmln[660 chars]exf>'
Diff is 1440 characters long. Set self.maxDiff to None to see it.
"""Fail immediately, with the given message."""
>> …
```
> Fix test_gexf to handle XML default serialisation order 

- networkx/classes/reportviews.py
We noticed that our garbage collection runs were frequently sweeping OutEdgeDataView objects. Turns out this was because `self._nodes_nbrs`, being stored on `self`, was also referring to `self` inside of its lambda, creating a cycle that required garbage collection to clear.
Fix this by instead holding onto the relevant dictionary object inside the lambda.
> remove cyclical references from OutEdgeDataView

- networkx/classes/function.py
The `as_view=True` argument is missing so the function returns a deepcopy instead of a view.
> fix to_directed function

- networkx/readwrite/gexf.py
- networkx/readwrite/tests/test_gexf.py
This fixes issue #3573 . As discussed in PR #3595, this is a PR that conforms to the best practices and passes the test for python 3.8. Please review and comment as necessary.
**Note**: A test for INF, -INF and NaN called test_specials() has been added in tests/test_gexf.py
> Fixes #3573:GEXF output problem

- doc/reference/algorithms/efficiency_measures.rst
- networkx/algorithms/__init__.py
- networkx/algorithms/efficiency_measures.py
- networkx/generators/tests/test_degree_seq.py
Fixes #3510 
This makes the algorithm theoretically faster because we use ```all_pairs_shortest_path_length``` instead of finding paths between each pair of nodes separately. In practice it doesn't seem to make much difference for networks less than a few thousand nodes.
I also added a seed to a troublesome test of the random degree sequence generator to make it deterministic.
> Global efficiency attempt to speed up

- networkx/readwrite/gml.py
- networkx/readwrite/tests/test_gml.py
As per issue #3157 
Added in support for string convertible objects to be used as ID's and labels, as well as source and targets for the GML reader. This adds increased flexibility in reading, even if the file is technically out of spec.
> Bugfix: Added flexibility in reading values for label and id

- networkx/algorithms/dag.py
- networkx/algorithms/tests/test_dag.py
Fixes #3187 
TC=transitive_closure(G, reflexive=False)  --> cycles in G create self-loops in TC
reflexive=True  --> each node gets a self-loop (for the path v-v). Called reflexive transitive closure. 
reflexive=None --> no self-loops.
Note: the default has changed from what was effectively None to False.
> Transitive_closure now finds self-loops when cycles present

- networkx/algorithms/link_analysis/pagerank_alg.py
- networkx/algorithms/link_analysis/tests/test_pagerank.py
This will add support for an initialization vector parameter 'nstart' to the ```pagerank_scipy``` method. Also includes relevant unit tests.
> Add support for initializing pagerank_scipy

- networkx/algorithms/flow/gomory_hu.py
Fixes #3293 
Gomory-hu found the right weights, but not always the right tree. 
The last 7 lines of the algorithm as published were not included in the function.
This adds them.
> Add last 7 lines of Gomory-hu algorithm Fixes #3293

- networkx/drawing/layout.py
- networkx/drawing/tests/test_layout.py
Fixes #3188
also fix some pycodestyle
> Keep shells with 1 node away from origin in shell_layout

- networkx/algorithms/coloring/greedy_coloring.py
Modify *'strategy_saturation_largest_first'* into *'saturation_largest_first'*
> Fix typo within incode documentation

- doc/reference/functions.rst
- networkx/classes/function.py
- networkx/classes/graphviews.py
This is functionality I've developed external to networkx and thought it might be a welcome feature.
An example of how I've used it is in an energy distribution circuit, where I want to stop iterating a series of conducting elements when I encounter an open switch. For example, in the following circuit i have several conductors (a,b), (b, c), (b, d) and (c, e) -- one of which is a switch. Depending on the status of the switch, i would want to stop traversing the graph so that I don't build a model of the circuit where there is a demand for power that can't be satisfied, which would probably cause my model to fail to solve.
```
a---------b---------c./ .e->L
\
\
d->L
```
I'm open to suggestions about how this could work , but my vision for it is that traversal functions can accept a …
> Document `subgraph_view` function with support for filter functions

- networkx/drawing/nx_pylab.py
Fix minor typo: `Laplacion` to `Laplacian`. 
Just to be fair to [Pierre-Simon_Laplace](https://en.wikipedia.org/wiki/Pierre-Simon_Laplace) :)
> Fix Docs Typo in networkx.drawing.nx_pylab.draw_spectral

- networkx/classes/tests/test_digraph.py
- networkx/classes/tests/test_graph.py
- networkx/classes/tests/test_special.py
@dschult I mentioned this problem in a previous PR.  I decided to repackage the issue in this PR and merge all the other changes in the previous PR.
I made the class names start with Test so pytest collects it to run.  I also changed from nose style `setUp` to pytest style `setup_method`.
Any idea how to fix this?
> Enable ThinGraph tests

- networkx/generators/small.py
- networkx/generators/tests/test_small.py
Fixes #3431 
Checked that `ltype` was either **adjacencylist/edgelist**, else raised an error. Also added a tiny test for the same. Also refractored a single line in the test file as it was too long as per *pycodestyle*.
Please let me know if something else needs to be modified.
> Fix issue 3431: Return error in case of bad input to make_small_graph

- networkx/drawing/nx_pylab.py
This PR adds the colomap and colomap limits to the LineCollection returned by draw_networkx_edges.  This allows the correct edge colormap to be added to the figure after it's created.  Since graphics are hard to test, here is the code I used to test this out.
```
import numpy as np
import matplotlib.pylab as plt
G = nx.grid_2d_graph(4, 4)  # 4x4 grid
H = G.to_directed()
pos = nx.spring_layout(G, iterations=100)
node_values = np.random.rand(H.number_of_nodes())+1 # values between 1 and 2
edge_values = np.random.rand(H.number_of_edges())+2 # values between 2 and 3
plt.figure()
ax = plt.gca()
nodes = nx.draw_networkx_nodes(H, pos, nodelist=list(H.nodes()), 
node_color=node_values,
vmin=1, vmax=2,
cmap=plt.cm.winter, ax=ax)
edges = nx.draw_networkx_edges(H, pos, …
```
> Add colormap and color limits to LineCollection

- networkx/drawing/tests/test_pylab.py
- requirements/extras.txt
Fix #3694.
The test was added b/c of #3295.
The graph
```
G = nx.path_graph(3, create_using=nx.MultiDiGraph)
```
I made the third node have size 0.  Does that seem reasonable?
> WIP: Fix matplotlib deprecation

- CODE_OF_CONDUCT.rst
- doc/developer/code_of_conduct.rst
- doc/developer/index.rst
/cc @dschult @jarrodmillman @hagberg 
To bring NetworkX in line with requirements for NumFOCUS affiliation.
I'm busy publishing a formal markdown translation of the NumFOCUS CoC [here](https://github.com/numfocus/numfocus/pull/31) that we can use once it has been merged.
> Add NumFOCUS CoC

- doc/conf.py
This should help search engines return the stable docs as the canonical source.
> Use canonical url to help search engines

- networkx/__init__.py
- networkx/release.py
- setup.py
The [Python packaging specifications](https://packaging.python.org/specifications/core-metadata) indicate that the [`license` parameter](https://packaging.python.org/specifications/core-metadata/#license) to `setup()` should be used in one of the following cases:
* the license is not a selection from the “License” Trove classifiers
* to specify a particular version of a license which is named via the `Classifier` field
* to indicate a variation or exception to such a license
This PR removes the explicit `license` parameter since the usage for this project does not fit any of those cases and it makes it more difficult to use tools like [pip-licenses](https://pypi.org/project/pip-licenses) since it is not consistent with other projects that just have `License :: OSI Approved :: BSD License` …
> Remove duplicate license parameter

- networkx/algorithms/approximation/connectivity.py
- networkx/algorithms/bipartite/basic.py
- networkx/algorithms/bipartite/matching.py
- networkx/algorithms/centrality/degree_alg.py
- networkx/algorithms/centrality/voterank_alg.py
- networkx/algorithms/components/attracting.py
- networkx/algorithms/components/biconnected.py
- networkx/algorithms/components/connected.py
- networkx/algorithms/components/semiconnected.py
- networkx/algorithms/components/strongly_connected.py
- networkx/algorithms/components/weakly_connected.py
- networkx/algorithms/connectivity/disjoint_paths.py
- networkx/algorithms/connectivity/edge_augmentation.py
- networkx/algorithms/connectivity/edge_kcomponents.py
- networkx/algorithms/connectivity/kcomponents.py
- networkx/algorithms/distance_measures.py
- networkx/algorithms/flow/gomory_hu.py
- networkx/algorithms/node_classification/hmn.py
- networkx/algorithms/node_classification/lgc.py
- networkx/algorithms/planarity.py
- networkx/drawing/layout.py
- networkx/generators/community.py
- networkx/generators/triads.py
This takes care of a couple of function in which the documentation of raised exceptions had gone bad. For instance, in [`flow.gomory_hu_tree`](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.flow.gomory_hu_tree.html#networkx.algorithms.flow.gomory_hu_tree), the documentation currently looks as follows:
We take care of all cases where this particular issue showed up; that is,
```
grep -r --include \*.py ": Exception"
```
outputs nothing after the fix.
> Fix documentation issues for exceptions in a few places

- networkx/algorithms/clique.py
- networkx/algorithms/flow/networksimplex.py
- networkx/drawing/tests/test_pydot.py
- networkx/readwrite/gml.py
- networkx/readwrite/gpickle.py
- networkx/readwrite/graphml.py
- networkx/readwrite/json_graph/jit.py
This removes some of the last remaining bits of Python 2 support.
@dschult Should we deprecate `literal_stringizer` and `literal_destringizer` in `networkx/readwrite/gml.py` (and remove it in nx 2.6)?  According to the documentation,
```
For better interoperability of data generated by Python 2 and Python 3,
we've provided `literal_stringizer` and `literal_destringizer`.
```
> Remove old Python 2 code

- networkx/algorithms/core.py
- networkx/algorithms/tests/test_core.py
NX is pruning edges incorrectly for k-truss. Specifically, NX is pruning edges that belong to fewer than k triangles. The correct definition is to remove edges that belong to fewer than (k-2) triangles. As such. NX is pruning edges in an aggressive manner.
The following links point to several verified sources that have the definition of k-truss (including the original paper by J. Cohen).
- https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.505.7006&rep=rep1&type=pdf  (page 6)
- https://graphchallenge.mit.edu/sites/default/files/documents/SubGraphChallenge-2017-02-09.pdf
- https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.505.7006&rep=rep1&type=pdf (page 2 on the bottom right)
This PR also fixes the problem.
> K-truss is defined for edges being in (k-2) triangles and not for k triangles

- .travis.yml
- networkx/readwrite/tests/test_gexf.py
readwrite.tests.test_gexf.TestGEXF.test_numpy_type failed under Python
3.8 due to ordering of XML attributes, handle it as per f75dbe8. Also
change travis to no longer allow failures under 3.8.
Fixes #3720
> Fix test_numpy_type to pass under Python 3.8

- examples/basic/plot_read_write.py
- examples/drawing/plot_atlas.py
- examples/drawing/plot_chess_masters.py
- examples/drawing/plot_circular_tree.py
- examples/drawing/plot_giant_component.py
- examples/drawing/plot_knuth_miles.py
- examples/drawing/plot_lanl_routes.py
- examples/drawing/plot_sampson.py
- examples/drawing/plot_spectral_grid.py
- examples/drawing/plot_unix_email.py
- examples/graph/plot_karate_club.py
- examples/graph/plot_roget.py
- examples/graph/plot_words.py
- examples/javascript/force.py
- examples/pygraphviz/plot_write_dotfile.py
- examples/subclass/plot_printgraph.py
Fix #3692.
I started by, for example, adding a line like
```
The data file can be found at:
- https://github.com/networkx/networkx/blob/master/examples/drawing/sampson_data.zip
```
to `plot_sampson.py`.
I also removed several `try` and `except` import blocks.  For example, I replaced things like
```
try:
import pygraphviz
from networkx.drawing.nx_agraph import graphviz_layout
except ImportError:
try:
import pydot
from networkx.drawing.nx_pydot import graphviz_layout
except ImportError:
raise ImportError("This example needs Graphviz and either PyGraphviz or pydot")
```
with
```
from networkx.drawing.nx_agraph import graphviz_layout
```
There are also a few other miscellaneous changes.
> Add links to data files

- .appveyor.yml
- .travis.yml
- doc/conf.py
- networkx/algorithms/community/quality.py
- networkx/algorithms/connectivity/tests/test_kcomponents.py
- networkx/algorithms/connectivity/tests/test_kcutsets.py
- networkx/algorithms/flow/tests/test_gomory_hu.py
- networkx/algorithms/flow/tests/test_maxflow_large_graph.py
- networkx/algorithms/shortest_paths/weighted.py
- networkx/algorithms/similarity.py
- networkx/conftest.py
- networkx/tests/test_all_random_functions.py
- networkx/tests/test_convert_pandas.py
- requirements/README.md
- requirements/extras.txt
- requirements/optional.txt
- tools/travis/build_docs.sh
- tools/travis/script.sh
My goal is to make the tests faster and to run more tests in more configurations.
Before changing anything, the 9 slowest tests account for over half the test time 
```
========================= slowest 10 test durations ===========================
51.69s call     algorithms/flow/tests/test_gomory_hu.py::TestGomoryHuTree::test_les_miserables_graph_cutset
36.20s call     algorithms/connectivity/tests/test_kcomponents.py::test_torrents_and_ferraro_graph
25.45s call     algorithms/connectivity/tests/test_kcutsets.py::test_alternative_flow_functions
14.92s call     algorithms/connectivity/tests/test_kcutsets.py::test_torrents_and_ferraro_graph
11.97s call     algorithms/connectivity/tests/test_kcomponents.py::test_shell
8.11s call …
```
> CI refactor

- networkx/readwrite/gml.py
- networkx/readwrite/tests/test_gml.py
Taking a stab at issue https://github.com/networkx/networkx/issues/3511
As I got into this, I realized it is tricky, and it seems as though it isn't possible to support lists fully. The list syntax cited in the issue is actually a dictionary key/value description. The way i've implemented the change is that the example,
```
graph [
node [
id 0
label "n1"
properties [
0 "a"
1 "b"
]
]
]
```
gets `properties` parsed as `OrderedDict([(0, "a"), (1, "b"])`. this gets us
* ability to index like a list, e.g. `graph.nodes(data=True)["n1"][1] >> "b"`
* ability to iterate e.g. `for index, value in enumerate(graph.nodes(data=True)["n1"])`
however, its perhaps surprising that if you write in a property with lists, you get back a dictionary.
I had thought that maybe an alternative would be to not …
> 3511 gml list support

- networkx/drawing/nx_pylab.py
When plotting a directed graph, linestyle is not set
from matplotlib import pyplot as plt
G = nx.DiGraph()
G.add_nodes_from([0,1])
G.add_edge(0,1)
pos = {0 : (0,0), 1 : (1,0)}
plt.figure()
nx.draw_networkx_nodes(G,pos=pos)
nx.draw_networkx_edges(G,pos=pos,style='dashed',arrows=True)
plt.show()
This results in a solid line between two nodes, instead of a dashed one. If arrows is set to False, the line is dashed, but of course there is no arrow anymore.
> added linestyle as argument

- networkx/generators/lattice.py
Trying to give a tuple of dimensions to networkx.grid_graph results in an exception:
from networkx import grid_graph
G = grid_graph(dim=(2, 3, 4))
File "[..]\Python38-32\lib\site-packages\networkx\generators\lattice.py", line 130, in grid_graph        
dlabel = "%s" % dim
TypeError: not all arguments converted during string formatting
That's despite the documentation saying "dim : list **or tuple** of numbers or iterables of nodes"
Well, since that variable is a leftover from some previous refactoring and is unused, we can just remove it.
I also changed the syntax to tuples in the documentation examples (because it's slightly more efficient and so a better style) and manually verified with doctest. This can also help with detecting regressions, though I'm not sure if your pytest …
> Remove unused variable so grid_graph() supports dim=tuple

- networkx/algorithms/centrality/eigenvector.py
- networkx/algorithms/centrality/subgraph_alg.py
- networkx/algorithms/link_analysis/hits_alg.py
- networkx/algorithms/link_analysis/pagerank_alg.py
- networkx/convert.py
- networkx/convert_matrix.py
- networkx/exception.py
- networkx/linalg/algebraicconnectivity.py
- networkx/linalg/attrmatrix.py
- networkx/linalg/bethehessianmatrix.py
- networkx/linalg/graphmatrix.py
- networkx/linalg/laplacianmatrix.py
- networkx/linalg/modularitymatrix.py
- networkx/linalg/spectrum.py
- networkx/linalg/tests/test_algebraic_connectivity.py
- networkx/linalg/tests/test_attrmatrix.py
- networkx/linalg/tests/test_bethehessian.py
- networkx/linalg/tests/test_laplacian.py
- networkx/linalg/tests/test_modularity.py
- networkx/linalg/tests/test_spectrum.py
- networkx/relabel.py
- networkx/tests/test_convert.py
- networkx/tests/test_convert_numpy.py
- networkx/tests/test_convert_scipy.py
- networkx/tests/test_relabel.py
@dschult This PR replaces things like `scipy.array` with `numpy.array`.  SciPy will remove these when they eventually release 2.0 and they are making noise in our test suite now.  Everything is straightforward except `scipy.sqrt`, which maps to `numpy.lib.scimath.sqrt` instead of `numpy.sqrt`.  Here is the difference:
```
>>> import numpy as np  
>>> import scipy as sp      
>>> sp.sqrt(-1)
1j
>>> np.lib.scimath.sqrt(-1)   
1j
>>> np.sqrt(-1)  
__main__:1: RuntimeWarning: invalid value encountered in sqrt
nan
```
Should we continue allowing negative square roots in this context?  I suspect not and am tempted to use `numpy.sqrt`.  I highlighted the two instances below.
> WIP: Fix scipy deprecation warnings

- networkx/conftest.py
@dschult This PR silences a ton of warnings in the test reports.   We need to fix them eventually, but they make it hard to see new warnings.  Please feel free to merge this once you've looked over the change.
> Silence known warnings

- networkx/drawing/nx_pylab.py
A user may want to draw bidirected edges.
e.g., CurveFilledAB	<|-|>
in `matplotlib.patches.FancyArrowPatch`
Hence, `shrink_source` needs to be calculated as `shrink_target` is determined.
> Shrink the source side of an arrow properly when drawing a directed edge. #3805

- networkx/algorithms/isomorphism/tests/test_isomorphvf2.py
- networkx/algorithms/isomorphism/vf2userfunc.py
For #3775, checks that core_1[neighbor] is in G2's adj before checking edge_match for semantic feasibility.
Checking for monomorphism for MultiDiGraph seems like it may be more subtle than I thought, so this just handles DiGraphs.
> Prevent KeyError on subgraph_is_monomorphic

- networkx/generators/random_graphs.py
- networkx/generators/tests/test_random_graphs.py
In it's present form, the `random_lobster` generator function produces valid lobsters with multiple leaves, but it's only capable of producing an extremely small subset of the allowable lobsters which fit the general definition of "a tree having the property that the removal of leaf nodes leaves a caterpillar graph" and where a caterpillar graph is on in which all leafs are only one edge from a continuous path graph.
To illustrate the present limitation I've created a 15 node lobster graph with the original implementation:
``` python
g = nx.random_lobster(15, 0.6, 0.5, seed=42)
pos = nx.nx_pydot.pydot_layout(g)
nx.draw(g, pos=pos)
```
This graph is clearly a valid lobster, and clearly has multiple leaves. However, none of the branches from the main path will ever fork even though it's …
> reconsider the lobster generator

- networkx/algorithms/connectivity/cuts.py
- networkx/algorithms/connectivity/tests/test_cuts.py
Fixes #3846 
As given in the issue description, replaced the list with set and changed the test that was expecting a list to make it expect a set. Please review and tell if anything else is to be done.
> make return value of minimum_st_node_cut consistently a set

- networkx/utils/misc.py
A straightforward simplification.
> Remove unused variable has_numpy from create_py_random_state

- networkx/drawing/nx_pylab.py
- networkx/drawing/tests/test_pylab.py
drawing an empty collection of nodes returns an empty PathCollection.
drawing an empty collection of edges returns (i) an empty LineCollection if neither a given graph is a directed graph nor `arrows` is enabled, (ii) an empty list, otherwise.
> Fix return values when drawing empty nodes and edges  #3833

- CONTRIBUTING.rst
I saw that in CONTRIBUTING.rst that is wasn't clear that you had to navigate to the folder before adding the upstream repo. So I added that to make sure that that was clearer for newbies like me.
> Made CONTRIBUTING.rst more clearer

- networkx/readwrite/pajek.py
Resolves #3910
Tested with Python 2.7 and 3.8
Preserves the original error message and adds the extra information as an additional argument.
> In Pajek export add extra information when casting 'id' to int() fails.

- networkx/generators/expanders.py
- networkx/generators/tests/test_expanders.py
Hi,
I'm a young researcher in math with a keen interest in graphs. I've been using networkx a lot recently so I'd like to start contributing.
I've been doing some work around expanders, a class of regular graphs for which there are only two generators currently available in networkx. This is a proposal to add the class of Paley graphs, a family of graphs on p nodes obtained by matching x and y iif y-x is a square mod p. 
Said graphs are indeed regular when p is a prime number (there are (p-1)/2 distinct squares in this case).
I tried to match the style of existing functions in expanders.py and the associated test, but any feedback would be greatly appreciated.
Thanks,
Patrick
P.S : below is a visualization of Paley graphs for a few increasing values of p:
> add paley graph

- networkx/readwrite/graphml.py
- networkx/readwrite/tests/test_graphml.py
Provide the option to give the `<key>` elements' `id` attribute the same value as the `attr.name`'s attribute value.
```
<?xml version='1.0' encoding='utf-8'?>					<?xml version='1.0' encoding='utf-8'?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:	  |	<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:
<key id="d1" for="node" attr.name="prop2" attr.type="string"/	  |	<key id="prop2" for="node" attr.name="prop2" attr.type="strin
<key id="d0" for="node" attr.name="prop1" attr.type="string"/	  |	<key id="prop1" for="node" attr.name="prop1" attr.type="strin
<graph edgedefault="directed"><node id="0">				<graph edgedefault="directed"><node id="0">
<data key="d0">val1</data>					  |	  <data key="prop1">val1</data>
<data key="d1">val2</data>					  |	  <data …
```
> Add option for named key ids to GraphML writing.

- networkx/convert_matrix.py
- networkx/tests/test_convert_pandas.py
`nx.to_pandas_edgelist()` will now check the source and target column names individually and raise a `NetworkXError` if there is a detected conflict.
Two tests also added to verify this. They try to convert a graph with source and target column names that already exist as attributes. They will only assert True if a `NetworkXError` is raised, otherwise they will assert False.
> Fix for #3930 (source & target columns not overwritten when converting to pd.DataFrame)

- networkx/algorithms/centrality/voterank_alg.py
As mentioned in Issue #3826, in the current implementation of VoteRank, the voting ability of a few nodes could become negative.
This was because step 4 of the reference paper was wrongly implemented. Step 4 states that the voting ability is updated only if the new value doesn't become negative. This is fixed in the pull request.
> Correct VoteRank Algorithm to align with reference paper and avoid negative voting ability

- doc/reference/utils.rst
- networkx/algorithms/components/strongly_connected.py
- networkx/algorithms/shortest_paths/generic.py
- networkx/algorithms/tests/test_dominance.py
- networkx/conftest.py
- networkx/utils/contextmanagers.py
The context manager reverses a DiGraph in-place which doesn't work well in multithread environments. (see #3936 ) The ```reversed_view``` a.k.a. ```G.reverse(copy=False)``` feature does the same as reversed, but you have to check if G is undirected.
This set of changes replaces code that uses the context_manager with the view. It also marks the context manager as deprecated and removes it from the documentation. Scheduled for removal in v2.7
Fixes #3936
> Deprecate context_manager reversed in favor of reversed_view

- CONTRIBUTORS.rst
- doc/reference/algorithms/d_separation.rst
- doc/reference/algorithms/index.rst
- networkx/algorithms/__init__.py
- networkx/algorithms/d_separation.py
- networkx/algorithms/tests/test_d_separation.py
This PR implements an algorithm for testing _d-separation_ in DAGs. _d_separation_ is a central concept in probabilistic graphical models and it is used for testing conditional independence between random variables. 
Given that many libraries for probabilistic graphical models (like Pomegranate, Pyro etc) use NetworkX, it is somewhat surprising that this hasn't made its way into NetworkX so far. While the application is for probabilistic graphical models, the concept is purely graph theoretical. So, I hope that it gets added to the NetworkX library.
> add d-separation algorithm

- networkx/algorithms/dag.py
I recently went over [Matplotlib](https://github.com/matplotlib/matplotlib/pull/16706), [Pandas](https://github.com/pandas-dev/pandas/pull/32322) and [NumPy](https://github.com/numpy/numpy/pull/15731), fixing a small mistake in the way that Python 3's exception chaining is used. If you're interested, I can do it here too. I've done it on just one file right now. 
The mistake is this: In some parts of the code, an exception is being caught and replaced with a more user-friendly error. In these cases the syntax `raise new_error from old_error` needs to be used.
Python 3's exception chaining means it shows not only the traceback of the current exception, but that of the original exception (and possibly more.) This is regardless of `raise from`. The usage of `raise from` tells Python to put a …
> Fix exception causes in dag.py

- CONTRIBUTING.rst
Adds a step to the procedure for first-time contributors in the contribution guidelines that encourages users to run the test suite locally. Links to other sections on setting up the build environment and testing later in the same document.
> DOC: Add testing bullet to CONTRIBUTING.rst

- doc/tutorial.rst
Set `None` to monospace in tutorial.
> Improve formatting of None in tutorial

- networkx/readwrite/graphml.py
- networkx/readwrite/tests/test_graphml.py
This fixes a bug where np.float64 values are given an integer type in the GraphML file, which leads to parsing errors.
> Correctly infer numpy float types

- networkx/readwrite/graph6.py
Closes #4032
The argument for `from_graph6_bytes` was originally named "string" but
the function expected a bytes object. Fixes the mismatch between
implementation and naming convention by updating argument name from
"string" to "bytes_in". Updates associated docstring accordingly.
More extensive changes are possible (e.g. adding an `isinstance` check),
but IMO updating the variable name/docstring signature is sufficient to
resolve the ambiguity in this case.
> MAINT: Update from_graph6_bytes arg/docs.

- networkx/generators/community.py
- networkx/generators/tests/test_community.py
As far as I understand, the connected caveman graph isn't defined when the size of cliques is < 2. However, there are no constraints on the parameters of the function `nx.generators.community.connected_caveman_graph()`: https://github.com/networkx/networkx/blob/eb75efa80831a08d58f17e54db20e1bfc11b67cc/networkx/generators/community.py#L85, and when called with `l=1`, the function raises the following somewhat unclear error:
```python
>>> nx.connected_caveman_graph(3, 1)
NetworkXError: The edge 0-1 is not in the graph
```
The PR ensures a slightly more informative error is raised when the function is called with `l=1`.
> Raise NetworkXError when k < 2

- networkx/algorithms/assortativity/correlation.py
- networkx/linalg/algebraicconnectivity.py
Partially addresses #3107.
Removes the use of numpy `matrix` objects from the implementation of two functions, one private and one public.
* 26e1e60 re-implements `_tracemin_fiedler` using `@` and `np.atleast_2d` in place of the corresponding functionality provided by the `matrx` class. 
* ac7678d does the same for the public `attribute_ac` function
This PR does introduce subtle differences in un-tested behavior. For example, the `asmatrix` function is not strictly equivalent to `atleast_2d` w.r.t. shape checking: the former will raise an exception if the input array has ndim > 2. In the case of `_tracemin_fiedler`, it is only intended for internal use and I didn't notice any codepaths that could generate input arrays with `ndim > 2`. For `attribute_ac`, there is a reduction in the amount …
> MAINT: Remove instances of np.matrix used in internal code.

- networkx/linalg/tests/test_algebraic_connectivity.py
Refactors `test_algebraic_connectivity.py` using pytest's parametrization facilities to break up tests into more fine-grained units (while maintaining the original class-based organization of the tests). Replacing the loops over certain kwargs (e.g. `method`) in the test suite gives more specific failures to help pinpoint potential problems (stumbled across this in conjunction with #4045).
A quick summary of the number/runtime of tests:
**Before**: ``19 passed in 0.48s``
**After**: ``83 passed in 0.63s``
So about 4x increase in test granularity at the cost of ~30% runtime increase.
> MAINT,TST: Parametrize algebraic connectivity tests

- networkx/classes/reportviews.py
- networkx/classes/tests/test_reportviews.py
I took the advice of last time and this time I think I am close, but I am still having trouble with the MultiEdge class family tests.
From what I can tell, it seems that as soon as you pass an `nbunch` parameter to the `EdgeView` cosntructor (and those of its family), it automatically redirects to an (associated) `EdgeDataView`. For this reason I didn't implement any nbunch check logic because it seems to already be handled in the associated EdgeDataViews.
However now it seems to be failing whenever it runs the `test_contains` function in the context of any `MultiEdge` class. It seems to me that this function is just run in all of its subclasses and can no longer handle the new restriction of edges via the `nbunch`. Could it be that this test was only passing due to the presence of the …
> WIP: Change EdgeDataView __contains__ feature (2nd attempt)

- networkx/drawing/layout.py
Fixed typo issue in "kamada_kawai_layout" method in "layout.py" file (Issue #3665 ).
> Fixed typo in kamada_kawai_layout doc string (Issue #3665)

- networkx/algorithms/bipartite/matching.py
- networkx/algorithms/bipartite/tests/test_matching.py
When first implementing `minimum_weight_full_matching`, we were still only requiring a SciPy version of 1.1.0, which meant that we had to require that the bipartite graph was complete. This requirement was removed in SciPy 1.4, and now (with 8d8aa86eede1bccc160af73e823492357196b341) that NetworkX specifies a minimum SciPy requirement of 1.4, the requirement can be removed here as well.
The only gotcha is that we can no longer use `biadjacency_matrix(...).toarray()`, which would leave unexisting edges with a value of 0, when what we need is actually `np.inf`; we handle this by explicitly creating an all-`np.inf` array, then populate it with the weights of the edges we do have.
> Remove completeness condition from minimum weight full matching

- networkx/algorithms/traversal/breadth_first_search.py
- networkx/algorithms/traversal/tests/test_bfs.py
Allow client to pass a function that customize the order in which neighboring nodes are queued.
> add the option of sorting node's neighbors during bfs traversal 

- networkx/algorithms/bipartite/matching.py
The documentation currently refers to "mate", which is not defined anywhere. It
could seem like that's simply an earlier name for the output directory, and we
update the documentation accordingly.
> Fix a few typos in documentation of implementations of maximum matching

- networkx/convert_matrix.py
- networkx/tests/test_convert_scipy.py
The nx.to_scipy_sparse_matrix(G, nodelist=None, dtype=None, weight='weight', format='csr') function will raise a ValueError if the the input graph G contains selfloops, but the subgraph induced on the input nodelist does not contains any selfloop. For example:
>>> g = nx.Graph()
>>> g.add_edges_from([[0,0],[1,2],[1,3]])
>>> nx.to_scipy_sparse_matrix(g, [1,2])
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "XXX/networkx/convert_matrix.py", line 845, in to_scipy_sparse_matrix
for u, v, d in selfloops
ValueError: not enough values to unpack (expected 2, got 0)
So when we subtract the data on the diagonal to avoid selfloop entries get double counted when symmetrizing, we only judge if the subgraph induced on the input nodelist contains selfloops, otherwise, we do …
> fix bug for to_scipy_sparse_matrix function

- networkx/drawing/nx_agraph.py
I noticed a memory leak in a downstream application that reads a ton of dot files and converts them to networkx objects using `read_dot` function. My application crashed after reading about 500 dot files (each has around 500 nodes). Upon inspecting the `nx_agraph.py` file, I noticed that the pygraphviz object created during `read_dot` is not cleared. This PR fixes the memory leak issue by first creating networkx object (the one we want to return) and then clearing the intermediate pygraphviz object.
P.S : The reverse function `write_dot` does indeed clear the intermediate object.
> Clear pygraphviz object after creating networkx object

- tools/travis/osx_install.sh
> Formulae that declare an unconditional dependency on the "python" formula are bottled against Homebrew’s Python 3.x and require it to be installed.
``graphviz``  declares an unconditional dependency on the "python", which is now 3.8 by default.  And
> WARNING: When you brew install formulae that provide Python bindings, you should not be in an active virtual environment.
So I moved the brew install before we create the venv.
NOTE:  Quotes are from https://docs.brew.sh/Homebrew-and-Python
> Install Python after updating brew

- networkx/generators/random_graphs.py
The functions `gnp_random_graph`, `binomial_graph` and `erdos_renyi_graph` are all aliases of each other. 
However current documentation reads like this, "_The functions `binomial_graph` and `erdos_renyi_graph` are aliases of this function._". 
This is a bit unclear. To improve clarity, this PR changes the wording of the documentation to "_The functions `gnp_random_graph`, `binomial_graph` and `erdos_renyi_graph` are aliases of each other._"
> Improves docs regarding aliases of erdos-reyni graph generators

- INSTALL.rst
The info on required versions of dependencies in INSTALL.rst had gotten out-of-sync with the actual requirements files. Rather than update them, I removed the version info from INSTALL and replaced it instead with a link to the requirements folder so that version info doesn't need to be maintained in multiple documents.
Currently, the link is external as the `requirements/` folder is not included in the docs build, though I could include it and use an internal link if that is preferred.
Also removed a note about needing to compile C/C++ for SciPy as this is generally not the case anymore.
> MAINT: Remove dependency version info from INSTALL

- networkx/linalg/laplacianmatrix.py
The docstrings for most of the functions in the
`laplacianmatrix` module listed incorrect types for the objects
returned by the functions.
This PR fixes the return types so they match the current implementations. The implementations themselves will likely be modified as part of the #3107 cleanup.
> DOC: Fix return types in laplacianmatrix.

- doc/reference/algorithms/community.rst
Fixes #4095 
modularity function was never added to docs when added to quality.py
> add modularity to the docs

- networkx/generators/spectral_graph_forge.py
Replaces `_truncate` which was used in spectral_graph_forge to limit values to the interval `[0.0, 1.0]` with `np.clip`.
> MAINT: replace private function in favor of numpy builtin.

- networkx/classes/multigraph.py
- networkx/convert_matrix.py
- networkx/tests/test_convert_pandas.py
Adding PR for feature stated in issue #4065, regarding the ability to provide a custom key for multigraphs in the from_pandas_edgelist function. Code currently (as stated in issue) deals with duplicate keys by overwriting them, and I will look into better mechanisms in future PRs. Tests have been added and code was run through black.
> Allow custom keys for multiedges in from_pandas_edgelist

- INSTALL.rst
- networkx/algorithms/bipartite/matrix.py
- networkx/algorithms/bipartite/spectral.py
- networkx/algorithms/centrality/second_order.py
- networkx/algorithms/centrality/subgraph_alg.py
- networkx/algorithms/centrality/tests/test_trophic.py
- networkx/algorithms/link_analysis/hits_alg.py
- networkx/algorithms/non_randomness.py
- networkx/algorithms/shortest_paths/dense.py
- networkx/algorithms/tree/tests/test_branchings.py
- networkx/convert_matrix.py
- networkx/generators/spectral_graph_forge.py
- networkx/linalg/bethehessianmatrix.py
- networkx/linalg/graphmatrix.py
- networkx/linalg/laplacianmatrix.py
- networkx/linalg/modularitymatrix.py
- networkx/linalg/spectrum.py
Related to the cleanup in #3107 
Replaces all internal instances (i.e. when used in the implementation of the function, but not affecting the output - see #3107 for details) of `to_numpy_matrix` and `from_numpy_matrix` with `to_numpy_array` and `from_numpy_array`. In preparation for the deprecation of the `*_numpy_matrix` functions.
If the changes are approved, I would propose that I squash this down to 2 commits, one for doc-only changes and one for code changes.
> MAINT: Replace internal usage of to_numpy_matrix and from_numpy_matrix

- doc/credits.rst
- doc/reference/algorithms/clique.rst
- networkx/algorithms/clique.py
I forgot to add the max_weight_clique function (#4016) to the documentation, so I have added it in this pull request. I have made a few minor changes to the function's docstring, such as correcting the syntax for italics and references. I have also also added my name to the list of contributors.
I'd also like to say a quick "thank you" to @dschult and @jarrodmillman for reviewing and merging my code in #4016. This was my first contribution to a large piece of software, and it has been an enjoyable experience.
> Add max_weight_clique to doc

- networkx/algorithms/community/quality.py
- networkx/algorithms/community/tests/test_quality.py
I've improved the runtime of the modularity calculation for a partition of a graph and simplified the function.
As mentioned in #4095 the modularity function not appearing in the documentation prompted me to implement it myself. Based on ["Finding community structure in very large networks"](https://arxiv.org/abs/cond-mat/0408187) and the lecture I was hearing at university, there is a more simplified approach to calculating the modularity of a partition of a graph. The simplification can be found in equation (7) in the [pdf of the paper](https://arxiv.org/pdf/cond-mat/0408187.pdf).
The simplified calculation seems to run 3 times as fast as the original function on some graphs, at least judging based on one test on [this commit](https://github.com/bernwaldl/networkx/commit/a7f5a5247392f47f …
> Improve modularity calculation

- doc/_static/custom.css
- doc/conf.py
- doc/credits.rst
- doc/team.rst
- tools/team_list.py
The ``team.rst`` page is generate from the NetworkX GitHub teams via:
```
python tools/team_list.py > doc/team.rst
```
Eventually I will add it to Travis-CI.   It needs some minor fixes and we may want to put it somewhere else.  This is based on:
https://github.com/scikit-image/scikit-image-web/pull/69
> Add team gallery

- .circleci/config.yml
- .github/workflows/circleci.yml
First part of addressing #4118 - this PR adds a circleCI config defining a workflow for building the documentation. Note that this workflow is *only* for documentation building - testing remains on travis.
Note: I set this up within the NetworkX organization so that all members of the organization *should* have full access on CircleCI to modify settings etc. This will likely require some additional tweaking but if there are access problems please let me know.
> CI: Setup circle CI for documentation builds

- networkx/readwrite/edgelist.py
- networkx/readwrite/tests/test_edgelist.py
Fixes #4116 
Multiple edge attributes are now parsed correctly. Additional test cases have been added.
> Fix parse_edgelist behavior with multiple attributes

- .circleci/config.yml
The CircleCI build intermittently fails to install the necessary dependencies for building the latex doc via the container's package manager (`apt-get`). This PR switches to a more modern version of Debian with the hope that the base-OS package management will be more reliable.
> CI: hypothetical fix for CI latex installation issues

- networkx/convert.py
Refactors `to_networkx_graph` to use ABCs from `collections.abc` for the `isinstance` checks which map the input data to the corresponding sub-function that does the conversion. The main improvement is that this replaces a hand-curated list of types (list, set, tuple, etc.) with the more general ABCs. A couple points that need special attention:
- I removed the `hasattr` checks for `_adjdict` and `next` though I'm not sure which kinds of objects they were designed to check. The test suite didn't complain about this, but if there are objects/types that depended on these (that perhaps aren't tested) please LMK.
- The execution order has to be modified for this check to work. Since the ABC-based check is the most general, I moved it to the last `if` (right before the final `raise` when the …
> MAINT: Switch to abc-based isinstance checks in to_networkx_graph

- networkx/algorithms/simple_paths.py
> Use dict instead of OrderedDict since dict is ordered by default from Python 3.6

- networkx/readwrite/edgelist.py
Some minor maintenance to `parse_edgelist` originating from review of #4125. This will cause merge conflicts with #4125, which should have higher priority. Changes include:
* Catch Exception rather than BaseException
* Add default values to docstring
* Fix poorly-formatted f-strings.
> MAINT: fixups to parse_edgelist.

- .circleci/config.yml
We were still getting errors on circleci.  The errors end with
```
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
I don't use Debian, so I am just guessing:  I suspect the image has an out-of-date apt cache and it is trying to install things with old/incorrect names.  Running ``sudo apt-get update`` updates the list of available packages and their versions.  So I suspect it will fix issues like this [one](https://app.circleci.com/pipelines/github/networkx/networkx/74/workflows/8494bd33-b0ab-48e0-83e3-e3f57961ec30/jobs/82) where it states:
```
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/r/ruby2.5/libruby2.5_2.5.5-3+deb10u1_amd64.deb  404  Not Found [IP: 199.232.64.204 80]
```
When I went to the website, it had …
> Update apt-get on circleci image

- networkx/relabel.py
- networkx/tests/test_relabel.py
Fixes #4058.
In a multigraph, relabeling two or more nodes that share predecessors into the same new label will preserve all edges, but will change the edge keys in the process. Previously, edge keys were not changed, but if edges ended up having the same (tail, head, key) tuple after the relabel, only one of those edges would be inserted into the relabeled graph.
> relabel_nodes now preserves edges in multigraphs

- networkx/drawing/nx_agraph.py
- networkx/drawing/tests/test_agraph.py
Improves the test coverage of `networkx/drawing/nx_agraph` module from ~85% -> 94%. Most of the improved coverage is related to keyword arguments whose non-default values were uncovered. This PR also includes a few ancillary fixes including things like fixing docstring formatting issues, fixing typos, etc. I'm happy to pull these out into a separate PR if it will make this easier to review. 
A couple notable points:
- Currently, there is no way to suppress the opening of the rendered graphs from `view_pygraphviz` (assuming an appropriate graph viewer is installed on the system). This means that running the test suite will open 2 new windows. With the additional tests in this PR, many more (>10 new windows) are opened. I've proposed a new kwarg in #4155 that allows users to toggle the …
> MAINT,TST: Improve coverage of nx_agraph module

- doc/developer/deprecations.rst
- networkx/drawing/nx_agraph.py
- networkx/drawing/tests/test_agraph.py
Adds a new keyword argument to view_pygraphviz to toggle whether or not the graph produced by `view_pygraphviz` will actually be displayed.
Currently, there are tests in `test_agraph` that result in graphs being displayed via external viewers (platform dependent) but that don't actually test whether the rendered graphs are correct.
> API: Add `show` kwarg to view_pygraphviz.

- doc/developer/deprecations.rst
- networkx/algorithms/chordal.py
> Prepare for turning chordal_graph_cliques into a generator

- networkx/algorithms/threshold.py
Adds properly-formatted docstrings for `is_threshold_graph` and `find_threshold_graph` which were recently added to the reference documentation in #4161 .
> DOC: Update docstrings for public functions in threshold module

- networkx/readwrite/graphml.py
I just noticed there are two new warnings when building the docs on 99fc1bb6. This fixes one of them. The other is in `doc/release/release_dev.rst` (line 276). I didn't change the latter as it seems the list is auto-generated from PR titles.
> DOC,BLD: Fix doc build warning from markup error.

- networkx/drawing/nx_pylab.py
This PR fix some issues with the Parameters section of the docstring for ``draw_networkx_edge_labels()``. Summary of the changes:
- ``clip_on`` was included as docstring parameter, but this isn't actually an argument accepted by the function - entry removed.
- Conversely, ``rotate`` is an acceptable argument, but there was no docstring entry - entry added.
- ``ax`` parameter was included twice - one entry removed.
- Erroneous default for ``font_size`` - fixed.
- Order of docstring parameters changed to match the function arguments order. This improves the readability of the docs.
PR also includes a fix for a typo on line 252.
Some of the other docstrings in nx_pylab.py would benefit from re-aligning the order of the parameters, making explicitly clear which parameters are optional, etc., …
> Some docstring fixes for draw_networkx_edge_labels() in nx_pylab.py + one typo

- networkx/tests/test_convert_pandas.py
Closes #4054 - hopefully for good this time. Applies the same explicit dtype to a df created in the test suite via the `DataFrame` constructor to prevent incorrect integer sizes being used on 32-bit platforms.
> TST: add dtype to pandas test

- doc/reference/algorithms/minors.rst
- networkx/algorithms/minors.py
- networkx/algorithms/tests/test_minors.py
Various updates in `algorithms/minors.py`:
* make `equivalence_classes` a public method
* tweak `quotient_graph` to accept partitions as dicts (of block labels as keys and block lists/tuples/sets as values)
* update `quotient_graph` docstring to provide examples to the user of how to use `equivalence_classes` to represent different representations of partitions in a form acceptable to `quotient_graph` (see discussion in https://github.com/networkx/networkx/pull/3839#issuecomment-675217619)
> Partitions for quotient graphs

- networkx/readwrite/graphml.py
- networkx/readwrite/tests/test_graphml.py
> graphml: re-add graph attribute type 'long' after 857aa81 removed it

- networkx/readwrite/json_graph/cytoscape.py
Add missing parameter and additional sections to `cytoscape_data` docstring, and add a docstring to the `cytoscape_graph` function.
Related to discussion in #4173
> DOC: Update docstrings in cytoscape module

- networkx/algorithms/cluster.py
Remove multiple calls to `_triangles_and_degree_iter`.
This cuts the `transitivity` calculation time by half.
> MAINT: Speed up transitivity, remove redundant call

- doc/release/migration_guide_from_1.x_to_2.0.rst
> Fixed "topolgical_sort" typo

- doc/release/release_dev.rst
- networkx/convert_matrix.py
- networkx/tests/test_convert_numpy.py
- networkx/tests/test_convert_scipy.py
Currently, adding non-nodes to nodelist makes the created matrices have empty rows/columns showing an isolated node. But this (silently) means typos in nodelist create isolated nodes instead of raising an exception.
I don't think users should create isolated nodes when converting a graph to matrix form.
It seems better to raise an exception to "avoid surprises" at the cost of making people add the isolated nodes to G.
I'm proposing changing this to raise an error if nodelist contains nodes not in G. 
Strictly speaking this is not backward compatible because someone might have written code that depends on the matrix conversion adding the extra nodes. But if we raise an exception with a good message, it should be obvious what the trouble is and easy to fix.
> to_numpy/scipy array functions should not allow non-nodes in nodelist

- networkx/readwrite/json_graph/tree.py
one was duplicate and one was self-referential.  https://networkx.github.io/documentation/stable/reference/readwrite/generated/networkx.readwrite.json_graph.tree_data.html
> fix "see also" links in json_graph.tree

- networkx/utils/tests/test_unionfind.py
- networkx/utils/union_find.py
Previous versions in this area of code used `max()` to select the root of the heaviest set, but a fix for a different issue changed this to pull the first element from the sorted set of roots, i.e. the _lightest_ root, not the heaviest.
> Fix UnionFind.union to actually select the heaviest root as the new root

- .circleci/config.yml
- .travis.yml
Closes #4118 - configure CircleCI to deploy the development documentation. Largely drawn from the doc deployment configuration for [scipy](https://github.com/scipy/scipy/blob/master/.circleci/config.yml).
Other tasks (beyond reviewing the proposed configuration) to be done before removing draft status:
> CI: Configure circleCI to deploy docs.

- networkx/classes/function.py
- networkx/classes/tests/test_function.py
- networkx/convert_matrix.py
I was reading the discussion into #4139 and it led me to some questionable code in `nx.info`. For example, in a digraph we compute the average in-degree and out-degree by iterating over the nodes (twice), even though both `G.number_of_edges` and `G.number_of_nodes` are called earlier in the function. Unless I'm missing something (certainly possible), these are both equal to #nodes/#edges by definition. Similarly, the average degree in an undirected graph should just be double the ratio of edges to nodes.
This is a small refactor to eliminate redundant computation. In theory, it should make `nx.info` faster on large graphs, but using @rossbar's example of `nx.path_graph(int(1e7))` I got similar results before and after the changes. So maybe it's unnecessary, but I figured I'd leave that up …
> MAINT: Refactor nx.info

- networkx/algorithms/community/kernighan_lin.py
- networkx/algorithms/community/tests/test_kernighan_lin.py
initialize side list from input partition, must set index of members of A, not the element itself
> Fix indexing in kernighan_lin_bisection

- networkx/algorithms/shortest_paths/tests/test_weighted.py
Closes #4203 
The `heuristic` function for the weighted astar search test formerly computed the hash of the input. The hypothesis is that the hashing function can vary between platforms, which means that this test was not deterministic and could fail on some untested platforms.
Replaced `hash` with a sum-of-squares function which should be platform independent and give the minimum path result on all platforms.
> MAINT,TST: Replace hash function for test of weighted astar #4236 

- doc/developer/deprecations.rst
- doc/release/release_dev.rst
- networkx/conftest.py
- networkx/convert_matrix.py
- networkx/tests/test_convert_numpy.py
Adds deprecation warnings + associated tests to `to_numpy_matrix` and `from_numpy_matrix`. 
Originally, `from_numpy_array` as simply a pass-through function calling `from_numpy_matrix`. Re-organized so that `from_numpy_matrix` is now the pass-through, and the implementation is in `from_numpy_array` to make the removal easier down the road.
Added tests to ensure the deprecation warnings are raised, and warnings filters to suppress warnings related to `to/from_numpy_matrix` in the remainder of the test suite.
> MAINT: Deprecate numpy matrix conversion functions

- networkx/classes/function.py
- networkx/classes/graph.py
- networkx/classes/tests/historical_tests.py
- networkx/classes/tests/test_graph.py
Follow up to #4193 to close #4139.
Replaces the original `__str__` method of Graph and friends with the output from the newly-modified `nx.info`, which summarizes the name, number of nodes, and number of edges in a nice narrative form.
Modifies the test suite to check the new `__str__` output.
> Add nx.info to str dunder for graph classes

- networkx/algorithms/centrality/betweenness.py
The links in the betweenness_centrality documentation no longer point to live paper references. This PR updates the docstrings with evergreen DOI links instead! :)
> Fix betweenness_centrality doc paper links

- networkx/algorithms/euler.py
- networkx/algorithms/tests/test_euler.py
Fixes #4244
As @rossbar said, the description does not match the implementation for a directed graph. This pull request fixes this issue.
The new implementation adequately checks if  
> "every other vertex has equal in_degree and out_degree".
It also addresses another issue about isolated points. The definition states
> "and all of its vertices with nonzero degree belong to a single connected component of the underlying undirected graph."
The previous implementation ignored vertices that had "nonzero degree". In this one, I created a copy of the graph and removed the isolated points before checking if it was weakly connected.
The code works on the test case that @tlarock brought up. However, this test case has not yet been added to test_euler.py
> Updated has_eulerian_path 

- examples/drawing/plot_giant_component.py
As a first attempt, I tried reducing the alpha value for nodes that are not part of connected components to de-emphasize their contribution to the visualization overall. Making the non-connected nodes have consistent position between the axes is trickier than I expected as the layout is re-computed for each graph to take into account the new edges. It should be possible with a little set intersection code, but I went with the simplest solution first.
LMK what you think - whether the alpha reduction is an improvement or a different approach is needed.
> Update giant component example

- .circleci/config.yml
- .travis.yml
- examples/drawing/plot_knuth_miles.py
- requirements/README.md
- requirements/example.txt
Uses `cartopy` to add a map of the US as a backdrop to the `plot_knuth_miles.py` example.
As of now, the example is organized so that it will run whether or not cartopy is available.
CI configuration for the `cartopy` dependency cherry-picked from #4250
> Update Knuth miles example.

- examples/drawing/plot_four_grids.py
* Prevent node clipping.
* Add slightly more descriptive intro to the example.
* Switch from `plt.subplot` mechanism to using the `ax=` kwarg of nx.draw to show how to populate existing axes instances
> Update "four_grids" gallery example

- examples/drawing/plot_labels_and_colors.py
Attempt to improve legibility of labels by:
* Increasing background alpha and background node size
* Increasing font size
* Changing to a light font color to contrast with the red/blue bgnds
> Improve legibility of labels in plot_labels_and_colors example

- examples/drawing/plot_chess_masters.py
The current visualization produced by `plot_chess_masters.py` results labels that are not very readible.
This PR contains some minor tweaks to improve the visualization without changing the overall aesthetic (colors etc., though the layout has changed), as well as some minor improvements to the code in the example.
> Improve readibility of chess_example in gallery

- networkx/algorithms/minors.py
- networkx/algorithms/tests/test_minors.py
Fixes issue #3139 where edge contraction had the incorrect assumption that edges were always a 2-tuple such as `('u', 'v')`. This was causing failures when contracting multigraph edges which can be referenced explicitly with their index such as `('u', 'v', 0)`.
Updated the edge contraction logic to use at most the first two elements in the tuple
> Fixed issue where edge contraction was unpacking edges incorrectly

- doc/developer/deprecations.rst
- doc/release/release_dev.rst
- networkx/utils/misc.py
The function `is_iterator` from the utils module is only used in one other place in NetworkX and is not currently tested. I think it can be safely replaced with an `isinstance` check against the `Iterator` abc.
> Deprecate `utils.is_iterator`

- doc/developer/deprecations.rst
- doc/reference/utils.rst
- doc/release/release_dev.rst
- networkx/utils/misc.py
Deprecates the (apparently) unused and untested `nx.utils.is_list_of_ints` function. Uses of this function within networkx appears to have been replaced with `nx.utils.make_list_of_ints` in #3617.
> Deprecate utils.is_list_of_ints

- examples/algorithms/plot_decomposition.py
Modifies the figure aspect, axes layout, and axes margin padding to reduce the overlap of nodes in the visualization of the junction tree. 
Note that the figure itself is not entirely reproducible because `junction_tree` is not deterministic.
> Improve axes layout in plot_decomposition example

- .travis.yml
- tools/travis/deploy_docs.sh
- tools/travis/linux_install.sh
Now Travis will only build the docs when it needs to deploy them after the PR is merged to master.  This will make Travis run the tests on PRs faster and simplifies the travis config.
> Build docs for deployment on Travis CI

- networkx/tests/test_convert_numpy.py
- networkx/tests/test_convert_pandas.py
- networkx/tests/test_convert_scipy.py
This PR increases the test coverage of the `convert_matrix` module to 100%.
It would be nice to also clean up these test modules (e.g. get rid of importorskip for numpy, scipy, etc.), but I only focused on the coverage in this PR.
> TST: Increase test coverage of convert_matrix

- networkx/release.py
fix #4288
When a repository calls import networkx it will
trigger a sequence of imports that will cause to
look for a version.py in the current working
directory. Because it is common for a repository to contain
a version.py, this will end up being executed.
The change guarantees that this library version.py is called.
Arguably, the line of code should not being called at all when
importing networkx.
> Don't import other people's version.py

- doc/reference/algorithms/index.rst
- doc/reference/algorithms/summarization.rst
- examples/algorithms/plot_dedensification.py
- networkx/algorithms/__init__.py
- networkx/algorithms/summarization.py
- networkx/algorithms/tests/test_summarization.py
**NOTE**:  This change was originally found in pull request #3856, but Github Actions wouldn't work anymore due to changes to the `.github/workflow` files since my initial fork, so I re-forked and re-implemented the changes.
Original content:
Adds dedensification (`networkx.algorithms.dedensification.dedensify`) and densification (`networkx.algorithms.dedensification.densify`) functions as defined in [Scalable Pattern Matching over Compressed Graphs via Dedensification](http://www.cs.umd.edu/~abadi/papers/graph-dedense.pdf) with option for `expansive` or `nonexpansive` results, and option for `inplace` dedensification or densification.
Examples of how functions can be called:
```python
graph = nx.DiGraph()
dedensified_graph, compression_nodes = …
```
> adds dedensification function

- networkx/classes/tests/test_multigraph.py
Adds a test for 4-tuple inputs to `MultiGraph.add_edges_from` that have the `key` and `data_dict` flipped.
> TST: improve multigraph test coverage to 100%

- examples/drawing/plot_rainbow_coloring.py
Add an example of colorizing the edges of a complete graph by distance between the corresponding nodes along a circle. Could be a nice candidate to expand upon in a `networkx-guides` example.
Inspired by: https://www.quantamagazine.org/mathematicians-prove-ringels-graph-theory-conjecture-20200219/
> Add rainbow coloring example to gallery.

- networkx/algorithms/components/strongly_connected.py
- networkx/algorithms/components/tests/test_strongly_connected.py
- networkx/algorithms/components/tests/test_weakly_connected.py
- networkx/algorithms/components/weakly_connected.py
fix order of yield and seen.update in all connected components routines
Fixes #4331 
See also  #3859 & #3823 
A similar bug was fixed in March 2020 for connected components -- this fixes the directed versions of that bug.
We update the `seen` set with the component's nodes before yielding it so no longer has the problem reported in #4331 of changing the component set yielded makes the function report the same component again.
> Fix bug where changing a yielded component set breaks the component finding routine.

- networkx/classes/reportviews.py
- networkx/classes/tests/test_reportviews.py
Follow-up to #4300 - I had intended to make the suggestions there, but didn't get to it in time.
This PR attempts to accomplish several things:
- Fix a typo in OutMultiEdgeView: `list(G.nodes)` -> `list(G.edges)`
- Modify the exception message so that the type of reportview is always correct, regardless of subclassing
- Adds error messages to the InMultiEdgeView and InEdgeView
- Modify the error message so that the full slice object is reported, instead of `{s.start}:{s.stop}`, which fails to include the `step` (if used).
The last bullet would be improved even further if there were a built-in for mapping slice objects back to their nice string representation (e.g. `slice(None, 10, 2)` -> `:10:2`). I'm not sure how to do this and didn't want to add a custom utility function for it.
> Updates to slicing error message for reportviews

- networkx/algorithms/euler.py
- networkx/algorithms/tests/test_euler.py
Fixes #3976 
The example outlined in issue #3976 gives incorrect answers for different source values. After analyzing the source code, I found several reasons for this. First, eulerian_path calls has_eulerian_path to check if the graph has an eulerian path before proceeding. However, this initial check did not take the source into account. In this pull request, I updated has_eulerian_path so that it has a source input.
Second, if a graph has an eulerian path starting at a particular source, doing eulerian_path (G, source) gives us an incorrect pathing because reverse() changes the source of the resultant graph. To counter this, I had to re-find the source if the graph was not an eulerian circuit, and even if the source was given.
Finally, if the graph was undirected, reverse() was …
> Eulerian path fix

- doc/developer/deprecations.rst
- networkx/readwrite/json_graph/cytoscape.py
- networkx/readwrite/json_graph/tests/test_cytoscape.py
Closes #4199 .
The biggest change here is the introduction of a FutureWarning to notify users of the function signature change in the cytoscape functions. Added a detailed warning about the change in API that would take affect in 3.0, but the current behavior & signature remains unmodified for now. I'm not sure if this is the best way to do this, but it is at least consistent with the deprecation policy. Might be worth adding a tracking issue with a 3.0 milestone if the FutureWarning approach is acceptable.
> Add FutureWarning in preparation for simplifying cytoscape function signatures.

- networkx/__init__.py
- networkx/generators/community.py
- networkx/generators/geometric.py
- networkx/generators/intersection.py
- networkx/generators/lattice.py
- networkx/linalg/algebraicconnectivity.py
- networkx/readwrite/gexf.py
- networkx/readwrite/graphml.py
- networkx/readwrite/tests/test_graphml.py
Some of the imports are at the module level still -- instead of inside a function.
This negates our efforts at lazy importing, thus increasing import time (by a very small amount but users are still complaining).
Fixes #2900 
I will take another look at this in light of #4277 before it should be merged.
Feedback? @pb-cDunn
> Move a few imports inside functions to improve import speed of the library

- networkx/convert.py
- networkx/tests/test_convert.py
Closes #4305 .
Updates the documentation of `to_dict_of_dicts` to better describe and provide examples for the `edge_data` kwarg. Also adds tests for the (previously uncovered) case when the `edge_data` kwarg is not `None`.
> Update to_dict_of_dict edge_data

- networkx/classes/function.py
- networkx/classes/tests/test_function.py
Closes #4341.
Add examples to the documentation of `set_node_attributes` and `set_edge_attributes` for the case where `values=` is a dictionary (or dict-of-dicts) containing nodes or edges that are not in the graph. These entries are silently ignored, e.g.:
```python
>>> G = nx.Graph()
>>> G.add_node(0)
>>> attr_dict = {0: {'name': 'foo'}, 1: {'name': 'bar'}}
>>> nx.set_node_attributes(G, attr_dict)  # There is no node 1 in G, so this entry is silently ignored
>>> G.nodes(data=True)
NodeDataView({0: {'name': 'foo'}})
```
Also adds tests for this behavior, improving test coverage of `networkx/classes/functions.py`.
> Test and document missing nodes/edges in set_{node/edge}_attributes

- networkx/classes/tests/test_function.py
This PR increases the test coverage of the `functions` module to 100% and refactors one large selfloop test into several smaller tests.
* 5f20f29 and a0f9d8b add tests to improve coverage of `restricted_view` and `selfloop_edges`, respectively
* facee99 refactors `test_selfloops` into several smaller tests. 
facee99 is not critical to improving test coverage, so I'm happy to pull it out into a separate PR to make reviewing easier if desired.
> Refactor and improve test coverage for restricted_view and selfloop_edges

- .github/workflows/deploy-docs.yml
- .travis.yml
- tools/travis/linux_install.sh
Followup to #4297 - adds configuration for headless mayavi to both gh-actions and travis configuration.
> CI: Add mayavi conf to travis and GH for doc deploy

- networkx/algorithms/shortest_paths/generic.py
Solves #3368 
Makes `nx.shortest_path` use `bidirectional_dijkstra` in case of weighted graphs (when source and target are known)
> Use bidirection_dijkstra as default in weighted shortest_path

- networkx/utils/misc.py
- networkx/utils/tests/test_misc.py
Also update flatten to always return a tuple. The previous behaviour of preserving the type was leading to test failure.  So we decided that while flattening there is no expectation to preserve the type.
> Add unit tests for utils.misc.flatten

- doc/release/release_dev.rst
- networkx/drawing/nx_pylab.py
- networkx/drawing/tests/test_pylab.py
draw_networkx_edges used touse a LineCollection (presumably for
performance reasons) when drawing un-directed graphs and generate many
FancyArrowPatch objects when drawing directed graphs.  This resulted
in issues due to return type instability (#3337) and inconsistency
with handling the input (#3398).
closes #3398
closes #3337
Later commit adds ability to draw a self-loop edge.
closes #2024
> API: always use list of FancyArrowPatch rather than LineCollection

- networkx/drawing/nx_pylab.py
Previously the logic to add the self-loop (which over-rides theConnectionStyle path!) would only be triggered if the user actually specified a ConnecitonStyle.  This pulls the default from FancyArrowPatch up to draw_networkx_edges.
Follow up to #4360 
```python
import matplotlib.pyplot as plt
plt.ion()
G = nx.Graph([('X','Y'), ('X', 'X'), ('Y', 'X')])
pos = nx.spring_layout( G )
nx.draw_networkx_nodes(G, pos,
nodelist=list(G.nodes))
out = nx.draw_networkx_edges(G, pos,
edgelist=list(G.edges),
style='dashed',
#connectionstyle="arc3,rad=0.3",
)
```
> MNT: make the self-loop appear in all cases

- doc/conf.py
- networkx/drawing/nx_pylab.py
Something I noticed when reviewing `draw_networkx_edges` - there were references to matplotlib classes for which the links were not being built because matplotlib wasn't in intersphinx mapping. I went ahead and added pandas and scipy too since they're default requirements and there are likely (or at least could be) references to their documentation.
Also removed some unnecessary `:py:class:` instances from `nx_pylab` docstrings.
> Add additional libraries to intersphinx mapping

- networkx/readwrite/tests/test_graphml.py
- networkx/tests/test_convert_numpy.py
NumPy is [deprecating some type aliases in 1.20](https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated). We had used some of these aliases in the test suite - this PR replaces them with the corresponding Python or numpy scalar type. I grepped through the rest of NX as well and didn't notice any other instances.
> MAINT: remove deprecated numpy type aliases.

- networkx/algorithms/tournament.py
Looks like someone copy-pasted the docs for `random_tournament` and `hamiltonian_path` from `is_tournament` and forgot to change the return types.
> DOC: Fix copy-pasted docs for random_tournament and hamiltonian_path

- doc/developer/deprecations.rst
- doc/release/release_dev.rst
- networkx/convert_matrix.py
- networkx/tests/test_convert_pandas.py
- networkx/tests/test_convert_scipy.py
Builds on  #4106 which added docs for `edge_key` to `from_pandas_edgelist`.
This adds an edge_key parameter to `to_pandas_edgeslist`.
Also deprecates the unused `order` parameter in `to_pandas_edgelist`
add line to deprecations.rst to remind to remove.
> Update docstring for to_pandas_edgelist and add edgekey parameter

- networkx/drawing/nx_pylab.py
- networkx/drawing/tests/test_pylab.py
Boosts the test coverage of `nx.drawing.nx_pylab` to 100%, minus the lines mentioned in #4374, which will be addressed separately after discussion of that issue.
Two points that I'd like to call attention to for review:
1) I've removed an `except` branch from nx_pylab in 59cc4c6 because I couldn't come up with a test case that would raise a ValueError here. I checked the `blame` and couldn't find any motivating case that way either. Please LMK if you have an idea of what case this branch was originally designed to detect.
2) The test I added in 9fe21a3 is a bit of a departure from most of the tests of `nx_pylab` in that I've tried to test the behavior of the visualization. On the one hand, this is nice, but it's also more detailed and arguably harder to grok. In addition, the test …
> TST: Boost test coverage of nx_pylab module

- networkx/algorithms/minors.py
- networkx/algorithms/tests/test_minors.py
This PR fixes issue #4150 where remapped edges during node contraction were silently overwriting existing edges. Take the example from the original reported issue:
Given a Graph or DiGraph with the shape `(src1) --> (dest) <-- (src2)`; the node `src2` is contracted into the node `src1` to give the resulting graph `(src1) --> (dest)`. Currently, the "disappearing" edge `(src2, dest)` _overwrites_ the existing edge `(src1, dest)` including all of the edge's attributes.
This PR adds a check for existing edges while remapping edges from the "disappearing" node to the existing one. If we would be overwriting an edge, we instead append the attributes of the "disappearing" edge into a `"contraction"` attribute on the existing edge - this mirrors how the contracting node attributes are handled. …
> Fixed issue where edge attributes were being silently overwritten during node contraction

- networkx/convert.py
- networkx/tests/test_convert.py
Try to improve test coverage of the `networkx/convert.py`. 
Todo:
- Remove warnings on ImportError for numpy/scipy/pandas etc.
* Tentatively in favor of leaving this as-is.
> Improve test coverage of convert module

- networkx/algorithms/cluster.py
- networkx/algorithms/tests/test_cluster.py
Peng et al. propose a modification of the clustering coefficient based on the work of Pedro G. Lind et al. On page 3, They give a counterexample that shows the equation by Lind et al. gives the incorrect number of squares for a particular graph.
Basically it boils down to changing this code:
potential += (len(G[u]) - degm) * (len(G[w]) - degm) + squares
to this:
potential += (len(G[u]) - degm) + (len(G[w]) - degm) + squares
I also updated the documentation and the unit tests (and added a new unit test).
> code and doc fix for square_clustering algorithm in cluster.py

- doc/developer/nxeps/nxep-template.rst
Numpy -> NetworkX in 2 places.
> fix typo in NXEP template

- networkx/drawing/nx_pylab.py
- networkx/drawing/tests/test_pylab.py
Closes #4374
Prevents edges whose endpoints are not in `nodelist` from being drawn by `draw_networkx_edges` (see #4374 for more details).
Also documents missing `node*` parameters in `draw_networkx_edges` docstring.
> Modify and document behavior of nodelist param in draw_networkx_edges.

- networkx/algorithms/community/kernighan_lin.py
The algorithm works incorrectly because of that bug as min_i in line 124 always gets 0.
> fix small index iteration bug in kernighan_lin algorithm

- .circleci/config.yml
- .github/workflows/deploy-docs.yml
- .travis.yml
- doc/conf.py
Closes #4325 This is a component of #4169
I finally settled on 
```python
latex_engine = "xelatex"
latex_use_xindy = False
```
Turns out xindy --- don't really know what that is --- was causing errors, and this setting allows xelatex to work (I think xindy is more a pdflatex thing?). 
This PR does not have any dependencies
This PR is depended on by  #4294, #4350, and #4327
> Use xetex for uft8 latex backend

- networkx/algorithms/clique.py
- networkx/classes/graph.py
- networkx/convert_matrix.py
- networkx/generators/spectral_graph_forge.py
- networkx/linalg/algebraicconnectivity.py
- networkx/readwrite/gml.py
Replace `…'{x}'…` with `…{x!r}…` when formatting unknown string values. This will correctly escape quotes.
> Safer repr format of variables

- doc/reference/classes/index.rst
- networkx/classes/coreviews.py
Adds the `coreviews` module and all classes defined therein to the reference guide.
A few things I was unsure about:
- Where to add this to the documentation. I went with `reference/classes/index.rst` because it felt like it fit in with `Graph Views` and `Filters` sections, though it is unfortunate that it gets nested under "Graph Types" top-level heading.
- I tried to briefly summarize the `coreviews` module in the module docstring (which provides the summary for this section in the reference guide), but I'm sure that could be massively improved.
- The `Filter*View` objects are all missing class docstrings, so the generated documentation for these classes is bad. Maybe they should be removed from the `autosummary` (at least for now)?
Closes #4397
> Add coreview objects to documentation

- examples/drawing/plot_selfloops.py
Inspired by and hopefully closes #4406
Adds an example related to drawing self-loops (with pylab) to the gallery.
I wasn't sure if it should be "selfloop" or "self-loop"... I went with the latter, but please correct me if that's the wrong terminology.
> Add gallery example for drawing self-loops.

- doc/developer/nxeps/index.rst
- doc/developer/nxeps/nxep-0003.rst
This NXEP presents ideas from #3036 as a reformulation of how graph generators produce output.
They can still return graphs as they currently do, but they can also yield from edgelists.
The generators are replaced with Graph Builders that allow create_using and edgelist options to be specified by the user.
The current edgelist reading tools like `G.update` will need to handle 1-tuples as potentially isolated nodes and also handle attribute dicts for graph, node, edge and multiedge objects as part of the edgelist stream.  The term edgelist may need to change to node_and_edgelist or something better.
We should create edgelist writing methods -- perhaps as part of `G.edges()` or perhaps a new method name. They need to basically be:  `chain( [(G.graph,)], map(tuple, G.nodes.data()), …
> NXEP 3: Allow generators to yield from edgelists

- networkx/algorithms/traversal/breadth_first_search.py
Corrects the return type of bfs_predecessors.
Adds more details to the return type of bfs_successors.
Adds doctests for bfs_predecessors and bfs_successors that
are indicative for the behaviour of these functions on DiGraphs.
Previous tests only used these functions on undirect Graphs.
> Improves description bfs_predecessors and bfs_successors.

- doc/developer/deprecations.rst
- doc/release/release_dev.rst
- networkx/algorithms/dag.py
- networkx/algorithms/tests/test_dag.py
- networkx/conftest.py
- networkx/utils/misc.py
We only use this in one place and it has a one-line body.
See #4224.
> Deprecate consume

- .appveyor.yml
- .github/workflows/test.yml
- INSTALL.rst
- doc/release/release_dev.rst
- networkx/__init__.py
- networkx/release.py
- setup.py
Several of the core packages have decided to drop support for Python 3.6 on their next release.
scikit-image already has a release without Python 3.6 support:
- https://pypi.org/project/scikit-image/  (Dec. 15)
NumPy, SciPy, and Pandas already have release candidates without Python 3.6 support:
- https://pypi.org/project/numpy/1.20.0rc1/  (Dec. 3)
- https://pypi.org/project/scipy/1.6.0rc1/  (Dec. 10)
- https://pypi.org/project/pandas/1.2.0rc0/  (Dec. 8)
I am not sure when Matplotlib is planning to make a new release, but they've removed support for 3.6 from master already.
- https://github.com/matplotlib/matplotlib/pull/17662 (Jul. 6)
GH actions/setup-python now supports PyPy-3.7:
- https://github.com/actions/setup-python/pull/168
I recommend we also follow NEP 29 and drop 3.6 support …
> Drop Py3.6 support per NEP 29

- doc/developer/deprecations.rst
- doc/release/release_dev.rst
- networkx/conftest.py
- networkx/generators/lattice.py
- networkx/utils/misc.py
This function added 10 years ago, so maybe it was needed for some Python 2 case that I can't recall.  If we are keeping it in, we should come up with an example of an ``obj`` such that
- ``hasattr(obj, "__iter__")`` is ``False``
- ``len(obj)`` doesn't raise an exception
and it makes sense to use it in ``flatten`` or ``generators/lattice.py``
See #4224.
> Deprecate iterable

- doc/release/release_dev.rst
- networkx/relabel.py
- networkx/tests/test_relabel.py
Motivated by #4465 this PR allows the mapping used in `nx.relabel_nodes` to contain keys that are not nodes even when `copy=False`.  Previous behavior is that `copy=True` would ignore those keys and `copy=False` would raise a KeyError.
I'm not sure whether this needs to be Deprecated rather than changed because it would affect any user that relies on the KeyError "feature" to indicate whether the mapping has spurious keys. They can of course check for that with e.g. `if set(mapping)-set(G): raise KeyError`.  Still, maybe a note in the release_nodes is sufficient rather than a deprecation.
> Allow relabel_nodes mapping to have non-node keys that get ignored

- networkx/drawing/nx_pylab.py
- networkx/drawing/tests/test_pylab.py
Fixes a corner-case of the new self-loop drawing in `nx_pylab`.
The self-loop drawing code uses the width/height of the box formed by the edge positions to determine the size of the self-loop curve. The current code runs into problems if the user passes in an `edgelist` that contains only a single self-loop, as the computed width and height are then 0, which results in a FancyArrowPatch with 0 extent. Example:
```python
>>> G = nx.path_graph(2)
>>> G.add_edge(0, 0)
>>> pos = {n: (n, n) for n in G.nodes}
>>> nx.draw_networkx_nodes(G, pos)
>>> # Intend to draw only the self-loop
>>> nx.draw_networkx_edges(G, pos, edgelist=[(0, 0)])
```
**Expected**:
**Observed**:
The fix proposed in this PR is to compute the width and height from *all* edge positions in the local scope of …
> Handle self-loops for single self-loop (drawing)

- networkx/algorithms/cuts.py
- networkx/algorithms/tests/test_cuts.py
Here I added some tests to test_cuts.py to improve code coverage. It should be at 100% now. I also change the term "sequence" to"container" in cuts.py. This is because the documentation refers to the inputs of the functions as sets and sets are unordered and therefore are not sequences.
> Improve code coverage for cuts.py

- networkx/algorithms/components/tests/test_strongly_connected.py
@dschult @rossbar I tried reenabling this in case Travis was the issue.  After looking into it more, I think we should just delete this test.  I noticed it wasn't consistent even on my laptop:
The code to produce the figure is here:  https://gist.github.com/jarrodmillman/a170d27fc8c5fcb5e03ff450e260ce42
> Delete old test

- networkx/readwrite/tests/test_edgelist.py
Parametrizes the tests related to edgelist reading and adds additional tests of `parse_edgelist`, originally authored by @AndrewEckart in #4192. The `parse_edgelist` tests complemented some additional tests added in #4310 - I moved all of the `parse_edgelist` tests so that they are all together while rebasing.
Closes #4127
> TST: An approach to parametrizing read_edgelist tests.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
Users will see a screen which asks them to make a choice between `Bug Report`, `Q-A`, `Discussions`, `Blank Issue` when they click on the `new issue` button on GitHub.
> use issue templates to redirect to discussions tab, add a bug report template

- networkx/algorithms/boundary.py
Before, `nset1` was created by iterating over nodes in `G` and checking for membership in `nbunch1`. However, `nbunch1` can be any iterable, so checking for membership is O(n) in the worst case. Instead, iterating over `nbunch1` and checking for membership in `G` should fix this performance issue.
> Fix performance issue in nx.edge_boundary

- networkx/algorithms/bipartite/generators.py
In algorithms/bipartite/generators.py, `configuration_model` generates several unnecessary intermediate lists. This PR removes those and changes one list comprehension a to generator.
This is my first PR for NetworkX; any guidance/feedback is welcome and appreciated.
> Clean up list comprehensions in bipartite/generators `configuration_model`

- networkx/algorithms/cluster.py
- networkx/algorithms/tests/test_cluster.py
The current code `(wt1 * wt2 * wt3) ** (1 / 3)` returns a complex number when the product of edge weights is negative. 
Negative edge weights can cause the `average_clustering` function to raise a `TypeError` when the parameter `count_zeroes = False`.
<details>
<summary>show testcases</summary>
Here are the graphs tested in `test_cluster.py`
`TestDirectedWeightedClustering::test_triangle_and_negative_edge`
`TestWeightedClustering::test_triangle_and_negative_edge`
`TestClustering::test_k5_signed`
`TestAverageClustering::test_average_clustering_signed`
</details>
Please let me know if I am misunderstanding "clustering coefficients", if the current code is as intended, or if there is anything that should be changed.
> Clustering for signed weighted graphs

- examples/drawing/plot_random_geometric_graph.py
The recent change in behavior of `node_list` kwarg in draw_networkx_edges (#4374) resulted in the edges disappearing for our gallery example (``examples/drawing/plot_random_geometric_graph.py``):
I don't understand what the intention of including ``nodelist=[ncenter]`` to the call to ``nx.draw_networkx_edges``.  As far as I could tell it just drew all the edges in 2.5.
Removing it results in on master:
> Fix for PR #4378

- networkx/drawing/nx_pylab.py
- networkx/drawing/tests/test_pylab.py
Reverts the behavior changes of the `nodelist` kwarg in `draw_networkx_edges` - see #4505 for discussion and motivation.
Note that the docstring changes to `draw_networkx_edges` are retained. If preferred, I can do a full reversion of #4378 and re-introduce the docstring changes in a separate PR.
> Partially revert #4378 - Modify behavior of nodelist param in draw_networkx_edges.

- networkx/algorithms/flow/capacityscaling.py
- networkx/algorithms/lowest_common_ancestors.py
- networkx/algorithms/shortest_paths/weighted.py
- networkx/generators/line.py
- networkx/generators/trees.py
Relates to #4224
Relates to #4454
All internal uses of generate_unique_node are better served using
more specific methods to choose a node. Two uses end up finding
an unused node by counting down from -1 until the integer is not
a node. I'm not sure that justifies a utility function to do that
so I haven't implemented one, but we could make one (or a graph method)
with api: `generated_unused_node(G)` or maybe `G.find_unused_node()`.
I like the idiom:
```python
node = -1
while node in G:
node -= 1
```
> Replace generate_unique_node internally where not needed

- networkx/algorithms/centrality/betweenness.py
- networkx/algorithms/centrality/betweenness_subset.py
- networkx/algorithms/centrality/group.py
- networkx/algorithms/centrality/percolation.py
- networkx/algorithms/centrality/tests/test_group.py
In this PR I improved the group betweenness centrality algorithm by using the algorithm of Puzis et al. "Fast algorithm for successive computation of group betweenness centrality".
In the previous implementation of the algorithm, for each pair of source - target non - group nodes permutation, all the shortest paths were found and if one of them go through one of the nodes in the group then the group betweenness centrality increases. This was done for each group.
Here I used Pusiz et al. implementation, which finds the GBC with running time of $O(K^3)$ for each group (k is the number of nodes in the group) and with a preprocessing time of $O(mn)$ for all the groups.
This unable us to find the GBC of many groups in one preprocessing step.
Furthermore, the article shows how to find the …
> improve group betweenness centrality

- networkx/readwrite/nx_yaml.py
Github Actions failing due to new release of [pyyaml==5.4](https://pypi.org/project/PyYAML/#history) this change will ensure that version 5.3 is used.  There may be a better/simpler way to account for this issue, just let me know.
> fixes Github Actions failures

- doc/conf.py
Re-organize image scraper configuration for sphinx gallery
so that the docs build will not completely fail if mayavi
not installed.
With this change, individual sphinx gallery examples will fail, but the sphinx build process will now complete.
> Less strict on mayavi constraint for doc building.

- networkx/algorithms/centrality/tests/test_katz_centrality.py
This is an example of the type of error that can be caught by `pytest-randomly`, see #4553.
Assuming you have NX set up for development (including the test requirements), the error that this PR fixes can be reproduced by:
```
pip install pytest-randomly
pytest --randomly-seed=3100993940 --pyargs networkx
```
> TST: Fix error in katz centrality test setup.

- networkx/generators/community.py
I've been using the networkx package and noticed this mistake on the LFR algorithm documentation.
As stated in [point 3](https://github.com/networkx/networkx/blob/ddf06e1e89b57ee6dcc139535b4a1544e6157f4c/networkx/generators/community.py#L838) in the algorithm for LFR generation, `(1 - \mu) \mathrm{deg}(u)` regards the intra-community degree of a node, which makes `mu` the fraction of inter-community degree.
Let me know if I have made a mistake in understanding this. Also, this is my first pull request, if there is anything missing just let me know. 🙂
> Correct mu parameter documentation for LFR

- requirements/example.txt
Fixes #4562 
Un-pin pygeos and set lower bound for geopandas to a version that supports pygeos 0.9.
> Unpin pygeos

- doc/reference/utils.rst
- networkx/utils/misc.py
- networkx/utils/tests/test_misc.py
Related to #4224.
Given how extensively `nx.utils.arbitrary_element` is used in the library (and test suite), my impression was that is should not be deprecated even though it is essentially a one-liner.
Updates the documentation and adds tests for `nx.utils.arbitrary_element`:
* Reorganize docstring to include headings (`Parameters`, `Returns`, `Examples`, etc.)
* Adds `arbitrary_element` to the reference guide
* Adds tests.
> Update documentation and testing of arbitrary_element

- networkx/algorithms/community/tests/test_kernighan_lin.py
This is a proposal to fix issue #4415 . I added a test which calls kernighan_lin_bisection() with max_iter argument set to 1. 
Since the test case is a simple situation, the algorithm finds the minimal cut at first iteration. Before issue #4398 was fixed, the test I wrote would fail because loop on line 130 on kernighan_lin_bisection only maxe one swap ( the _kernighan_lin_sweep function was always returning 0 in second position). 
The test case I used can be found on page 7 here : http://users.ece.northwestern.edu/~haizhou/357/lec2.pdf
NB: This is my first time contributing so I would happy to have any feedbacks.
> Add test Kernighan Lin Algorithm

- networkx/algorithms/operators/all.py
- networkx/algorithms/operators/binary.py
- networkx/algorithms/operators/tests/test_all.py
- networkx/algorithms/operators/tests/test_binary.py
This is a proposition to fix issue #3265 - Enhancement for the intersection of two graphs. 
The code does not raise a Value Error anymore when we try to intersect two graphs that don't have the same node sets. It now returns a graph which contains all the nodes that are the intersection of the two node sets and edges that are the intersection of the two edge sets.
I added a few tests and modified those which where expecting an error when running intersection function for two different node sets. I updated documentation accordingly.
> Enhancement intersection function 3265

- .github/workflows/test.yml
- networkx/drawing/tests/test_agraph.py
- requirements/extra.txt
Bash and PowerShell have different syntax for line continuations and for ``for`` loops.  So you can not do something like
```
- name: Before install
run: |
if [ "$RUNNER_OS" == "Linux" ]; then
sudo apt-get update
sudo apt-get install graphviz graphviz-dev
elif [ "$RUNNER_OS" == "macOS" ]; then
brew install graphviz
elif [ "$RUNNER_OS" == "Windows" ]; then
choco install graphviz
fi
```
without also doing something like
```
extra:
runs-on: ${{ matrix.os }}
defaults:
run:
shell: bash
```
That uses Bash for all OSes; but then Windows fails to build extension code because the development environment for Windows is not setup/configured for Git Bash.  It may be possible to get this working, but I decided to use the default shell for each OS.
This requires moving the logic that detects what OS …
> Pygraphviz choco

- doc/developer/deprecations.rst
- networkx/conftest.py
- networkx/drawing/nx_agraph.py
- networkx/drawing/tests/test_agraph.py
- networkx/utils/misc.py
`networkx.utilities.misc` has the `default_opener` function which is used in `nx_agraph` to display the results of drawing with pygraphviz. The pygraphviz drawing functionality writes an image to file, and `default_opener` is used to open that file using the default image viewing utility on various platforms.
Now that matplotlib is a default dependency, `Pillow` should be installed by default, so we can instead rely on the purpose-built Pillow utilities to display images from file. If this is an acceptable alternative, then `default_opener` can be deprecated.
> Use Pillow for viewing AGraph output and deprecate default_opener

- doc/developer/deprecations.rst
- doc/release/release_dev.rst
- networkx/algorithms/simple_paths.py
- networkx/conftest.py
- networkx/utils/misc.py
Related to #4224 
`networkx.utils` provides `empty_generator` to create an empty Generator object. The only use of this utility was in `all_simple_paths`. The motivation for deprecating this function is that it seems like it is not very specific to NetworkX and is generally achievable by various one-liners, e.g. `(x for x in ())`. IMO it makes more sense to deprecate than to test/document it - LMK what you think!
One tricky thing about this - the warning won't be emitted *on instantiation* of the generator object, but rather only if it is ever iterated over:
```python
>>> empty = nx.utils.empty_generator()  # Doesn't raise deprecation warning
>>> next(empty)
DeprecationWarning
Traceback
...
StopIteration
```
I think this is probably okay, but if we want to work out a way that the warning …
> Deprecate networkx.utils.empty_generator.

- networkx/algorithms/clique.py
Fixes issue #4621 by moving an early return opportunity earlier into the
method call, potentially avoiding one function call to `find_cliques`
that otherwise returns early, itself
> return earlier from `clique.graph_clique_number`

- .gitignore
CONTRIBUTING.rst recommends creating a virtual env in the directory
`networkx-dev/`. This change adds that directory to `.gitignore`
Fixes #4618 - recommended virtual env name should be in .gitignore
> add recommended venv directory to .gitignore

- requirements/default.txt
Temporary fix for #4626, at least for failing CI. Prevents scipy version 1.6.1 from being picked up by `pip`.
Avoid test failures due to change in behavior for default dtype when creating coo_matrices.
> Add scipy-1.6.1 to blocklist.

- doc/developer/deprecations.rst
- doc/release/release_dev.rst
- networkx/algorithms/link_analysis/hits_alg.py
- networkx/conftest.py
Related to #4091 - adds deprecation to `hub_matrix` and `authority_matrix` from the `hits_alg` module. As noted in the linked issue, the functions are primarily pedagogical, so I updated the `hits_numpy` docstring example with a section showing how the two matrices are computed. I also tried to provide a detailed deprecation warning message to illustrate how the hub and authority matrices can be computed from a given Graph.
This addresses part of #4091, but it would still be nice to have a gallery example illustrating the hits algorithm. I don't have a compelling example, so I will leave it for a followup PR. However, if anyone does have a nice example, feel free to push to this branch!
> Deprecate hub_matrix and authority_matrix

- doc/credits.rst
- examples/graphviz_layout/plot_atlas.py
An email from Philip Boalch points out that the previous
code didn't include atlas graph number 208 and used a
`could_be_isomorphic` fast routine which returned
incorrect results.
The correct number of connected graphs 
with 6 or fewer nodes is 142, not 137.
Using the `GraphMatcher` method `subgraph_is_isomorphic`
provides the correct result.
> Correct and update Atlas example

- networkx/classes/multidigraph.py
`attr_dict` parameter in `MultiDiGraph.add_edge` was removed in https://github.com/networkx/networkx/commit/1b35e352daf740f115012427d53a48f460a62206
This PR updates the docstring to conform to the above-mentioned update.
> Remove attr_dict from parameters list in the docstring

- networkx/algorithms/matching.py
- networkx/algorithms/tests/test_matching.py
Previously the is_matching() function was never checking the edges in
the provided matching against the graph, it would just validate there
were no shared endpoints. The graph object passed in to the function was
never used. This commit updates the function to check that all the edges
in the matching are valid and present in the provided graph before
checking if the are no shared endpoints.
> Verify edges are valid in is_matching()

- doc/developer/deprecations.rst
- doc/release/release_dev.rst
- networkx/classes/ordered.py
- networkx/conftest.py
Closes #4614 
Deprecate the `Ordered` variants of the four graph classes. Adds deprecation notices in the docs to the `networkx.class.ordered` module, as well as the class docstrings. Adds an `__init__` method to each `Ordered` class which is responsible for raising a `DeprecationWarning`, then delegates to the parent constructor.
> Deprecate Ordered graph classes

- networkx/algorithms/centrality/katz.py
Both references to Katz' article have been fixed with the actual article link.
Fixes #4648
> Fix article link in katz_centrality definition

- networkx/algorithms/shortest_paths/tests/test_weighted.py
- networkx/algorithms/shortest_paths/weighted.py
Use keyword argument instead of positional argument to avoid argument mismatch.
Affected function: `negative_edge_cycle`
> [fix] for negative_edge_cycle incorrect call of bellman_ford

- networkx/drawing/layout.py
Fixes #4061 
Since the logic for drawing the graph in both `vertical` and `horizontal` alignment is the same we can use one loop and just flip the positions.
Results are the same as before.
> Optimize multipartite_layout

- networkx/algorithms/approximation/tests/test_maxcut.py
- networkx/algorithms/centrality/betweenness.py
- networkx/algorithms/tests/test_triads.py
- networkx/algorithms/triads.py
- networkx/generators/directed.py
- networkx/generators/internet_as_graphs.py
Closes #4555
I took a conservative approach and used `sorted` to convert sets to lists. This may cause a performance hit, but I figured this was safer from the perspective of reproducibility, though I'm not sure it's necessary. In some circumstances it may be sufficient to simply convert to `list` directly.
> Remove instances of random.sample from sets (deprecated in Python 3.9)

- requirements/default.txt
Not sure if we want to introduce this upper bound or just wait for micheles/decorator#103 to be resolved. It'd be nice to get the CI test suite back up and functional, but if the fix is imminent we can just be patient and not have to deal with adding/removing pins like this.
On a side note, it would've been nice to catch this before the new major dependency release. We run the test suite against pre-releases of the main dependencies but `decorator` must not have had a release candidate. Maybe we could consider running against the development branch of dependency projects instead? That could also help catch things like #4626.
> Pin upper bound of decorator dep.

- .circleci/config.yml
Currently, the pip install step of the docs build job on circleci takes ~2min each run, largely due to some wheels being built locally. This time-consuming step could be significantly improved by persisting the pip cache between CI runs. The approach taken here is to persist the cache between circleCI runs, and add an `--upgrade` flag to all of the dependency installs. This ensures that the newest versions of libraries are always grabbed and (hopefully) eliminates the need to manually manage the cache.
> CI: persist pip cache between circleci runs

- doc/_static/networkx_banner.svg
- doc/_templates/docs-navbar.html
- doc/_templates/layout.html
- doc/conf.py
- requirements/doc.txt
NumPy, SciPy, and other projects are moving (or have moved) to using the [pydata sphinx theme](https://github.com/pydata/pydata-sphinx-theme) for documentation.  I believe it is nicer looking and, more importantly, will help us create a more unified scientific Python ecosystem.  We also know the maintainers, so we can easily help fix and improve the theme.
I plan to clean up a few things, but I wanted to get some feedback before putting too much more time in to this.  We could merge this as is and I could do the clean up in a separate PR or I could make the changes to this PR.  I slightly prefer merging this first, but I don't have a strong preference.
> Use pydata sphinx theme

- networkx/generators/directed.py
I was trying to use `scale_free_graph` from `generators.directed` and noticed it drastically grew slower with number of nodes n, rendering it effectively useless for large numbers of nodes (e.g. 1M). Since the gist of the algorithm involves preferential attachment, and other networkx methods like the ones based on Barabási–Albert _are_ in fact fast, I took a look at the implementation. Parts of the current node sampling have O(n) time complexity, effectively rendering the generator as a whole O(n^2). I rewrote that sampling to be O(1), so now the generator itself is O(n).
**Changes**
Like e.g. the implementation for `barabasi_albert_graph` or `dual_barabasi_albert_graph`, the new implementation keeps simple lists of repeated nodes representing the in- and out-degrees so we can perform …
> O(n^2) -> O(n) implementation for scale_free_graph

- networkx/algorithms/bipartite/tests/test_edgelist.py
- networkx/classes/tests/historical_tests.py
- networkx/readwrite/tests/test_adjlist.py
- networkx/readwrite/tests/test_edgelist.py
Some tests relied on `!=` to check whether or not two Graph instances where the same object. This PR updates these lines to `is not` instead, which I think is more idiomatic. Inspired by the discussion in #4746.
> TST: be more explicit about instance comparison.

- networkx/utils/misc.py
- networkx/utils/random_sequence.py
- networkx/utils/tests/test__init.py
Adds `__all__` attrs to modules in `utils` and adds a test to
ensure objects and aliases defined in `utils` modules are
not unintentionally exposed in the `utils` namespace.
Closes #4752
> MAINT: Add missing __all__'s to utils modules + test.

- networkx/generators/geometric.py
Since on different versions of python `sp.spatial.cKDTree` gives the edge indices in different order, it becomes impossible to reproduce exactly the same graph, even when passing the same random number generator state.
This PR solves the problem by sorting the`edge_indexes` after getting the result from cKDTree.
Closes #4767
> Improve reproducibilty of geometric graphs

- requirements/default.txt
I'm maintaning the [`manim`](https://aur.archlinux.org/packages/manim/) AUR package, which depends on [`python-networkx`](https://archlinux.org/packages/community/any/python-networkx/). Due to #4718 being only solved for the latest version of [`python-decorator`](https://archlinux.org/packages/community/any/python-decorator/) in HEAD, I've started maintaining [`python-networkx-git`](https://aur.archlinux.org/packages/python-networkx-git/), which requieres [a manual patch](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-networkx-git#n23) for the `decorator` requierement version.
This small PR updates the requirements [stated by @dschult](https://github.com/networkx/networkx/issues/4718#issuecomment-819489576) so that other projects don't have to manually patch them.
> Updated decorator requirement for #4718

- examples/drawing/plot_custom_node_icons.py
- examples/graph/plot_football.py
This PR originally fixed `examples/drawing/plot_custom_node_icons.py` import *urllib* issue in #4790.
What find in discussion below is following,
1. That `examples/drawing/plot_custom_node_icons.py` will work in ipython, but if run with vanilla python, there will be an error `AttributeError: module 'urllib' has no attribute 'request'.`
2. `examples/graph/plot_football.py` also import *urllib*, but with a different workaround.
So now this PR is updated to cover both `examples/drawing/plot_custom_node_icons.py` and `examples/graph/plot_football.py`, regarding import *urllib*.
> fix urllib import

- requirements/default.txt
Adds upper bound to decorator dependency in preparation for 2.6 release.
Addresses #4732 in the short term for the 2.6 release.
> Pin upper bound on decorator for 2.6 release.

- networkx/drawing/nx_agraph.py
- networkx/linalg/attrmatrix.py
- Use `callable()` to check if the object is calllable
- Fix dangerous default argument
- Remove unnecessary return statement
- Add .deepsource.toml
I ran a DeepSource Analysis on my fork of this repository. You can see all the issues raised by DeepSource [here](https://deepsource.io/gh/HarshCasper/networkx/).
DeepSource helps you to automatically find and fix issues in your code during code reviews. This tool looks for anti-patterns, bug risks, performance problems, and raises issues. There are plenty of other issues in relation to Bug Discovery and Anti-Patterns which you would be interested to take a look at.
If you do not want to use DeepSource to continuously analyze this repo, I'll remove the `.deepsource.toml` from this PR and you can merge the rest of the fixes. If you want to …
> Fixed Code Quality Issues

- doc/developer/deprecations.rst
- networkx/conftest.py
- networkx/readwrite/json_graph/cytoscape.py
- networkx/readwrite/json_graph/tests/test_cytoscape.py
- networkx/readwrite/json_graph/tests/test_tree.py
- networkx/readwrite/json_graph/tree.py
Closes #4783.
Similar to #4284, though the approach here is actually better in that it allows the user to use the new kwargs now to get rid of warnings and be forward compatible. If others agree I will also apply this pattern to the cytoscape functions.
> Remove dictionary from signature of tree_graph and tree_data

- doc/conf.py
- doc/developer/index.rst
- doc/index.rst
- doc/release/index.rst
This PR adds a link to https://networkx.org/nx-guides/ with the name `NX Guides` to the navbar:
Is there a better name?  E.g., `Tutorials and Guides`, `Interactive Tutorials and Guides`, `Interactive Guides`, etc.
> Link to guides

- networkx/drawing/layout.py
This allows the `source` link to appear on the docs for this function.
I believe it shouldn't affect performance/behavior in any way.
Fixes:  #4819
> switch alias direction of spring_layout and fruchterman_reingold_layout

- networkx/readwrite/gml.py
- networkx/readwrite/tests/test_gml.py
Fixes issue #4484 
Write floats inf as +INF and nan as _NAN for gml files.  Read +INF, -INF, _NAN as floats.
> Fixes read/write_gml with nan/inf attributes

- networkx/algorithms/core.py
Fix #3944 by clarifying exact behaviour of `k_crust(G, k)`
Tagging @dschult for review
> DOC: Clarify behaviour of k_crust(G, k)

- .circleci/config.yml
May speed up any long-running examples that rely on numpy/scipy linalg.
See how the sphinx-gallery build goes in circleci, apply to other CI services if it has an effect.
> Limit number of threads used by OMP in circleci.

- doc/developer/nxeps/nxep-0002.rst
- networkx/algorithms/assortativity/connectivity.py
- networkx/algorithms/assortativity/correlation.py
- networkx/algorithms/bipartite/centrality.py
- networkx/algorithms/bipartite/cluster.py
Chipping away at the link warnings when running sphinx in nit-picky mode.
For reference: you can have sphinx report broken links when building like so: `make SPHINXOPTS=-n html`. You should also comment out the `default_role = obj` from `conf.py` (there is a strange interplay between the rtd theme, numpydoc, and sphinx here... not quite sure what's the best way to resolve it so skipping over the details for now). Doing so, I get about 540 broken links (on de9c66ff). This PR should reduce that number by 8.
> Fix a few broken links in the html docs

- networkx/drawing/nx_pylab.py
- networkx/drawing/tests/test_pylab.py
#4360 switched all edge drawing from LineCollection (in some cases) to always using FancyArrowPatches. This enabled nice new features such as self-loop drawing #4370 and a consistent, iterable return type, which makes it easier for users to modify individual edges (as FancyArrowPatches) after they have been created by `draw_networkx_edges`.
One downside of removing LineCollection is a large performance regression for drawing edges in undirected graphs, see #4806.
This PR tries to get the best of both worlds by re-introducing LineCollection for faster edge drawing, while keeping all the nice features of #4370 including drawing self-loops and the ability to draw curved edges.
The basic approach is:
1. Add back the LineCollection drawing functionality that was removed in #4360.
2. …
> Fix edge drawing performance regression

- networkx/algorithms/chains.py
- networkx/algorithms/smetric.py
- networkx/classes/digraph.py
- networkx/classes/graph.py
- networkx/classes/multidigraph.py
- networkx/classes/multigraph.py
- networkx/readwrite/text.py
- networkx/tests/test_import.py
**EDIT**: Partially addresses #4426; fixes `from networkx import nx` by adding some missing `__all__`'s to modules.
Original discussion (which attempted to tackle multiple issues at once) below.
---
Related to #4426 - attempting to fix bad import patterns like `from networkx import nx` or `from networkx import networkx`.
Adds tests for the two patterns mentioned above. Adding the `__all__` dunders to a couple modules where they were missing (found with `grep -L`) fixes the `from networkx import nx` problem, but I haven't been able to crack the second case in this first pass. Suggestions welcome!
If worse comes to worst, one hack-y solution would be to add `del networkx` to `networkx/__init__.py`; though IMO it would be preferable to find where/how `networkx` is being imported into itself …
> Fix bad import pattern

- doc/release/release_dev.rst
- networkx/algorithms/centrality/subgraph_alg.py
- networkx/algorithms/centrality/tests/test_subgraph.py
> Remove unused `normalized` parameter from communicability_betweenness_centrality

- doc/developer/deprecations.rst
- doc/release/release_dev.rst
- networkx/algorithms/centrality/katz.py
- networkx/linalg/graphmatrix.py
- networkx/linalg/tests/test_graphmatrix.py
- networkx/tests/test_convert_numpy.py
@dschult This adds a dtype argument to `adjacency_matrix` and deprecates `adj_matrix`.
> Add dtype argument to adjacency_matrix

- networkx/__init__.py
- networkx/algorithms/__init__.py
- networkx/classes/__init__.py
- networkx/linalg/__init__.py
- networkx/tests/test_import.py
Followup to #4839. This was originally attempted there, but ultimately ended up seemingly like a more complicated issue.
The goal is to prevent `networkx` from being imported in the top-level `networkx` namespace. In other words, this should not be possible: `from networkx import networkx`. See the discussion in #4839 for original discussion and some ideas for how to probe/fix this problem.
> Remove "networkx" from top-level networkx namespace

- networkx/readwrite/gml.py
The GML specification documentation is not available anymore on the linked website, use archive to points towards an older version of the website.
> DOC: point towards web archive link in GML docs

- doc/release/release_dev.rst
- networkx/drawing/layout.py
This pull request addresses the issue when `fixed` nodes passed to the `spring_layout` function are not in the original graph nodes. The current behavior: an unintuitive error is shown.
```python
graph = nx.Graph()
graph.add_nodes_from([1])
pos = {n: (0, 1) for n in [1, 2]}
nx.spring_layout(graph, fixed=[1, 2], pos=pos)
Traceback (most recent call last):
File "<input>", line 7, in <module>
File "<decorator-gen-736>", line 2, in fruchterman_reingold_layout
File "/home/dizcza/miniconda3/envs/networkx/lib/python3.9/site-packages/networkx/utils/decorators.py", line 408, in _random_state
return func(*new_args, **kwargs)
File "/home/dizcza/miniconda3/envs/networkx/lib/python3.9/site-packages/networkx/drawing/layout.py", line 461, in fruchterman_reingold_layout
fixed = …
```
> spring_layout: ignore 'fixed' nodes not in the graph nodes

- networkx/drawing/nx_pylab.py
- networkx/drawing/tests/test_pylab.py
Followup to #4825 
In #4825 the `arrows` kwarg was switched from being a boolean to an optional boolean with `None` as the default value. This was correctly updated in `draw_networkx_edges`, but I forgot to update the default in `draw_networkx`! This results in all graphs drawn with `nx.draw` or `nx.draw_networkx` being drawn with arrows by default, which was a major oversight.
This PR should go in before the 2.6 release to avoid a behavior change from 2.5.
> Update arrows default value in draw_networkx.

- networkx/algorithms/traversal/breadth_first_search.py
- networkx/algorithms/traversal/depth_first_search.py
- networkx/algorithms/traversal/edgedfs.py
Some docstring improvements that may further help to address issues like #4899 
The main improvements include:
* Fixing cross-references between the various algorithms both in the text and the `See Also` sections.
* Converting `Returns` -> `Yields` for the edge generators
* Adding a `References` for more nicely-formatted links to external references.
I only touched the docstrings directly linked-to from `dfs_edges`. I expect that similar improvements could be made to some of the other dfs/bfs functions. I'll either review them myself when I have more time or open an issue about it if you think these changes are worthwhile!
> Update docstrings for dfs and bfs edges and fix cross links

- networkx/classes/digraph.py
- networkx/classes/tests/test_digraph.py
- networkx/classes/tests/test_graph.py
In `DiGraph.to_undirected`, local variable `graph_class` was defined but not used in this function. 
Though it is not a serious problem, this should be removed.
> In `DiGraph.to_undirected`, remove not accessed variable

- doc/release/release_dev.rst
- networkx/algorithms/assortativity/correlation.py
- networkx/algorithms/assortativity/mixing.py
- networkx/algorithms/assortativity/tests/base_test.py
- networkx/algorithms/assortativity/tests/test_correlation.py
- networkx/algorithms/assortativity/tests/test_mixing.py
This fixes some problems with assortativity coefficient calculation #3917, #4368, #4369, #4776. 
Here is my explanation of fixes. The question is what do we expect the `mapping` variable to actually *map*? I have read the whole `mixing.py` module, the original Newman's article https://arxiv.org/abs/cond-mat/0209450 and decided that the most natural way to define the `mapping` variable is as follows: 
*The `mapping` variable maps the unique nodes' attribute values to mixing matrix row and column indices.*
For example, if the network consists of nodes with the attribute "gender" of values "male" and "female", the `mapping` will be `{'female': 0, 'male': 1}`. In this terms, the entry [0, 1] of the normalized mixing matrix will contain the fraction of links that follow from female nodes to …
> Fix assortativity coefficent calculation and tests

- networkx/readwrite/gml.py
Responding to issue #4877 by adding a simple destringizer example to the
read_gml docstring.
> Update read_gml docstring with destringizer ex

- doc/release/migration_guide_from_2.x_to_3.0.rst
- doc/release/release_dev.rst
I am not sure how much more detail to add.  Maybe just pointing to the release notes for details about the deprecated code would be enough for now.
> Add 3.0 migration guide

- networkx/algorithms/minors/contraction.py
Small fix to the documentation of `networkx.algorithms.minors.quotient_graph` which I think makes it a bit clearer. The docs refer to `node_relation` which isn't a parameter and isn't referred to elsewhere. Basically it should just be referring to the partition.
> quotient_graph doc fix

- networkx/algorithms/centrality/katz.py
Minor fix for Katz centrality documentation. Page referenced in `Networks, An Introduction` appears wrong when I went to read the reference:
> Page number for Katz centrality reference

- networkx/readwrite/gml.py
Add to the example showing read_gml with and without a destringizer.
Show the nodes of the graph created with read_gml will be str unless a
destringizer is specified. 
I looked around the repo to find multi-line examples but I'm not sure if 
this formatting is the most clear or that it follows convention in networkx. 
Please let me know if you have feedback on readability or formatting. 
Closes #4877
> Expand destringizer example in read_gml docstring

- networkx/algorithms/minors/contraction.py
Making the private function free from argument checking may allow Louvain method code to call the private version to avoid argument checking because we know the inputs are ok.
> move partition checking outside private _quotient_graph function

- examples/algorithms/plot_parallel_betweenness.py
Add comment about single core CI/CD showing slower parallel output in example script.
Added text:
```
Note: The example output below shows that the non-parallel implementation is
faster. This is a limitation of our CI/CD pipeline running on a single core.
Depending on your setup, you may observe a 4x speed improvement.
```
Following the discussion in the ticket, I left the multiprocessing as-is because I think it probably makes MORE sense than using concurrent.futures.
Here was my output running the script:
```
⇒  python examples/algorithms/plot_parallel_betweenness.py
Computing betweenness centrality for:
Name:
Type: Graph
Number of nodes: 1000
Number of edges: 2991
Average degree:   5.9820
Parallel version
Time: 0.7211 seconds
Betweenness centrality for node 0: 0.00201
Non-Parallel …
```
> Fixes #4275 - Add comment to parallel betweenness example

- networkx/algorithms/assortativity/correlation.py
- networkx/algorithms/assortativity/tests/base_test.py
- networkx/algorithms/assortativity/tests/test_correlation.py
It fixes #4776 and wrong assortativity coefficient calculation in some cases that follow PR #4851.
A cause of the issue is in `numeric_ac` in [correlation.py](https://github.com/networkx/networkx/blob/main/networkx/algorithms/assortativity/correlation.py). Before my fixes in `numeric_ac`
```python
x = np.arange(nx)
y = np.arange(ny)
```
we create supports for random variables x and y. We assume that node values are integer and coincide with mixing matrix indices — 0 is in the first row/column, 1 is in the second row/column and so on. But after PR #4851, node values can also be negative or float. In such cases we need to know a mixing matrix indices for each unique pair of values. After my fixes, supports of x and y contain all node values, not only integers. The same for degree …
> Fix numeric and degree assortativity coefficient calculation

- doc/developer/deprecations.rst
- doc/release/release_dev.rst
- networkx/algorithms/assortativity/connectivity.py
- networkx/conftest.py
The function name `k_nearest_neighbors` isn't used n any of the cited papers, is the same name as used for commonly used machine learning algorithms (which are not related to this degree_correlation work.  Perhaps it came from "nearest neighbor degree" which **is** used in the papers, and does depend on "k", but importantly, is not called "k nearest neighbors".  Since this function name is simply an alias we should just redirect users to `average_degree_connectivity` which is the name used for the actual function definition.  That name is not great either given that there is a function `average_neighbor_degree`, but that naming discussion can be delayed to another PR. (see issue #4936)
This PR also fixes handling of degree/in_degree/out_degree for average_neighbor_degree and adds some …
> Deprecate k_nearest_neighbors

- doc/reference/readwrite/index.rst
- doc/reference/readwrite/matrix_market.rst
Adds an .rst stub to the readwrite docs in the reference guide to provide background and examples for I/O with the Matrix Market format using SciPy's built-in parsers.
Related to the discussion in https://github.com/networkx/networkx/pull/4922#issuecomment-866651631.
> Add matrix market to readwrite reference

- networkx/algorithms/assortativity/neighbor_degree.py
- networkx/algorithms/assortativity/tests/test_neighbor_degree.py
Make `average_neighbor_degree` work for directed graphs, add tests and inline one function to simplify.
> Fix neighbor degree for directed graphs

- networkx/algorithms/traversal/breadth_first_search.py
I think there is no reason to limit `descendants_at_distance` to DiGraphs. My change affects the documentation only.  If I am wrong, maybe a check would make sense.
> `descendants_at_distance` also for non-DiGraphs

- doc/developer/nxeps/nxep-0003.rst
- doc/reference/introduction.rst
- doc/release/migration_guide_from_1.x_to_2.0.rst
- doc/release/old_release_log.rst
- doc/tutorial.rst
- examples/subclass/plot_antigraph.py
- networkx/algorithms/graph_hashing.py
- networkx/algorithms/link_analysis/hits_alg.py
- networkx/classes/graph.py
- networkx/generators/trees.py
- networkx/utils/misc.py
- skip running the entire test quite as an example in old_release_log.rst
- capture output from subplot and rename DiGraph as DG in introduction.rst
- Remove one line from 1->2 migration rst file
the line shows code that works for 1.x *and* 2.x.
But it no longer works for all v2.x code.  Readers should just use the
next line of code, so no reason to keep this in the file.
- add nx. prefix to doctest function calls
- rst double colons for example code
> Changes to rst files to make doctests pass

- .circleci/config.yml
- .github/workflows/coverage.yml
- .github/workflows/deploy-docs.yml
- .github/workflows/test.yml
- CONTRIBUTING.rst
- INSTALL.rst
- doc/release/migration_guide_from_2.x_to_3.0.rst
- doc/release/release_2.6.rst
- networkx/__init__.py
- requirements.txt
- setup.py
Having scipy as a default dependency introduce a circular build dependency issue for scipy:  https://github.com/scipy/scipy/issues/14335 and https://github.com/serge-sans-paille/pythran/issues/1837
This PR removes numpy, scipy, matplotlib, and pandas as "default" dependencies for NetworkX.  With this PR,
```
pip install networkx
```
requires installing no additional packages and we will ask users to install networkx via
```
pip install networkx[default]
```
I propose releasing networkx 2.6.2 with this PR merged and removing 2.6.0 and 2.6.1.  I would still like to figure out a way for users to install networkx with its "default" dependencies using only
```
pip install networkx
```
for 2.7.  Currently, I think we may want to release two packages on PyPI:
- ``networkx-core`` for libraries …
> Remove default dependencies

- networkx/algorithms/community/modularity_max.py
- networkx/algorithms/community/tests/test_modularity_max.py
Fixes [bug](https://github.com/networkx/networkx/issues/4966) which makes `greedy_modularity_communities` crash if the graph nodes have been relabeled.
> modularity_max: provide labels to get_edge_data

- networkx/algorithms/community/modularity_max.py
- networkx/algorithms/community/tests/test_modularity_max.py
This patch solves the following bug:
In ```greedy_modularity_communities()``` an encoder/decoder pair is used (```node_for_label``` & ```label_for_node```), in order to encode node-labels to contiguous integers, to use them as indexes. In order to access edge data with ```G.get_edge_data(i, j)```, ```i``` and ```j``` have to be node-labels of G and NOT their integer representations. 
The current tests are using ```nx.karate_club_graph()```, which already has contiguous integers (starting from 0) as labels and, thus, ```node_for_label``` is encoding to the same labels:
```bash
python -c "import networkx as nx; print(nx.karate_club_graph().nodes)"
```
```
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]
```
and …
> Bugfix - use node labels with get_edge_data() at greedy_modularity_community()

- doc/_templates/autosummary/class.rst
- doc/reference/algorithms/isomorphism.ismags.rst
- networkx/utils/decorators.py
In the documentation currently, when a class is added to an `.. autosummary` directive, the docstring for the class itself is automatically generated for the reference docs, but any methods/attributes are not. For example, see the [docs for the argmap class](https://networkx.org/documentation/latest/reference/generated/networkx.utils.decorators.argmap.html#networkx.utils.decorators.argmap.__init__). The `__init__` method is automatically documented and embedded in the page (though in this case it doesn't have a docstring) while all of the other methods (`assemble`, `compile`, and `signature`) don't link to their respective docstrings.
The reason for this is that the default class template for `autosummary` is missing the `:toctree:` option, which is what signals to sphinx that …
> Fix automatic documenting of class methods via autosummary

- networkx/algorithms/traversal/breadth_first_search.py
- networkx/algorithms/traversal/tests/test_bfs.py
Documented some examples and added a couple of unit tests for `nx.descendants_at_distance`. Also did some minor refactoring to eliminate an unreachable line. Increases module coverage to 100%.
Fixes #4957
> Add unit tests and examples / doctests for nx.descendants_at_distance

- networkx/algorithms/community/modularity_max.py
- networkx/algorithms/community/tests/test_modularity_max.py
Hi; a small suggestion to allow breaking the greedy_modularity_max loop when a certain number of communities is reached. Nothing changes when using the default configuration, i.e. if the parameter is not specified... Would help for my work!
> modularity_max: breaking the loop when given community size is reached

- networkx/algorithms/link_prediction.py
- networkx/algorithms/tests/test_link_prediction.py
(Note: the question at the bottom should be discussed and addressed before merging)
Fixes a bug where CCPA throws a KeyError due to there being no path between nodes. I assume that the method should return a score of 0 if there is no path between two nodes. I make this assumption based on this being a local neighbourhood similarity score based on common neighbours and shortest path. CCPA gives a higher score for nodes that have a small shortest path and a lower score for a longer shortest path. No shortest path means the nodes have no structural connection and also no common neighbours, thus a score of 0 is sensible. This is in line with other link prediction methods (based on common neighbours) which simply returns a score of 0 inherently, due to there being no common neighbours.
I …
> Fix disconnected graph bug in link prediction CCPA and add tests

- networkx/algorithms/connectivity/edge_augmentation.py
As discussed in #3700, repetitive access to the `Graph.adj` property may degrade performance. This is the case for the current implementation of the `complement_edges` function located in `networkx.algorithms.connectivity.edge_augmentation.py`.
This PR includes a trivial change to store the adjacency view as a local variable instead of repeatedly accessing the property inside of a loop. This eliminates `(n choose 2)` function calls, so the performance gain can be noticeable.
Demo code (profiled line-by-line using [pprofile](https://pypi.org/project/pprofile/)):
```python
import pprofile
from networkx.algorithms.connectivity.edge_augmentation import complement_edges
if __name__ == "__main__":
G = nx.complete_graph(1000)
prof = pprofile.Profile()
with prof():
res = …
```
> Store `G.adj` as a local variable to speed up `complement_edges(G)`

- networkx/algorithms/approximation/tests/test_traveling_salesman.py
#4740 recently included a lot of really nice tests for the aTSP problem. Two of those tests in particular have [quite long runtimes](https://github.com/networkx/networkx/pull/4740#discussion_r693340037). This PR proposes to mark these tests as slow so that they are not run in the test suite by default.
> Mark two atsp tests as slow

- networkx/drawing/nx_pylab.py
- networkx/drawing/tests/test_pylab.py
Fixes #4994.
There is a bug in the current code where if a user tried to exclude self-loop drawing via the `edgelist` parameter, it would not work and the selfloops would be drawn anyways. This fixes that by only drawing selfloops when they are part of the original edgelist.
> Fix bug in selfloop drawing in draw_networkx_edges

- networkx/algorithms/centrality/betweenness.py
- networkx/algorithms/centrality/betweenness_subset.py
- networkx/algorithms/centrality/tests/test_betweenness_centrality.py
This PR adds betweenness centrality (BC) for multigraphs. The function ```betweenness_centrality``` is currently marked as ```@not_implemented_for("multigraph")``` however ```edge_betweenness_centrality``` is not even though it suffers from the same shortcomings. With this PR both functions should yield correct results.
The PR consists of three commits addressing issues with BC for multigraphs:
**1. Edge betweenness centrality lacks ```not_implemented``` decorator**
The first commit marks ```èdge_betweenness_centrality``` as not implemented for multigraphs.
It suffers from the issues described below and should at least be marked correctly.
**2. Weighted betweenness centrality disregards weight of parallel edges**
The second commit resolves an issue regarding both betweenness for nodes and …
> Add multigraph betweenness

- networkx/algorithms/community/modularity_max.py
- networkx/algorithms/community/quality.py
- networkx/algorithms/community/tests/test_modularity_max.py
This PR fixes #3112 . ```greedy_modularity_communities()``` is extended to ```DiGraph```'s, ```MultiGraph```'s and ```MultiDiGraph```'s. The formulas used can be found in the [paper](https://github.com/elplatt/Paper-CNM-Modularity/blob/master/paper.pdf) provided by @elplatt.
The bulk of the changes concerns the initialization of the data structures:
- ΔQ matrix (```dq_dict```). It holds the ΔQ of the merge of every pair of communities
- ```a``` dict. It contains the fraction of (total weight of the) ends of edges that are attached to vertices in each community
- ```b``` dict. It is introduced when the graph is directed and contains the fraction of (total weight of the) heads (in_degree) of edges that are attached to vertices in each community. In that case, ```a``` contains the fraction …
> Fixes #3112 - Extends greedy_modularity_communities() to digraphs, multigraphs and multidigraphs

- networkx/algorithms/smallworld.py
Fixed typo in description of smallworld.omega algorithm.
small-work --> small-world
(This is my first contribution to any project on GitHub. I've followed the contribution guidelines and hope I have done everything correctly!)
> Fix typo smallworld.omega

- networkx/algorithms/community/modularity_max.py
- networkx/algorithms/community/tests/test_modularity_max.py
- networkx/utils/mapped_queue.py
- networkx/utils/tests/test_mapped_queue.py
This builds on discussion in #4992 and #5000.
- adds a test for that breaks with a KeyError caused by round-off error when resolution is 0.99
- updates MappedQueue to split priority from the element in the heap. Add appropriate tests
This uses @tristanic's idea for a Class to do this.
- update max_modularity.py module to work with the new MappedQueue class
Closes #4992 
Closes #5000
> Allow greedy_modularity_communities to use floating point weights or resolution

- .github/workflows/coverage.yml
- .github/workflows/deploy-docs.yml
It looks like `gdal==3.0.4` is failing with the latest version of `setuptools`. Try removing this upper bound to see if CI gets unstuck.
> CI/MAINT: drop gdal tests

- networkx/readwrite/edgelist.py
- networkx/readwrite/tests/test_edgelist.py
Closes #4989
Adds support for `comments=None` to allow users to indicate that *no* character should be interpreted as indicating the start of a comment. This is a pretty niche case, but one could imagine a scenario where node names in an edgelist can be composed of a wide range of characters. If a user reading an edgelist wants to guarantee that part of a node string won't erroneously be taken as the start of a comment, they need to select a character to pass into the `comments` kwarg that is *not* used in any of the node names in the data file. Adding support for `comments=None` is a more straightforward solution for this case.
> Support `comments=None` in read/parse edgelist

- doc/reference/algorithms/graph_hashing.rst
- doc/release/release_dev.rst
- networkx/algorithms/graph_hashing.py
- networkx/algorithms/tests/test_graph_hashing.py
- add a new method `weisfeiler_lehman_hash_subgraphs`, and refactored `weisfeiler_lehman_hash_graph` so the two methods share common steps and are more efficient.
- added docstring with example for `weisfeiler_lehman_hash_subgraphs`
- added test class for `weisfeiler_lehman_hash_subgraphs` with randomly generated graphs for each test
- replaced tests for  `weisfeiler_lehman_hash_graph`  to be aligned with the coverage of tests for `weisfeiler_lehman_hash_subgraphs`
The current `weisfeiler_lehman_hash_graph` returns a hash for a graph, but sometimes it is useful to keep the subgraph hashes induced by k-hops from each node generated by the iterations along the way. For example when building general WL graph kernels [1] or in the popular 'Graph2Vec' algorithm [2] where these subgraph hashes …
> Add weisfeiler lehman subgraph hashing

- doc/developer/deprecations.rst
- doc/reference/utils.rst
- doc/release/release_dev.rst
- networkx/drawing/layout.py
- networkx/linalg/algebraicconnectivity.py
- networkx/utils/decorators.py
- networkx/utils/tests/test_decorators.py
This was originally identified by @boothby in #4739:
There are three decorators for setting functions with a reproducible random seed: `py_random_state`, `np_random_state`, and `random_state`. Of the three, [only `random_state` is documented in the ref guide](https://networkx.org/documentation/latest/reference/utils.html#module-networkx.utils.decorators). However, `random_state` is only an alias for `np_random_state`. This PR proposes to deprecate the `random_state` alias in favor of the more explicit `np_random_state` name, and document the two functions.
> Deprecate `random_state` decorator

- networkx/algorithms/shortest_paths/tests/test_weighted.py
- networkx/algorithms/shortest_paths/weighted.py
- networkx/algorithms/simple_paths.py
Fixes issue #5023 and similar issue
`single_source_dijkstra` and `single_source_bellmanford` now raise exception when source and target are same but they are not in graph, which previously was returning 0.
> Bug fix for issue #5023 :  corner-case bug in single_source_dijkstra

- networkx/readwrite/graphml.py
- networkx/readwrite/tests/test_graphml.py
Closes #5024
Modifies how the dict that defines supported GraphML types is accessed so that an informative exception is raised if a user tries to save an attribute of an unsupported type.
This solution is technically backward incompatible, as it changes the (currently public) `xml_types` attr of the `GraphML` class from a dict to a method. The reason for doing it this way is that it provides an easy way to ensure that the exception is raised for all of node, edge, and graph attrs. If this is a problem though, we can always go with the clunkier (but backward compatible) approach which would add try-excepts each time the dict is accessed. LMK what you think!
> More informative GraphML exceptions

- doc/reference/generators.rst
- networkx/generators/geometric.py
Adds `geometric_edges` to top-level `nx` namespace and improves documentation for this function.
Closes #5025
> Document `geometric_edges` and add it to main namespace

- networkx/algorithms/centrality/trophic.py
In return value description: "vale" -> "value"
> Fix small typo in `trophic_levels` documentation

- networkx/algorithms/dag.py
- networkx/algorithms/tests/test_dag.py
Closes #5043 
---
Please look for a description in related issue
> Adding graph/multigraph support to function `transitive_closure`

- networkx/generators/random_graphs.py
- networkx/generators/tests/test_random_graphs.py
This fixes #3389 with the change suggested by @proto-n in that issue.  I have generated hundreds of thousands of graphs to confirm that the edge counts are as expected.
> Fix fast_gnp_random_graph for directed graphs (issue #3389)

- networkx/generators/tests/test_random_graphs.py
Minor improvement related to the issue #5092.
All the occurences of `sum(1 for _ in G.edges())` in ./networkx/generators/tests/test_random_graphs.py have been replaced with `G.number_of_edges()`.
> Get number of edges by calling the proper method (issue #5092)

- doc/developer/projects.rst
Update the [mentored projects](https://networkx.org/documentation/latest/developer/projects.html) section in the developer docs to reflect the successful completion of several ideas from the latest round of GSoC.
I decided to remove the community detection section entirely since it was all about Louvain, but if we'd prefer to simply update it (e.g. w/ Leiden instead), please revert 4952ee8 and update the wording as you see fit!
> Update mentored projects section in docs

- networkx/algorithms/shortest_paths/tests/test_weighted.py
Just something I noticed while reviewing #5033:
Slightly refactors the tests of the shortest-path functions to parametrize over the function being tested. The main motivation is to make it more clear which test is failing if/when they fail.
Other changes include:
- using `pytest.raises` as a context manager in these tests
- Adding a src==tgt branch for the multisrc tests.
> Parametrize shortest path node-checking tests.

- networkx/drawing/layout.py
- networkx/drawing/tests/test_layout.py
`multipartite_layout()` was failing on graphs containing nodes with non-numeric partition labels because node coordinates were being created using the partition labels. Changed loop to use `enumerate()` so that node coordinates are generated from the index of the partition, not its label (per @LelioC 's fix [here](https://github.com/networkx/networkx/issues/5123)).  
I added test for nodes w/ non-numeric partition labels and non-numeric names to `test_multipartite_layout()`.
Closes #5123
> Bugfix for issue 5123

- networkx/drawing/nx_pylab.py
From the discussion in #matplotlib/matplotlib#21517, ax.transOffset would have had no effect prior to matplotlib-3.5.0rc1. Looking at `blame` doesn't indicate any specific reason why the `transOffset` arg was passed to the LineCollection constructor - [this has been the case since `nx_pylab` was introduced](https://github.com/networkx/networkx/blame/3f478bba187e34a3bed6609be1bd9c21486fe875/networkx/drawing/nx_pylab.py#L316).
In principle, removing this should have no effect. I've built the docs locally and compared the NX gallery examples both with and without this change and didn't notice anything visually.
Closes gh-5167
> Rm passing ax.transOffset to LineCollection when drawing undirected edges

- doc/developer/new_contributor_faq.rst
Mostly states that there is no "official" policy, but that algorithms should be published (and preferrably cited) to warrant inclusion in NetworkX. Also adds a link to the Mission & Values docs to give more high-level guidance.
> Add a Q&A to the contributor FAQ about algorithm acceptance policy.

- requirements/extra.txt
Reverts networkx/networkx#5156
There is now a conflict in `packaging` with the new pyparsing, and they have pinned to pyparsing < 3, which causes problems for our fix. Removing the pin here should mean that we default to the `packaging` pin, which should keep the `pyparsing`/`pydot` problems at bay.
Closes #5157
> Revert "Add temporary pyparsing pin to fix CI."

- networkx/algorithms/link_prediction.py
This PR adds a branch in `common_neighbor_centrality` to introduce a simple performance optimization. Computing `nx.shortest_path_length(G)` is extremely computationally expensive, so we should avoid this call, especially if the corresponding result isn't used.
When `alpha = 1`, the expression:  
```python
(1 - alpha) * (G.number_of_nodes() / path_len)
```
evaluates to 0.
As such, `path_len`, and consequently `spl` aren't being used.
`alpha = 1` is a common enough configuration for the parameter that I feel this optimization is justified. The tradeoff is between the complexity of the newly introduced code and the performance benefit of avoiding computing shortest path legnths.
I believe the tradeoff has a clear winner.
This PR tries to avoid the computationally expensive call to generate …
> Only compute shortest path lengths when used

- .github/workflows/mypy.yml
- .mypy.ini
- networkx/algorithms/approximation/kcomponents.py
- networkx/algorithms/approximation/tests/test_traveling_salesman.py
- networkx/algorithms/bipartite/edgelist.py
- networkx/algorithms/centrality/katz.py
- networkx/algorithms/community/lukes.py
- networkx/algorithms/connectivity/__init__.py
- networkx/algorithms/d_separation.py
- networkx/algorithms/flow/tests/test_maxflow.py
- networkx/algorithms/shortest_paths/tests/test_weighted.py
- networkx/algorithms/tests/test_cycles.py
- networkx/algorithms/tests/test_graph_hashing.py
- networkx/algorithms/tests/test_smallworld.py
- networkx/algorithms/traversal/tests/test_edgebfs.py
- networkx/algorithms/traversal/tests/test_edgedfs.py
- networkx/classes/graphviews.py
- networkx/classes/tests/test_multigraph.py
- networkx/drawing/layout.py
- networkx/generators/line.py
- networkx/readwrite/graphml.py
- networkx/readwrite/nx_shp.py
- networkx/readwrite/tests/test_gml.py
- networkx/utils/decorators.py
- requirements/developer.txt
The purpose of this PR is to evaluate the impact of adding the static type checker Mypy to the development workflow of NetworkX. This PR **does not add any type annotations**! The goal is to see what impact the static type checker has on the existing code base. Adding this infrastructure is the first step in enabling support for type annotations moving forward. This PR also aims to focus the discussion in #5073 and provide an objective accounting of what sort of things `mypy` catches in the NX codebase and how these issues can be fixed.
The first step in the analysis is to ascertain what mypy reports on the existing codebase, which doesn't contain any type annotations (with the exception of one function). This can be done on `main` in an existing development environment as follows: …
> Add Mypy type checking infrastructure

- networkx/drawing/tests/test_pydot.py
A second attempt at a temporary solution to the failing pydot tests due to its pyparsing dependency (see #5155, pydot/pydot#277 pyparsing/pyparsing#338).
Rather than alter dependency pinning which has proven to be fragile, the pydot tests can be xfailed which should both fix CI now *and* notify us when the pydot/pyparsing issue is fixed, because the xfailed tests will start passing again.
> CI: xfail pydot tests.

- networkx/linalg/algebraicconnectivity.py
There is an internal `_CholeskySolver` class that does nothing other than raise an exception upon instantiation. The exception message indicates that it is intended to be replaced by the LU solver, though there is no deprecation warnings or anything like that.
Since this is a private class, and since it was otherwise accessible only via one undocumented keyword argument, I think it is safe to remove. Users would already get an exception message if they tried to use it - this will still be the case, though the exception message is slightly less specific.
> Remove unused internal solver from algebraicconnectivity

- networkx/convert_matrix.py
Minor cleanup of old code designed to catch a behavior change around scipy 1.1. The minimum required `scipy` version for NetworkX is now well above 1.1, so I think it's safe to remove the extra check/comment.
> Remove check/comment for scipy 1.1 behavior.

- networkx/algorithms/tests/test_dag.py
`nx.ancestors` and `nx.descendants` currently work with undirected inputs, but there are currently no tests for undirected inputs. This PR adds a regression test so that a behavior change w/ undirected inputs would be caught in the test suite - see e.g. #5176
> Add regression test for ancestors & descedants with undirected graphs

- networkx/algorithms/distance_measures.py
- networkx/algorithms/tests/test_distance_measures.py
Removes an internal function that was used to remove rows/columns from a Laplacian matrix in favor of a simpler approach based on advanced indexing. Also removes the tests for the internal function.
I think there are other opportunities to improve the function (e.g. see the repeated code below for computing `LdiagA` and `LdiagAB`) but I'll keep the scope of the PR limited to make reviewing easier.
> Improve `resistance_distance` implementation with advanced indexing

- networkx/linalg/laplacianmatrix.py
- networkx/linalg/tests/test_laplacian.py
Calling `nx.directed_laplacian_matrix` currently results in:
```python
>>> import networkx as nx
>>> G = nx.gn_graph(10)
>>> nx.directed_laplacian_matrix(G)
Traceback (most recent call last)
...
AttributeError: module 'scipy.sparse' has no attribute 'linalg'
```
This is because `directed_laplacian_matrix` and `directed_combinatorial_laplacian_matrix` are missing internal imports of the scipy.sparse.linalg subpackage.
Alarmingly, this was not caught by the test suite - likely due to imports persisting within the test class. Breaking the two test methods for the `directed` Laplacians out of the class into test functions is sufficient to catch the missing imports (this is the only change to the tests that I made for this PR).
> Fix missing import and tests for directed Laplacian functions

- networkx/drawing/layout.py
- networkx/drawing/tests/test_layout.py
Closes #5202 
So far no one has been able to reproduce the CI failures locally, so opening a draft pull request to investigate if refactoring the failing test has any effect on the problem.
At this point I have no concrete idea as to why this is failing on CI (ubuntu) but not any locally tested platforms (arch, debian). The test does rely on `linalg` so maybe a linalg backend issue? Seems unlikely as this probably would have resulted in much more noisy failures elsewhere.
> Investigate pre-release test failures

- networkx/tests/test_convert_scipy.py
Minor cleanup: removes two unnecessary lines and converts test suite assertions to the preferred style (i.e. assert statements rather than using `assert_` functions).
This would also make it easier to refactor these tests using a non-OO design in the future.
> Remove assertion test method in favor of assert statements
