- networkx/algorithms/centrality/closeness.py
Fixed issue which is related to #1318.
> Fixed 404 link of reference pdf

- networkx/classes/tests/test_timing.py
- networkx/classes/tests/timingclasses.py
This style of testing works with nose and compares to
previous code (v1.9) so it gives long term baseline.
Its a step toward v2.0 where base classes will change.
We can't overload this or tests will take too long.
As currently config'd it adds about 5 seconds.
The code also runs on its own and produces a timing report.
python test_timing.py
> Add timing tests and baseline classes to compare to.

- networkx/convert.py
> Simplifies _prep_create_using function

- .travis.yml
- doc/source/reference/convert.rst
- networkx/classes/tests/test_timing.py
- networkx/convert.py
- networkx/convert_matrix.py
- networkx/drawing/tests/test_pylab.py
> to/from Pandas Dataframe 

- networkx/drawing/nx_pylab.py
1. A minor correction to the comment.
2. A minor change to the default value in terms of consistency.
> Minor correction of comments and default value regarding alpha

- networkx/__init__.py
Added a bibtex attribute for quick command-line access to the recommended citation info. Idea by @jakevdp: https://twitter.com/jakevdp/status/524329573580697600
> added networkx.__bibtex__ attribute

- networkx/classes/digraph.py
- networkx/classes/graph.py
This puts add_nodes_from assignments inside the try/except clause so that ironpython works even pre-2.7.5.
Fixes #1327
> Address ironpython issues from #1327

- examples/algorithms/davis_club.py
- networkx/generators/social.py
Keep track of ordering in davis club and show how to use one-mode projections.
> Simplify Davis Club example

- doc/source/reference/algorithms.bipartite.rst
- networkx/algorithms/bipartite/__init__.py
- networkx/algorithms/bipartite/matching.py
- networkx/algorithms/bipartite/tests/test_matching.py
Adds the Hopcroft--Karp algorithm for finding a maximum cardinality
matching in bipartite graphs.
I wasn't sure whether to put this in `networkx.algorithms.matching` or in `networkx.algorithms.bipartite`; I chose the latter.
> Maximum cardinality matching in bipartite graphs.

- doc/source/reference/credits.rst
> Update link in credits to Guido essay on graphs

- doc/source/reference/api_2.0.rst
- networkx/algorithms/centrality/__init__.py
- networkx/algorithms/centrality/harmonic.py
- networkx/algorithms/centrality/tests/test_harmonic_centrality.py
Added a new algorithm for centrality based on Harmonic Centrality.
> Added Harmonic Centrality Algorithm

- networkx/algorithms/operators/binary.py
> Fixed node attributes in compose function

- networkx/algorithms/centrality/betweenness.py
Hi all, I'm new here, so apologize if I did anything stupid, I just happened to need this function, and figured out this is in the wishlist #1220, so I mimic the approximation method in betweenness_centrality to add approximation for edge betweenness centrality. Hope this is the correct way to contribute to network :)
> Add Approximation for edge_betweenness_centrality as wishlist in #1220

- networkx/classes/graph.py
> Correct add_nodes_from use of adjlist_dict_factory

- doc/source/reference/api_2.0.rst
@ysitu I revised the file as you said and checked the commits since last November. I found 3 changes worth adding. Please see them.
> Revised api_2.0.rst and added some major contributions

- networkx/algorithms/connectivity/connectivity.py
- networkx/algorithms/connectivity/tests/test_connectivity.py
See explanation at #1406 . Also added tests.
> Fix all_pairs_node_connectivity results dict. Fixes #1406.

- doc/source/reference/algorithms.dag.rst
- doc/source/reference/api_2.0.rst
- networkx/algorithms/dag.py
- networkx/algorithms/tests/test_dag.py
> Expose transitive_clousure and antichains in the public API

- networkx/drawing/nx_pylab.py
Addresses the documentation issue that I point out #1441, in the case that this functionality is officially supported (though unit tests should also likely be added as well if that's the case, and if they don't already exist).
> MAINT: updated description of this parameter

- networkx/linalg/__init__.py
- networkx/linalg/modularitymatrix.py
- networkx/linalg/spectrum.py
- networkx/linalg/tests/test_modularity.py
- networkx/linalg/tests/test_spectrum.py
This pull request implements the modularity matrix (MEJ Newman, 2006, PNAS) with associated test suites and spectrum operations.
I did not implement any weighted/multigraph/directed methods since there is no consensus on the definition, to the best of my knowledge.
This is my first contribution to NetworkX, comments are more than welcome.
> Modularity matrix

- doc/source/reference/api_2.0.rst
- doc/source/reference/generators.rst
- networkx/generators/classic.py
- networkx/generators/tests/test_classic.py
This is a generalization of the complete bipartite graph generator.
> Adds generator for complete multipartite graph.

- doc/source/reference/api_2.0.rst
- doc/source/reference/credits.rst
- doc/source/reference/generators.rst
- networkx/generators/__init__.py
- networkx/generators/nonisomorphic_trees.py
- networkx/generators/tests/test_nonisomorphic_trees.py
Added a generator for non isomorphic trees as suggested by @hagberg in https://github.com/networkx/networkx/issues/1034.
* should we keep `_layout_to_matrix`?
> Non Isomorphic Trees generator

- doc/source/reference/introduction.rst
> Fix developer zone link

- doc/source/reference/algorithms.triads.rst
- doc/source/reference/api_2.0.rst
- networkx/algorithms/__init__.py
- networkx/algorithms/tests/test_triads.py
- networkx/algorithms/triads.py
Fixes issue #191.
I took one of the implementations and one of the test functions I found in the referenced issue and updated them, mostly for style.
> Adds triadic census function to new `triads` module

- networkx/algorithms/swap.py
This implements an optimization that speeds up the
`connected_double_edge_swap()` function. It uses a threshold, below
which graph connectivity is checked after each swap, and above which,
graph connectivity is only checked after a number of swaps are made.
This code is from #325, with updates mostly for style.
> Optimization for connected double edge swap.

- doc/source/reference/algorithms.operators.rst
- doc/source/reference/api_2.0.rst
- networkx/algorithms/operators/product.py
- networkx/algorithms/operators/tests/test_product.py
> Added power function for simple graphs

- networkx/algorithms/components/strongly_connected.py
Reported in #1473 
Removed line 156.
Also a pep8 fix.
> Docstring fix for strongly_connected_components_recursive()

- networkx/generators/social.py
Also updates the documentation to disclose previously undocumented node
attributes and provides PEP8 compliance.
> Simplifies the code for the karate club graph.

- networkx/generators/stochastic.py
PEP8 fixes, updates and clarifies documentation, and imports real
division in order to remove casting numbers to floats.
> Cleans generators.stochastic docstrings and code

- networkx/utils/union_find.py
> Simplifies call to max() in utils.union_find

- doc/source/reference/generators.rst
- networkx/generators/random_graphs.py
Also exposes previously unexposed `duplication_divergence_graph` function.
> Cleans documentation for generators.random_graphs

- networkx/algorithms/block.py
trivial change, but slightly cleaner?
> zip(range(len(x)),x) -> enumerate(x) for pythonism

- networkx/algorithms/flow/preflowpush.py
- networkx/algorithms/flow/tests/test_maxflow.py
This change resolves issue #1542
> Makes enough levels in preflow_push

- networkx/readwrite/gml.py
As discussed in #1449 and then stated in #1454.
> fix documentation for write_gml()

- doc/source/reference/api_1.10.rst
- doc/source/reference/api_changes.rst
> Update api_2.0.rst to api_1.10.rst and deprecate *iter functions

- networkx/algorithms/shortest_paths/tests/test_weighted.py
- networkx/algorithms/shortest_paths/weighted.py
In response to https://github.com/networkx/networkx/issues/1506 this pull request updates ``johnson`` in order graph not be modified.
To be more specific, not any node is added to the graph to compute dist values of each other node using Bellman - Ford algorithm. For this purpose, a new function is added ``_bellman_ford_relaxation`` which contains the relaxation loop for Bellman - Ford. It is used both in ``johnson`` and ``bellman_ford``
> Update Johnson's algorithm so that graph is not modified(#1506)

- doc/source/reference/algorithms.minors.rst
- networkx/algorithms/minors.py
> make identified_nodes an alias for contracted_nodes

- networkx/algorithms/matching.py
https://github.com/networkx/networkx/issues/1564
> Update documentation of networkx.algorithms.matching to include reference to networkx.algorithms.bipartite.matching for bipartite graphs

- networkx/drawing/nx_pylab.py
#1557 
TODO
- code refactoring and pep8
> add arrows parameter in draw_networkx

- doc/source/reference/drawing.rst
This PR adds some comments about the state of graph visualization in NetworkX. It also includes links to Cytoscape, Graphviz, and PGF/TikZ (which as of version 3.0 has automated graph layout algorithms implemented via LuaTeX).
> Add some comments/recommendations about drawing.

- networkx/algorithms/operators/all.py
- networkx/algorithms/operators/binary.py
- networkx/algorithms/operators/product.py
- networkx/algorithms/operators/unary.py
Fixes #1599.
I also used the opportunity to change the modules in `algorithms.operators` as per pep8 compilance.
> Docstring update for Cartesian product and Tensor product

- networkx/algorithms/assortativity/connectivity.py
> Update assortativity/connectivity.py, target_degree to take in iterator instead of list

- doc/source/download.rst
- doc/source/install.rst
- doc/source/overview.rst
While writing similar docs for `networkx-metis` I spotted few updates for `doc/source/overview.rst`.
> Few updates in doc/source/overview.rst

- examples/drawing/unix_email.py
- examples/graph/football.py
- examples/graph/unix_email.py
- examples/subclass/antigraph.py
The example in the the `networkx/examples` directory are updated. They follow the recent changes made in core classes and the subclass `AntiGraph`.
> Update examples directory

- .travis.yml
This is my first attempt for the switch. Let's see if it needs more.
> Switch to container based travis build

- networkx/classes/graph.py
This comment obviously only applies to directed graphs..
> Fix wrong comment

- networkx/algorithms/distance_regular.py
Also makes some PEP8 style fixes.
> Simplifies global_parameters function in distance_regular module.

- networkx/algorithms/core.py
> Simplify and refactor functions related to k-cores

- networkx/algorithms/euler.py
Also updates documentation and makes PEP8 style fixes.
> Simplifies is_eulerian function.

- doc/source/reference/algorithms.community.rst
- networkx/algorithms/community/__init__.py
- networkx/algorithms/community/centrality.py
- networkx/algorithms/community/tests/test_centrality.py
This pull request implements Girvan-Newman algorithm which detects communities by progressively
removing edges from the original graph.
For this reason, we created a new module named ``community.py`` and there added the ``girvan_newman`` function
> Add Girvan-Newman algorithm for communities detection

- doc/source/reference/migration_guide_from_1.x_to_2.0.rst
- doc/source/reference/moving_from_1.xx_to_2.0.rst
- doc/source/reference/release_2.0.rst
This adds a note regarding the work in iter_refactor branch
> Update 2.0 notes

- doc/source/reference/api_changes.rst
- doc/source/reference/release_2.0.rst
- doc/source/tutorial/tutorial.rst
- examples/algorithms/blockmodel.py
- examples/subclass/antigraph.py
- networkx/classes/digraph.py
- networkx/classes/graph.py
- networkx/classes/multidigraph.py
- networkx/classes/multigraph.py
Mostly doc string tweaks for graph classes, tutorial.
Fixes of blockmodel and antigraph examples
api_changes and release_2.0 updates. Addresses #1655
> minor changes related to _iter removal

- networkx/algorithms/matching.py
- networkx/algorithms/tests/test_matching.py
add weight attribute parameter in `max_weight_matching`
> weight parameter for max_weight_matching

- networkx/algorithms/matching.py
keep a set of used vertices instead of used edges
> constant factor improvement for maximal_matching

- .travis.yml
- networkx/readwrite/nx_shp.py
> For v1.11 drop support for python3.2 and add 3.5

- networkx/readwrite/gml.py
- networkx/readwrite/tests/test_gml.py
> Issue 1780

- networkx/algorithms/centrality/harmonic.py
- networkx/algorithms/shortest_paths/generic.py
- networkx/algorithms/shortest_paths/tests/test_generic.py
- networkx/algorithms/shortest_paths/tests/test_weighted.py
- networkx/algorithms/shortest_paths/weighted.py
- networkx/algorithms/vitality.py
https://github.com/networkx/networkx/issues/1765
> Update all_pairs_dijkstra_path_length and single_source_dijkstra_path_length

- doc/source/install.rst
Add conda update/conda install to install documentation
> Update install documentation

- networkx/algorithms/centrality/harmonic.py
Better use of iterator functionality of path functions, but still returns a dict. 
So is not an iterator itself (yet -- should it be?).
> Rewrite harmonic_centrality to better use iterator

- networkx/algorithms/shortest_paths/weighted.py
> Change comments about fringe tuples in dijkstra

- networkx/algorithms/flow/__init__.py
The ```__all__``` variables are currently not loading correctly in the algorithms/flow/__init__.py file.
This fixes that.
> Make sure __all__ variables loaded in flow __init__.py

- networkx/algorithms/flow/__init__.py
> v1.11 Add utils functions to flow variable __all__

- examples/3d_drawing/mayavi2_spring.py
- examples/advanced/heavy_metal_umlaut.py
- examples/drawing/degree_histogram.py
- examples/drawing/ego_graph.py
- examples/drawing/random_geometric_graph.py
- examples/drawing/sampson.py
- examples/graph/degree_sequence.py
- examples/pygraphviz/pygraphviz_attributes.py
- examples/subclass/antigraph.py
- examples/subclass/printgraph.py
This will help with readthedocs make_gallery #1667
These are solely due to the switch to our 2.0 API
> Update examples for iterator edges and nodes methods

- networkx/linalg/algebraicconnectivity.py
> fix compatible issue with new numpy

- networkx/algorithms/__init__.py
- networkx/algorithms/reciprocity.py
Implemented Issue #731 
This Issue has been there for a while and it seems no one want to touch it so I just did it by myself.
The styles of the file are based on other similar modules.
> Implement reciprocity for directed graph.

- networkx/classes/tests/test_graph.py
This should have been included in pull request #1813.
> Adds unit test for new use of string.format().

- networkx/readwrite/__init__.py
I couldn't import json_graph so I added the import!
> Fix import issue for readwrite.json_graph

- networkx/algorithms/cycles.py
> Correct the documentation for simple_cycles

- doc/source/reference/generators.rst
- networkx/generators/community.py
- networkx/generators/tests/test_community.py
This pull request adds the  `ring of cliques` function which generates a ring of cliques graph.
It takes two parameters, the number of cliques and the size of cliques.
> Add generator for a ring of cliques graph

- networkx/algorithms/centrality/current_flow_betweenness.py
> add documentation for exception for directed graphs

- networkx/classes/function.py
- networkx/classes/tests/test_function.py
> #1849 add with_data to create_empty_copy

- networkx/algorithms/flow/networksimplex.py
Small change to the docstring to mention that the demands also should not be floating point.
> DOC: Updating docstring to mention issues about demands.

- networkx/generators/directed.py
for big network this speed improvement matters
> float take out of inner loop for speed

- networkx/algorithms/richclub.py
- networkx/algorithms/tests/test_richclub.py
> Fixed Rich Club Boundary Case

- doc/source/reference/algorithms.tournament.rst
- networkx/algorithms/__init__.py
- networkx/algorithms/tests/test_tournament.py
- networkx/algorithms/tournament.py
- networkx/utils/misc.py
Creates a new module, `networkx.algorithms.tournament`.
This is also creates a new utility function `is_path`, which may be useful in other places in NetworkX.
> Adds functions operating on tournament graphs.

- doc/source/reference/algorithms.distance_regular.rst
- networkx/algorithms/distance_regular.py
- networkx/algorithms/tests/test_distance_regular.py
This commit introduces the `is_strongly_regular` function.
> Adds test for whether graph is strongly regular.

- networkx/algorithms/dominating.py
Also updates documentation and makes PEP8 fixes.
> Simplifies dominating set functions.

- networkx/algorithms/community/quality.py
- networkx/algorithms/cuts.py
- networkx/algorithms/minors.py
- networkx/algorithms/tests/test_minors.py
https://github.com/networkx/networkx/pull/1845, https://github.com/networkx/networkx/pull/1771
> Update community/quality to use quotient_graph instead of blockmodel

- networkx/classes/graph.py
Although I am still not a Git master, I think this one is correct.
> Bugfix (or simplification) of the size method in the Graph class

- networkx/release.py
#1882
@hagberg Should I cherry-pick this commit and create a new PR for master branch?
> Modified release.py

- doc/source/reference/algorithms.reciprocity.rst
- doc/source/reference/algorithms.rst
> add algorithms.reciprocity to reference documentation

- networkx/algorithms/connectivity/cuts.py
- networkx/algorithms/connectivity/tests/test_cuts.py
Fixes [ #1812](https://github.com/networkx/networkx/issues/1812)
@dschult please take a look.
> minimum_st_node_cut incorrect  if source and target are connected 

- doc/source/reference/algorithms.community.rst
- networkx/algorithms/community/__init__.py
- networkx/algorithms/community/community_utils.py
- networkx/algorithms/community/kernighan_lin.py
- networkx/algorithms/community/tests/test_kernighan_lin.py
This is one of the algorithms for community detection from #764. I made PEP8 fixes.
> Adds Kernighan--Lin bipartition algorithm.

- networkx/algorithms/cluster.py
Replaces numbers like `1.0` with `1` after importing division from `__future__`, which should solve the problem that using the decimal points intended to solve.
> Simplifies functions in cluster.py.

- networkx/algorithms/community/tests/test_kernighan_lin.py
> Marks file encoding as UTF-8

- networkx/algorithms/vitality.py
This commit changes the behavior of the `closeness_vitality()` function
so that it only computes the Wiener index of the original graph once
instead of recomputing the same value for each node in the graph.
> Don't recompute Wiener index unless necessary.

- networkx/algorithms/richclub.py
Uses enumerate and heapq instead of more complicated code constructions.
Also updates documentation and makes PEP8 style fixes.
> Simplifies rich-club coefficient code.

- networkx/classes/graph.py
> Doc tweak on edges for v1.11

- examples/drawing/degree_histogram.py
- examples/drawing/degree_rank.py
Degree_histogram renamed degree_rank.
New Degree_histogram example shows histogram.
Discussed in #1774
> Rename degree_histogram example and add replacement

- doc/source/reference/utils.rst
- networkx/utils/misc.py
- networkx/utils/tests/test_misc.py
Add cycle keyword argument to pairwise
Add tests for pairwise
see #1883
> Add cycle argument to utils.misc.pairwise

- networkx/generators/classic.py
- networkx/generators/geometric.py
also PEP8.   Files: classic.py and geometric.py
> Update generator docstrings for nodes_or_number

- doc/source/reference/algorithms.minors.rst
- networkx/algorithms/minors.py
> Update deprecation warning

- doc/source/reference/readwrite.json_graph.rst
- examples/jit/rgraph.py
- networkx/readwrite/json_graph/__init__.py
- networkx/readwrite/json_graph/jit.py
- networkx/readwrite/json_graph/tests/test_jit.py
Added tests, implemented `jit_graph`.
> JIT JSON writer, updates #881

- networkx/readwrite/gml.py
Deal with the issue #1783. Also change the variable name from type to category to avoid confusion.
> Gml read fix.

- networkx/readwrite/gml.py
Should complete #1775 and #1847.
> Small changes leftover from #1847

- networkx/algorithms/core.py
- networkx/algorithms/tests/test_core.py
Fixes #1959 
Two fairly simple graph theory projects for someone interested in getting into the code:
- Make k-core work for self-loops.  I think it might already work for multiedges with this fix.
- Create D-core module (referred to in original issue)
> Fix k_core for directed graphs. Add tests

- networkx/algorithms/shortest_paths/tests/test_weighted.py
- networkx/algorithms/shortest_paths/weighted.py
This commit allows the user to provide an arbitrary function that
computes the weight of an edge instead of relying on an edge attribute.
This is a backwards-compatible change.
If this pull request is merged, then pull request #1555 should be updated in the manner described there.
> Allows weight functions in shortest path functions

- networkx/algorithms/shortest_paths/weighted.py
Fixed up some docs and whitespace noticed while reviewing #1690.
One content change to get ```cost``` of uv-edge once in _dijkstra.
> minor doc changes on weighted.py

- networkx/convert_matrix.py
- networkx/tests/test_convert_pandas.py
Addresses Issue #1982, from_pandas_dataframe with create_using= nx.MultiGraph() raised an error.
> bug fix in convert_matrix.py

- networkx/algorithms/assortativity/connectivity.py
- networkx/algorithms/assortativity/tests/test_connectivity.py
This commit improves the test coverage by both simplifying the code and adding missing unit tests.
> Improves test coverage for avg degree connectivity

- doc/source/reference/algorithms.communicability_alg.rst
- doc/source/reference/algorithms.rst
- doc/source/reference/classes.digraph.rst
- doc/source/reference/classes.graph.rst
- doc/source/reference/classes.multidigraph.rst
- doc/source/reference/classes.multigraph.rst
- doc/source/reference/functions.rst
- doc/source/reference/generators.rst
- networkx/algorithms/community/quality.py
- networkx/algorithms/cuts.py
- networkx/algorithms/reciprocity.py
Some modules moved or were removed. A few indentation issues.
Fixes #2025
>  Fix sphinx autosummary doc generation errors.

- networkx/readwrite/gexf.py
- networkx/readwrite/tests/test_gexf.py
This is related to #1949.
Changes in first commit: 
* Apply PEP8
* Fix a little bug where `'1'` was keyed to `False` although `1` was keyed to `True` (this was certainly not intended)
* Expand docstring of `relabel_gexf_graph()` with information on raised errors
Changes in second commit:
* Add all `.graph` attributes to `<graph>` tag in xml
* Read `name` from `<graph>` tag in xml
* Add `<meta>` tag with creator + version and datecreated as text (this required two new packages to be imported)
> Improve gexf.py

- README.rst
- doc/source/index.rst
Fixes https://github.com/networkx/networkx/issues/2008
> Readme.rst should mention Decorator package is required.

- networkx/readwrite/pajek.py
This is a fix for the reported issue  #1948. I also added checking for empty string attribute values for nodes and applied PEP8 formatting.
> fix issue #1948 and PEP8 formatting

- networkx/algorithms/shortest_paths/tests/test_weighted.py
- networkx/algorithms/shortest_paths/weighted.py
This commit also makes the test classes use inheritance.
Fixes issue #2032.
> Uses weight function for dijkstra_path_length.

- networkx/algorithms/community/centrality.py
- networkx/algorithms/community/tests/test_centrality.py
This includes the fixes from pull request #1703, pull request #1725, and fixes for issue #1799.
> Fixes several issues with the Girvan-Newman partitioning function

- doc/source/reference/algorithms.simple_paths.rst
- networkx/algorithms/simple_paths.py
- networkx/algorithms/tests/test_simple_paths.py
- networkx/algorithms/tournament.py
- networkx/utils/misc.py
This commit adds the `is_simple_path` function to the public API.
As suggested in pull request #1816.
> Moves is_path from utils to simple_paths.

- doc/source/conf.py
- doc/source/reference/algorithms.centrality.rst
- networkx/algorithms/centrality/load.py
- networkx/algorithms/centrality/tests/test_load_centrality.py
- networkx/algorithms/dag.py
- networkx/algorithms/operators/product.py
- networkx/readwrite/graph6.py
- networkx/readwrite/json_graph/node_link.py
- networkx/readwrite/sparse6.py
There does not seem to be a reference for the definition of edge load.
Our function seems like a reasonable way to count number of
shortest_paths across each edge. But I don't see any articles that
use this definition.
Also, I fixed some sphinx errors that have crept into the code base over time.
> Fixes #1998 edge_load function needs documentation.

- doc/source/reference/algorithms.coloring.rst
- networkx/algorithms/coloring/greedy_coloring.py
This commit also lists the built-in strategy functions separately in the
documentation.
> Simplifies code in functions for greedy coloring.

- networkx/drawing/layout.py
> Fix spring_layout for single node graph.

- networkx/classes/function.py
This commit simplifies `set_node_attributes` and `set_edge_attributes`
by using `zip_longest` in order to avoid creating a list when not
necessary. It also clarifies the documentation.
The documentation change was suggested in issue #1818.
> Updates set_{node,edge}_attributes and docs.

- doc/source/reference/algorithms.community.rst
- networkx/algorithms/community/__init__.py
- networkx/algorithms/community/generators.py
- networkx/algorithms/community/tests/test_generators.py
This is a generator for graphs based on desired community structure from pull request #764. I made PEP8 fixes and some structural changes for clarity.
> Adds LFM benchmark graph generator for communities

- doc/source/reference/algorithms.efficiency.rst
- networkx/algorithms/__init__.py
- networkx/algorithms/efficiency.py
- networkx/algorithms/tests/test_efficiency.py
> Adds global and local efficiency functions.

- networkx/algorithms/community/generators.py
Replace encode elipses with asci ... in file wih no encoding declared.
> Remove encoded ... to plain ascii

- networkx/linalg/modularitymatrix.py
- networkx/linalg/tests/test_modularity.py
@hagberg 
Sorry for the tad late fix, got very busy with work. 
I have created a pull request with the modified code and the tests. Note that one of the test (first assert in test_modularity_weight) should have passed in the previous version, however it did fail as a result of the bug (https://github.com/networkx/networkx/issues/2072). 
Let me know if you want me to change anything
Cheers, 
Enrico
> Issue 2072 weighted modularity

- networkx/readwrite/json_graph/node_link.py
- networkx/readwrite/json_graph/tests/test_node_link.py
- networkx/utils/misc.py
- networkx/utils/tests/test_misc.py
fix for #1975 
Creation of to_tuple in "utils.misc" and converted nodes to tuples in node_linnk_graph.
> Fjmalass nodes as tuples

- networkx/algorithms/community/asyn_lpa.py
- networkx/algorithms/community/community_generators.py
- networkx/algorithms/community/community_utils.py
- networkx/algorithms/community/kernighan_lin.py
> Adds missing __all__ attributes.

- networkx/algorithms/dominance.py
- networkx/algorithms/tests/test_dominance.py
1) Should not discard source u. Fixes #2071
2) Ignore unreachable entry poitns. Fixes #2070
> Fixes 2 bugs in dominance frontier code

- networkx/algorithms/tree/mst.py
- networkx/algorithms/tree/tests/test_mst.py
- networkx/utils/union_find.py
This commit also simplifies the unit tests for the minimum spanning tree
functions while maintaining full test coverage.
This fixes issue #417.
> Adds Borůvka's minimum spanning tree algorithm.

- doc/source/reference/algorithms.centrality.rst
- networkx/algorithms/centrality/__init__.py
- networkx/algorithms/centrality/reaching.py
- networkx/algorithms/centrality/tests/test_reaching.py
This supercedes pull request #1555 and #6 to implement issue #698.
> Adds global/local reaching centrality functions.

- networkx/algorithms/simple_paths.py
- networkx/algorithms/tests/test_simple_paths.py
- networkx/exception.py
Replaces #1894 
related to #1705
> Remove conflicts from #1894 (Update Exception Classes)

- networkx/algorithms/simple_paths.py
- networkx/algorithms/tests/test_simple_paths.py
- networkx/exception.py
> [WIP] Update exception classes

- doc/source/reference/exceptions.rst
- doc/source/reference/release_2.0.rst
- networkx/algorithms/shortest_paths/astar.py
- networkx/algorithms/shortest_paths/generic.py
- networkx/algorithms/shortest_paths/tests/test_astar.py
- networkx/algorithms/shortest_paths/tests/test_weighted.py
- networkx/algorithms/shortest_paths/unweighted.py
- networkx/algorithms/shortest_paths/weighted.py
Fix conflicts for #1445 and use NodeNotFound exception.
Fixes #1433
> Exceptions for missing source in shortest_path

- doc/source/reference/api_2.0.rst
- doc/source/reference/exceptions.rst
- networkx/algorithms/shortest_paths/astar.py
- networkx/algorithms/shortest_paths/generic.py
- networkx/algorithms/shortest_paths/tests/test_astar.py
- networkx/algorithms/shortest_paths/tests/test_weighted.py
- networkx/algorithms/shortest_paths/unweighted.py
- networkx/algorithms/shortest_paths/weighted.py
- networkx/algorithms/simple_paths.py
- networkx/algorithms/tests/test_simple_paths.py
- networkx/exception.py
I decided to raise NetworkxNoPath exception.
> Fixed all_shotest_paths key error  #1433

- networkx/algorithms/matching.py
- networkx/algorithms/operators/product.py
> Fix docs for maximal_matching and tensor_product

- networkx/algorithms/traversal/breadth_first_search.py
The current one is copy-pasted from bfs_edges.
> replace example in bfs_tree with a correct one

- doc/source/reference/classes.multidigraph.rst
- doc/source/reference/classes.multigraph.rst
- networkx/algorithms/isomorphism/isomorph.py
- networkx/classes/multidigraph.py
- networkx/classes/multigraph.py
- networkx/convert_matrix.py
Also add_edge/add_edges_from returns edge keys
Fixes #2119 Fixes #1376 Fixes #1654
Relevant for #278
> Isolate edge key generation in multigraphs

- networkx/generators/classic.py
- networkx/generators/tests/test_classic.py
Adding a generator for the Turan Graph to generators/classic.py
https://en.wikipedia.org/wiki/Tur%C3%A1n_graph
> Turan graph

- doc/source/reference/algorithms.flow.rst
- networkx/algorithms/connectivity/connectivity.py
- networkx/algorithms/connectivity/tests/test_connectivity.py
- networkx/algorithms/connectivity/tests/test_cuts.py
- networkx/algorithms/connectivity/tests/test_kcutsets.py
- networkx/algorithms/flow/__init__.py
- networkx/algorithms/flow/boykovkolmogorov.py
- networkx/algorithms/flow/maxflow.py
- networkx/algorithms/flow/tests/test_maxflow.py
- networkx/algorithms/flow/tests/test_maxflow_large_graph.py
This algorithm has worse case complexity `O(n^2m|C|)` where |C| is the
cost of the minimum cut [1], but it is faster than other algorithms with
theoretically better worse case complexities for some problems, such as
vision and image processing, and maybe others.
For the case of connectivity problems in networks with higly skewed
degree distributions (eg social networks) this algorithm doesn't run
faster than Edmonds-Karp but after reading about it I thought that it
was really cool and decided to implement it.
This is still WIP as the marking heuristic described in [2] is
not yet implemented. According to the authors it speeds up the running
time considerably.
[1] Boykov, Y., & Kolmogorov, V. (2004). An experimental comparison of
min-cut/max-flow algorithms for energy minimization in …
> Add Boykov Kolmogorov algorithm for maximum flow problems.

- doc/source/reference/algorithms.bipartite.rst
- doc/source/reference/algorithms.covering.rst
- doc/source/reference/algorithms.rst
- networkx/algorithms/__init__.py
- networkx/algorithms/bipartite/__init__.py
- networkx/algorithms/bipartite/covering.py
- networkx/algorithms/bipartite/tests/test_covering.py
- networkx/algorithms/covering.py
- networkx/algorithms/tests/test_covering.py
> Added Minimum Edge Cover Functionality

- networkx/utils/tests/test_decorators.py
This PR also simplifies the `try`/`finally` and `if` logic in these tests, using the `with` statement.
> Remove temporary files after tests are run.

- networkx/convert_matrix.py
- networkx/linalg/tests/test_graphmatrix.py
> Add support for subgraphs with no edges in convert_matrix.to_scipy_sparse_matrix.

- networkx/readwrite/pajek.py
- networkx/readwrite/tests/test_pajek.py
> Add support for reading adjacency matrix in readwrite.pajek.parse_pajek.

- networkx/algorithms/centrality/subgraph_alg.py
- networkx/algorithms/centrality/tests/test_subgraph.py
- networkx/algorithms/communicability_alg.py
- networkx/convert_matrix.py
> Use arrays instead of matrices in scipy.linalg.expm()

- networkx/classes/digraph.py
- networkx/classes/multidigraph.py
- networkx/classes/tests/test_digraph.py
- networkx/classes/tests/test_multidigraph.py
> Making in_edges equivalent to out_edges

- networkx/algorithms/tests/test_boundary.py
- networkx/algorithms/tests/test_core.py
- networkx/algorithms/tests/test_minors.py
- networkx/algorithms/tests/test_simple_paths.py
- networkx/classes/tests/test_digraph_historical.py
- networkx/classes/tests/test_function.py
- networkx/classes/tests/test_graph.py
- networkx/classes/tests/test_multigraph.py
- networkx/generators/tests/test_classic.py
- networkx/generators/tests/test_ego.py
- networkx/generators/tests/test_line.py
- networkx/readwrite/tests/test_graph6.py
- networkx/readwrite/tests/test_graphml.py
- networkx/readwrite/tests/test_leda.py
- networkx/utils/misc.py
https://github.com/networkx/networkx/issues/2203#issuecomment-236373973
> Fix tests failing because of ordering issues.

- networkx/algorithms/isomorphism/isomorphvf2.py
I closed the PR that was not on the master branch.
> Correct typo

- networkx/algorithms/dag.py
- networkx/algorithms/tests/test_dag.py
> have dag_longest_path_length return path length, not edge count

- networkx/algorithms/community/asyn_lpa.py
- networkx/algorithms/community/tests/test_asyn_lpa.py
https://github.com/networkx/networkx/issues/2219
> fix LPA bug, see issues/2219

- doc/source/reference/algorithms.clustering.rst
- networkx/algorithms/cluster.py
- networkx/algorithms/tests/test_cluster.py
Added the functionality to compute the [generalized degree](https://arxiv.org/abs/1101.2435) which returns the number of edges a node has that participate in a given number of triangles.
P.S. Is there a way to test the documentation generated from docstrings before merging to see if the maths markdown has rendered correctly?
> Generalized degree

- networkx/classes/tests/test_digraph.py
- networkx/classes/tests/test_function.py
- networkx/classes/tests/test_multidigraph.py
- networkx/generators/small.py
- networkx/generators/tests/test_atlas.py
- networkx/generators/tests/test_classic.py
- networkx/generators/tests/test_community.py
- networkx/generators/tests/test_line.py
- networkx/generators/tests/test_nonisomorphic_trees.py
- networkx/readwrite/edgelist.py
- networkx/readwrite/graph6.py
- networkx/readwrite/sparse6.py
- networkx/readwrite/tests/test_edgelist.py
- networkx/readwrite/tests/test_gexf.py
- networkx/readwrite/tests/test_gml.py
- networkx/readwrite/tests/test_p2g.py
- networkx/readwrite/tests/test_sparse6.py
- networkx/tests/test_convert.py
- networkx/tests/test_relabel.py
- networkx/utils/tests/test_rcm.py
> Test ordering

- networkx/algorithms/centrality/harmonic.py
as described in this comment: networkx#1360 (comment)
> added paramether nbunch

- networkx/generators/small.py
- networkx/generators/tests/test_small.py
The Hoffman-Singleton graph is one of the most famous graphs in graph theory.
https://en.wikipedia.org/wiki/Hoffman%E2%80%93Singleton_graph
> add the Hoffman-Singleton graph

- networkx/generators/geometric.py
> Corrects navigable small world graph param docs

- networkx/algorithms/cycles.py
- networkx/algorithms/tests/test_cycles.py
Fixes https://github.com/networkx/networkx/issues/2323
> Fix bug in find_cycle.

- networkx/algorithms/shortest_paths/weighted.py
Are the source and target flipped in this error message?
> flip source target

- examples/advanced/iterated_dynamical_systems.py
Test the function with the attached code.
[test_digitsrep.txt](https://github.com/networkx/networkx/files/646152/test_digitsrep.txt)
> Simpler version of digitsrep(..) function

- networkx/algorithms/components/biconnected.py
- networkx/algorithms/components/tests/test_biconnected.py
> change articulation_points so that it only returns every vertex once

- networkx/algorithms/link_analysis/pagerank_alg.py
- networkx/algorithms/link_analysis/tests/test_pagerank.py
Would close #2327 
Happy to process any feedback, if there is any.
> Allowing incomplete personalization

- networkx/algorithms/isomorphism/isomorphvf2.py
> Documents orderable node requirement for isom.

- networkx/generators/degree_seq.py
- networkx/generators/tests/test_degree_seq.py
There are two major changes in this commit. One is refactoring the
common code from the undirected and directed versions of the
configuration model graph generator. The other removes a few unnecessary
data structures from the `expected_degree_graph` function.
This also updates test code, adds missing tests, and makes some PEP8 changes in the module.
> Simplifies degree sequence graph generators.

- networkx/classes/graph.py
- networkx/classes/multigraph.py
Updates documentation to avoid the confusion reported in issue #2356.
> Corrects number_of_edges docs for directed graphs

- networkx/classes/digraph.py
- networkx/classes/tests/test_digraph.py
> Update predecessors/successors in edge subgraph

- networkx/linalg/graphmatrix.py
Fixes https://github.com/networkx/networkx/issues/2394.
> Fix typos in generating NXError in networkx.linalg.graphmatrix.incidence_matrix

- networkx/drawing/nx_pylab.py
Fixes https://github.com/networkx/networkx/issues/2392
> Fix broken links

- networkx/readwrite/gexf.py
fixes https://github.com/networkx/networkx/issues/2336
> correct logic in GEXFWriter

- README.rst
- setup.py
https://github.com/networkx/networkx/issues/2147
> list optional dependencies in setup.py

- networkx/readwrite/json_graph/__init__.py
- networkx/readwrite/json_graph/cytoscape.py
- networkx/readwrite/json_graph/tests/test_cytoscape.py
Adds functions allowing manipulation of Cytoscape JSON format (.cyjs).
> Added cytoscape JSON handling

- networkx/readwrite/json_graph/node_link.py
- networkx/readwrite/json_graph/tests/test_node_link.py
also set and dict creation changed.
tests added
> Fixed bug on custom attrs usage: unavailable iteritems method for dict.

- networkx/algorithms/distance_measures.py
- networkx/algorithms/tests/test_distance_measures.py
Applied patch sent to networkx-discuss and added tests and style changes
> Implement bounds method for distance_measure by Frank Takes

- networkx/algorithms/traversal/breadth_first_search.py
- networkx/algorithms/traversal/depth_first_search.py
> Update docs in traversal. Add see also, change produce to iterate over

- doc/source/reference/release_2.0.rst
- networkx/algorithms/approximation/kcomponents.py
- networkx/algorithms/distance_regular.py
- networkx/algorithms/euler.py
- networkx/algorithms/traversal/edgedfs.py
- networkx/classes/__init__.py
- networkx/classes/digraph.py
- networkx/classes/function.py
- networkx/classes/graph.py
- networkx/classes/multidigraph.py
- networkx/classes/multigraph.py
- networkx/classes/tests/test_digraph.py
- networkx/classes/tests/test_graph.py
- networkx/classes/tests/test_multigraph.py
- networkx/classes/tests/test_timing.py
- networkx/classes/tests/test_views.py
- networkx/classes/tests/timingclasses.py
- networkx/classes/views.py
- networkx/convert.py
- networkx/drawing/layout.py
- networkx/tests/test_convert.py
- networkx/tests/test_convert_numpy.py
This is just a clean up before implementing views.
> Add graph view classes for nodes/edge/degrees

- networkx/algorithms/bipartite/projection.py
> Fix docs for bipartite projection and pep8, decorators etc

- .travis.yml
Another attempt at upgrading PyPy. Same as #2334 but with 5.7.1 as well.
> Added more modern PyPy versions to the build matrix

- doc/source/developer/gitwash/following_latest.rst
- doc/source/reference/algorithms.dispersion.rst
- doc/source/reference/algorithms.tree.rst
- doc/source/reference/classes.digraph.rst
- doc/source/reference/classes.graph.rst
- doc/source/reference/classes.multidigraph.rst
- doc/source/reference/classes.multigraph.rst
- networkx/algorithms/shortest_paths/weighted.py
- networkx/generators/atlas.py
Fixes #2223 as well as some errors that showed up in sphinx processing.
> Fix sphinx errors and class outlines

- doc/source/reference/release_2.0.rst
- networkx/algorithms/community/__init__.py
- networkx/algorithms/community/asyn_fluidc.py
- networkx/algorithms/community/tests/test_asyn_fluidc.py
Hello there,
We are interested in adding the fluid communities algorithm [1] to networkx. It's a community detection algorithm competitive both in performance (close to multilevel) and in scalability (close to LPA).
So far we have a tested version of the code based on the LPA code originally found in  "networkx/networkx/algorithms/community/asyn_lpa.py".
Best regards,
[1] https://arxiv.org/pdf/1703.09307.pdf
> Fluid communities algorithm implementation

- doc/source/tutorial/tutorial.rst
Let me know if you want me to change anything, but I suspect this should be completely non-controversial.
> Remove confusing sentence from tutorial

- networkx/algorithms/boundary.py
This commit was extracted from pull request #2213.
> Allow either orientation of edges in edge boundary

- doc/source/reference/algorithms.community.rst
- networkx/algorithms/__init__.py
- networkx/algorithms/community/__init__.py
- networkx/algorithms/community/community_generators.py
- networkx/algorithms/community/kclique.py
- networkx/algorithms/community/kernighan_lin.py
- networkx/algorithms/community/quality.py
- networkx/algorithms/community/tests/test_asyn_lpa.py
- networkx/algorithms/community/tests/test_centrality.py
- networkx/algorithms/community/tests/test_generators.py
- networkx/algorithms/community/tests/test_kclique.py
- networkx/algorithms/community/tests/test_kernighan_lin.py
- networkx/algorithms/community/tests/test_quality.py
- networkx/algorithms/community/tests/test_utils.py
fixes #1932  merge conflicts.  (I couldn't push to the original branch -- though I notice that is now the default for PRs -- at least for me) so maybe in the future it will be more commonly accessible.
This is almost all written by @jfinkels....  Thanks!
> Rebase of Moves is_partition to community.utils

- networkx/algorithms/dag.py
Fixes #2240 
@dschult This is ready to merge.
> Note the precondition that graphs are directed and acyclic

- CONTRIBUTE.rst
- INSTALL.txt
- doc/source/developer/contribute.rst
- doc/source/developer/index.rst
> Add CONTRIBUTE file

- doc/source/reference/generators.rst
- networkx/generators/community.py
- networkx/generators/tests/test_community.py
Take care, sir," cried Sancho. "Those over there are not giants but windmills. Those things that seem to be their arms are sails which, when they are whirled around by the wind, turn the millstone."
> Adding support for windmill graphs to the community generators

- networkx/algorithms/traversal/depth_first_search.py
- networkx/algorithms/traversal/tests/test_dfs.py
rebase of #2258 and thus also #1928 to implement depth limited search using keyword ```depth_limit```
Fixes #2258 
Fixes #1928
> Depth limited search

- networkx/readwrite/gml.py
- networkx/readwrite/tests/test_gml.py
> Add GML handling for bool and tuple types

- networkx/algorithms/bridges.py
- networkx/algorithms/tests/test_bridges.py
Resolves #2273
Includes ideas about local_bridges from #2273 and adds tests.
Bridges were also discussed in #903
@erotemic Perhaps parts of bridges.py could be used in (or improved by) #2459
> Add local_bridges to bridges.py

- .travis.yml
- networkx/readwrite/graphml.py
- networkx/readwrite/tests/test_graphml.py
- requirements.txt
> Update graphml to care for a number of issues.

- networkx/algorithms/mis.py
- networkx/algorithms/tests/test_mis.py
> Add exception for DiGraph to max indep set

- networkx/algorithms/minors.py
- networkx/algorithms/tests/test_minors.py
in docstring and tests
Fixes #1540
> Add multigraph example of contracted_nodes

- networkx/drawing/layout.py
- networkx/drawing/tests/test_layout.py
rescale_layout didn't work well for negative values.
Fixes #2537
> Fix rescale_layout, add tests and tweaks docs

- .travis.yml
> Use precise until we sort out pypy on trusty 

- doc/reference/algorithms/minors.rst
- doc/reference/utils.rst
- examples/algorithms/plot_blockmodel.py
- examples/graph/plot_degree_sequence.py
- networkx/algorithms/connectivity/tests/test_kcomponents.py
- networkx/algorithms/connectivity/tests/test_kcutsets.py
- networkx/algorithms/graphical.py
- networkx/algorithms/minors.py
- networkx/algorithms/shortest_paths/weighted.py
- networkx/algorithms/tests/test_graphical.py
- networkx/algorithms/tests/test_minors.py
- networkx/drawing/nx_pydot.py
- networkx/generators/degree_seq.py
- networkx/utils/random_sequence.py
- networkx/utils/tests/test_misc.py
- networkx/utils/tests/test_random_sequence.py
This removes deprecated code marked for removal in 2.0 or code that was deprecated more than 4 years ago.  I also marked 2.1 as the removal release for ``bellman_ford``.
I still need to add a note to ``doc/release/release_2.0.rst`` and to ``doc/news.rst``.
> Remove deprecated code

- networkx/algorithms/tree/mst.py
The default argument could apply to either weight or data
so its confusing when there are two references. Looked at
two new default arguments and decided it wasn't an improvement.
I did include changes suggested in the comment referred to in #2068 
Resolves #2068
> Update mst docs and decide not to add default argument.

- networkx/algorithms/tree/mst.py
- networkx/algorithms/tree/tests/test_mst.py
> Filter nan edges in minimum_spanning_

- doc/conf.py
- doc/requirements.txt
Use explicit order sortkey to specify the subsection's order within a
gallery.
> Update sphinx-gallery to v0.1.12

- doc/release/migration_guide_from_1.x_to_2.0.rst
This is ready to merge.
Incorporates text from Mridul Seth and closes #2540.
> Update migration guide

- networkx/algorithms/minors.py
> Fix contracted_nodes with self_loops=True.

- doc/reference/algorithms/community.rst
Solving Issue [#2590](https://github.com/networkx/networkx/issues/2590).
> Reference documentation of fluid communities added

- networkx/testing/tests/test_utils.py
- networkx/testing/utils.py
> Add tests for assert_edges_equal and fix

- examples/algorithms/plot_blockmodel.py
- examples/javascript/force.py
> Fix examples

- networkx/classes/digraph.py
- networkx/classes/function.py
- networkx/classes/graph.py
- networkx/classes/multidigraph.py
- networkx/classes/multigraph.py
> Update docs of base class and function modules.

- networkx/classes/coreviews.py
- networkx/classes/reportviews.py
- networkx/classes/tests/test_coreviews.py
- networkx/classes/tests/test_reportviews.py
I think this is sufficient for #2611 
I haven't added tests to verify, but those tests won't be very interesting.  
What do you think?
> Make a nice printout with __str__ for Views

- doc/release/release_dev.rst
- networkx/drawing/nx_pylab.py
Deprecated in e222c41b on Dec 29, 2005.
> WIP: Removed draw_nx

- doc/release/release_dev.rst
- doc/release/release_template.rst
- networkx/generators/atlas.py
Last PR before beta release later today.
> Prep beta release

- networkx/algorithms/structuralholes.py
> Make parameter nodes effective in effective_size()

- networkx/classes/graph.py
- networkx/classes/tests/test_graph.py
> Deprecate node

- networkx/algorithms/connectivity/edge_kcomponents.py
- networkx/algorithms/operators/binary.py
- networkx/algorithms/operators/unary.py
- networkx/algorithms/tree/branchings.py
- networkx/algorithms/tree/mst.py
- networkx/classes/digraph.py
- networkx/classes/function.py
- networkx/classes/graph.py
- networkx/classes/multidigraph.py
- networkx/classes/multigraph.py
- networkx/classes/ordered.py
- networkx/classes/tests/test_graphviews.py
- networkx/drawing/tests/test_pydot.py
- networkx/generators/line.py
- networkx/relabel.py
> Replace __class__ with fresh_copy in G.reverse and elsewhere

- networkx/algorithms/operators/all.py
- networkx/drawing/nx_pylab.py
- networkx/readwrite/leda.py
- networkx/readwrite/p2g.py
- networkx/readwrite/pajek.py
- networkx/utils/misc.py
See https://github.com/matplotlib/matplotlib/pull/8011
> Use isinstance in is_string_like

- networkx/readwrite/gexf.py
> Correct order of edge key and data in GEXFwriter.add_edges

- networkx/algorithms/tree/mst.py
isolated nodes with self-loops included in tree as isolated nodes.
Fixes #2667
> MST doc note: isolated nodes with self-loops case

- doc/reference/drawing.rst
Added references to new Kamada-Kawai layout functions in Sphinx documentation.
> Added Kamada-Kawai functions to Sphinx documentation

- networkx/convert_matrix.py
> Fix create_using of nx.from_pandas_adjacency()

- networkx/drawing/nx_pylab.py
Tested it in my virtual environment. 
Fixes bug #2503 .
> Fixes bug #2503 by removing arrow labels

- networkx/algorithms/simple_paths.py
- networkx/algorithms/tests/test_simple_paths.py
Bug was in deviation finding part of algorithm.  Instead of ignoring first (i - 1) vertices in path, algorithm ignored i-th vertex in path.
> Fix for issue #2427

- CONTRIBUTORS.rst
- networkx/algorithms/dag.py
- networkx/algorithms/tests/test_dag.py
Hi,
I implemented a small patch to fix issue #2578. I used the solution propsed there and added appropriate tests.
Andre
> Copy graph in transitive closure algorithm.

- doc/tutorial.rst
> fix typo in tutorial

- networkx/classes/coreviews.py
- networkx/classes/digraph.py
- networkx/classes/graph.py
- networkx/classes/multidigraph.py
- networkx/classes/multigraph.py
Fixes #2743
Addresses #2716
Relates to #2687
> Speedups for subgraph and copy methods

- networkx/algorithms/assortativity/neighbor_degree.py
> a minor correction in docs

- networkx/algorithms/approximation/kcomponents.py
- networkx/algorithms/approximation/tests/test_kcomponents.py
- networkx/algorithms/assortativity/mixing.py
- networkx/algorithms/connectivity/tests/test_kcutsets.py
- networkx/algorithms/flow/tests/test_maxflow.py
- networkx/algorithms/flow/tests/test_maxflow_large_graph.py
- networkx/algorithms/flow/utils.py
- networkx/algorithms/shortest_paths/weighted.py
- networkx/drawing/nx_pylab.py
- networkx/readwrite/graphml.py
- networkx/relabel.py
This PR is #1700 with conflicts resolved.
> Dictionary comprehensions from #1700 merged conflicts

- networkx/readwrite/gml.py
- networkx/readwrite/tests/test_gml.py
> Fix typo in write_gml and add test

- networkx/algorithms/simple_paths.py
- networkx/algorithms/tests/test_simple_paths.py
Following instruction on fix for issue #2762
> all_simple_paths should not return cycles. Fix issue #2762

- networkx/algorithms/minors.py
- networkx/algorithms/tests/test_minors.py
Hi, this PR adds support for incomplete partitions as discussed in #2529 .
> Add support for incomplete partitions in quotient_graph.

- networkx/generators/degree_seq.py
- networkx/generators/tests/test_degree_seq.py
Fixes #2767
Also adds some tests that the nuber of nodes is correct
(which would have flagged the bug) Not sure how to do
a better set of tests for the edges given the randomness.
> Fix bug in expected_degree_graph generator

- networkx/drawing/layout.py
> Add threshold option to spring layout

- networkx/algorithms/approximation/vertex_cover.py
Change weight to refer to nodes (instead of edges)
> Correct docstring for weight parameter

- doc/reference/algorithms/approximation.rst
- networkx/algorithms/approximation/__init__.py
- networkx/algorithms/approximation/steinertree.py
> Add docs for steiner_tree and metric_closure

- doc/reference/generators.rst
- networkx/generators/__init__.py
- networkx/generators/inverse_line.py
- networkx/generators/tests/test_inverse_line.py
> Add inverse_line_graph generator from #2241

- networkx/drawing/nx_pylab.py
> Control node-border color in draw_networkx_nodes

- doc/release/release_dev.rst
- networkx/algorithms/shortest_paths/weighted.py
> MRG: Remove ``bellman_ford``

- doc/release/release_dev.rst
- networkx/convert_matrix.py
- networkx/tests/test_convert_pandas.py
> MRG: Remove ``to_pandas_dataframe`` and ``from_pandas_dataframe``

- networkx/classes/reportviews.py
- networkx/classes/tests/test_reportviews.py
> Fix bug in len(edges) for self-loops

- networkx/readwrite/json_graph/jit.py
- networkx/readwrite/json_graph/tests/test_jit.py
Just added the support for getting directed graphs from a previously generated JIT file.
> Add directed graphs support for jit_graph reading

- networkx/classes/digraph.py
- networkx/classes/graph.py
- networkx/classes/multidigraph.py
- networkx/classes/multigraph.py
As suggested by @mddddd in #2728
> Adjust docs for graph class edge attrib assignment

- doc/reference/algorithms/cycles.rst
- networkx/algorithms/cycles.py
- networkx/algorithms/tests/test_cycles.py
This was originally #1649  by @debsankha
Resolved conflicts to allow merge
> Minimum cycle basis

- networkx/algorithms/flow/maxflow.py
- networkx/algorithms/traversal/edgedfs.py
- networkx/algorithms/tree/branchings.py
- networkx/classes/digraph.py
- networkx/classes/function.py
- networkx/classes/graph.py
- networkx/classes/multidigraph.py
- networkx/classes/multigraph.py
- networkx/classes/tests/test_digraph.py
- networkx/classes/tests/test_graph.py
- networkx/classes/tests/test_multigraph.py
- networkx/exception.py
- networkx/readwrite/nx_yaml.py
- networkx/utils/decorators.py
I didn't change functions defined in tests.
I also left drawing routines as is at least for now.
Addresses #1582
Fixes #1583
> change variable names to avoid kwargs clobber

- CONTRIBUTORS.rst
- doc/reference/algorithms/community.rst
- networkx/algorithms/community/__init__.py
- networkx/algorithms/community/modularity_max.py
- networkx/algorithms/community/tests/test_modularity_max.py
- networkx/utils/mapped_queue.py
- networkx/utils/tests/test_mapped_queue.py
* Adds modularity_max module to networkx.algorithms.community package
* Adds greedy_modularity_communities() function with CNM implementation
* Adds test using Zachary karate club network
* Add networkx.utils.mapped_queue used by the above implementation
* Add tests for networkx.utils.mapped_queue
> Add Clauset-Newman-Moore modularity-max community detection

- doc/release/migration_guide_from_1.x_to_2.0.rst
- doc/release/release_2.0.rst
Updated migration guide and release notes for topological sort changes.
> Updated migration guide and release notes.

- networkx/algorithms/bridges.py
> Fixing typo in bridges module

- networkx/classes/function.py
> Update docs for set_node-edge_attributes

- networkx/algorithms/bipartite/tests/test_generators.py
Add test to cover not complete random bipartite graph.
> Add test case for not complete random bipartite graph.

- networkx/algorithms/bipartite/generators.py
- networkx/algorithms/bipartite/tests/test_generators.py
Sorry I just realized a few other models have the same bug.
> Fix a few bugs to allow bipartite generators accept empty lists.

- networkx/convert_matrix.py
> Order the output of columns in doctests for pandas

- networkx/readwrite/pajek.py
- networkx/readwrite/tests/test_pajek.py
> Check if attribute is str like in writing to Pajek Fixes #2933

- doc/reference/algorithms/matching.rst
- networkx/algorithms/matching.py
- networkx/algorithms/tests/test_matching.py
Add a method to check whether a maximum matching is perfect.
> Add is_perfect_matching function

- networkx/drawing/nx_pylab.py
> Update docs for draw_networkx_labels

- networkx/algorithms/shortest_paths/generic.py
Clarify error message raised in all_shortest_paths() to user.
> Clarify NetworkXNoPath exception in all_shortest_paths()

- networkx/algorithms/components/strongly_connected.py
- networkx/algorithms/components/tests/test_strongly_connected.py
Fixes #2831 with good help from @ghost for profiling and
good help from @ArseniyAntonov and PR #2841
Here we also avoid mutating the graph so no copy needed.
> Make strongly_connected_components linear time O(m+n)

- examples/drawing/plot_directed.py
> Add colorbar example for DiGraph edge colors

- networkx/algorithms/approximation/steinertree.py
- networkx/algorithms/approximation/tests/test_steinertree.py
> Add check to metric_closure for is_connected

- doc/release/release_dev.rst
- networkx/classes/digraph.py
- networkx/classes/function.py
- networkx/classes/graph.py
- networkx/classes/graphviews.py
- networkx/classes/multigraph.py
- networkx/classes/reportviews.py
- networkx/classes/tests/test_graph.py
- networkx/classes/tests/test_graphviews.py
Related to #3011 and #2885 and maybe #2793
> Remove cyclic reference in G.root_graph

- networkx/classes/ordered.py
also add words to make more clear the expectations for these graph classes.
Fixes #2911
> Add docs to orderedgraph module about subgraph

- networkx/drawing/nx_agraph.py
- networkx/drawing/nx_pydot.py
Show how to convert to integers, use GraphViz to get the layout
and then translate back to pos dict with original nodes.
Fixes #1568
> Add docs for graphviz_layout for complex nodes

- networkx/algorithms/bipartite/projection.py
add the explanation of how to calculate the weight in projection.
> explanation of weight in projection

- networkx/algorithms/approximation/dominating_set.py
- networkx/generators/degree_seq.py
> Correct documentation wording for min_weighted_dominating_set

- networkx/algorithms/flow/networksimplex.py
- networkx/algorithms/flow/tests/test_mincost.py
> stop infinite loop in min_cost_flow

- networkx/algorithms/cycles.py
- networkx/algorithms/tests/test_cycles.py
- networkx/algorithms/traversal/__init__.py
- networkx/algorithms/traversal/depth_first_search.py
- networkx/algorithms/traversal/edgebfs.py
- networkx/algorithms/traversal/edgedfs.py
- networkx/algorithms/traversal/tests/test_edgebfs.py
- networkx/algorithms/traversal/tests/test_edgedfs.py
- add docs to explain that dfs_edges is not edge_dfs
Fixes #2840 
- clean up edge_dfs return values to unify length of yielded tuple
Fixes #3037  
- add edge_bfs to match edge_dfs
Fixes #2792
>  Fix up edge_dfs and add edge_bfs

- .travis.yml
- networkx/algorithms/connectivity/edge_augmentation.py
- networkx/algorithms/connectivity/edge_kcomponents.py
- networkx/algorithms/traversal/edgebfs.py
- networkx/algorithms/traversal/edgedfs.py
- networkx/generators/classic.py
- networkx/readwrite/sparse6.py
Set up travis to run python3.7-dev but allow failures on travis.
Also applied the patch from #3046 to avoid StopIteration error.
@jarrodmillman can you see if this will be useful for getting 3.7 going?
Merge if you think its helpful.
> Pull request to set up python3.7 testing on travis

- requirements/extras.txt
This is on hold pending the 4.2 release:
https://github.com/yaml/pyyaml/issues/193
They removed 4.1 and released 3.13.  The next release will be 4.2, I believe.
> Use pyyaml updates

- networkx/algorithms/dag.py
relates to discussion in #3043
> update docs for transitive_reduction to show example using line_graph

- networkx/algorithms/dag.py
- networkx/algorithms/tests/test_dag.py
Issue #2720 
Implementation of an enumeration algorithm for topological sorts. Based on https://doi.org/10.1016/0020-0190(74)90001-5
> Enumerate all topological sorts of a digraph

- networkx/convert_matrix.py
- networkx/tests/test_convert_pandas.py
> faster, type-preserving from_pandas_edgelist

- networkx/utils/decorators.py
- networkx/utils/tests/test_decorators.py
> allow open_file to handle pathlib objects

- networkx/algorithms/simple_paths.py
- networkx/algorithms/tests/test_simple_paths.py
See discussion of this at https://github.com/networkx/networkx/issues/2975#issuecomment-406354042
> In all_simple_paths(). Replace list with OrderedDict for speedup

- CONTRIBUTORS.rst
- networkx/algorithms/euler.py
- networkx/algorithms/tests/test_euler.py
As discussed in [issue 2869](https://github.com/networkx/networkx/issues/2869), I have implemented a function to transform a graph into an Eulerian graph along the lines mentioned in [these lecture notes](http://www.math.unl.edu/%7Ebharbourne1/M203Spr07/EulerizationHandout.pdf) and using the method described [here](https://cs.stackexchange.com/questions/9126/is-there-a-non-brute-force-algorithm-for-eulerization-of-graphs) to find an efficient set of paths.
I have also written test cases for Eulerization of Erdos-Renyi graphs and some complete graphs.
I am labeling this as a WIP because this would be my first commit to NetworkX and expect that there may be things I haven't thought of or things I have done wrong.  I have also not implemented this for directed graphs.  This is because I use …
> [WIP] Added function to eulerize simple graphs to algorithms.euler

- networkx/algorithms/traversal/breadth_first_search.py
- networkx/algorithms/traversal/tests/test_bfs.py
Addresses [#2352](https://github.com/networkx/networkx/issues/2352). Added code for depth_limit for BFS along with the tests, references, and examples.
> Depth-limited Breadth First Search

- doc/README.md
Added space for the sake of proper styling and understanding
> Minor fix on paragraph #18 (proposal)

- networkx/algorithms/similarity.py
> Add docstring to module for similarity

- networkx/classes/digraph.py
- networkx/classes/tests/test_special.py
> Fix adjlist factory bug in DiGraph

- networkx/readwrite/gml.py
> Update docstrings in gml to warn about underscores.

- networkx/classes/digraph.py
> Clarify documentation for predecessors() and successors(). Fixes #3113.

- networkx/algorithms/isomorphism/isomorphvf2.py
- networkx/algorithms/isomorphism/tests/test_isomorphvf2.py
See description of issue in #3134.
> Handle noncomparable nodes in isomorphism matcher

- networkx/convert_matrix.py
> Fix tiny typo in the document about from/to_pandas_edgelist.

- .appveyor.yml
- .travis.yml
- INSTALL.rst
- doc/reference/introduction.rst
- doc/release/api_1.0.rst
- doc/release/migration_guide_from_1.x_to_2.0.rst
- doc/release/release_2.0.rst
- doc/tutorial.rst
- examples/basic/plot_read_write.py
- examples/drawing/plot_unix_email.py
- examples/graph/plot_erdos_renyi.py
- networkx/__init__.py
- networkx/drawing/nx_pylab.py
- networkx/release.py
- requirements/doc.txt
- requirements/extras.txt
- requirements/test.txt
- setup.py
> 3.7 default and drop 2.7 for CI

- networkx/classes/digraph.py
> Replaced deprecated usage of ReverseView with reverse_view, fixes #3252

- networkx/generators/directed.py
> Fix typo in docstring

- networkx/drawing/nx_pydot.py
Update the broken link to the Graphviz package
> Fix docstring broken link to Graphviz

- networkx/classes/function.py
frozen should have kwargs otherwise when calling a frozen graph method with a keyword you get
a TypeError : frozen() got an unexpected keyword argument ..
> fix frozen function

- CONTRIBUTORS.rst
I noticed that there is an opt-in contributors file, and I'd like to add my name for my merged PRs: #2572,  #2571, #2568, and #2554.
> Add Jon Crall to contributors

- networkx/classes/function.py
- networkx/classes/tests/test_function.py
WIP- I have added the support for adding an iterator with a single element(Singleton). I will add the test cases as well.
> adding support for singleton in add_path and add_star

- networkx/algorithms/lowest_common_ancestors.py
> Update page reference

- networkx/drawing/layout.py
- networkx/drawing/nx_pylab.py
Added documentation as proposed in #2971
> Added documentation for spectral layout (#2971)

- README.rst
.. in README/Github front page
> Python syntax highlighting

- networkx/linalg/spectrum.py
- networkx/linalg/tests/test_spectrum.py
Add the normalized_laplacian_spectrum and its test functions. 
Resolves https://github.com/networkx/networkx/issues/3315#issue-407978202, which is created by me.
> Issue-3315: add normalized_laplacian_spectrum

- networkx/linalg/laplacianmatrix.py
- networkx/linalg/tests/test_laplacian.py
Hi,
I gave the integration of the directed combinatorial laplacian a try as suggested in #2404 . This includes some tests. As the calculation oft the transition probability matrix is the same as in the normalized directed laplacian, I refactored it into a separate function. Open to any feedback!
> Directed combinatorial laplacian as in #2404

- CONTRIBUTORS.rst
Adding myself as a new contributor to the list :)
> Adding myself as a new contributor

- examples/javascript/force.py
- examples/javascript/force/force.css
- examples/javascript/force/force.html
- examples/javascript/force/force.js
Update D3 version and fix file access.
> Javascript exemple update

- networkx/readwrite/nx_yaml.py
- requirements/extras.txt
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
> Update pyyaml and fix yaml.load(input) deprecation warning

- doc/reference/algorithms/centrality.rst
- networkx/algorithms/centrality/__init__.py
- networkx/algorithms/centrality/tests/test_voterank.py
- networkx/algorithms/centrality/voterank_alg.py
VoteRank computes a ranking of the nodes in the graph G based on a voting
scheme. With VoteRank, all nodes vote for each neighbours and the node with
the highest score is elected iteratively. The voting ability of neighbors of
elected nodes will be decreased in subsequent turnself.
> added implementation of VoteRank

- networkx/generators/directed.py
> Fix error message

- networkx/algorithms/shortest_paths/unweighted.py
> Fix error message for single_target_shortest_path

- networkx/drawing/nx_agraph.py
- networkx/drawing/nx_pydot.py
> Update docs for pydot_layout and pygraphviz_layout

- networkx/algorithms/centrality/closeness.py
- networkx/algorithms/centrality/tests/test_closeness_centrality.py
> Correct closeness_centrality for weighted directed G

- networkx/readwrite/gexf.py
- networkx/readwrite/tests/test_gexf.py
Allow write numpy type attribute values in gexf
Fixes #2204
Fixes #2969
Make sure edge_ids are unique
Fixes #1296
> Fix GEXF edge_ids and numpy types

- networkx/algorithms/bipartite/generators.py
> Add reference for preferential_attachment_graph

- networkx/drawing/nx_pylab.py
- networkx/drawing/tests/test_pylab.py
> Allow multidigraph edgelist in draw_networkx

- doc/release/index.rst
- networkx/release.py
> Document version naming policy

- networkx/algorithms/shortest_paths/astar.py
- networkx/algorithms/shortest_paths/weighted.py
Match with below
https://github.com/networkx/networkx/blob/b74d4bcc5a14263d562c045e84c39f2ec02962ba/networkx/algorithms/shortest_paths/weighted.py#L237
> typo: swap source and target

- networkx/readwrite/edgelist.py
read_* should have more see also
> Improve edgelist See Also

- doc/reference/drawing.rst
add required argument to `write_graphml` example in the documentation
> Minor fix in documentation

- doc/reference/linalg.rst
Tiny doc PR as mentioned in PR #3401
> [Linealg] Reorder and complete doc

- doc/reference/algorithms/core.rst
- networkx/algorithms/core.py
- networkx/algorithms/tests/test_core.py
Added algorithm for calculating maximal k-truss to core.py. Added unit tests to test_core.py.
> Naive k-truss algorithm implementation.

- .gitignore
- CONTRIBUTORS.rst
- doc/reference/algorithms/distance_measures.rst
- networkx/algorithms/distance_measures.py
- networkx/algorithms/tests/test_distance_measures.py
Added memory efficient algorithm for calculating resistance distance on a undirected graph
> New Feature - Resistance Distance

- doc/reference/algorithms/centrality.rst
- networkx/algorithms/centrality/group.py
- networkx/algorithms/centrality/tests/test_group.py
- networkx/classes/graph.py
Closeness centrality measure implemented for groups. Improvement of module created in PR #3421.
References:
http://www.analytictech.com/borgatti/group_centrality.htm
http://wwwconference.org/proceedings/www2014/companion/p689.pdf
Please do tell me if there is anything I should correct.
> Added group closeness and group degree centralities

- networkx/algorithms/traversal/breadth_first_search.py
- networkx/algorithms/traversal/depth_first_search.py
See PR #3484 and issue #3483 
This PR fixes errors in docstrings for BFS and DFS.
> Correct docstring errors in traversal

- CONTRIBUTORS.rst
- doc/reference/algorithms/operators.rst
- doc/reference/generators.rst
- networkx/algorithms/operators/binary.py
- networkx/algorithms/operators/tests/test_binary.py
- networkx/generators/__init__.py
- networkx/generators/cographs.py
- networkx/generators/tests/test_cographs.py
A cograph is a graph containing no path on four vertices. Cographs or $P_4$-free graphs can be obtained from a single vertex by disjoint union and complementation operations.
The generator starts of from a single vertex and performes disjoint union and full join operations on itself at each iteration. The decision on which operation will take place is random.
Full join is the union of G and H in which all edges between G and H are added. The full join operation of two graphs G and H is the same as getting their complement, performing a disjoint union, and finally getting the complement of the resulting graph.
This PR adds the cograph generator and the full join operation.
Reference on cographs: https://www.sciencedirect.com/science/article/pii/0166218X81900135?via%3Dihub
> Full join operation and cograph generator

- networkx/algorithms/components/strongly_connected.py
Replaced the scc_found dictionary with a set since we don't use the value of the
dictionary.
Changed done's variable type to boolean so that PyPy's JIT would
recognize that there are only two possible states for the condition.
> Optimize the strongly connected components algorithm

- networkx/algorithms/components/strongly_connected.py
I removed the unnecessary usage of the nbrs dictionary.
This will reduce memory consumption, especially on large graphs.
> Optimize the strongly connected components algorithm - Take 2

- networkx/algorithms/similarity.py
This will solve the ZeroDivisionError as explain in Issue #3524
> Small fix for bug found @ issue #3524

- networkx/algorithms/tree/coding.py
resolves #3521.
I suggest these changes, as the already implemented paper's solution is fine and only a simple fix in networkx' current implementation is required. In contrast, #3523 implements another paper's solution.
> Linear prufer coding

- networkx/generators/line.py
- networkx/tests/test_line.py
> Fix inverse_line_graph.

- networkx/drawing/nx_pylab.py
Solve the error as https://github.com/networkx/networkx/issues/3552 , which allows us to use numpy ndarray.
Thank you for your time to check my work.
> Try to bug Fix #3552

- networkx/classes/graph.py
> Fix a typo in docstring for get_edge_data

- doc/reference/algorithms/smallworld.rst
Fixes the documentation's menu.
> Fix wrong title

- doc/reference/classes/index.rst
- Suggestion for beginners to make clear that multi(di-)graphs can also have loops.
- Used the word 'allowed' to suggest that the feature is optional.
> Improved graph class selection table

- networkx/algorithms/tree/mst.py
- networkx/algorithms/tree/tests/test_mst.py
Fixes issue #3502. 
Made the lists into sets. Prim and Kruskal implementations have now equivalent time execution.
> Prim from list to set

- networkx/readwrite/edgelist.py
- networkx/readwrite/tests/test_edgelist.py
Solves issue #3491 . Please find a sample execution before and after the changes
**Note** : The recommended solution in the thread (using *try-except* blocks) failed in **windows 10 1903, python 3.7.4** and it seems to be an issue with networkx itself as other `AttributeError` conditions are caught by python just fine. Hence, I went with the method of detecting versions, which solves it without any such problems. 😄 
Do let me know if this idea is intractable for some reason.
> Fix issue 3491

- networkx/convert_matrix.py
- networkx/drawing/nx_pydot.py
- networkx/drawing/tests/test_pydot.py
Fixes issue #3605 . 
Also made minor code changes (primarily, changing the lines
```python
except:
```
to
```python
except Exception as e:
```
and some length trimming to satisfy **pycodestyle**. As I understood from my previous PR, it's appreciated if **pycodestyle** cleanup is done.
Please have a look at it and let me know if it wasn't necessary to make it **pycodestyle** compliant, in which case I would gladly revert the changes 😄
> Replaced is with == and minor pycodestyle fixes

- doc/release/migration_guide_from_1.x_to_2.0.rst
- examples/drawing/plot_knuth_miles.py
- networkx/algorithms/centrality/closeness.py
- networkx/algorithms/traversal/breadth_first_search.py
- networkx/algorithms/traversal/depth_first_search.py
- networkx/algorithms/traversal/edgebfs.py
- networkx/drawing/layout.py
Fixes #3473 migration guide in_degree wording
Fixes #3463 add warning to closeness centrality about in_degree
Fixes #3498 cross document BSF functions 
Fixes #3469 link to miles datafile in example
Fixes #3489 allow scale=None in spring_layout
> Resolve many documentation issues

- doc/reference/algorithms/euler.rst
- doc/reference/algorithms/index.rst
- networkx/algorithms/euler.py
- networkx/algorithms/tests/test_euler.py
Added functions to check if a graph has an Euler Path, whether it is semi Eulerian, and to return an Euler Path if one exists.
Also adds initial test cases for new functions.
Supersedes previous similar (closed) pull requests #1878 and #1488. See comment [here](https://github.com/networkx/networkx/pull/1878#issuecomment-485263242).
To do: a function implementing the [BEST theorem](https://en.wikipedia.org/wiki/BEST_theorem) to return _all_ Euler Paths (for a directed graph).
> Implemented Euler Path functions

- networkx/algorithms/community/label_propagation.py
The nodes in the function of label_freq.update are opposite.
> Fix the direction of edges in label_propagation.py

- networkx/generators/duplication.py
> Fix operation order in partial_duplication_graph

- networkx/readwrite/json_graph/jit.py
- networkx/readwrite/json_graph/tests/test_jit.py
> Allow jit_graph to read json string or json object

- networkx/convert_matrix.py
- networkx/tests/test_convert_pandas.py
> Handle edgeattr in from_pandas_edgelist when no columns match request

- doc/release/contribs.py
- doc/release/release_2.4.rst
- doc/release/release_dev.rst
Also added printing commits to ```contribs.py```
> Make draft of release notes for v2.4

- networkx/readwrite/gexf.py
- networkx/readwrite/tests/test_gexf.py
> add check of attr type before converting inf/nan in GEXF

- .appveyor.yml
- tools/appveyor/install.ps1
> Test Python 3.8 with AppVeyor

- networkx/algorithms/clique.py
Removed example of worst case scenario for finding maximal cliques on a complete graph
> fix documentation notes (#3644)

- .pep8speaks.yml
- networkx/readwrite/gexf.py
- networkx/readwrite/tests/test_gexf.py
> Fixes issue 3610: Bug in version attribute of gexf.py

- networkx/algorithms/shortest_paths/unweighted.py
The helper function 
_networkx.algorithms.shortest_path.unweighted.**_single_shortest_path_length**_ 
can be optimized.
**Current implementation**: add neighbours of visited nodes to "nextlevel" set. Later, iterate through "nextlevel" set to expand their unseen neighbours. Iterate until "nextlevel" is empty.
**Suggested optimization 1**: keep track of nodes to be expanded in a queue (collections.deque) that remains sorted by distance from source node. Do not add already visited nodes to any set.
**Suggested optimization 2**: terminate immediately if all nodes have been visited. This saves a lot of work for dense, strongly connected graphs.
Investigation and analysis shows the effectiveness of the optimizations. Measured speedup is **at least a factor of 2**, for graphs where python …
> Optimize _single_shortest_path_length

- networkx/drawing/layout.py
Thanks for the great library! Here's a little typo fix.
> Fix typo: Laplacion -> Laplacian

- doc/reference/algorithms/community.rst
- networkx/algorithms/community/__init__.py
- networkx/algorithms/community/lukes.py
- networkx/algorithms/community/tests/test_lukes.py
Introduces the Lukes optimal tree partitioning algorithm in networkx.algorithms.community. This algorithm partitions a tree with float weighted edges and integer weighted nodes, in such a way that the total node weight of the block does not exceed a maximum size and the edge cuts are minimum. It is an exact algorithm and it runs in pseudo-polynomial time.
Reference: Lukes, J. A. (1974). Efficient Algorithm for the Partitioning of Trees. IBM Journal of Research and Development, 18(3), 217–224. https://doi.org/10.1147/rd.183.0217
> Lukes algorithm implementation

- networkx/classes/graph.py
> Update docs to be more accurate about speed of G.neighbors

- networkx/classes/graph.py
issue https://github.com/networkx/networkx/issues/3733
not sure which branch to merge to, please correct if wrong
> Sample code for subgraph copy: add parenthesis to is_multigraph

- doc/citing.rst
Fix for #3740. Thanks @MridulS for the pointer!
> fix citation links

- setup.py
fixes https://github.com/networkx/networkx/issues/3737
> remove f strings from setup.py for clear error message < py3.6

- examples/javascript/force.py
> Link to files needed for example

- networkx/generators/random_graphs.py
> fixed a typo

- networkx/drawing/layout.py
- networkx/drawing/tests/test_layout.py
Also add a feature: rotation of initial angle for each shell
controlled by new argument "rotate"
Add a test to check this fix
Update for PEP8
Fixes #3753
> Fix scaling of single node shells in shall_layout

- networkx/algorithms/connectivity/connectivity.py
- networkx/algorithms/connectivity/tests/test_connectivity.py
- networkx/algorithms/isomorphism/tests/test_isomorphism.py
- networkx/classes/tests/test_reportviews.py
> Improve test coverage

- networkx/algorithms/operators/binary.py
Adding some consistence as comments split by object type while code splits by graph.
> Minor comments issue

- networkx/algorithms/__init__.py
I made sure that the public function names don't conflict with others in the namespace.
There are interesting functions which are not exposed public interface by the __all__ attribute.
May be someone could figure out which one worth being made public.
> Adding moral and threshold packages to main namespace

- networkx/algorithms/shortest_paths/astar.py
- networkx/algorithms/shortest_paths/tests/test_astar.py
- networkx/algorithms/shortest_paths/tests/test_weighted.py
- networkx/algorithms/shortest_paths/weighted.py
See discussion in #3754 and #3774.
Knock-on benefits: 
1. Uncovered/fixed an inconsistency in Bellman-Ford (easy 1-line fix)
2. Added support for multigraphs in `astar`
> Add weight functions to bidirectional_dijkstra and astar

- networkx/generators/lattice.py
- networkx/generators/tests/test_lattice.py
I'm not super happy with how I wrote those docstrings; suggestions are welcome.
> option for partially-periodic lattices (networkx #3586)

- networkx/utils/tests/test_unionfind.py
- networkx/utils/union_find.py
> UnionFind's union doesn't accurately track set sizes

- networkx/algorithms/components/connected.py
- networkx/algorithms/components/tests/test_connected.py
> Make connected_components safe to component set mutation

- networkx/convert_matrix.py
My first, tiny contribution to networkx.
> Fixed nx.Digraph to nx.DiGraph - Issue #3867

- networkx/convert.py
> allow set of edge nodes

- doc/reference/generators.rst
Just merged paley graph (https://github.com/networkx/networkx/pull/3900) but forgot to add an entry in the doc, so here goes.
> add paley graph to doc

- networkx/algorithms/shortest_paths/astar.py
Correct the docstring of the function astar_path for the commit  #3799
> Update astar.py to fix docstring for the commit  #3799

- networkx/generators/community.py
> Use keywords for positional arguments

- networkx/algorithms/structuralholes.py
- networkx/linalg/graphmatrix.py
> fix documentation

- networkx/algorithms/structuralholes.py
> fix documentation 

- networkx/algorithms/shortest_paths/generic.py
- networkx/algorithms/shortest_paths/tests/test_generic.py
- networkx/algorithms/shortest_paths/tests/test_weighted.py
- networkx/algorithms/shortest_paths/weighted.py
> Correct handling of zero-weight edges in all_shortest_paths

- networkx/classes/graph.py
Please let me know if there's anything else that need to accompany this change!
> Fix Graph Documentation Typo

- networkx/algorithms/similarity.py
Fix the returns documentation of simrank_similarity_numpy
> Fix: documentation of simrank_similarity_numpy

- networkx/algorithms/simple_paths.py
- networkx/algorithms/tests/test_simple_paths.py
Add this function for aligning the weight function in shortest paths class.
> Add weight function for shortest simple paths for #3948

- networkx/algorithms/communicability_alg.py
Fix defination of communicability as mentioned in #3811
> Fixes documentation issue #3811 

- networkx/algorithms/community/kernighan_lin.py
- networkx/algorithms/community/tests/test_kernighan_lin.py
> implemented faster sweep algorithm for kernighan_lin_bisection

- networkx/algorithms/centrality/tests/test_voterank.py
- networkx/algorithms/centrality/voterank_alg.py
1. Implemented the VoteRank algorithm for directed graphs as described in the reference paper.
2. Removed the max_iter parameter. In each iteration, a new node is selected as an influential spreader. The max_iter parameter should be the same as the number of nodes to extract.
3. The code returns only nodes with positive votes as per the previous author. Updated the document for the same.
4. Added unit test for voterank algorithm on directed graphs.
> Enhancement for voterank

- networkx/algorithms/cycles.py
> DOC: added see also section to find_cycle

- networkx/classes/graphviews.py
> improve docs for subgraph_view filter_edge

- networkx/convert.py
> use raise from for exceptions in to_networkx_graph

- examples/subclass/plot_antigraph.py
- networkx/algorithms/approximation/kcomponents.py
- networkx/algorithms/assortativity/correlation.py
- networkx/algorithms/bipartite/cluster.py
- networkx/algorithms/bipartite/edgelist.py
- networkx/algorithms/bipartite/matching.py
- networkx/algorithms/bipartite/matrix.py
- networkx/algorithms/bipartite/spectral.py
- networkx/algorithms/centrality/current_flow_betweenness.py
- networkx/algorithms/centrality/current_flow_betweenness_subset.py
- networkx/algorithms/centrality/katz.py
- networkx/algorithms/centrality/second_order.py
- networkx/drawing/tests/test_pylab.py
@dschult This is the continuation of #4000
I also noticed a few mistakes in error messages along the way, I corrected these too.
> Fix exception causes and messages in 12 modules

- networkx/readwrite/gexf.py
- networkx/readwrite/graphml.py
np.int is just int--it is not a numpy type.
> Remove usage of deprecated np.int

- doc/reference/algorithms/index.rst
- doc/reference/algorithms/regular.rst
- networkx/algorithms/__init__.py
- networkx/algorithms/regular.py
- networkx/algorithms/tests/test_regular.py
Adds the functions `is_regular`, `is_k_regular`, and `k_factor`.
The functions `is_regular` are fairly self-explanatory. The
`k_factor` function implements an algorithm for computing the k-factor
of a graph. The algorithm is described in "An algorithm for computing simple
k-factors" (Meijer, H., Núñez-Rodríguez, Y., & Rappaport, D. 2009).
> Add algorithms for regular graphs

- networkx/algorithms/approximation/treewidth.py
Hello,
This is my first time contributing to networkx. I hope I'm following the contributing guidelines.
I just spotted a small typo. A first name isn't spelled properly. Is it worth fixing?
Thanks :)
> Typo Hand should be Hans

- doc/conf.py
- networkx/classes/digraph.py
- networkx/classes/graph.py
- networkx/classes/multidigraph.py
- networkx/classes/multigraph.py
- networkx/readwrite/gpickle.py
- networkx/utils/random_sequence.py
> Update links to Py3 docs

- RELEASE.rst
- doc/_templates/dev_banner.html
- doc/_templates/eol_banner.html
- doc/_templates/layout.html
- doc/conf.py
Closes #3998 and adds some stubs pertaining to #2730.
> Add URLs/banner/titlebar to documentation

- CONTRIBUTORS.rst
- doc/reference/algorithms/link_prediction.rst
- networkx/algorithms/link_prediction.py
CCPA was published in Nature Scientific Reports -2020. I will add some more link prediction algorithm later.
> added new Link Prediction algorithm (CCPA)

- networkx/tests/test_convert_pandas.py
> TST: remove int64 specification from test.

- .travis.yml
- tools/travis/linux_install.sh
- tools/travis/osx_install.sh
- tools/travis/script.sh
> Use newer osx on travis

- networkx/classes/function.py
- networkx/classes/tests/test_function.py
> Allow G.remove_edges_from(nx.selfloops_edges(G))

- networkx/drawing/layout.py
Remove duplicated Parameters section in docstring
> Fix planar_layout docstring

- CONTRIBUTING.rst
- doc/developer/deprecations.rst
- doc/developer/gitwash/index.rst
- doc/developer/index.rst
- requirements/developer.txt
In addition to fixing some minor formatting and editing stuff, here are the main changes I made:
- I moved setting up the build environment to the initial setup section.
- In "Divergence from ``upstream master``", we used to recommend rebasing.  It now says to merge.  I borrowed text from ``scikit-image``.
- I put all the deprecation information in one location ``doc/developer/deprecations.rst``.
> Update contributor guide

- networkx/convert_matrix.py
> Update docstring for from_pandas_edgelist
