networkx/networkx

doc/reference/drawing.rst
networkx/drawing/layout.py
networkx/drawing/tests/test_layout.py

merge #3146 which came from unknown repository
@frhyme and @leeseunghoon originally proposed this.

new function rescale_layout_dict to rescale a dict-based layout

---

networkx/algorithms/approximation/steinertree.py
networkx/algorithms/approximation/tests/test_steinertree.py

Get steiner_tree to work with MultiGraphs by postprocessing

---

networkx/readwrite/json_graph/cytoscape.py
networkx/readwrite/json_graph/tests/test_cytoscape.py

I added a test that failed before this change.  Fixes #4173.

fix issue #4173: cytoscape_graph(input_data) did modify the original data

---

networkx/classes/digraph.py
networkx/classes/graph.py

rewrite add_nodes_from to relax code meant to allow ironpython pre-2.7.5

remove code in add_nodes_from that supports ironpython <2.7.5

---

doc/developer/nxeps/index.rst
doc/developer/nxeps/nxep-0002.rst

[Draft of a draft enhancement proposal]

NXEP 2 — API design of view slices

---

networkx/utils/misc.py

changed is_string_like to isinstance

---

.circleci/config.yml

* Try removing manual known_hosts addendum
* Update fingerprint

CI: update circleci doc deployment.

---

doc/developer/nxeps/nxep-0002.rst

Adds a discussion to NXEP2 on the various alternatives and proposes a plan of action.
I tend towards "quite verbose", so please feel free to slash/reword liberally!

NXEP: Add discussion to NXEP 2.

---

networkx/algorithms/minors.py

* Remove duplicate Notes section
* Remove unnecessary indentation.

DOC: Minor reformatting of contract_nodes docstring.

---

doc/developer/deprecations.rst
doc/release/release_dev.rst
networkx/readwrite/nx_yaml.py

Deprecate nx_yaml

---

doc/developer/deprecations.rst
doc/release/release_dev.rst
networkx/readwrite/gpickle.py

Deprecate gpickle

---

networkx/classes/graph.py
networkx/classes/tests/test_graph.py

Refactor exception handling in `nbunch_iter` and improve test specificity.
Should get `networkx/classes/graph.py` to 100% test coverage.

TST: Refactor exception handling to improve coverage

---

networkx/readwrite/json_graph/tests/test_tree.py
networkx/readwrite/tests/test_edgelist.py

Improve readwrite test coverage

---

.appveyor.yml
.github/workflows/testing.yml
.travis.yml
INSTALL.rst
networkx/release.py
requirements/default.txt

Test on Python 3.9

---

examples/subclass/plot_antigraph.py

Update adjacency_iter to adjacency

---

.circleci/config.yml
doc/conf.py
examples/3d_drawing/plot_mayavi2_spring.py
requirements/example-requirements.txt
requirements/example.txt

Should generate images/thumbnails for the 3d drawing example that uses mayavi.
See: https://sphinx-gallery.github.io/stable/configuration.html?highlight=mayavi#image-scrapers

Enable mayavi in sphinx gallery.

---

networkx/utils/misc.py

Fixes #4336 by adding an else clause to avoid resetting rng to None, and i moved the try/except to encapsulate the import statement only.

Bugfix for issue 4336, moving try/except and adding else clause

---

networkx/classes/tests/test_graph.py

Skip memory leak test for PyPy

---

examples/geospatial/plot_osmnx.py

@jarrodmillman I've added a simple OSMnx usage example for your review.
Cross-reference #4366 #4298.

add OSMnx usage example

---

networkx/algorithms/communicability_alg.py
networkx/conftest.py

Ignore expected warnings

---

networkx/algorithms/assortativity/correlation.py
networkx/algorithms/centrality/flow_matrix.py
networkx/algorithms/centrality/subgraph_alg.py
networkx/algorithms/centrality/tests/test_trophic.py
networkx/algorithms/communicability_alg.py
networkx/algorithms/node_classification/hmn.py
networkx/algorithms/node_classification/lgc.py
networkx/algorithms/node_classification/utils.py
networkx/algorithms/similarity.py
networkx/algorithms/tests/test_threshold.py
networkx/convert.py
networkx/drawing/tests/test_layout.py
networkx/generators/random_graphs.py
networkx/generators/spectral_graph_forge.py
networkx/linalg/algebraicconnectivity.py
networkx/linalg/laplacianmatrix.py
networkx/linalg/tests/test_algebraic_connectivity.py
networkx/readwrite/tests/test_gexf.py
networkx/utils/misc.py

This mainly about using the matrix multiplication operator ``@``.  It also makes the ``numpy/scipy`` imports more consistent.

Use matrix multiplication operator

---

networkx/algorithms/community/centrality.py
networkx/algorithms/flow/capacityscaling.py
networkx/algorithms/flow/networksimplex.py
networkx/algorithms/minors.py
networkx/algorithms/traversal/beamsearch.py
networkx/classes/graph.py
networkx/conftest.py
networkx/readwrite/gexf.py
networkx/readwrite/graphml.py
networkx/readwrite/tests/test_gexf.py
networkx/readwrite/tests/test_graphml.py
networkx/utils/misc.py

Remove xml import checks

---

networkx/algorithms/link_analysis/pagerank_alg.py
networkx/algorithms/link_analysis/tests/test_pagerank.py

Pagerank followup

---

examples/basic/plot_properties.py
examples/graph/plot_degree_sequence.py
examples/graph/plot_erdos_renyi.py
examples/graph/plot_roget.py
networkx/algorithms/centrality/tests/test_reaching.py

Don't import nx from networkx

---

examples/applications/plot_circuits.py

Add circuit plot

---

examples/graph/plot_words.py

Add words graph plot

---

doc/release/api_1.6.rst
doc/release/release_2.0.rst
networkx/algorithms/approximation/tests/test_approx_clust_coeff.py
networkx/algorithms/assortativity/correlation.py
networkx/algorithms/centrality/subgraph_alg.py
networkx/algorithms/connectivity/disjoint_paths.py
networkx/algorithms/connectivity/edge_kcomponents.py
networkx/algorithms/connectivity/tests/test_edge_kcomponents.py
networkx/algorithms/isomorphism/isomorphvf2.py
networkx/algorithms/minors.py
networkx/algorithms/operators/binary.py
networkx/algorithms/planar_drawing.py
networkx/algorithms/shortest_paths/tests/test_astar.py
networkx/algorithms/shortest_paths/weighted.py
networkx/algorithms/simple_paths.py
networkx/classes/graph.py
networkx/drawing/nx_pylab.py
networkx/generators/atlas.py
networkx/generators/stochastic.py
networkx/linalg/algebraicconnectivity.py
networkx/linalg/laplacianmatrix.py
networkx/utils/rcm.py

Remove repeated words from docs and comments.

DOC: Remove repeated words

---

examples/algorithms/plot_rcm.py
requirements/example.txt

Add plot for rcm example

---

examples/drawing/plot_atlas.py
examples/drawing/plot_lanl_routes.py
examples/graph/dot_atlas.py
examples/graph/plot_roget.py
examples/graph/plot_words.py

Use str dunder

---

.travis.yml

Attempt to fix missing fonts for travis CI doc deploy

CI: Add recommended fonts to travis.yml.

---

.travis.yml

Proposed fix based on: https://bugs.launchpad.net/ubuntu/+source/texlive-base/+bug/556071

CI: travis font naming bug

---

networkx/generators/classic.py

Minimal document updates... it snowballed from what I intended.
I don't think it conflicts with #4401

Updates to docs and imports for classic.py

---

examples/external/plot_igraph.py
requirements/example.txt

igraph recently added functions to convert to/from networkx:
https://github.com/igraph/python-igraph/pull/242

Add igraph example

---

doc/Makefile
examples/geospatial/README.txt
examples/geospatial/extended_description.rst

Co-authored-by: Brendan Ward <bcward@astutespruce.com>
Co-authored-by: Martin Fleischmann <martin@martinfleischmann.net>
Co-authored-by: Geoff Boeing <gboeing@users.noreply.github.com>
Co-authored-by: Ross Barnowski <rossbar@berkeley.edu>

Update geospatial readme

---

examples/external/javascript_force.py

JavaScript example: fix link

---

networkx/algorithms/flow/networksimplex.py

Correct networkxsimplex docstring re: multigraph

---

networkx/generators/classic.py
networkx/generators/tests/test_classic.py

binomial_tree() with "create_using parameter

---

networkx/algorithms/approximation/kcomponents.py

Just re-added the decorator and updated the docs for the `k_components` function in the `networkx.algorithms.approximation` module.

Fixed docs + added decorator for k_components

---

networkx/algorithms/cluster.py

Tries to make more clear that number of # of triangles double counts in the undirected functions.
Doesn't change that behavior (which also saves dividing by 2 and then multiplying by 2 later).
Just tries to make it more clear.
Fixes #4348

Update docs for clustering Fixes #4348

---

README.rst

Update GH actions links in README

---

networkx/algorithms/centrality/tests/test_katz_centrality.py
networkx/algorithms/isomorphism/tests/test_ismags.py
networkx/algorithms/tests/test_threshold.py

Reenable tests

---

requirements/example.txt

Simplify example dependencies

---

.github/workflows/test.yml

Run pypy tests separately

---

.github/workflows/deploy-docs.yml

Move devdoc deployment from Travis to GH actions.
Still to do:
- Setup deploy keys/secrets for cross-repo deploy

Setup cross-repo doc deploy via actions.

---

networkx/algorithms/tests/test_swap.py

Here, I added some tests to tests_swap.py to improve code coverage.

Improve code coverage of swap.py

---

networkx/algorithms/approximation/kcomponents.py
networkx/algorithms/bipartite/basic.py
networkx/algorithms/chordal.py
networkx/algorithms/regular.py
networkx/algorithms/shortest_paths/astar.py
networkx/algorithms/shortest_paths/weighted.py
networkx/algorithms/simple_paths.py
networkx/algorithms/smallworld.py
networkx/classes/digraph.py
networkx/classes/function.py
networkx/classes/graph.py
networkx/generators/random_graphs.py
networkx/generators/trees.py
networkx/readwrite/gexf.py
networkx/readwrite/json_graph/adjacency.py
networkx/readwrite/json_graph/tree.py
networkx/readwrite/multiline_adjlist.py
networkx/readwrite/nx_shp.py
networkx/readwrite/nx_yaml.py

This PR fixes some of the parameters in the docstrings (typos or missing) + remove a couple of unused variables.

Fix docstrings

---

networkx/algorithms/chordal.py
networkx/algorithms/tests/test_chordal.py

Here I added some additional tests to test_chordal.py to improve the code coverage. These include tests for self-loops and graphs which are not chordal. I also improved the efficiency of a couple of functions in chordal.py such as is_chordal() and _chordal_graph_cliques(). Thanks, @dschult for your help with this!

Improving code coverage of chordal.py

---

doc/reference/algorithms/approximation.rst
networkx/algorithms/approximation/__init__.py
networkx/algorithms/approximation/distance_measures.py
networkx/algorithms/approximation/tests/test_distance_measures.py

Closes #4475 
The PR aims at implementing a module with the functionalities to compute a `lower bound` on the diameter for both undirected and directed graphs.

Approximated Diameter 

---

networkx/algorithms/shortest_paths/weighted.py

The changes were made to the definition of cutoff param in the weighted.py file

updated cutoff def in weighted.py

---

networkx/algorithms/dag.py

update anceestor&descendent doc

---

requirements/example.txt

Pin pygeos==0.8

---

networkx/drawing/tests/test_pylab.py

I am simplifying test_pylab.py in preparation for using pytest-mpl.

Simplify test pylab

---

requirements/doc.txt

Fix search

---

networkx/algorithms/shortest_paths/dense.py
networkx/algorithms/shortest_paths/tests/test_dense_numpy.py

Add tests for NetworkXError when nodelist is not a full order.
Fixes #4587

Check nodelist input to floyd_warshall

---

networkx/drawing/tests/test_agraph.py
networkx/drawing/tests/test_pydot.py

Remove mktemp usage

---

networkx/algorithms/non_randomness.py
networkx/algorithms/tests/test_non_randomness.py

Added two tests to improve code coverage of nonrandomness.py

Code coverage nonrandomness

---

doc/developer/projects.rst

Add 2 more projects to the list of projects (and minor edits to others)
Traveling salesman problem: Asadpour (2017) provides the best approximate **directed** version.
Graph Isomorphism: VF2++ for graph/subgraph/induced subgraph problems for directed/undirected.

More for projects page: TSP and Graph Isomorphism

---

README.rst

Directly takes you to issues grouped with "Good First Issue" label

Add a good first issue badge to README 

---

networkx/algorithms/tests/test_regular.py

Added a test to increase code coverage

Increase code coverage of regular

---

networkx/algorithms/cycles.py

Just a minor doctest improvement I noticed while reading about cycles.

Improve doc example for find_cycle.

---

CONTRIBUTING.rst

Remove old file reference

---

.github/workflows/coverage.yml
.github/workflows/deploy-docs.yml
.github/workflows/test.yml

Update CI to use main

---

networkx/algorithms/bipartite/matching.py
networkx/algorithms/bipartite/tests/test_matching.py

The issue is well-described in #3306.
This code change consists of:
- style change from lazy to eager
- Test addition for reproduction
I tried not to invade original intention of code.
Closes #3306

Fix to_vertex_cover

---

networkx/algorithms/community/modularity_max.py
networkx/algorithms/community/tests/test_modularity_max.py

Unfortunately I couldn't find a related issue or PR, so here's my suggestion to account for the edge weights.

modularity_max: account for edge weights

---

networkx/algorithms/dag.py

Fixing Bug in Transitive Reduction, resulting in loss of node/edge attributes

---

networkx/algorithms/approximation/clustering_coefficient.py

Updating average_clustering() documentation - Issue #4734

---

networkx/algorithms/approximation/clustering_coefficient.py

Just to keep things consistent with #4163 .
I had meant to comment this on #4735 but I wasn't fast enough - sorry about that!

rm nx import from docstring example.

---

.circleci/config.yml
requirements/example.txt

Attempt to temporarily fix the cartopy wheel build failure in circleCI.

CI: Fix cartopy build failure in docs workflow

---

networkx/drawing/nx_pylab.py

Pull request addressing [issue 3443](https://github.com/networkx/networkx/issues/3443)

Add auto-margin scaling in draw_networkx_nodes function (fix for issue 3443)

---

doc/conf.py
requirements/doc.txt

Update documentation dependencies

---

doc/developer/new_contributor_faq.rst
doc/developer/projects.rst
doc/developer/release.rst

Just some cleanup to get rid of sphinx-build warnings.

Fix sphinx warnings during doc build.

---

doc/_static/custom.css
doc/_templates/dev_banner.html
doc/_templates/layout.html
doc/_templates/version.html
doc/conf.py

@rossbar Could you take a quick look at this?

Improve documentation look

---

doc/reference/algorithms/summarization.rst
examples/algorithms/plot_snap.py
networkx/algorithms/summarization.py
networkx/algorithms/tests/test_summarization.py

An implementation of the SNAP graph summarization algorithm from [Efficient Aggregation for Graph Summarization](http://pages.cs.wisc.edu/~jignesh/publ/summarization.pdf).
This algorithm creates a summary graph of supernodes, where supernodes represent sets of nodes that have the same attributes and edges with nodes in the same supernodes in the summary graph.

adds implementation of SNAP summarization algorithm

---

doc/developer/deprecations.rst
networkx/algorithms/link_analysis/hits_alg.py
networkx/algorithms/link_analysis/tests/test_hits.py

Wrappers for HITS, https://github.com/networkx/networkx/issues/4371

Make nx.hits a wrapper around different implementations, use scipy one by default

---

networkx/algorithms/approximation/traveling_salesman.py
networkx/algorithms/graphical.py
networkx/algorithms/summarization.py

Fix Sphinx errors

---

doc/developer/deprecations.rst
doc/release/release_dev.rst
networkx/conftest.py
networkx/utils/decorators.py

Deprecate preserve_random_state

---

CONTRIBUTING.rst
networkx/conftest.py
networkx/testing/__init__.py

Depends on #4556 and is depended upon by #4579.

Add info about testing and examples

---

doc/developer/deprecations.rst
doc/release/release_dev.rst
networkx/algorithms/link_analysis/hits_alg.py
networkx/algorithms/link_analysis/tests/test_hits.py

Use scipy to compute eigenvalues

---

doc/developer/deprecations.rst
doc/release/release_dev.rst
networkx/algorithms/similarity.py
networkx/algorithms/tests/test_similarity.py

Default to NumPy for simrank_similarity

---

networkx/generators/trees.py

Fix docstring typo

---

networkx/generators/sudoku.py

The grid table was not properly formatted using reStructuredText Markup which is required by Sphinx.

Reformatted  table to address issue #4852

---

doc/tutorial.rst
networkx/algorithms/tests/test_lowest_common_ancestors.py
networkx/classes/digraph.py
networkx/classes/graph.py
networkx/classes/multidigraph.py
networkx/classes/multigraph.py
networkx/classes/tests/test_function.py
networkx/classes/tests/test_graph.py

Removed some tests that checked that errors raised when None was a node.
Fixes #4788

Raise ValueError if None is added as a node.

---

doc/developer/deprecations.rst
doc/release/release_dev.rst
networkx/algorithms/assortativity/mixing.py
networkx/conftest.py

Re-submission of #4920 - I had a hard time resolving all the conflicts during rebasing.

Deprecate numeric_mixing_matrix.

---

doc/developer/release.rst

Update release process

---

networkx/algorithms/community/quality.py

Removed some unnecessary imports and fixed some minor docstring issues

Minor Improvements on Networkx/algorithms/community/quality.py

---

networkx/conftest.py

fix spelling in docstring of conftest.py

---

networkx/algorithms/approximation/tests/test_traveling_salesman.py
networkx/algorithms/approximation/traveling_salesman.py

fix trouble with init_cycle argument to two TSP functions

---

doc/release/release_dev.rst

fix typo for PR number of deprecation

---

doc/conf.py

Fix version pull down

---

doc/_templates/layout.html
doc/release/release_2.6.rst
doc/release/release_dev.rst
doc/release/release_template.rst

Finalize 2.6 release notes

---

networkx/readwrite/gpickle.py

This text should warn developers about the risks involved using this format.

Added security warning to the pickle documentation

---

networkx/readwrite/graphml.py

added security warning for graphml files

---

networkx/readwrite/gexf.py

Added security warning to gefx parser

---

doc/developer/about_us.rst

My second attempt at updating this file.
First attempt is PR #5018.

updated contributor file for GSoC 2021, take 2

---

networkx/generators/geometric.py

update docs to match implementation of geographical threshold graph

---

networkx/algorithms/dag.py
networkx/algorithms/tests/test_dag.py

[GSoC contribution] Improving functions `descendants` and `ancestors` in dag.py

---

networkx/algorithms/dag.py

I noticed that examples are missing for some functions. Fixed this.

[GSoC contribution] Adding examples to docstrings in dag.py

---

networkx/readwrite/gml.py

Add references to literal de/stringizer in gml function docstrings

---

requirements/default.txt

Test scipy and pandas on py3.10

---

doc/reference/algorithms/shortest_paths.rst
networkx/algorithms/shortest_paths/tests/test_weighted.py
networkx/algorithms/shortest_paths/weighted.py

add code to find negative cycle if bellman_ford detects one
This just builds the code into the bellman_ford function. We should also provide it as a public function.

Add a function to find the negative cycle using bellman_ford

---

INSTALL.rst
requirements/default.txt
setup.py

Test on Python 3.10

---

networkx/generators/mycielski.py

Removed unused variable in mycielski.py (prev line 55).
Thanks for the opportunity to make my first pull request - great project!

Remove unused variable in mycielski.py

---

examples/algorithms/plot_subgraphs.py

Fixes https://github.com/networkx/networkx/issues/4220

[MRG] Create plot_subgraphs.py example

---

examples/drawing/plot_tsp.py

Me and @Mdontas created this pull request in order to add a drawing example for the tsp. It's been tested locally and it follows the Black code format.

Add a drawing example regarding the solution of traveling salesman problem

---

requirements/example.txt

Use new package name

---

.pre-commit-config.yaml
requirements/developer.txt

Update dev deps

---

networkx/algorithms/structuralholes.py

Update minor doc issues with tex notation

---

requirements/developer.txt

Update to stable version of black

---

doc/developer/nxeps/nxep-0002.rst

Wasn't super sure about how to update this so added a new section `Resolution` in the NXEP

DOC: change status to accepted for NXEP2, add resolution

---

requirements/test.txt

Update test requirements

---

networkx/convert_matrix.py

Document default dtype in to_numpy_recarray docstring.

---

networkx/generators/line.py
networkx/generators/tests/test_line.py

Closes https://github.com/networkx/networkx/issues/4459
Also removed other helper functions which could be rewritten quickly with python one liners.

MAINT: Remove unnecessary helper functions, use inbuilt methods for line graph generator

---

doc/release/release_dev.rst

Just a listing of notes and thoughts from having reviewed all the merged PRs since the 2.6 release.

First pass at 2.7 release notes.

---

doc/release/migration_guide_from_2.x_to_3.0.rst

Add pickle and yaml migration info

---

doc/developer/deprecations.rst
doc/release/release_dev.rst
networkx/classes/function.py
networkx/conftest.py

Deprecate info

---

networkx/tests/test_convert_pandas.py
requirements/default.txt

Fix pandas warning

---

.github/workflows/test.yml
requirements/test.txt

Test on 3.11-dev

---

doc/developer/projects.rst

Update mentored project info with the expected time commitment

---

.circleci/config.yml
requirements/developer.txt
requirements/doc.txt
requirements/test.txt

Remove stuff conda doesn't support

---

doc/_templates/layout.html
doc/developer/release.rst

Fix development banner

---

networkx/lazy_imports.py

Simplify DelayedImportErrorModule

---

networkx/algorithms/centrality/betweenness.py
networkx/classes/digraph.py
networkx/classes/multidigraph.py
networkx/classes/multigraph.py

Fix missing backticks

---

networkx/classes/multidigraph.py

Updated MultiDiGraph documentation to include more examples of actually
using parallel edges, and fixed references to things like G[u, v] where
G[u, v, k] is required for a MultiDigraph. Have not made parallel
changes in MultiGraph which should maybe also be made?
Docs tests pass on my end; no code outside of comments was changed.
-Peter Mawhorter

Updated MultiDiGraph documentation to include more examples of actually

---

networkx/classes/multidigraph.py
networkx/classes/multigraph.py

Here's my pull request for an update to the MultiGraph docs that parallels the updates I just suggested to the MultiDiGraphs docs which were accepted (PR #5387 ).

Multigraph docs update

---

networkx/classes/function.py

This is based on https://stackoverflow.com/q/71494698/10693596

Correct typo in docstring (int -> float)

---

networkx/algorithms/graph_hashing.py

Otherwise they are just seen as text

DOC: examples code blacks needs a blank line

---

networkx/readwrite/sparse6.py

Update sparse6 urls to use https

---

networkx/algorithms/approximation/connectivity.py
networkx/algorithms/approximation/kcomponents.py
networkx/algorithms/asteroidal.py
networkx/algorithms/chordal.py
networkx/readwrite/nx_shp.py
networkx/utils/contextmanagers.py

I was recently stuck on a plane and passed the time by reading through the networkx source. Here are a collection of (hopefully uncontroversial) improvements that I collected while reading.

Minor improvements from general code readthrough

---

networkx/algorithms/tests/test_polynomials.py

Just a quick followup to #5265 
This PR parametrizes the tests suite, which saves a few lines of code and in principle makes it easier to add new test cases if desired (just add a new `graph: polynomial` to the `_test_graphs` mapping).

Parametrize tutte polynomial tests

---

CONTRIBUTING.rst

Just some opinions about how to add references, feel free to edit them :)

DOCS: add some guidelines for references

---

networkx/algorithms/covering.py
networkx/drawing/layout.py

This pull request aims at resolving two issues addressed in issue https://github.com/networkx/networkx/issues/5212

Fix for issue 5212

---

networkx/algorithms/shortest_paths/generic.py

I added more comments and made the example more clear.

shortest_path() example

---

.pre-commit-config.yaml
CONTRIBUTING.rst
README.rst
doc/developer/nxeps/nxep-0003.rst
requirements/developer.txt

Run black on docs

---

networkx/algorithms/planarity.py

Closes #5090.
Please let me know if this needs any modification.

Improve documentation of PlanarEmbedding class

---

networkx/algorithms/planarity.py

A quick followup to #5523 to fix the broken doc build.

Fix doc build error in planarity

---

networkx/readwrite/gml.py
networkx/utils/decorators.py

Missing `f` prefix on f-strings fix

---

networkx/drawing/nx_pydot.py

improve docstring for read_doc, see issue #5604

---

networkx/classes/graph.py
networkx/classes/tests/test_graph.py

Closes https://github.com/ComplexGroupInteractions/xgi/issues/103

Cache `nodes` property on Graph

---

.github/workflows/coverage.yml
.github/workflows/deploy-docs.yml
.github/workflows/lint.yml
.github/workflows/mypy.yml
.github/workflows/test.yml

Update GH actions

---

doc/release/release_dev.rst
networkx/algorithms/euler.py
networkx/algorithms/tests/test_euler.py

Disallow isolated nodes for Eulerian Path

---

.github/workflows/coverage.yml
.github/workflows/deploy-docs.yml
.github/workflows/test.yml

Use new ubuntu LTS release

---

networkx/algorithms/moral.py

added example on moral graph

---

networkx/linalg/laplacianmatrix.py

Was reading the codebase for Laplacian today :)

DOC: fix up links, remove references to directed graphs, add proper cites

---

networkx/algorithms/operators/unary.py

Added example under unary operators

---

networkx/algorithms/matching.py

Added examples on matching

---

networkx/algorithms/chains.py

added examples to chains.py

---

networkx/algorithms/traversal/tests/test_dfs.py

From https://github.com/networkx/networkx/pull/1826, the current tests for DFS may miss an edge case (have multiple successors) if there are any changes in the code in the future.

Update dfs_test with more comprehensive tests

---

networkx/algorithms/centrality/closeness.py

added example to closeness.py

---

networkx/algorithms/coloring/greedy_coloring.py

The correct spelling of the author is "Narsingh Deo" not "Marsingh Deo".

Correcting a typo in the references

---

networkx/classes/tests/test_subgraphviews.py

I guess we will see a bunch of other things when https://github.com/networkx/networkx/pull/4553 is merged and the cron job runs every day.

Another catch by pytest-randomly

---

networkx/utils/tests/test.txt

Remove unused file from utils.test

---

requirements/release.txt

Update release requirements

---

.pre-commit-config.yaml
doc/release/contribs.py
requirements/developer.txt

Update developer requirements

---

networkx/generators/community.py

It seems to me that these pieces in the docs should be inline math, not inline code.

Use inline math

---

requirements/doc.txt

Update doc requirements

---

doc/developer/deprecations.rst
networkx/conftest.py
networkx/drawing/nx_pydot.py

Add PendingDeprecation for pydot

---

doc/developer/deprecations.rst
doc/reference/algorithms/similarity.rst
networkx/algorithms/similarity.py
networkx/algorithms/tests/test_similarity.py

Remove deprecated simrank_similarity_numpy

---

doc/developer/deprecations.rst
doc/reference/algorithms/assortativity.rst
networkx/algorithms/assortativity/mixing.py
networkx/algorithms/assortativity/tests/base_test.py
networkx/algorithms/assortativity/tests/test_correlation.py
networkx/algorithms/assortativity/tests/test_mixing.py
networkx/conftest.py

Remove deprecated numeric_mixing_matrix

---

doc/developer/deprecations.rst
networkx/algorithms/community/modularity_max.py

Remove _naive_greedy_modularity_communities

---

networkx/algorithms/link_analysis/pagerank_alg.py
networkx/algorithms/link_analysis/tests/test_pagerank.py

Maybe there is some docs I am missing to update here?

Update return type of google_matrix to numpy.ndarray

---

networkx/linalg/attrmatrix.py

It does feel like I'm missing some update to documentation here.

Update return type of attrmatrix

---

networkx/algorithms/bipartite/centrality.py
networkx/algorithms/bipartite/tests/test_centrality.py

Fixes #5620 
with typo in bipartite closeness_centrality and thought-o in tests

Fix typo in bipartite closeness_centrality and thought-o in tests

---

.github/workflows/test.yml

Test out explicit paths while installing pygraphviz in macOS

---

doc/reference/functions.rst
examples/algorithms/plot_parallel_betweenness.py
networkx/algorithms/connectivity/tests/test_kcutsets.py
networkx/classes/function.py
networkx/classes/graph.py
networkx/classes/tests/test_function.py
networkx/convert_matrix.py

bye bye nx.info, we should really try to get something which is more useful and informative.

Remove deprecated function nx.info

---

doc/reference/algorithms/link_analysis.rst
networkx/algorithms/link_analysis/hits_alg.py
networkx/algorithms/link_analysis/tests/test_hits.py
networkx/conftest.py

Remove deprecated functions hub_matrix and authority_matrix

---

networkx/algorithms/components/strongly_connected.py

Added two examples for the better understanding of the condensation funciton use

Add examples for the condensation function

---

networkx/relabel.py
networkx/tests/test_relabel.py

This preserves the original order of the nodes, as discussed in https://stackoverflow.com/a/70706215/10693596

Update relabel.py to preserve node order

---

.pre-commit-config.yaml
requirements/developer.txt

Update precommit linters

---

networkx/algorithms/efficiency_measures.py

added examples to efficiency_measures.py

---

networkx/algorithms/regular.py

added examples to regular.py

---

networkx/algorithms/triads.py

Fixes #5498
I have added the examples for 7 Functions in Triads.py file. I manually applied black style to the doc examples as well. I will update the documentation under the same thread. Please let me know if I can improve the examples further.

Examples for 7 Functions in Triads.py added solving issue #5498

---

networkx/algorithms/triads.py
networkx/tests/test_all_random_functions.py

Make sure results are reproducible.

Use py_random_state to control randomness of random_triad

---

doc/reference/algorithms/lowest_common_ancestors.rst
doc/reference/classes/index.rst
networkx/algorithms/components/strongly_connected.py
networkx/algorithms/lowest_common_ancestors.py

Just a few fixups for sphinx warnings that I noticed during a local doc build.

Minor doc fixups

---

examples/graph/plot_morse_trie.py

I was recently wasting time on the internet when I came across a Morse code signal decoders chart, which immediately struck me as a good example of a prefix tree. I thought it might make a nice gallery example!

Gallery example: Morse code alphabet as a prefix tree

---

networkx/algorithms/lowest_common_ancestors.py

Fixes #5862 
I have updated all_pairs_lca and naive_all_pairs_lca docstrings
I am new to open source, so please tell if I am doing anything wrong.

update all_pairs_lca docstrings

---

networkx/algorithms/shortest_paths/unweighted.py

Update docs to include description of the `return_seen` kwarg (previously not documented)

Update docs to include description of the `return_seen` kwarg

---

doc/developer/about_us.rst

Add to about_us.rst

---

networkx/conftest.py
networkx/readwrite/graph6.py
networkx/readwrite/sparse6.py

Remove old Appveyor cruft

---

networkx/algorithms/approximation/tests/test_treewidth.py
networkx/algorithms/approximation/treewidth.py

Allow unsortable nodes in approximation.treewidth functions

---

networkx/classes/function.py

Updated networkx/classes/function.py . Solves Issue #5463

---

networkx/algorithms/simple_paths.py

Improved the documentation for all_simple_paths.
This is a PR following the discussion in  #5936.

Improved documentation for all_simple_paths

---

doc/developer/projects.rst

This moves VF2++ from the list of available mentored projects to the "completed projects" list.

Update mentored projects list

---

examples/drawing/plot_directed.py

I thought we had gotten all of these in previous PRs, but it looks like we missed one.

Fix failing example due to mpl 3.6 colorbar.

---

README.rst

Add Tidelift security vulnerability link

---

README.rst

(not sure if it matters but trying to clear tidelift "tasks")

update secutiry link to tidelift

---

.github/workflows/test.yml
setup.py

Support Python 3.11

---

networkx/algorithms/bipartite/matrix.py
networkx/algorithms/centrality/betweenness.py
networkx/algorithms/centrality/betweenness_subset.py
networkx/algorithms/chordal.py
networkx/algorithms/tournament.py
networkx/classes/coreviews.py
networkx/classes/digraph.py
networkx/classes/graph.py
networkx/classes/multidigraph.py
networkx/classes/multigraph.py
networkx/conftest.py
networkx/convert.py
networkx/convert_matrix.py
networkx/linalg/attrmatrix.py
networkx/linalg/bethehessianmatrix.py
networkx/linalg/graphmatrix.py
networkx/linalg/laplacianmatrix.py
networkx/linalg/modularitymatrix.py

Use scipy.sparse array datastructure

---

networkx/readwrite/json_graph/tests/test_adjacency.py
networkx/readwrite/json_graph/tests/test_cytoscape.py
networkx/readwrite/json_graph/tests/test_node_link.py
networkx/readwrite/json_graph/tests/test_tree.py
networkx/tests/test_relabel.py

Add missing asserts to tests

---

networkx/algorithms/centrality/tests/test_load_centrality.py

fixes #6036

---

networkx/generators/tests/test_expanders.py

added tests to Improve test coverage on expanders line graph generators

Improve test coverage expanders line graph generators solved (PR for issue #6034)

---

networkx/algorithms/flow/tests/test_maxflow.py

Tested boykov_kolmogorov and dinitz with cutoff

---

networkx/generators/tests/test_trees.py

I added some tests to improve coverage in generators/trees.py
Closes #6103

added coverage in generators/tree.py

---

networkx/algorithms/__init__.py
networkx/algorithms/bipartite/projection.py

Another deprecation to be expired for 3.0

Remove deprecated project function from bipartite package.

---

.github/workflows/test.yml

Test on Python 3.11

---

networkx/algorithms/approximation/tests/test_steinertree.py
networkx/algorithms/shortest_paths/tests/test_unweighted.py

Hi @MridulS, please review. I did not explicitly create an issue for the task

Improve test coverage in algorithms shortest paths unweighted.py

---

networkx/algorithms/tests/test_covering.py
networkx/generators/tests/test_expanders.py

Increases coverage to reach final conditional

Increase covering coverage

---

networkx/linalg/algebraicconnectivity.py

I added an example in `algebraic_connectivity`.

Added an example to algebraic_connectivity

---

networkx/algorithms/traversal/tests/test_beamsearch.py

For isseu #6030  Add test coverage for algorithms in beamsearch.py

For issue #6030 Add test coverage for algorithms in beamsearch.py

---

networkx/generators/tests/test_stochastic.py

Improve test coverage expanders stochastic graph generators

---

.pre-commit-config.yaml
requirements/developer.txt

Update developer requirements 

---

networkx/classes/digraph.py
networkx/classes/multidigraph.py

Improved the docstring description and added examples for how InEdgeView works. 
Note: Examples were extracted from discussions that were help in [this](https://github.com/networkx/networkx/issues/4745).
Related to #4765 
@MridulS , please review and merge it if possible so that I can complete my application

Di graph edges doc fix

---

networkx/algorithms/tests/test_core.py
networkx/algorithms/tests/test_covering.py

Increased Test coverage in test_core.py 
Pursuant to issue #6115

Improve coverage for core.py

---

networkx/algorithms/bipartite/redundancy.py

Reverts the code changes from #6219 - see [this discussion](https://github.com/networkx/networkx/pull/6219#issuecomment-1318650349).

Revert 6219 and delete comment.

---

networkx/algorithms/community/quality.py

The wording of this error message had the graph and collection switched around, so I fixed it

fix wording in error message

---

doc/release/index.rst
doc/release/release_2.8.6.rst
doc/release/release_2.8.7.rst
doc/release/release_2.8.8.rst

Add 2.8.x release notes

---

doc/developer/about_us.rst

Add a contributor

---

networkx/algorithms/simple_paths.py

Improve readability of the BFS.
Resolves https://github.com/networkx/networkx/issues/3912.

Update simple_paths.py to improve readability of the BFS.

---

networkx/classes/digraph.py
networkx/classes/graph.py
networkx/classes/multigraph.py

Resolves https://github.com/networkx/networkx/issues/2717

doc: update documentation when providing an iterator over current graph to add/remove_edges_from.

---

networkx/algorithms/isomorphism/tests/test_isomorphvf2.py
networkx/algorithms/isomorphism/vf2pp_helpers/feasibility.py

Fix bug vf2pp is isomorphic issue 6257

---

networkx/generators/classic.py

Resolves https://github.com/networkx/networkx/issues/6285

[DOC] Follow numpydoc standard in barbell_graph documentation

---

LICENSE.txt
README.rst

Time for the new-year-update-copyright PR. Happy new year!
There is a debate about this if we even need to keep the years in the notice[1][2] but until that is resolved let's update them.
[1] https://hynek.me/til/copyright-years/
[2] https://github.com/scipy/scipy/issues/15282#issuecomment-1003762552

Update copyright years to 2023

---

doc/developer/about_us.rst
networkx/algorithms/approximation/steinertree.py
networkx/classes/backends.py
networkx/classes/digraph.py

Fix the warnings that arise from `make doctest`

fix warnings for make doctest

---

.github/workflows/deploy-docs.yml

Fix documentation deployment

---

doc/release/release_dev.rst

Fix links to migration guide

---

examples/external/force/README.txt

Closes Issue #6217 
Changes made:
- Fix typo in readme.txt for missing file force.py

Fix typo in readme file

---

doc/release/release_dev.rst

The list of commits and authors was updated via:
```
git checkout networkx-2.8.8
git pull origin networkx-2.8.8
git checkout main
git pull origin main
git cherry -v networkx-2.8.8 main > cherry-log.txt
grep "^+" cherry-log.txt | cut -d " " -f 3- > 3.0-new-commit-messages.txt
grep "^+" cherry-log.txt | cut -d " " -f 2  > 3.0-new-commit-hashes.txt
> 3.0-new-commit-authors.txt
lines=$(cat 3.0-new-commit-hashes.txt)
for line in $lines
do
git log --format="%an" ${line}^! >> 3.0-new-commit-authors.txt
done
sort -u -o 3.0-new-commit-authors.txt{,}
awk -i inplace '{ print "-", $0 }' 3.0-new-commit-messages.txt
awk -i inplace '{ print "-", $0 }' 3.0-new-commit-authors.txt
```

Update release notes

---

.pre-commit-config.yaml
requirements/developer.txt

Update precommit hooks

---

networkx/algorithms/cluster.py

doc:improve doc of possible values of nodes and expected behaviour

---

doc/release/release_3.0.rst

add OrderedGraph removal as an API change in release_3.0.rst

---

networkx/drawing/nx_latex.py

as mentioned on https://github.com/networkx/networkx/issues/6357, tikz wants degrees (or radians, but these must be suffixed with `r`)

provide tikz with degrees, not radians

---

doc/reference/classes/multidigraph.rst

Fixes https://github.com/networkx/networkx/issues/6408

DOC: list pred method for MultiDiGraphs

---

networkx/algorithms/bipartite/matching.py

This is a re-submission of #6207 limited to the changes agreed upon in the review there.

Comment out unused unlayered dict construction.

---

CONTRIBUTING.rst

Small text update to resolve [Issue 6302](https://github.com/networkx/networkx/issues/6302).

Update installation test instructions

---

networkx/algorithms/tests/test_clique.py

Close #6141 
Added some tests to improve coverage to 100%

Added new tests in test_clique.py

---

networkx/algorithms/shortest_paths/dense.py
networkx/algorithms/shortest_paths/unweighted.py
networkx/algorithms/shortest_paths/weighted.py

We've added Floyd-Warshall algorithms to `graphblas-algorithms`, and Bellman-Ford and some other shortest path algorithms are next.

Add dispatching to more shortest path algorithms

---

networkx/generators/tests/test_directed.py

Completes coverage of the generators/directed file

Added tests to test_directed.py.

---

networkx/generators/line.py

This is a pull request with the changes in the documentation to resolve "Reference for inverse_line_graph #6428   "
Closes #6428

Fix reference in line.py-inverse_line_graph

---

doc/developer/projects.rst

I've added two possible project topics.
I could also add isomorphism VF3 or RI if we want to continue to focus on cleaning up the isomorphism subpackage.
I removed my name from the Notebooks project mentoring because I haven't been doing much review there.
Please add your name as an interested mentor if you are interested. (or leave a comment and I will add it).
Suggestions?

Add project desc for visualization and ISMAGs

---

doc/developer/nxeps/nxep-0000.rst
doc/developer/nxeps/nxep-0001.rst

We should change the status of our governance NXEP to "Accepted".

NXEP 0 and NXEP 1 - change status to Accepted

---

networkx/tests/test_convert_numpy.py

Added test for when the node list includes a node that is not in the graph.
Added test for when the incoming array is 3 dimensional.

Added two tests for convert_numpy

---

networkx/algorithms/components/connected.py
networkx/algorithms/components/weakly_connected.py
networkx/algorithms/shortest_paths/weighted.py
networkx/algorithms/traversal/breadth_first_search.py
networkx/algorithms/traversal/edgebfs.py

I've already implemented the majority of these in `graphblas_algorithms` and hope to implement the rest soon.

Dispatch more BFS-based algorithms

---

networkx/generators/classic.py

Fixes link and removes sphinx warning.

Fix reference formatting in generator docstring.

---

networkx/algorithms/tree/tests/test_branchings.py

Fixes #6520 
@MridulS @rossbar @paulitapb Please have a look

improve test coverage for branchings.py

---

examples/algorithms/plot_girvan_newman.py

I have written a python script that demonstrates the use of Girvan-Newman method to detect communities in the Zachary Karate Club dataset. It also plots the change in modularity as the important edges are removed with each iteration.

Add community detection example to Gallery

---

README.rst

This PR fixes the formatting of the URL for the NetworkX Survey 2023 (in `README.rst`).

Fix survey URL

---

doc/developer/nxeps/nxep-0001.rst
doc/developer/team.rst
tools/team_list.py

Update team galleries

---

networkx/algorithms/isomorphism/ismags.py

Closes #6594 
Changed the method description of `partition_to_color` so that it is easier to understand.

Fixed method description in ismags.py

---

doc/release/release_dev.rst

The empty sections are supposed to be filled during the release process, so we just need to fill in the `Highlights`, `Improvements`, and `Deprecations` sections.  I removed the `API Changes`, since I don't think this release has any. Please correct me if I am wrong.

Draft release notes

---

doc/release/release_dev.rst
networkx/algorithms/cycles.py
networkx/algorithms/tests/test_cycles.py

Fixes issue https://github.com/networkx/networkx/issues/6653

Make cycle_basis() deterministic

---

doc/developer/about_us.rst

Adding my github links next to my name in the contributors list.

Adding GitHub Links next to Dheeraj's name in the contributors list

---

networkx/algorithms/approximation/clique.py

MAINT: minor coverage cleanup.

---

networkx/algorithms/assortativity/tests/test_neighbor_degree.py

Improve test coverage for neighbor_degree.py

---

.github/workflows/circleci.yml

This PR will (maybe) work once the secret is added to the github secrets setting

try adding circleci artifact secret

---

networkx/algorithms/tests/test_euler.py

added tests to euler.py

---

networkx/algorithms/tree/tests/test_mst.py

fixes for #6539 @paulitapb @MridulS please have a look. 
I also have issues understanding what to do from line 337 to line 341 in https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/algorithms/tree/mst.py

Improve test coverage for mst.py

---

README.rst

remove survey banner

---

.github/workflows/nightly.yml

implements https://github.com/networkx/networkx/issues/6700
Just testing this out, still need to add a token.

MAINT: Add a github action cron job to upload nightly wheels

---

.github/workflows/nightly-release-test.yml

implements https://github.com/networkx/networkx/issues/6703
Currently using https://pypi.anaconda.org/scipy-wheels-nightly/simple which hosts the nightly wheels

MAINT: cron job to test against nightly deps every week

---

.github/workflows/test.yml

See https://github.com/scipy/scipy/issues/18603

Skip scipy-1.11.0rc1 due to known issue

---

requirements/default.txt

Update core dependencies per SPEC0

---

doc/reference/algorithms/walks.rst
networkx/algorithms/__init__.py
networkx/algorithms/components/semiconnected.py
networkx/algorithms/tests/test_walks.py
networkx/algorithms/walks.py

I created test_walks.py for the new methods,  when I tried to run them locally by `pytest test_walks.py` it gives the following output:
What should I do to succesfully run the tests? @dschult @rossbar @MridulS

Graph walks implementation by jfinkels & dtekinoglu

---

doc/reference/algorithms/index.rst

DOCS: Add walks to algorithms.index

---

networkx/algorithms/operators/all.py
networkx/algorithms/operators/tests/test_all.py

Fix for issue #6728 
Implemented the suggested fix for `intersection_all` method.

Fix intersection_all method

---

doc/README.md

…with example gallery
This implements the changes to doc/README.md discussed with @rossbar [here](https://github.com/networkx/networkx/issues/6764).

Document additional imports required for building the documentation

---

networkx/algorithms/centrality/katz.py
networkx/algorithms/distance_measures.py

Followup to #6768, fixing up a few more numpy deprecations with some very minor code tightening along the way.

Minor fixups to clear up numpy deprecation warnings

---

doc/developer/nxeps/nxep-0003.rst

1) keep create_using
2) allow edgelist generation via [~~nx.path_graph.edges_plus(9)~~] `nx.path_graph_generator(9)`

Rewrite NXEP 3

---

pyproject.toml
tools/pyproject.toml.in

Include missing package_data

---

doc/reference/algorithms/d_separation.rst
networkx/algorithms/d_separation.py
networkx/algorithms/tests/test_d_separation.py

Signed-off-by: Adam Li <adam2392@gmail.com>
Closes: #6247 
Fixes: #6216
I am opening this PR since the other one seems stalled.

[BUG] Patch doc and functionality for `is_minimal_d_separator`

---

networkx/algorithms/bipartite/projection.py
networkx/algorithms/dag.py
networkx/algorithms/minors/contraction.py
networkx/algorithms/operators/all.py
networkx/algorithms/operators/binary.py
networkx/algorithms/tree/mst.py
networkx/relabel.py
networkx/utils/backends.py

implements the idea by @eriknw in https://github.com/networkx/networkx/pull/6688/files#issuecomment-1652314158

Add preserve_all_attrs to convert_from_nx to make it concise

---

networkx/convert_matrix.py
networkx/tests/test_convert_numpy.py

Begins to resolve #6248; tagging so @rossbar and @dschult can follow along :)

Allow user to opt out of edge attributes in from_numpy_array

---

networkx/algorithms/shortest_paths/generic.py
networkx/algorithms/tests/test_time_dependent.py
networkx/algorithms/time_dependent.py

These are the new functions that I know about that didn't yet dispatch.

Add @nx._dispatch to {single_source,all_pairs}_all_shortest_paths, cd_index

---

.github/workflows/nightly-release-test.yml
networkx/conftest.py

Follow-up to #6852. Close #6846.

Unpin numpy nightly wheels

---

pyproject.toml
requirements/doc.txt

This reverts commit a068e47d92e9cf2f1f17b1363057b55d16ed7df1.

Revert "Pin sphinx<7 as temporary fix for doc CI failures (#6680)"

---

networkx/algorithms/community/label_propagation.py
networkx/algorithms/community/tests/test_label_propagation.py

Fast variant of label propagation algorithm for community detection (documented, referenced, with tests).
Vincent A. Traag & Lovro Šubelj. "Large network community detection by fast label propagation." Scientific Reports 13 (2023): 2701. [https://doi.org/10.1038/s41598-023-29610-z](https://doi.org/10.1038/s41598-023-29610-z)
The implementation should work with any type of NetworkX graph (possibly weighted).

Fast label propagation algorithm for community detection

---

examples/algorithms/plot_subgraphs.py
networkx/algorithms/smetric.py
networkx/readwrite/text.py

Minor doc build errors warnings

fix doc build errors/warnings

---

networkx/classes/reportviews.py
networkx/classes/tests/test_reportviews.py

Resolves https://github.com/networkx/networkx/issues/6264
Ready for review.

Patch view signature

---

networkx/generators/geometric.py
networkx/generators/tests/test_geometric.py

Implements the node attr part from https://github.com/networkx/networkx/issues/6753

Make position part of the API for geometric_edges

---

networkx/algorithms/graphical.py

Examples were added to the doc strings for non-graphical sequences.
Fixes https://github.com/networkx/networkx/issues/6944

Doc add nongraphical examples 6944

---

networkx/algorithms/summarization.py

Add missing parameter to snap_aggregation docstring

---

doc/_static/version_switcher.json

This PR needs to be merged to test #6930.

Add for testing new pydata-sphinx-theme PR

---

networkx/algorithms/community/asyn_fluid.py
networkx/algorithms/community/kernighan_lin.py
networkx/algorithms/community/lukes.py
networkx/algorithms/community/modularity_max.py
networkx/algorithms/community/quality.py

I added documentation about the graph parameters of the algorithms, as mentioned in issue #6849 , and similarly for a few other community algorithms not mentioned there. I also fixed some reference links and removed one unused import statement.

document graph type; add links; rm unused import

---

CONTRIBUTING.rst

Update contributing guide for changelist workflow

---

.github/workflows/test.yml
pyproject.toml

Support Python 3.12

---

.circleci/config.yml
.github/workflows/deploy-docs.yml

This should be more reliable.
CC @rlratzel

pip install nx-cugraph from git, not nightly wheels, for docs

---

networkx/algorithms/approximation/traveling_salesman.py

old PR : https://github.com/networkx/networkx/pull/7001
Closes #6745

updated docs of SA_tsp and TA_tsp

---

networkx/algorithms/operators/product.py

Fix syntax warning from bad escape sequence.

---

networkx/algorithms/distance_measures.py

#6925 improved the `resistance_distance`, but I forgot to remove the old code, which is fixed in this PR.

Remove unused code resistance_distance

---

networkx/generators/mycielski.py

There was an "off-by-one" error.

Fix error message for `nx.mycielski_graph(0)`

---

networkx/algorithms/operators/all.py

It should be a string, but the commas make it a tuple.
Also minor touchups to the message itself, but happy to revert to the original text!

MAINT: Fixup union exception message.

---

networkx/algorithms/bipartite/edgelist.py
networkx/algorithms/centrality/katz.py
networkx/algorithms/coloring/greedy_coloring.py
networkx/algorithms/covering.py
networkx/algorithms/richclub.py
networkx/algorithms/tests/test_planar_drawing.py
networkx/drawing/nx_agraph.py
networkx/generators/community.py
networkx/generators/interval_graph.py
networkx/readwrite/adjlist.py
networkx/readwrite/graph6.py
networkx/readwrite/multiline_adjlist.py
networkx/readwrite/sparse6.py

I keep seeing these, and I've behaved myself the last couple months by not doing pushing a silly formatting PR, but I'm annoyed by these so here you go.
Ideally a linter would automatically fix these.

Fix annoying split strings on same line

---

doc/_static/version_switcher.json
doc/release/release_3.2.1.rst
doc/release/release_3.2.rst

Add Python versions to release notes

---

doc/conf.py
networkx/generators/classic.py

This is just an initial PR to start working on adding some graph drawings in the graphs generators' docstrings.

DOC: Turn on inline plots in graph generators docstrings

---

networkx/utils/backends.py

Backends should have had enough time to update by now.

Remove usage of `__networkx_plugin__` (use `__networkx_backend__` instead)

---

doc/reference/algorithms/community.rst

addresses https://github.com/networkx/networkx/pull/6843#issuecomment-1855983250

DOC: add reference to fast_label_propagation_communities

---

networkx/algorithms/centrality/laplacian.py
networkx/linalg/laplacianmatrix.py

Document the walk_type argument default in directed_laplacian and similar functions.

---

doc/reference/algorithms/isomorphism.vf2.rst

Added `subgraph_is_monomorphic` and `subgraph_monomorphisms_iter` in docs

---

doc/developer/projects.rst
networkx/algorithms/community/label_propagation.py
networkx/algorithms/distance_measures.py
networkx/algorithms/similarity.py
networkx/classes/function.py
networkx/generators/expanders.py

I found these when working on #7194

Fix warnings when building docs

---

networkx/algorithms/similarity.py

Improve docs for optimal_edit_paths

---

networkx/algorithms/operators/product.py

Hi,
A very quick PR for a type in the tensor product documentation. This Fixes #7228
Thanks

Fixed typo in tensor product documentation (Fixes #7228)

---

networkx/algorithms/swap.py
networkx/algorithms/tests/test_swap.py

updated test_directed_edge_swap #5814 

---

doc/reference/algorithms/community.rst
networkx/algorithms/community/__init__.py
networkx/algorithms/community/divisive.py
networkx/algorithms/community/tests/test_divisive.py

This PR brings in the algorithms implemented in https://github.com/networkx/networkx/pull/764, cleaned up a bit.

Divisive community algorithms

---

doc/reference/algorithms/operators.rst
networkx/algorithms/operators/product.py
networkx/algorithms/operators/tests/test_product.py

Hi all,
I added the [Modular Graph Product](https://en.wikipedia.org/wiki/Modular_product_of_graphs), an interesting product providing an equivalence of cliques to isomorphic subgraphs.
Thank you

Added feature modular graph product

---

networkx/algorithms/cluster.py
networkx/algorithms/tests/test_cluster.py

ref. https://github.com/networkx/networkx/discussions/7238
- added self-loop notes in `transitivity` and `generalized_degree`
- added `test_self_loops_square_clustering`

adding self loops related docs and tests for functions in `cluster.py`

---

networkx/generators/tests/test_mycielski.py

I have increased test coverage for mycielski.py according to here at 91.67%:-
https://app.codecov.io/gh/networkx/networkx/blob/main/networkx%2Fgenerators%2Fmycielski.py
I would love a review on this and do any changes if required!

Improving test coverage for Mycielsky.py 

---

.github/workflows/nightly.yml

CI: update upload-nightly-action to 0.5.0

---

networkx/algorithms/similarity.py
networkx/algorithms/tests/test_similarity.py

add seed to `nx.generate_random_paths`

---

networkx/algorithms/approximation/clustering_coefficient.py
networkx/algorithms/approximation/distance_measures.py
networkx/algorithms/approximation/dominating_set.py
networkx/algorithms/approximation/maxcut.py

I have added the following things :- 
1. Added raises to - clustering_coefficients.py, dominating_sets.py, maxcut.py functions
2. Added examples to distance _measures.py, dominating_sets.py, maxcut.py functions
I would like a review on this and do any changes required.

Doc Improvements for Approximations Files

---

doc/developer/about_us.rst

'cause I've made a couple small commits ;)
https://github.com/networkx/networkx/commits?author=eriknw

Add eriknw as contributor

---

networkx/algorithms/tests/test_richclub.py

origin https://github.com/networkx/nx-parallel/actions/runs/8308817363/job/22739461230?pr=53
https://github.com/networkx/nx-parallel/pull/53

added `seed` to `test_richclub_normalized`

---

networkx/algorithms/tests/test_link_prediction.py

Added 2 tests to link_prediction.py according to here :- 
https://app.codecov.io/gh/networkx/networkx/blob/main/networkx%2Falgorithms%2Flink_prediction.py. 
Coverage is now at 100% ,do let me know any changes to be made. Thanks.

Add tests to link_prediction.py

---

networkx/algorithms/broadcasting.py

I reviewed all changes since https://github.com/networkx/networkx/pull/7302 to look for updates to make for the dispatch decorator. My goal is to do this kind of check before each new release.

Add dispatching to broadcasting.py

---

networkx/algorithms/connectivity/connectivity.py

Following the steps of #7036 and #7166, I have refactored the if/elif statements in ``networkx/algorithms/connectivity/connectivity.py`` with match/case statements.
There was a couple of unwanted matches since they can be replaced with ``or`` , I guess they were there because of reference equality with ``is``, but matching with name makes it easier to group similar conditions together.

Simplify flow func augmentation logic in `connectivity` module

---

networkx/algorithms/bipartite/generators.py
networkx/algorithms/bipartite/tests/test_generators.py

Fixes  #7396. Also, I added a testcase :)

Fix graph name attribute for `complete_bipartite_graph`

---

CONTRIBUTING.rst
networkx/algorithms/graph_hashing.py
networkx/readwrite/text.py

Remove repetitive words

---

networkx/algorithms/cycles.py

Including correcting the parameter description to note that all graph types (simple, directed, multi) are supported, per [this comment](https://github.com/networkx/networkx/issues/7401#issuecomment-2061988760)

Minor updates to simple_cycles docstring.

---

networkx/algorithms/approximation/tests/test_traveling_salesman.py
networkx/algorithms/tree/tests/test_branchings.py
networkx/algorithms/triads.py
networkx/drawing/tests/test_pylab.py

chore: fix some typos in comments

---

.github/workflows/test.yml

Update tests for macOS Sonoma v14

---

networkx/convert_matrix.py
networkx/tests/test_convert_pandas.py

Fix nx.from_pandas_edgelist so edge keys are not added as edge attributes and edge keys

---

networkx/generators/trees.py

Add docstring example for directed tree.

---

networkx/algorithms/shortest_paths/generic.py

Change docs of `shortest_path_length` so return is number instead of int

---

networkx/algorithms/link_prediction.py
networkx/generators/geometric.py
networkx/utils/misc.py

chore: fix some comments

---

networkx/utils/backends.py

Fixes #7505 (hopefully 🤞).
Thanks @Schefflera-Arboricola for raising this issue! I just took a guess at a solution.

Fix dispatch tests when using numpy 2

---

networkx/algorithms/operators/product.py

Fixes #7510 
I added the adjacency description as well, since that's how I remember learning it in school

strong product docs update

---

networkx/algorithms/dominance.py
networkx/algorithms/tests/test_dominance.py

Fixed the citation in `dominance.py` [Issue #7522]

---

.circleci/config.yml
.github/workflows/deploy-docs.yml

Fixes #7536 temporarily by pinning nx-cugraph to a specific commit.
@rlratzel and I will need to investigate how to fix this in a more permanent way.

Fix CI installation of nx-cugraph in docs workflow

---

networkx/generators/classic.py
networkx/generators/tests/test_classic.py

Quick leftovers from review of #7473 - nothing important!

Minor doc/test tweaks for dorogovtsev_goltsev_mendes

---

doc/developer/deprecations.rst
networkx/conftest.py
networkx/generators/tests/test_trees.py
networkx/generators/trees.py

Finalizes the removal of `random_tree`

Expires the `random_tree` deprecation

---

networkx/algorithms/efficiency_measures.py
networkx/algorithms/isolate.py
networkx/algorithms/shortest_paths/weighted.py
networkx/algorithms/tournament.py
networkx/algorithms/vitality.py

removing `#TODO` comments from algorithms that are implemented in [nx-parallel](https://github.com/networkx/nx-parallel) repo

WIP : removing parallelisation related TODO comments

---

pyproject.toml

Add changelist config

---

networkx/drawing/nx_pydot.py

Make the graph export error message better reflect which part of the graph contains data with the ":".

#7546 More detail error message for pydot

---

networkx/utils/backends.py

This is mostly aspirational for now, but it shows what's possible today and hopefully illustrates what we want to do.
CC @rlratzel @Schefflera-Arboricola
Let's see what silly Sphinx mistakes I made this time...

Add `Introspection` section to backends docs

---

README.rst

- Add hyperlinks
- Use code blocks for shell commands
- Clean up blue mark between badges
- Add some PyPI badges

Prettify `README.rst`

---

networkx/algorithms/similarity.py

Removed iteration and instead used efficient boolean masking to improve the code performance

avoid iteration and use boolean indexing

---

networkx/drawing/nx_agraph.py

Prevent `to_agraph` from modifying graph argument

---

networkx/algorithms/graph_hashing.py

See Issue #7593 for context
CC @dschult

`weisfeiler_lehman_graph_hash`: add `not_implemented_for("multigraph")` decorator

---

networkx/utils/backends.py

This PR fixes the rendering or the dispatch docs:
This PR:
On main:

Fix dispatch docs formatting

---

doc/developer/projects.rst

added nx-parallel gsoc project

---

doc/developer/about_us.rst

Adding self to contributor list
#7422

Add to Contributor List

---

examples/algorithms/plot_maximum_independent_set.py

Modified plot_maximum_independent_set.py (changed seed to 251134665)
So that it shows a better example of the graph.
Document needs to be modified
Closes #7633

Example fix for issue 7633

---

doc/conf.py

DOC: Bring back plausible for docs

---

.github/workflows/test.yml
pyproject.toml

Support Python 3.13

---

.github/workflows/test.yml

Use official Python 3.13 release

---

networkx/classes/graphviews.py
networkx/utils/decorators.py

Remove old deprecation decorator

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.rst

Add disclaimer about LLM driven PRs

---

.github/workflows/benchmark.yml
requirements/benchmarking.txt

Updating `pip install`s in benchmarking workflow

---

.github/workflows/lint.yml
.github/workflows/mypy.yml
.github/workflows/nightly-release-test.yml
.github/workflows/nightly.yml
.github/workflows/pytest-randomly.yml
.github/workflows/test.yml
INSTALL.rst
benchmarks/asv.conf.json
pyproject.toml
requirements/developer.txt

Let's wait a week or so before merging this to see if there are any major issues with NX 3.4.

Drop support for Python 3.10

---

networkx/algorithms/approximation/tests/test_traveling_salesman.py
networkx/algorithms/approximation/traveling_salesman.py

Fixes #7720. See that issue for a description of the issue and solution.

Fix TSP weight parameter issues

---

networkx/algorithms/approximation/tests/test_traveling_salesman.py
networkx/algorithms/approximation/traveling_salesman.py

fixes https://github.com/networkx/networkx/issues/7752

BUG: fixed the `if` condition in `asadpour_atsp`

---

networkx/drawing/nx_pylab.py
networkx/drawing/tests/test_pylab.py

Closes: https://github.com/networkx/networkx/issues/7735
With this addition, all existing connection styles are supported for both fancy arrows and labels.

Implement Bar ConnectionStyle for labels

---

CONTRIBUTING.rst

Add blurb about pytest-mpl dependency to contributing guide.

---

networkx/algorithms/shortest_paths/unweighted.py

* Wrap parameters in single quotes
* Simplify docstring example
* Make see-also section linkable and add dijkstra + bf
* Add 1-sentence description to each See-Also Entry

Minor updates to `single_source_shortest_path_length` docstring

---

networkx/drawing/layout.py

This was requested as a dispatchable function: https://github.com/rapidsai/nx-cugraph/issues/63

Make `forceatlas2_layout` dispatchable

---

doc/developer/about_us.rst

As title, add myself to the contributor list #4842.

[easy] Add to Contributor List

---

networkx/generators/expanders.py
networkx/generators/tests/test_expanders.py

fix typo in ramanujan branch

---

doc/developer/about_us.rst

resolves https://github.com/networkx/networkx/issues/7809

DOC: Add details about more grants

---

doc/developer/about_us.rst

Followup PR for [this comment](https://github.com/networkx/networkx/pull/7823#pullrequestreview-2600659527).
This adds NVIDIA Corporation to the list of supporters.
cc @MridulS @dschult

Adds NVIDIA Corporation to list of supporters

---

networkx/drawing/nx_agraph.py

fix #7848  'wrong example of pygraphviz_layout'

Fix pygraphviz_layout example

---

networkx/algorithms/approximation/tests/test_density.py

A minor follow-up to #7770 . Refactors tests for a bit more code reuse. The main change is to use the `generate_close_cliques` (renamed `close_cliques_example`) to create the test case for `test_big_fista_dataset`. The remainder of the changes are cosmetic (i.e. putting comments above rather than at the end of lines, etc.)
I considered turning the fns that create the test cases into fixtures, but honestly I thought it was easier to read if they're left as normal functions. Parametrizing fixtures is a nice feature, but IMO harder to understand for this particular case.
@FaroukY if you could take a quick look and make sure I'm not unintentionally breaking something intended in the original test organization that'd be great!

TST: Refactor example test case generation functions.

---

benchmarks/benchmarks/benchmark_to_networkx_graph.py
doc/developer/nxeps/nxep-0003.rst
doc/reference/backends.rst
doc/release/release_3.3.rst
doc/release/release_3.4.rst
doc/tutorial.md
examples/3d_drawing/plot_3d_animation_walk.py
examples/algorithms/plot_bipartite_motif_abcore.py
networkx/algorithms/community/local.py
networkx/convert_matrix.py
networkx/drawing/layout.py

Fix some typos

---

doc/developer/projects.rst

- Added 2 new projects for GSoC 2025.
- Added myself as secondary mentor for 2 existing projects.
- added a note about meetings in the start.
Please LMKWYT.
@dschult @MridulS @rossbar @eriknw Please feel free to add yourself as mentors to these projects.
Thank you!

added 2 projects for GSoC 2025

---

doc/developer/projects.rst

I won't have bandwidth this summer so I'll remove myself for the time being.

DOC: Remove myself from the mentor list for projects

---

networkx/algorithms/isomorphism/tests/test_tree_isomorphism.py
networkx/algorithms/isomorphism/tree_isomorphism.py

Replaces assertions with exceptions in `tree_isomorphism` input validation.

Tree isomorphism input validation

---

networkx/readwrite/graph6.py
networkx/readwrite/tests/test_graph6.py

BUG: graph6 format invariant to trailing newline.

---

networkx/algorithms/isomorphism/tree_isomorphism.py

Here are the additional changes I proposed in #7945 
- Removed `generate_isomorphism` as a standalone function and moved implementation into the spot where it was used in `rooted_tree_isomorphism`
- Re-did how the `ordered_children` are `reversed` with the goal of maintaining the current order of the returned values
Sorry if I jumped the gun @amcandio , I just happened to be looking at this when #7945 was merged and wanted to get it out while it was fresh in my head!

MAINT: Follow-up to 7945 - rm helper function

---

networkx/utils/backends.py

This followup PR for backends.py tweaks focuses on  `_will_call_mutate_inputs()`.
I'm hoping it is as performant as the original code while being more readable.
Comments add info like: 
- no nx function currently use a mutates_input dict with more than one item. 
- When `mutates_input` is a dict, it can be "not copy" or an arg_name of the function's arg that holds a node or edge attribute name to be mutated with default `None` meaning no mutation. So the code can just check if the value `is not None`.
- if new nx functions mutate graphs is other ways this code will need to change.
I think all info from previous comments is still there.
I also pulled out `len(args)` partially in the spirit of iterating over the dict, but also because it helps allow the arg-value lookups to easily visibly …

new try at will_call_mutate_inputs

---

networkx/algorithms/distance_measures.py
networkx/algorithms/isomorphism/tree_isomorphism.py
networkx/algorithms/tests/test_distance_measures.py

When working with https://github.com/networkx/networkx/pull/7945 I tried running tree_isomorphism for big (over 1000 nodes) path graphs and realized method was pretty slow even though docs claimed time complexity of ``O(n*log(n))``. After diving deep I realized center calculation was not leveraging the fact input graph was a tree, where we can use specialized algorithm with better time complexity.
This PR optimizes the time complexity of two key algorithms in NetworkX:  
1. **Tree Center Calculation** (`_tree_center`):  
- Replaces the previous approach (which involved all-pairs shortest path computations) with an iterative leaf-removal method.  
- **Time complexity improvement**: **O(N² log N) → O(N)**.  
- Updates the `center` function to use `_tree_center` when applicable.  
2. **Tree …

Improve Performance of Tree Isomorphism and Center Calculation 

---

networkx/algorithms/threshold.py

This PR adds descriptions for 
> right_d_threshold_sequence()
and 
> left_d_threshold_sequence()
functions in 
> threshold.py

Add function descriptions in the threshold.py file

---

networkx/utils/configs.py
networkx/utils/tests/test_config.py

Thanks @Schefflera-Arboricola for catching and reporting this (here: https://github.com/networkx/networkx/pull/7760#pullrequestreview-2829062783)!

Fix bug when assigning list to `nx.config.backend_priority`

---

networkx/algorithms/cluster.py

A simple solution to the problem originally posed in #8135 - so simple (and nice in the sense that it uses `triangles` instead of other alternatives like `cycles` or `triads`) that I thought it was worth documenting! Thanks @dschult for pointing it out!

DOC: Add docstring example count number of unique triangles

---

networkx/algorithms/tests/test_regular.py

This pulls out the changes to the test suite from #8139. CC @rossbar.

test: clean up `k_factor` tests

---

networkx/classes/function.py

This PR addresses Issue #8044 by improving the documentation for the `all_neighbors()` function instead of adding new methods to graph classes, as suggested by the maintainers.
The original issue reported that `G.all_neighbors(n)` fails with AttributeError on undirected graphs, while `nx.all_neighbors(G, n)` works correctly. The maintainers provided feedback that they prefer documentation improvements over adding new methods to the graph classes.
Enhanced the documentation for the existing `nx.all_neighbors()` function in `networkx/classes/function.py` with:
- **Comprehensive examples** for both undirected and directed graphs
- **Error handling documentation** (NetworkXError)
- **Detailed Notes section** explaining:
- How the function works for different graph types
- Why it provides a …

Improve docs for `all_neighbors()`

---

doc/reference/algorithms/tree.rst
networkx/algorithms/distance_measures.py
networkx/algorithms/tests/test_distance_measures.py
networkx/algorithms/tree/distance_measures.py
networkx/algorithms/tree/tests/test_distance_measures.py

This is a measure of centrality specific to trees that is based on balancing the number of nodes around the chosen node or nodes.  I believe I have successfully implemented the algorithm with O(N) time complexity.
https://en.wikipedia.org/wiki/Tree_(graph_theory)#Properties
I waffled a bit whether to put it in the `networkx/algorithms/tree/` directory, but there isn't much that it really fits with over there, and it feels like it belongs near the graph `center` algorithm.
I see that there had previously been a ticket #3525 opened, that was subsequently closed without a PR.

Implement the algorithm to find the centroid(s) of a tree

---

README.rst

Rm outdated codecov badge from README
