networkx/networkx

networkx/algorithms/centrality/betweenness.py

I noticed that you are using an ordinary list when performing BFS. If you pop(0) from a list, it takes O(N) time complexity since all the element in the list have to move 1 step to the left. However, if you use Queue module, pop() operation is done in O(1) time complexity, and it's going to be faster.

used queue instead of ordinary list

---

doc/developer/deprecations.rst
doc/release/release_dev.rst
networkx/algorithms/link_analysis/pagerank_alg.py
networkx/conftest.py

[The `google_matrix` function](https://github.com/networkx/networkx/blob/4be27b6eb32b77ccc0242368e7a5cadaaa77e7af/networkx/algorithms/link_analysis/pagerank_alg.py#L175-L268) currently returns a `np.matrix` object and uses matrix semantics internally. This PR:
1. Refactors the function to use array semantics internally, and wraps the outputs in `np.asmatrix` for compatibility.
2. Adds a `FutureWarning` to warn users that the output type will change from `np.matrix` to `np.ndarray` in NetworkX 3.0
When the `FutureWarning` expires in version 3.0, the `np.asmatrix` wrappers can simply be removed.
Alternatively, one could do away with the FutureWarning and simply change the behavior now, but IMO it's safer to provide a `FutureWarning` given the behavior differences between matrix and array …

Add FutureWarning about matrix->array output to `google_matrix`

---

networkx/convert.py
networkx/tests/test_convert_scipy.py

Removes a couple other instances of `numpy.matrix` being used internally.

A few `np.matrix` cleanups

---

networkx/algorithms/centrality/current_flow_betweenness.py
networkx/algorithms/centrality/current_flow_closeness.py
networkx/algorithms/centrality/flow_matrix.py

The `flow_matrix` module defines a `laplacian_sparse_matrix` helper-function that is used to calculate the Laplacian for the flow_betweenness centrality measures. The `laplacian_sparse_matrix` function duplicates the functionality of `nx.laplacian_matrix`, so I propose removing the former in favor of the latter.
Though not preceded by an underscore, `laplacian_sparse_matrix` is not exposed in any namespaces so I'm operating under the assumption that it is safe to remove it outright. I'm happy to deprecate it instead if others feel extra caution is warranted - LMK what you think!

Remove internal laplacian function in favor of laplacian_matrix.

---

networkx/classes/digraph.py
networkx/classes/graph.py
networkx/classes/multidigraph.py
networkx/classes/multigraph.py

Closes #4985 
On going through the code ,I found that the "nbunch" parameter has been used more than a couple of times and the description for all of those was misleading . Hence I have fixed the description of each of those as required.

Fixed inconsistent documentation for nbunch parameter in DiGraph.edges()

---

networkx/algorithms/link_analysis/tests/test_hits.py
networkx/algorithms/tests/test_node_classification_deprecations.py
networkx/drawing/layout.py
networkx/linalg/tests/test_algebraic_connectivity.py
networkx/readwrite/json_graph/tests/test_cytoscape.py
networkx/readwrite/json_graph/tests/test_tree.py

A few minor cleanups and removal of usage-patterns that will result in DeprecationWarnings in the upcoming scipy/pytest releases. These were identified by running the test suite with the numpy-1.22rc2, scipy-1.8rc1, and pytest-7.0.0rc1.
- Use the pytest `recwarn` fixture instead of `pytest.warns(None)`, which is deprecated in 7.0
- Access various scipy.sparse.linalg tools from the `scipy.sparse.linalg` namespace, since many of the sparse.linalg subpackages have been made private.

Compatibility updates from testing with numpy/scipy/pytest rc's

---

networkx/algorithms/isomorphism/matchhelpers.py
networkx/algorithms/isomorphism/tests/test_vf2userfunc.py

There is an internal function called `close` defined in `isomorphism/matchhelpers` that appears to duplicate the functionality of the built-in `math.isclose`. I think it would be an improvement to use the built-in instead.
The safest thing to do would probably be to deprecate it (or add a `__getattr__` exception) since it doesn't follow the "private" naming-convention (i.e. starting with an underscore); however, I've simply removed it in this PR since it wasn't in the `__all__` for the module. I'm leaning towards deprecating instead, but wanted to see what others thought for this particular case.
Note also that there is an internal implementation of `allclose` which mirrors the element-wise behavior of `numpy.allclose`. Switching to the `numpy` function would inject a numpy dependency …

Replace internal `close` fn with `math.isclose`.

---

networkx/algorithms/shortest_paths/weighted.py

added following feature also to bidirectional Dijkstra: The weight function can be used to hide edges by returning None.

Allowing None edges in weight function of bidirectional Dijkstra

---

doc/developer/new_contributor_faq.rst

Adds a Q&A to the new contributor FAQ clarifying that issues are not typically assigned to users.

Add an FAQ about assigning issues.

---

networkx/algorithms/community/label_propagation.py

The innermost loop of the asynchronous label propagation algorithm counts the frequencies of labels among a node's neighbours.
The current implementation initialises a collections.Counter object, loops through all neighbouring nodes, and adds each of them to the counter:
```
label_freq = Counter()
for v in G[node]:
label_freq.update({labels[v]: G.edges[node, v][weight] if weight else 1})
```
In cases where the counts are not weighted, it is much more efficient to directly update the counter with a list of labels:
```
label_freq = Counter()
label_freq.update([labels[v] for v in G[node]])
```
A dummy script shows that the direct update from a list is more than 10x faster than the loop.
```
import random
from collections import Counter
random_list = [random.randrange(100) for _ in …
```

Minor changes to speed up asynchronous label propagation for community detection.

---

networkx/generators/small.py

Added docstrings in small.py with `Description`, `Parameters`, `Returns`, `References`  sections explaining the graphs.
Fixes #5213

Docstrings for the small.py module

---

networkx/readwrite/gexf.py

Hi, we've recently put the GEXF website again into its own domain http://gexf.net/ so this documentation should be updated. Thanks!

Update gexf website link in documentation

---

doc/developer/deprecations.rst
doc/release/release_dev.rst
networkx/conftest.py
networkx/convert_matrix.py
networkx/tests/test_convert_scipy.py

The scipy.sparse array alternatives that supersede `to_scipy_sparse_matrix` and `from_scipy_sparse_matrix` are added in #5139. This is a follow-on PR to deprecate `to/from_scipy_sparse_matrix`.
Note this depends on #5139, so the history & diffs are a mess - marking as draft for now; I will clean up the history after #5139 is in.

Deprecate scipy sparse matrix conversion functions

---

networkx/algorithms/lowest_common_ancestors.py
networkx/algorithms/tests/test_lowest_common_ancestors.py

This fixes the bug in `lowest_common_ancestors` using the [change](https://github.com/networkx/networkx/issues/4942#issuecomment-919675945) proposed by @dschult.
The discussion in issue #4942 includes an extra (naive) algorithm. Should we add this as an additional option, or perhaps just use it for testing?
We should also add a test case to make sure the bug doesn't reappear.

Fix lowest_common_ancestors (issue #4942)

---

networkx/generators/tests/test_small.py

Increases the specificity of the tests for the `small` graph generators (`bull_graph`, `chvatal_graph`, etc.). Instead of testing that the number_of_nodes is correct, check that the sorted sequence of nodes is as expected (i.e. integer nodes starting from 0).

Make small graph generator node test more specific.

---

networkx/generators/small.py
networkx/generators/tests/test_small.py

Related to the question in #5266 - there are many internal uses of `make_small_graph` to generate some of the named graphs in the `generators.small` module. In these use-cases, `make_small_graph` is used to generate graphs from a list-of-list adjacency representation. This PR refactors the functions to use `nx.from_dict_of_lists`, which is a more generic function for constructing graphs from adjacency info.
The `create_using` behavior is not currently tested for the `small` graphs (except `tutte_graph`). I added a regression test to verify that the graph generators that don't currently directed outputs continue to raise an exception when `create_using` is some form of directed graph. To cut down on the amount of boilerplate, I implemented this check in a decorator; if this adds too much …

Use from_dict_of_lists instead of make_small_graph in generators.small

---

networkx/convert_matrix.py
networkx/tests/test_convert_numpy.py

A different approach to constructing the adjacency matrix with numpy. Currently, `to_numpy_array` creates an internal array with float type with `np.nan` as a hard-coded sentinel value, that is then modified/replaced in a for-loop over the edges in the graph. As noted in #5245, this causes problems for numerical weights that are not safely castable to floats, such as complex numbers.
The approach in this PR is based on [@dschult's idea](https://github.com/networkx/networkx/pull/5245#issuecomment-1008215532) to use the dtype and user-specified sentinel directly in the array construction. This would avoid the hard-coded sentinel issue and would allow users to have e.g. complex weights by specifying so in the `dtype` argument. In fact, this approach should give the users access to the full …

Refactor `to_numpy_array` with advanced indexing

---

networkx/algorithms/community/louvain.py
networkx/algorithms/community/tests/test_louvain.py

Currently `threshold` in `louvain_partitions` does not work. This is because `mod` in the while loop (lines 181-191) is not updated since it is initialized with the modularity of the first partition (where each node is in a community that only has the node).

Fix: Update louvain_partitions for threshold (update mod to new_mod in each level)

---

networkx/readwrite/json_graph/tests/test_tree.py
networkx/readwrite/json_graph/tree.py

Closes #5286.
This PR checks if the Graph is weakly connected to avoid the recursion error described in #5286 
Alternatively the issue could be solved by checking for cycles like this:
```Python3
try:
nx.find_cycles(G, source=root)
raise TypeError("G contains cycles")
except nx.NetworkXNoCycle:
pass
```
but since it doesn't really make sense to create a tree from a graph that isn't connected I feel the `is_weakly_connected` choice is better.

Add exception for unconnected graph

---

networkx/algorithms/components/strongly_connected.py

The previous implementation traversed the same edges multiple times harming the overall time complexity of the algorithm.
This is because if we look at the following lines in current implementation:
```
for w in neighbors[v]:
if w not in preorder:
```
the for loop is executed once for each neighbor of `v`, and therefor the if statement is executed a quadratic number of time per vertex (quadratic in the amount of neighbors). This can lead to cubical complexity with respect to the nodes in the worst case. Moreover, it can be proven that the complexity is `O(E^2/V)` which can be cubical on the vertices as long as the amount of edges is quadratical with respect to the amount of nodes (See complexity proof below).
In order to avoid traversing the same neighbors every time, we can store a …

Fixing Tarjan's strongly connected components algorithm implementation to have O(|E|+|V|) time complexity instead of O(|E|^2/V)

---

doc/developer/deprecations.rst
doc/release/release_dev.rst
networkx/conftest.py
networkx/linalg/attrmatrix.py

The `attr_matrix` function currently returns a `numpy.matrix`. One of the goals for NetworkX 3.0 is to remove uses of `numpy.matrix` in favor of array semantics, so this PR adds a `FutureWarning` that the return type will change from `np.matrix` to `np.ndarray` in NetworkX 3.0.
Another option would be to return a `scipy.sparse` array object (and then deprecate the `attr_sparse_matrix` function - see #5195 ). Either way, I think we definitely want to remove the usage of `np.matrix`.

Add FutureWarning to `attr_matrix` to notify users of return type change

---

networkx/algorithms/shortest_paths/generic.py
networkx/algorithms/shortest_paths/weighted.py

While going through some of the docs I saw that the documentation doesn't accurately represent what the `weight` argument can do. We can pass in a function callable to the `weight` argument too for these methods.

DOC: Update documentation to include callables for weight argument

---

networkx/algorithms/d_separation.py

This is leftover from the MyPy cleanup - there is a stray import of `AbstractSet` from the typing module that is no longer used.
Note that there is also another instance where objects from the typing module are used in `networkx/readwrite/gml` to define a `NamedTuple`. I think this syntax is more clear than the `namedtuple` constructor, so I'm inclined to leave it.

Remove unused import

---

doc/developer/deprecations.rst
doc/release/release_dev.rst
networkx/conftest.py
networkx/generators/small.py

Closes #5266.
This PR depends on #5267, so marking as draft until that's in.

Deprecate `make_small_graph` and `make_small_undirected_graph`

---

networkx/drawing/nx_pylab.py

This PR adds to the existing `draw_<layout>` convenience functions to emphasize their intended use-case and highlight using the layout functions explicitly for more involved usages. I've done this primarily by adding a short line to the extended summary explaining what the convenience function wraps, as well as a `Notes` and `See Also` section that highlight other use-cases.
This also closes #5215 by updating the parameters and simplifying the argument parsing. Technically this is a change to the signature, but I don't think it needs any sort of warning as the behavior is equivalent.
This addresses most of https://github.com/networkx/networkx/discussions/5220#discussioncomment-1961800, though there is still the matter of adding convenience functions for the missing layouts, which I …

Update `draw_<layout>` docstrings with usage examples

---

examples/algorithms/plot_rcm.py
networkx/algorithms/assortativity/correlation.py
networkx/algorithms/shortest_paths/dense.py
networkx/algorithms/similarity.py
networkx/classes/digraph.py
networkx/classes/graph.py
networkx/classes/multidigraph.py
networkx/classes/multigraph.py
networkx/convert.py
networkx/linalg/laplacianmatrix.py

I did a final check to make sure we had covered all instances of `numpy.matrix` in the codebase. From extensive grepping, there were a few left - mostly in docstrings, comments, and exception messages.
This PR corrects a few docstrings and removes as many explicit references to `numpy.matrix` objects as possible.

More numpy.matrix cleanups for NX2.7

---

networkx/algorithms/assortativity/connectivity.py
networkx/algorithms/assortativity/correlation.py
networkx/algorithms/assortativity/mixing.py
networkx/algorithms/assortativity/neighbor_degree.py
networkx/algorithms/assortativity/pairs.py
networkx/algorithms/assortativity/tests/test_connectivity.py
networkx/algorithms/assortativity/tests/test_correlation.py
networkx/algorithms/assortativity/tests/test_mixing.py
networkx/algorithms/assortativity/tests/test_neighbor_degree.py
networkx/algorithms/assortativity/tests/test_pairs.py

Raise errors instead of accepting invalid arguments silently
This would also help with less errors for folks using linters locally in their IDEs

MAINT: Cleanup assortativity module, remove unused variables

---

networkx/drawing/nx_pylab.py
networkx/drawing/tests/test_pylab.py

Closes #5294 
Improve the exception message when a user attempts to draw edge labels with multiedges that include keys (i.e. edges as 3-tuples).

Add informative exception for drawing multiedge labels.

---

doc/_templates/autosummary/base.rst
doc/developer/nxeps/nxep-0002.rst

Related to #4855 
The pydata-sphinx-theme appears to construct the sidebars elements in the docs directly from the html toctree elements. So, one way to address the "full paths in the sidebar" problem would be to modify the templates that the toctrees are constructed from for the files generated by autosummary.
This PR illustrates this approach by overriding the default autosummary template to use the specific `objname` var instead of the `fullname`. This "fixes" the sidebar problem, but also has other effects. For example, the titles of the autogenerated pages no longer include the full path, just the function/class name. Whether or not this is an improvement is in the eye of the beholder.
This is a pretty invasive solution to the problem that may have more subtle effects, since it …

Potential resolution to full paths to functions in docs

---

networkx/algorithms/link_analysis/__init__.py
networkx/algorithms/link_analysis/hits_alg.py
networkx/algorithms/link_analysis/pagerank_alg.py
networkx/algorithms/link_analysis/tests/test_hits.py
networkx/algorithms/link_analysis/tests/test_pagerank.py

Remove more characters from our codebase.
Make linters like pylint, isort a bit more happier.
Tiny subjective nitpicks around the code.

MAINT: Cleanup link analysis module, remove unused variables

---

doc/release/release_dev.rst
networkx/algorithms/smallworld.py
networkx/algorithms/tests/test_smallworld.py

Closes #5064 
The problem of #5064 regards network examples, where the calculated small-world omega metric does not lie within the bounds of the specified [-1,1] intervall. In order to check where this is coming from, I tried to find any differences in the description of the calculation from the original paper to the implemented version. The following was changed in this PR:
- Changing from nx.transitivity to nx.clustering for the clustering coefficient
- Changing default values for niter and nrand. Note: niter=5 is specified for the lattice and niter=10 is specified for the random reference. And nrand_random=50 is mentioned in the section "Random and lattice network construction" for the random reference graph. nrand_lattice is not explicitly stated, which is why I leave the default …

Keep omega within [-1, 1] bounds

---

networkx/algorithms/clique.py
networkx/algorithms/tests/test_clique.py

Finding clique has an exponential running time.
It is common to want to find maximal cliques containing a **specific set of nodes**.
There **exists actually already a function**: `algorithms.clique.cliques_containing_node`.
Unfortunately, this function `cliques_containing_node` simply computes all cliques and filters them down to the ones containing the target node. This is very naive and unusable in practice.
Yet, the original clique algorithm of `algorithms.clique.find_cliques` can be quite easily adapted to start with our desired set of nodes. 
I adapted the initialization of the algorithm in `find_cliques` to use such a set of starting nodes. `find_cliques` now accepts a `nodes` argument, the same `cliques_containing_node` has.
There is no overhead complexity compared to a normal call …

Add support for finding maximal cliques containing a set of nodes

---

networkx/generators/degree_seq.py

This warning is raised during execution of the full test suite (including slow tests) - that's why it was missed during the initial round of cleanups.

sampling from dict_keys objects is deprecated.

---

networkx/utils/misc.py
networkx/utils/tests/test_misc.py

NumPy introduced a [new interface for generating random numbers](https://numpy.org/devdocs/reference/random/index.html) back in [version 1.17](https://numpy.org/devdocs/reference/random/index.html). The random number generator machinery in NetworkX does not yet support the newer `numpy.random.Generator` interface.
This PR adds support for `numpy.random.Generator` to the random number machinery, primarily in `networkx.utils.misc` and `networkx.utils.decorators`. Now the following will work:
```python
>>> import numpy as np
>>> from networkx.utils import np_random_state
>>> my_rng = np.random.Generator(np.random.Philox(12345))
>>> @np_random_state(1)
... def foo(num, seed=None):
...     return [seed.random() for _ in range(num)]
>>> foo(10, seed=my_rng)
[0.42075435954078155, …
```

Add support for `numpy.random.Generator`

---

doc/release/release_dev.rst
networkx/algorithms/matching.py
networkx/algorithms/tests/test_matching.py

Expand tests
Change API to raise NetworkXError when matching involves nodes not in G
Update is_*_matching to 100+ times faster.
Still need to:

Update matching functions for error validation and speed

---

networkx/convert_matrix.py
networkx/tests/test_convert_numpy.py

#5250 added generic dtype support, which means arrays can now be created with structured dtypes, opening the path for creating multi-attribute adjacency matrices, i.e. what `to_numpy_recarray` does. This PR shows how this feature could be implemented within `to_numpy_array`. It takes the same basic approach as `to_numpy_recarray`, where the attribute names are taken from the names of the dtype fields. This fully replicates the behavior of `to_numpy_recarray` and would allow it to be removed, which I think is worthwhile since recarrays are not really a first-class citizen in NumPy, just a convenience layer for accessing structured arrays.
The thing that I don't like about this approach is that it makes `to_numpy_array` less readable. I don't think there's a good way to loop through …

Add structured dtypes to `to_numpy_array`

---

doc/developer/deprecations.rst
doc/release/release_dev.rst
networkx/conftest.py
networkx/convert_matrix.py
networkx/tests/test_convert_numpy.py

Depends on #5324 so marking as draft for now.
Alternatively - `to_numpy_recarray` could still be deprecated *even if* the structured dtype support is not added to `to_numpy_array`, though then there would be a loss of functionality (and the warning messages here would have to change).

Deprecate `to_numpy_recarray`

---

networkx/convert_matrix.py

Just something I noticed while working on the `to/from` numpy functions in this module.
The module docstring contains an example of creating a random DiGraph with `np.random.randint` + `from_numpy_array`. I updated the example to use `rng.integers` instead. I also made a few other minor changes:
- Making the reference to `to_networkx_graph` a link
- Demoing both `from_numpy_array` and the `DiGraph` constructor instead of `to_networkx_graph`
- Referencing scipy.sparse arrays instead of matrices.

Update `convert_matrix` module docstring

---

networkx/drawing/layout.py
networkx/drawing/tests/test_layout.py

Fixes #5211 
**Brief description of the change** 
Just by simple `print` statements between lines  as shown below, I could figure out that the measurements for the first node were off by some account , leading to the error 
```
for _ in range(len(G)):
print(theta)
r = step * theta
print(r)
theta += chord / r
pos.append([np.cos(theta) * r, np.sin(theta) * r])
```
The values of `theta` and `r` obtained on master are when number of node are `6` are as follows
```
theta = [0.175, 3.032142857142857, 3.1970427393572267, 3.353437270417054, 3.50253801680967, 3.6452916422094113]
r = [8.220459030036954, 0.9679057090890294, 0.9707783270266445, 0.9731756361695102, 0.975206931979123,
0.9769503470399769]
```
The differences are quite obvious as the first node stands out . Now this was happening because …

Fixes equidistant parameter for spiral layout whenever passed as True explicitly

---

.circleci/config.yml
doc/_templates/layout.html
doc/reference/convert.rst
doc/release/index.rst
doc/release/release_2.7.rst
doc/release/release_dev.rst
networkx/__init__.py
networkx/drawing/layout.py
networkx/drawing/tests/test_layout.py
networkx/generators/line.py
networkx/generators/tests/test_line.py
requirements/developer.txt
requirements/doc.txt
requirements/test.txt

As described in issue #5329, the line graph construction didn't work for unordered node labels. This has been fixed by numbering the nodes and ensuring a canonical representation w. r. t. the numbers (instead of attempting to compare the node labels directly).
I also included a test case that executes the lines
```python
G = nx.path_graph([1, 2, 3, "a", "b", "c"])
H = nx.line_graph(G)
```
which previously led to a TypeError.

Fix line graph construction

---

networkx/drawing/nx_pylab.py
networkx/drawing/tests/test_pylab.py

The new detection for multi-edge labels raises, if an empty dict
was passed. Before this detection that was fine, because the loop
iterating over the passed labels just passed.
Added small test as well.

[nx_pylab] fix StopIteration, if empty dict is passed for labels.

---

networkx/utils/misc.py
networkx/utils/tests/test_misc.py

Follow up to #5336.
In adding support for `numpy.random.Generator`, I somehow forgot to also modify the `create_py_random_state` function which is called by the `@py_random_state` decorator.
This was a major oversight on my part since the majority of functions that use randomness are decorated with `py_random_state`, so without this most functions in NX won't work with `numpy.random.Generator`.  For this reason, I think it'd be good to get it into a 2.7 release if possible.

Add Generator support to create_py_random_state.

---

doc/developer/nxeps/nxep-0004.rst

A proposal to switch to the `numpy.random.Generator` interface for the cases where users pass in `None`, `numpy.random` or integer values to the `seed` parameter of functions decorated with `np_random_state`.

NXEP 4: Updating the default numpy random number generator in NetworkX

---

doc/developer/deprecations.rst
doc/release/release_dev.rst
networkx/algorithms/community/modularity_max.py

Followup to #5227
Adds note to developer docs about the parameter deprecation. This should also include a release note, but that will depend on which release this is included in. If #5227 is to be included in the 2.7.2 release, then a deprecation note should be added to the 2.7.2 release note. To be discussed...

Updates to greedy_modularity_communities docs

---

doc/developer/nxeps/nxep-0004.rst

Rounds out the last few TODO's in NXEP 4:
- Adds a section linking to related discussions in `scikit-learn` regarding rng policy
- Adds a very basic implementation to help frame the discussion
- Adds discussion about alternative implementation (a package-level switch to toggle the rng backend for all random functions) that was brought up in a  previous discussion

Finish up NXEP 4 first draft

---

networkx/algorithms/bridges.py
networkx/algorithms/tests/test_bridges.py

This PR modifies `nx.bridges` to accommodate multigraphs. 
The fast bridge-finding algorithm used by `nx.bridges` ([Algorithm 1](https://arxiv.org/abs/1209.0700)) requires a simple graph. A bridge in a multigraph must have multiplicity one, so running the algorithm on the simple version of a multigraph and verifying that any discovered bridges are not multi-edges should be sufficient.

Multigraph bridges

---

networkx/algorithms/distance_measures.py
networkx/algorithms/tests/test_distance_measures.py

Issue number: [#5402](https://github.com/networkx/networkx/issues/5402)
I have updated extrema_bounding function's documentation:
- In parameters section, "eccentricities" is listed with explanation,
- In returns section, eccentricities' return value is listed
- In raises section, NetworkXError to be raised when compute parameter is passed an invalid argument is written
In extrema_bounding function, when compute parameter is passed  "eccentricities" argument, the ruled_out variable is set to an empyt set (rather than an empty dict). Moreover, if the compute parameter is not passed a valid extreme distance metric argument (not one of the 'diameter', 'radius', 'periphery', 'center', 'eccentricities'), a NetworkXError is raised with appropriate message.

Update extrema bounding method for compute="eccentricities" parameter

---

doc/developer/deprecations.rst
doc/release/release_dev.rst
networkx/algorithms/distance_measures.py
networkx/algorithms/tests/test_distance_measures.py

Closes #5415
Marks `extrema_bounding` for deprecation in favor of the `usebounds` kwarg in the related distance functions. In other words, users should use `nx.diameter(G, usebounds=True)` instead of `nx.extrema_bounding(G, compute="diameter")`.

Deprecate extrema bounding

---

doc/developer/nxeps/index.rst
doc/developer/nxeps/nxep-0004.rst

I forgot to add NXEP4 to the nxeps toctree so it wasn't showing up in the list. Also fixed up a couple intersphinx/external links that were warning during the doc build.

Add NXEP4 to developer toctree and fix broken links

---

doc/developer/deprecations.rst
doc/release/release_dev.rst
networkx/utils/misc.py
networkx/utils/tests/test_misc.py

I think this one is relatively uncontroversial, so I didn't bother opening an issue first...
There are three functions in `utils.misc` for converting nested dicts to numpy arrays. Note that these are *not* for Graph objects themselves, but for other nested dicts that are produced by networkx functions like eccentricity or shortest_path. There is one main function `dict_to_numpy_array` which handles both dicts and dict-of-dicts by calling `dict_to_numpy_array1` and `dict_to_numpy_array2` respectively. It's pretty clear form the code that `dict_to_numpy_array` is intended to be the public function while the other two are dimension-specific implementations.
This PR adds a deprecation warning to the public helpers and moves them to private functions.

Deprecate dict to numpy helpers

---

doc/developer/deprecations.rst
doc/release/release_dev.rst
networkx/conftest.py
networkx/readwrite/json_graph/node_link.py
networkx/utils/misc.py

Closes #5426
Moves `to_tuple` to a private, internal function in `json_graph.nodelink` and deprecates the public-facing function for removal in 3.0. See #5426 for discussion.

Deprecate `to_tuple`

---

doc/release/release_dev.rst
networkx/algorithms/assortativity/neighbor_degree.py
networkx/algorithms/assortativity/tests/test_neighbor_degree.py

Fixes: #5383
There was a problem with average neighbor degree calculations in a directed graph. The method was working as expected when the source argument was "out". But when the source argument was "in", it gave different results then expected. 
I have made it so that we check the source argument before deciding on which nodes are neighbors. 
Let's say we have the following directed graph: 1->2->3->4
and we are asked to find the average neighbor degree for node 2. Then if the source argument is "in", we should look for the nodes which have an edge "to" node 2 and these will be neighbors of node 2. However, if the source parameter is "out", we should look for the nodes which have an edge "from" node 2 and these will be neighbors of node 2.
I have also updated the documentation of method. …

Fix average_neighbor_degree calculations for directed graph

---

doc/index.rst

The server reset from https://github.com/networkx/networkx/issues/5433 fixed the resolution issues, but both Firefox and Chromium refuse to play nice with the .`bib` file on this machine, apparently because they're concerned with the insecurity of the `http:` target. 
Both are happy to download the .bib from `https:...`. I've changed the PDF and .bib links to `https`.

Use https links for conference.scipy.org

---

networkx/readwrite/graph6.py
networkx/readwrite/tests/test_graph6.py

I also added a few tests for the `to_graph6_bytes` method (they're very similar to those for the `write_graph6` method).
Closes #5443

Don't use graph6 with directed graphs (#5443)

---

requirements/default.txt
requirements/extra.txt

I made sympy an extra (not default) dependency as we had previously discussed not making things default dependencies until they are used a lot or for core functionality.
I also updated the minimum dependency from 1.0 to 1.10. This is a new dependency used by a single function that didn't exist before. I don't think there is any need to support a release of sympy that came out in 2016 and only claims to work on Python 3.5 or older.  (We only run on 3.8 or more recent).

Make sympy extra dep

---

networkx/algorithms/tree/mst.py

The current implementation of Prim's algorithm in `prim_mst_edges` is inefficient: it keeps iterating over all the edges in the frontier even though all the nodes in the graph have been added to the tree.
This version allows the algorithm to return as soon as the MST has been computed, allowing for a major speedup on large graphs.
Some quick benchmarks on a randomly generated complete graph of N nodes showed:
- the new version is 2x faster for N=1000
- the new version is 3.5x faster for N=2000
- no performance deterioration was measured for small graph sizes (N=5, N=50, N=100)
<details>
<summary>Click to show code used for random complete graph generation</summary>
```
import random
N = 500
G = nx.complete_graph(N)
for (u,v,w) in G.edges(data=True):
w['weight'] = …
```

Optimize prim for mst

---

networkx/algorithms/tree/tests/test_mst.py

While reviewing https://github.com/networkx/networkx/pull/5455 I realized we weren't explicitly testing a couple of unit tests with `prim`'s algorithm.

MAINT: Prim MST test didn't pass algorithm name to all unit tests

---

networkx/classes/multidigraph.py
networkx/classes/tests/test_graph.py
networkx/classes/tests/test_multidigraph.py
networkx/classes/tests/test_multigraph.py

Fixed the issue that the wrong dict factory on a MultiDiGraph was used for edge attributes (edge_key_dict_factory instead of edge_attr_dict_factory)
Extended tests to typecheck the dict factories and added a test that incorporates custom dict factories on a MultiDiGraph

Fixed wrong dict factory usage on MultiDiGraph

---

networkx/drawing/nx_pylab.py
networkx/drawing/tests/test_pylab.py

While working with edge colors I found the following problem.
Suppose we have a simple undirected graph with loops. We want to draw it with specified `edge_color` argument as follows:
```python
edges = [(1, 3), (1, 2), (2, 3), (1, 1), (3, 3), (2, 2)]
edge_colors = ['pink', 'cyan', 'black', 'red', 'blue', 'green']
H = nx.Graph()
H.add_edges_from(edges)
nx.draw(H, edgelist=edges, edge_color=edge_colors, with_labels=True)
```
With `networkx` version `2.7.2rc1.dev0` we will have quite a strange result (colors of loops do not match the declared colors):
The problem is [this part of ](https://github.com/networkx/networkx/blob/6a0b4faf09ec9d3d40ad93e2ec9b431d6bab5dc4/networkx/drawing/nx_pylab.py#L885) the `draw_networkx_edges`  function where we redefine `edge_pos`. So when we call the function …

added extra condition for fancy arrow colors

---

networkx/drawing/layout.py

Just a little cleanup to ensure the incorrect reference doesn't make it into the release.
Figuring out an appropriate reference can be done in follow up.

Rm incorrect reference from spiral_layout docstring.

---

doc/release/migration_guide_from_2.x_to_3.0.rst

I've added a list along with some paragraph-length explanations of the numpy/scipy integration work we've been doing. The goal is to give a quick summary of the changes related to numpy/scipy and explain what users can expect for NX 3.0 on this front.

Add notes about NumPy/SciPy integration to NX 2->3 migration guide

---

networkx/drawing/nx_pylab.py

I changed default arrowstyle to "-" for undirected graphs. A person can still set another arrowstyle if he/she wants. But if `arrows=True` for undirected graphs without specifying an arrowstyle, no arrow-heads will be shown as expected.

Change default value of arrowstyle for undirected graphs

---

networkx/algorithms/similarity.py
networkx/algorithms/tests/test_similarity.py

An attempt to resolve a dormant bug in the graph edit distance algorithm. The cited paper leaves the implementation of the edge matching up to the user. In the current implementation every time a new node in G1 is matched, self-edges on the newly matched node and every edge from the newly matched node to every other previously matched node in the search tree are inspected for potential edge matches in G2.
The issue arises when the first node matched has a self edge on it. The first node matched implicitly has no previous nodes matched and therefore no edges to any other nodes are inspected. This forces the self-edge to be deleted rather than being matched to an edge between two nodes.
This fix stops edge matching occurring on the first node match. Instead it is allowed only after at least …

a hack to force self edges to be ignored on the first node inspected

---

networkx/algorithms/connectivity/edge_augmentation.py
networkx/utils/decorators.py
networkx/utils/tests/test_decorators.py

See issue #5520 for details.
~Work in progress, needs doc updates.~
~Also, there's an issue where `open_file` and `not_implemented_for` are like oil and water -- specifically `not_implemented_for` is like oil and should go on top.  This isn't currently an issue in the codebase but should be addressed before it causes an obnoxious bug (see #5520 for discussion)~

De-Regression: eagerly evaluate not_implemented_for in decorated generators

---

doc/reference/algorithms/planarity.rst

A minor organizational proposal for the `planarity` docs:
The `PlanarEmbedding` class is currently included in the ref guide with the `.. autoclass` directive, which dumps the entire docstring into the planarity summary page. If we instead just include it in the `.. autosummary`, it will be listed/linked to in the same manner as `check_planarity`. The full `PlanarEmbedding` class docstring will still be autogenerated & accessible, but it is linked to rather than embedded in the main planarity page. The methods/attributes of `PlanarEmbedding` are *also* summarized instead of embedded which should further improve the digestibility of the page.
This may also help with #5090 .

PlanarEmbedding in autosummary instead of autoclass.

---

networkx/algorithms/covering.py
networkx/algorithms/tests/test_covering.py

Fixes the defect described in #5538 while maintaining the current discrepancy between `matching` APIs for bipartite and non-bipartite matching functions. bipartite returns a matching dict of mates, while non-bipartite returns the matching as a set of edges.  
That means that the corrected `min_edge_covering` still returns two types of sets -- if a bipartite matching algorithm is used, it returns a set with both 2-tuples for each edge; while if a non-bipartite matching algorithm is used, it returns a set with one 2-tuple for each edge.  It seems like this should be changed too. And I could add that to this PR or to a separate PR.
This PR also updates the documentation which e.g. currently says that this function only works for bipartite graphs.

Fix min_edge_cover in special cases (#5538)  and correct documentation

---

networkx/algorithms/bridges.py

This PR solves documentation problems of bridge algorithms. (Adding `Raise` `NetworkXNotImplemented` for directed graphs.)
@dschult I pushed another commit and reopened the PR for the following reason:
As you told, a previous PR makes bridge algorithms work for multigraphs as well. Thus, I revert my change `Raise` `NetworkXNotImplemented` for multigraphs. However, documentation did not include the raise for directed graphs. So, in my opinion, it needs to be included. I made that change.

Improve bridges documentation

---

networkx/algorithms/community/modularity_max.py
networkx/algorithms/community/tests/test_modularity_max.py

Fixes #5530 
After the community merging iteration stops, we have to check whether the number of communities is still too many for the `best_n` criteria.  If so, merge the biggest 2 components repeatedly to keep modularity as big as we can.

fix greedy_modularity when multiple components exist.

---

networkx/classes/function.py

Closes #5566 
Adding a more directly relevant example for induced_subgraph method.

replace induced_subgraph example with directly relevant example

---

networkx/algorithms/operators/binary.py

Closes #4485
I added examples that show how to update node/edge attributes after `compose` operation.
@dschult @rossbar

Add examples to compose operation

---

networkx/algorithms/community/label_propagation.py

This PR fixes a simple documentation issue noted in #5587

Fix typo in label propagation documentation

---

networkx/algorithms/flow/tests/test_maxflow.py

MyPy just released a new version a few hours ago which was causing CI failures.
The problem is related to using `sum` to concatenate functions in one of the test files. I fixed this by switching to sets instead of concatenating lists, which I think is a better fit anyways.

Fix for MyPy 0.95

---

networkx/classes/digraph.py
networkx/classes/graph.py
networkx/classes/multidigraph.py
networkx/classes/multigraph.py

In the past, degree() used to return an int or an iterator. In networkx#2458, the implementation was changed, so that the function returns a MultiDegreeView object, but the function docs weren't updated accordingly.
This incorrect return type causes issues in PyCharm type hinting mechanism - it thinks the function returns an int.
This PR updates the declared return type to be MultiDegreeView.

Update MultiGraph.degree() docs: outdated return type

---

doc/release/release_dev.rst
networkx/algorithms/bipartite/basic.py
networkx/algorithms/bipartite/projection.py
networkx/algorithms/bipartite/tests/test_basic.py
networkx/algorithms/bipartite/tests/test_project.py
networkx/algorithms/flow/tests/test_maxflow.py

- `is_bipartite_node_set` raises an exception if the node set is not distinct. This is to avoid unexpected errors or incorrect results when using bipartite algorithms, for instance `weighted_projected_graph`, where results can be out by a factor.
- `weighted_projected_graph` raises an exception if the node set is greater than or equal to the graph size. Previously the user recieved an enigmatic `ZeroDivisionError` in this case. 
Follows the discussion of #5403.
I think there's still some discussion to be had on whether `is_bipartite_node_set` should raise an exception or simply return `False` like it does for other invalid partitions.

Fixes #5403: Errors on non-distinct bipartite node sets

---

networkx/generators/spectral_graph_forge.py

In the `spectral_graph_forge` module there is an internal helper function called `_mat_spect_approx` which is used in the `spectral_graph_forge` algorithm. AFAICT, the purpose of the helper is to compute a low-rank approximation of a matrix from the eigenvectors that correspond to the `n` largest eigenvalues of the matrix.
The procedure seems straightforward enough, but I found the implementation in `_mat_spect_approx` to be quite confusing; especially since there are a lot of unused parameters in the function. There are several keyword arguments in the helper function that are never changed from their default value when the function is used, which means that the function itself has a bunch of extra logic and branches that are never hit. In addition, the interpretation of some of the …

Remove `_mat_spect_approx` in favor of simpler procedure

---

networkx/drawing/layout.py

Replaces the usage of `np.flip` with the equivalent indexing operations in the various layout functions.
In principle indexing is much faster than `flip` as there is no overhead for indexing:
```python
In [1]: a = np.random.random((10, 2))
In [2]: %timeit np.flip(a, 1)
1.62 µs ± 8.84 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
In [3]: %timeit a[:, ::-1]
169 ns ± 3.37 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
```
In practice this won't have any much positive impact on the performance of the layout functions as the coordinate swapping is unlikely to be a performance bottleneck. The main motivation for the change is more pedagogical - users are encourage to use indexing rather than the `flip` helpers when writing numpy code, so I propose to follow …

Replace np.flip with indexing in layouts.

---

networkx/algorithms/approximation/kcomponents.py
networkx/classes/digraph.py
networkx/classes/graph.py
networkx/classes/multidigraph.py
networkx/classes/multigraph.py
networkx/classes/reportviews.py
networkx/classes/tests/test_digraph.py
networkx/classes/tests/test_graph.py
networkx/classes/tests/test_multidigraph.py
networkx/classes/tests/test_multigraph.py

Use cached_property for caching the view properties of graph classes (not `G.name` which can be changed and thus should be a regular non-cached property).
The changed properties include: G.edges, G.degree, G.adj  (and G.in_edges, G.out_edges, G.in_degree, G.out_degree, G.pred, G.succ).  Added tests that multiple calls return the same object (caching is successful). 
Changes to Graph, DiGraph, MultiGraph, MultiDiGraph and AntiGraph.  Also reportviews.py had to change one `__setstate__` function.

Cache edges, degree, adj properties of Graph classes

---

networkx/algorithms/tests/test_triads.py
networkx/algorithms/triads.py

The goal of this PR is to fix the nodelist parameter for `triadic_census`. Closes #5557 
This first pair of commits add tests to show that the older code does not produce the correct results for some simple cases, and then add some changes to the algorithm to allow it to work with single node entries in the nodelist parameter.
What was needed is to revise the triads that have calculated counts instead of brute-force counts.  These are: '012', '102' and '003'.  It looks like the '003' special case code was fine.  But the '012' and '102' formulas calculated only the triads that involved an edge for a node in `nodelist`.  That means it misses any triads that have an edge between 2 nodes NOT in `nodelist` and an isolated node in `nodelist`. The case with no `nodelist` specified still works …

Fix triadic census

---

networkx/algorithms/bipartite/generators.py
networkx/algorithms/bipartite/tests/test_generators.py
networkx/generators/classic.py
networkx/generators/geometric.py
networkx/generators/tests/test_classic.py
networkx/generators/tests/test_lattice.py
networkx/utils/decorators.py

Tweak the usage of nodes_or_number in a few functions.
See #5582
That issue revealed that a few functions test the result against `int` instead of `numbers.Integral` when processing the output of the `nodes_or_numbers` decorator.  That leads to an exception when e.g. numpy integers are used to indicate how many nodes to generate in a new graph. While investigating that issue, a few other corner cases were found -- listed in #5582. And it was found that `star_graph` and `wheel_graph` don't need the decorator because they immediately call `empty_graph` on the results.
The functions changed are:
- star_graph
- wheel_graph
- lollipop_graph
- complete_bipartite_graph
Other items that might be considered (not included in this first set of changes) are:  
- ~~Consider not using …

Adjust the usage of nodes_or_number decorator

---

.github/workflows/deploy-docs.yml

Rasterio doesn't have a wheel for Python 3.10 yet and
we don't want to manually build it.

Build docs with Py 3.9

---

networkx/algorithms/moral.py

Just something I noticed when looking at #5633 ...
I don't think this validation is necessary - in fact, I don't think it's possible to hit this branch since the `not_implemented_for` will catch any non-graph inputs first and raise an `AttributeError`.

Rm unnecessary input validation from moral_graph.

---

networkx/algorithms/connectivity/edge_augmentation.py
networkx/algorithms/connectivity/tests/test_edge_kcomponents.py

No code changes, just a typo I noticed in the docs and one more typo in a comment that I found by searching the repo.

doc: fix typos in docstring and comment

---

networkx/algorithms/shortest_paths/weighted.py

Removed a comment because the argument `target` cannot be specified

DOC: remove a comment

---

networkx/classes/reportviews.py
networkx/classes/tests/test_reportviews.py

This should fix https://github.com/networkx/networkx/issues/5655
The state written to disk was recently changes in https://github.com/networkx/networkx/pull/5614 for `OutEdgeView` but the sub-classes `InEdgeView` and `InMultiEdgeView` still depended on the old read mechanism from the Graph object itself, this PR changes it to read directly from the `_adjdict` state.

Fix __setstate__ for OutEdgeView subclasses, read _adjdict from state

---

networkx/drawing/nx_pylab.py

This makes sure we don't miss the cases where we add a new
argument to a `draw_networkx_*` and not update the valid kwargs
in `draw_networkx`.
An extremely explicit way of dealing with https://github.com/networkx/networkx/issues/5658
(I can go back to old way of checking valid kwds if this doesn't look good :) )

Extract valid kwds from the function signature for draw_networkx_*

---

networkx/drawing/nx_pydot.py
networkx/drawing/tests/test_pydot.py

Maybe we should error out gracefully when there is an issue with converting a python string (name of the node in the networkx object) to a pydot Node object.
This should help out with issues like https://github.com/networkx/networkx/issues/5662, https://github.com/networkx/networkx/issues/4663
Also this way we can probably catch other parsing errors, not just `:` ones.

Error out when pydot fails to correctly parse node names

---

networkx/generators/nonisomorphic_trees.py

This PR removes a line of code that is called, but doesn't do anything.
I noticed this when looking at the code for the currently longest running tests on the CI. I was checking to see if there was any small speedups that could be made in here (nothing that I saw that really that has any major impact, there might be a way to do the first step of `_split_tree` faster with a generator, two next calls, and a try/except StopIteration). But did I notice this one line that (unless I'm really missing something) doesn't seem to do anything. Removing it speeds up the test a tiny amount (but not in a noticeable way). Either way I thought I'd make a quick PR to clean it up.
This should be an obvious review and merge. The variable `result` is assigned to but never used (it even causes flake8 to raise …

Remove unused logic in nonisomorphic_trees

---

networkx/algorithms/coloring/equitable_coloring.py

This PR adjusts equitable_coloring to compute first value lazily using iterator instead of computing whole list of values. This yields not negligible performance increase:
```bash
$ python -m timeit -s 'import networkx as nx; G = nx.circular_ladder_graph(5000)' -- 'd = nx.coloring.equitable_color(G, num_colors=4)'
1 loop, best of 5: 939 msec per loop
$ python -m timeit -s 'import networkx as nx; G = nx.circular_ladder_graph(5000)' -- 'd = nx.coloring.equitable_color(G, num_colors=4)'
2 loops, best of 5: 142 msec per loop
```

equitable_coloring: Get lazily first item instead of creating whole list

---

networkx/classes/tests/test_subgraphviews.py

pytest-randomly fails here (https://github.com/networkx/networkx/pull/4553)

Update subgraph views tests to pass with out of order execution

---

networkx/algorithms/tests/test_mis.py

I was fiddling around with [memray](https://github.com/bloomberg/memray) and maximal_independent_set tests popped up because of the randomised graph test.
Changed a couple of tests (empty_graph makes more sense to test out the seed) and removed the class structure.

Clean up maximal_independent_set tests

---

networkx/algorithms/tree/tests/test_mst.py

fixes https://github.com/networkx/networkx/issues/5692
To catch this we would have to run a CI pipeline with numpy but without scipy. I don't think we should be doing that as it takes up too much CI time, so just adding a fix and no test.

importorskip scipy instead of numpy for total spanning tree

---

networkx/algorithms/cycles.py

`Returns` -> `Yields` as `simple_cycles` is a generator. I also took the liberty to make minor adjustments to the examples to make them a bit more descriptive.

Update simple_cycles docstring w/ yields and examples

---

networkx/drawing/nx_pydot.py
networkx/drawing/tests/test_pydot.py

pydot has it's own mechanism to deal with quoting string and we shouldn't try to change that.
In https://github.com/networkx/networkx/pull/5667 I added a catch all which didn't work with the internal system of pydot as it adds quotes for some strings.
In this PR I am explicitly looking for `:` and if someone provides a node/edge name/attribute without the double quotes it will fail on the them gracefully. But this change should keep on working for people who were depending on pydot to add quotes to their strings.

Catch ':' explicitly while working with pydot

---

.github/workflows/test.yml

Reverts networkx/networkx#5680
This should no longer be necessary with Python 3.11b3 out.

Revert "Add workaround for pytest failures on 3.11b2"

---

doc/conf.py
networkx/algorithms/distance_measures.py

Closes #5714.
Sets the default documentation theme back to light mode, but adds a toggle to the navbar to allow users to try the dark mode theme if they wish. I advocate for defaulting to light mode until we've had time to investigate how well dark mode works for the docs and whether there's anything that needs to be tweaked (darkmode logo, banners, pygments (syntax highlighting) themes, etc.)

Default to lightmode for documentation

---

.github/workflows/coverage.yml

This is the longest-running job so it'd be good to have a bit
more info on the test runtimes in github actions.

Add durations flag to coverage run on CI.

---

networkx/drawing/layout.py
networkx/drawing/tests/test_layout.py

Closes #5691.
Sorts the positions by layer in the case where the `subset_key` is sortable, but still supports the case where it isn't. Note that this is an alternative to #5515 which preserves support for non-sortable subset_keys.

Recover order of layers in multipartite_layout when layers are sortable

---

networkx/classes/multidigraph.py
networkx/classes/multigraph.py

Follow-up to #5389 to further refine the docstrings for the `edges` property of the MultiGraph and MultiDiGraph classes.
Closes #4962, which was already mostly addressed in #5389.

Touchups to MG and MDG edges docstrings.

---

networkx/algorithms/dag.py

Implements the suggestion from #5712 to add an example of the `topo_order` kwarg to the `dag_longest_path` docstring.

Add example of topo_order kwarg to dag_longest_path

---

.github/workflows/pytest-randomly.yml

Adds a single workflow that runs the test suite with the tests executed in random order. This can help identify problems with poorly-designed tests.
On the one hand, adding this to CI can help improve the robustness of the test suite. OTOH, it can also introduce failures to PRs that are not related to the submitted changes.
One alternative could be to de-couple this from submitted PRs and just have a time or status-based workflow (e.g. run the workflow once a day). LMK if you think this is worthwhile to pursue!

CI: add pytest-randomly workflow.

---

networkx/conftest.py
networkx/utils/misc.py
networkx/utils/tests/test_misc.py

Remove deprecated function is_string_like

---

doc/reference/utils.rst
networkx/conftest.py
networkx/utils/misc.py
networkx/utils/tests/test_misc.py

Remove deprecated function make_str

---

networkx/utils/misc.py

Remove deprecated function is_iterator

---

networkx/utils/misc.py

Remove deprecated function utils.consume

---

doc/developer/deprecations.rst
networkx/conftest.py
networkx/convert_matrix.py
networkx/tests/test_convert_numpy.py

Remove deprecated function `to_numpy_recarray` for NX 3.0.

Rm `to_numpy_recarray`

---

networkx/conftest.py
networkx/utils/misc.py
networkx/utils/tests/test_misc.py

Remove deprecated function utils.to_tuple

---

networkx/utils/misc.py

Remove deprecated function is_list_of_ints

---

doc/developer/deprecations.rst
networkx/algorithms/chordal.py
networkx/algorithms/tests/test_chordal.py

Make chordal_graph_cliques a generator

---

doc/reference/utils.rst
networkx/conftest.py
networkx/utils/misc.py

Remove deprecated function utils.default_opener

---

networkx/readwrite/json_graph/tests/test_tree.py
networkx/readwrite/json_graph/tree.py

Removes the deprecated `attr` keyword from `tree_graph` and `tree_data`.

remove old attr keyword from json_graph/tree

---

networkx/algorithms/components/weakly_connected.py

This PR computes `is_weakly_connected` lazily. This can yield significant performance increase. E.g. for case of discrete graph:
```python
import timeit
vertices = [1, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000, 10000, 50000]
times = []
for i in vertices:
times_patched.append(timeit.timeit(stmt='nx.is_weakly_connected(G)', setup=f'import networkx as nx; G = nx.DiGraph(); G.add_nodes_from(range({i}))', number=100))
```

Compute `is_weakly_connected` lazily

---

networkx/algorithms/components/strongly_connected.py

The PR computes strongly connected components lazily. This approach avoids the need of computing all strongly connected components and yields performance increase of graphs having more strongly connected components. The following example is based on directed path graph:
```python
import timeit
vertices = [1, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000, 10000, 50000]
times = []
for i in vertices:
times.append(timeit.timeit(stmt='nx.is_strongly_connected(G)', setup=f'import networkx as nx; G = nx.path_graph({i}, create_using=nx.DiGraph)', number=100))
````

Compute `is_strongly_connected` lazily

---

doc/reference/algorithms/link_analysis.rst
networkx/algorithms/link_analysis/hits_alg.py
networkx/algorithms/link_analysis/tests/test_hits.py
networkx/conftest.py

Okay this one may require some discussion.
Should we keep both implementations which use scipy?

Make HITS numpy and scipy private functions

---

networkx/generators/geometric.py
networkx/generators/tests/test_geometric.py

Closes #5046 .
Adds input validation that raises a more clear exception in the case where any node in the input graph does not have a `"pos"` attribute, which is required by the `geometric_edges` function.
I structured this in such a way that the input validation is only done in the user-facing function so that it doesn't add overhead to all of the other geometric graph generators.

Check that nodes have "pos" attribute in geometric_edges

---

doc/reference/algorithms/swap.rst
doc/release/release_dev.rst
networkx/algorithms/swap.py
networkx/algorithms/tests/test_swap.py

I'm working on a project where I'll be swapping edges to build a baseline distribution of graphs. However, the graphs are directed, so [double_edge_swap](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.swap.double_edge_swap.html) doesn't work. I found an old issue ([#490](https://github.com/networkx/networkx/issues/490)) that mentions a three-edge swapping solution from [this paper](https://arxiv.org/pdf/0905.4913.pdf). This PR implements that algorithm, documents it, and adds tests.
A few questions:
- I named the new method `directed_edge_swap` to differentiate it from the other two swapping functions. Is that a reasonable name, or should it be `triple_edge_swap`?
- Is there a recommended method/citation style for adding references to the …

Implement directed edge swap

---

networkx/algorithms/approximation/traveling_salesman.py

SciPy 1.9 (currently in rc1) switches the default `method` for `sp.optimize.linprog` from `internal-point` to `highs`. The new method results in a slight behavior change in that `None` is returned when `linprog` fails instead of an array of zeros.
This temporary fix switches back to the scipy1.8 default method, which warns but doesn't result in an exception raise. In the longer run this needs to be revisited as it turns out our held-karp test cases all result in failed optimizations from `optimize.linprog`. I'll create a separate issue for that.
See also scipy/scipy#16466

Temporary fix for failing tests w/ scipy1.9.

---

networkx/algorithms/centrality/closeness.py

Alternative to #5695.
Update the description of the  parameter in the
closeness_centrality function to note that by default, the edge
distances (weights) are assumed to be 1, and that no input
validation is performed.
Closes #3880

Update distance parameter description.

---

networkx/algorithms/minors/contraction.py

Just came across a weird thing when trying to render with papyri,
and it looks like what was attempted here was a list enumeration, so
converting to a enumerated list instead of a code/verbatim block

DOC: Rst syntax update.

---

networkx/drawing/nx_agraph.py

Adds warnings to the write/draw/layout functions in `nx_agraph` to address #299 .
It seems some graphviz layouts are not guaranteed to be deterministic, i.e. multiple calls with the same input may result in different layouts. See https://gitlab.com/graphviz/graphviz/-/issues/1767 for details. This has caught out some NX users via the `nx_agraph` package, so this PR adds a note about the potential non-determinism of some graphviz layouts.

Add warning to nx_agraph about layout nondeterminism.

---

.github/FUNDING.yml

If someone clicks on the `<3 Sponsor` button top of the repo in https://github.com/networkx/networkx/ this change will let them directly sign up via GitHub sponsors and it will take them to https://github.com/sponsors/networkx (which we need to update).

Add direct link to github networkx org sponsorship

---

doc/reference/glossary.rst

Dear community,
This is a tiny patch though, 
point to 3.x document URL as Python 2.x has been deprecated a long time ago.
Thanks,

Point to the latest URL for the description.

---

networkx/utils/union_find.py

As suggested by @dschult in https://github.com/networkx/networkx/pull/4810, but FWIW it doesn't have that much of difference in speed. I'm +0 on this.

Speed up unionfind a bit by not adding root node in the path

---

networkx/classes/digraph.py
networkx/classes/graph.py
networkx/classes/multidigraph.py
networkx/classes/multigraph.py

We originally had copied the class factory attributes to the instance for an attempt as speed-up.
It now looks like it is a small slowdown.  But perhaps more importantly given the minor impact of these speedups is that it should be easier to read the `__init__` function without getting hung up in all the factories. And trying to figure out why we would be copying them from the class to the instance anyway.   BTW my measure of the speed up is about 15-20% of the time to create a Graph object... but that is so small to start with that it probably isn't important.  Still, if this way is slightly faster and easier to read, maybe we should do it.
This has been separated from #5836 to ease review.

Move factory attributes to the class instead of instance.

---

doc/release/release_dev.rst
networkx/algorithms/shortest_paths/weighted.py
networkx/classes/digraph.py
networkx/classes/graph.py
networkx/classes/graphviews.py
networkx/classes/tests/test_digraph.py
networkx/classes/tests/test_graph.py
networkx/classes/tests/test_multidigraph.py
networkx/classes/tests/test_special.py
networkx/generators/classic.py
networkx/generators/tests/test_directed.py

As discussed in #5796 there was a slowdown in e.g. `copy` when we changed the base classes to use `cached_property` instead of `property`.  This was due to the need to check whether to reset the cached property during `__init__`.  But it actually doesn't have to happen during `__init__`. So I have moved that check to the places in our codebase where we are replacing or changing `G._adj`/`G._succ`/`G._pred`. The danger is that we change `G._adj` and don't get an updated cached_property.  Within our codebase this is only needed inside `graphviews.py`.  It is hard to know how many users would be affected. If they swap out `G._adj` without resetting the cache property on `G.adj` then they might see some strange results where `G.adj` reports one thing while `G._adj` reports another.
We could …

Attempt to reverse slowdown from hasattr  needed for cached_property

---

networkx/__init__.py
networkx/lazy_imports.py
networkx/tests/test_lazy_imports.py
networkx/utils/misc.py

A bug in lazy_import (see #5838) or in Python's LazyLoader causes trouble for direct import of subpackages after the lazy load but before the full load. We believe this stems from a difference in how LazyLoader imports to subpackages compared to the standard import process.  We are not sure whether this will need Python LazyLoader changes or if there is a workaround locally.  
This PR removes the use of this function in NetworkX (one place) and makes the function itself private (hopefully easy for people who still want to use it to convert for the new version of NX, but discouraging others from using it until we figure out a fix).

make lazy_import private and remove its internal use

---

networkx/algorithms/lowest_common_ancestors.py

Some minor fixups I noticed while reviewing #5876:
1. The `if None in G` checks are not necessary as it is not possible to add `None` as a node to the base graph classes (as of #4892)
2. Some of the raising branches used `elif` instead of `if`.

Improve LCA input validation

---

networkx/algorithms/bridges.py
networkx/algorithms/chains.py
networkx/algorithms/tests/test_bridges.py
networkx/algorithms/tests/test_chains.py

This fixes #5636 and it is ready to merge!
1. I added the root argument in the `nx.bridges` call in the `has_bridges` function. 
2. I added tests for the `has_bridges` function since they were missing. 
3. I fixed the bridges function when there is more than one connected component. 
4. I added tests for chain decomposition function.

Fixed unused root argument in has_bridges

---

networkx/classes/graph.py
networkx/classes/tests/test_graph.py

Fixes #5893 
Add a data descriptor which resets the cached G.nodes whenever G._node is set to a new object.

Add cache reset for when G._node is changed

---

networkx/relabel.py
networkx/tests/test_relabel.py

Fixes #5896 
Currently classes like str/int and friends don't work in `nx.relabel_nodes` even though they are callable and functions do work. When we check for the attribute `__getitem__` to see if we can use a lookup to the mapping, we should also check that the `__getitem__` attribute is a bound method. If it is not, we can't use it as a mapping so we try calling `mapping` like a function.
Here's a test that ensures classes can be used to "cast" nodes to a new type.
It currently fails and this PR enables it.
```python
def test_relabel_nodes_classes(self):
G = nx.empty_graph()
G.add_edges_from([(0, 1), (0, 2), (1, 2), (2, 3)])
H = nx.relabel_nodes(G, str)
assert nodes_equal(H.nodes, ["0", "1", "2", "3"])
```

Allow classes to relabel nodes -- casting

---

networkx/algorithms/operators/binary.py

Updated docstrings for `union`, `disjoint_union`, and `compose`. resolves #5828 
- Added explanations on how these three operators differ and some hints on which use case would be appropriate.
- Added notes to link users to their other choices.
- Graph.update() was also added as an alternate choice, but no changes were made to the docstring of Graph.update().
Please review and comment.
Note: once there is agreement on the changes, they should also be rolled into `union_all`, `disjoint_union_all`, `compose_all` to be consistent.

docstring updates for `union`, `disjoint_union`, and `compose`

---

networkx/algorithms/traversal/breadth_first_search.py
networkx/algorithms/traversal/tests/test_bfs.py

Adds ```bfs_layers``` method to [breadth_first_search.py](https://github.com/networkx/networkx/blob/main/networkx/algorithms/traversal/breadth_first_search.py).
```python3
def bfs_layers(G, sources):
"""Returns an iterator of all the layers in breadth-first search traversal.
Parameters
----------
G : NetworkX graph
A graph over which to find the layers using breadth-first search.
sources : node in `G` or list of nodes in `G`
Specify starting nodes for single source or multiple sources breadth-first search
Yields
-------
layer: list of nodes
Yields list of nodes at the same distance from sources
Examples
--------
>>> G = nx.path_graph(5)
>>> dict(enumerate(nx.bfs_layers(G, [0, 4])))
{0: [0, 4], 1: [1, 3], 2: [2]}
>>> H = nx.Graph()
>>> H.add_edges_from([(0, 1), (0, 2), (1, 3), (1, 4), (2, …
```

Adds ```nx.bfs_layers``` method

---

doc/developer/deprecations.rst
networkx/conftest.py
networkx/readwrite/json_graph/node_link.py
networkx/readwrite/json_graph/tests/test_node_link.py

Signature change for `node_link` functions resolves #5787.
Attributes are passed by keyword instead of a dictionary.
Not yet complete.
*** The deprecation warnings need to be edited to include the target version for the change ***
Tests
- Tests were added to check the new signature with keywords.
- A test was added to verify that the warning message is triggered when the old style signature is used.
- Tests that check the old style signatures were kept, but were tagged with TODO comments for deletion.
Docs
- The doc strings were updated with deprecation notices
- *** The examples in the doc strings still need updating.

signature change for `node_link` functions: for issue #5787

---

networkx/algorithms/community/louvain.py
networkx/algorithms/community/tests/test_louvain.py

Fixes #5901 by yielding a list of copies-of-sets in the partition instead of the partition-list-of-sets that will be used for computing the next partition.

Fix Louvain_partitions by yielding a copy of the sets in the partition gh-5901

---

doc/reference/algorithms/traversal.rst
networkx/algorithms/euler.py
networkx/algorithms/traversal/breadth_first_search.py

The bfs_layers function seems to have been left out of the docs.
Also fixed two doc_string formatting typos.

Add function bfs_layers to docs

---

doc/developer/deprecations.rst
networkx/conftest.py
networkx/readwrite/json_graph/node_link.py

I propose to bump the deprecation expiration for the arguments of the `node_link_` functions from v3.1 to v3.2. See https://github.com/networkx/networkx/pull/5928#issuecomment-1213017715 and https://github.com/networkx/networkx/pull/5899#issuecomment-1212910911 for further discussion.
Also includes minor fixup to the warnings filter.

Bump nodelink args deprecation expiration to v3.2

---

doc/release/release_dev.rst
networkx/relabel.py
networkx/tests/test_relabel.py

Related to #5903 and #5896.
#5903 was a very nice solution to the problem identified in #5896 - i.e. the input-munging logic for the `mapping` parameter used a `hasattr("__getitem__")` check which was fragile in the case of the built-in `str`. The trick here was that `str` is a Python *type*, which both has a `__getitem__` attr, *and* is a Callable.
The logic has been updated to fix this specific case in #5903, but I'd like to propose using `isinstance` checks against ABC's if for no other reason that I personally find them slightly easier to reason about.
One major difference with this change is how the code fails. Note that previously if a user passed in an object that was neither a `Mapping` nor `Callable`, then they would eventually get an `AttributeError` when the `.get` method was …

Update mapping logic in `relabel_nodes`

---

networkx/readwrite/json_graph/node_link.py

Just an idea I had while following up on #5787 
Since we're adding these new arguments to replace the strange `attrs` munging (an obvious improvement, thanks @brocla ) I thought it might make sense to set the new args to keyword only.
Note - if we decide to do this, it should go in before the next release!

Propose to make new node_link arguments keyword only.

---

networkx/algorithms/dag.py

Added docstring improvements to lexicographical_topological_sort as discussed in issue 5681. Partially resolves #5681 
- explains effect and purpose for lexi sort in the short and long descriptions.
- add hints for fixing un-sortable nodes
- adds hint to exception msg
- Adds example to demonstrate fixing un-sortable nodes with key function

docstring update to lexicographical_topological_sort issue 5681

---

examples/drawing/plot_directed.py
networkx/drawing/nx_pylab.py
requirements/default.txt

Matplotlib 3.6rc1 just came out:
https://pypi.org/project/matplotlib/3.6.0rc1/
While preparing NX 2.8.6, I noticed we are getting errors with this prerelease. I don't have time to look at it right now, but wanted to create this PR to see if anyone else could look into it before I have a chance.
```
if ax is None:
>           if cf._axstack() is None:
E           TypeError: '_AxesStack' object is not callable
networkx/drawing/nx_pylab.py:113: TypeError
=============================== warnings summary ===============================
networkx/drawing/tests/test_pylab.py::test_alpha_iter
/home/circleci/project/networkx/drawing/tests/test_pylab.py:489:
MatplotlibDeprecationWarning: Auto-removal of overlapping axes is deprecated since 3.6 and
will be removed two minor releases later; explicitly …
```

See matplotlb 3.6rc1 failure

---

networkx/drawing/layout.py
networkx/drawing/tests/test_layout.py

Implements arf layout (Geipel 2006) which provides improvements over the traditional spring layout.
Short description
The attractive and repulsive forces (arf) layout (Geipel
2006) improves  the spring layout in  three ways. First,
it prevents congestion of  highly connected nodes due to
strong forcing  between nodes.  Second, it  utilizes the
layout space  more effectively by preventing  large gaps
that  spring layout  tends  to create.  Lastly, the  arf
layout represents symmmetries in  the layout better than
the default spring layout.
Example:
<details>
<summary>Plotting code </summary>
``` python
import networkx as nx, numpy as np, matplotlib.pyplot as plt
from functools import partial
graphs = [nx.krackhardt_kite_graph(),
nx.florentine_families_graph(),
nx.grid_graph((5,5)), …
```

Arf layout

---

networkx/algorithms/approximation/steinertree.py
networkx/algorithms/approximation/tests/test_steinertree.py

Re discussion #5352 
This PR adds two new approximation algorithms for the Steiner tree problem: one from Wu et al. (1986), and another from Mehlhorn (1988). Both are asymptotically faster than the existing approximation from Kou et al. (1981).
One thing I haven't done is change the default algorithm from Kou's, although I think this would be desirable. I suggest setting Wu's as the default, as although the worst-case runtime is slower than Mehlhorn's, in practice I've found it to be faster. This is probably down to Mehlhorn requiring in all cases the shortest paths from all terminal nodes to all other nodes to be calculated; this is not the case with Wu's algorithm.
Any comments and feedback appreciated.

Add Mehlhorn Steiner approximations

---

networkx/classes/function.py
networkx/classes/tests/test_function.py

is_path currently raises a KeyError if a node in the path provided does not exist.
The more appropriate outcome would be a False output, since the path provided is not, in fact, a path.
G = nx.MultiDiGraph()
assert nx.is_path(G,[0,1]) == False
To address this, I revised the is_path method to check if each element on the tentative path is a nodem namely by calling has_node on each iteration.

Improve is_path

---

doc/release/release_dev.rst
networkx/classes/function.py
networkx/classes/tests/test_function.py

Just a few minor changes I'd like to propose to follow-up on #5943:
- A few docstring/formatting touchups
- Condense conditionals using `or`
- parametrize test and remove redundant case
Nothing critically important, feel free to ignore!

Minor docstring touchups and test refactor for `is_path`

---

doc/conf.py
doc/index.rst

By default, the latest `pydata-sphinx-theme` only shows 5 header link items in the navbar, placing the extra in a dropdown menu under "More". In our case, this ended up hiding the `Gallery` link, which I wanted to bring back out to make sure it as always visible. Therefore I made two changes:
1. Keep header links always visible by increasing the number allowed from 5->7
2. Re-ordered the links so that `Gallery` is before the developer guide link and the release notes.

Update documentation header links for latest pydata-sphinx-theme

---

networkx/algorithms/isomorphism/vf2pp.py

Switch imports of vf2pp_helpers to relative imports. This should fix the current doc build/deploy error (tested locally).
I think there's multiple things going on here: 1) `vf2pp_helpers` doesn't have an `__init__.py` and therefore isn't a package. However, that's not the *only* thing... `vf2pp_helpers` isn't accessible from the `__init__.py` of any of the parent packages (e.g. algorithms, isomorphism), so doing absolute imports from the root of the directory shouldn't be expected to work. In principle, this was by design as we don't want to expose the `vf2pp_helpers` directly to users.
As for why this wasn't caught in CI... the imports are generally hard to test reliably as it's affected by import order. It's *possible* that the `pytest-randomly` workflow would've caught this down the …

Switch to relative import for vf2pp_helpers.

---

setup.py

Follow up to #5973, which didn't actually fix the problem with the doc build.
After more debugging, I determined that the problem was the `vf2pp_helpers` subpackage wasn't actually included in the wheel. I missed this in my first round of debugging that led to my mis-diagnosis in #5973 likely from accidentally using `pip -e` and still building the docs from the source directory. We should probably add/update at least one CI job to not use editable installs to catch this problem in the future, though it's worth noting that the `vf2pp_helpers` subpackage appears to be unique - i.e. there are no other "helper" subpackages that are *not* included in an __init__.py somewhere.
In the slightly longer term, it might be better to refactor the `vf2pp_helpers` subpackage into a submodule instead …

Add vf2pp_helpers subpackage to wheel

---

networkx/algorithms/components/biconnected.py

Index costs the size of the stack, which is always greater than or equal to the size of the newly discovered biconnnected component, and in general much larger. Updated to use edge stack as a stack instead of indexing, which has a cost of the size of the newly discovered biconnencted component as opposed to the size of the entire stack .

Enhance biconnected components to avoid indexing

---

.github/workflows/coverage.yml
.github/workflows/lint.yml
.github/workflows/mypy.yml
.github/workflows/test.yml

This addition to the workflow is intended to cancel running jobs within a workflow when new changes are pushed up. This should help in situations where there are a lot of rapid pushes to a PR, which can trigger a long queue of CI jobs to build up. 
See: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-fallback-value
See also: scipy/scipy#15634 and numpy/numpy#21110. And thanks to @HarshCasper for calling attention to this improvement.

Add concurrency hook to cancel jobs on new push.

---

networkx/algorithms/operators/all.py
networkx/algorithms/operators/binary.py
networkx/algorithms/operators/tests/test_all.py

Hi 👋 
This PR makes `union_all`, `disjoint_union_all`, `compose_all`, `intersection_all` generator friendly, allowing for a much smaller memory footprint when dealing with many graphs.
We have a bunch of large, dense, and overlapping graphs on disk. To create a composition, they would all have to be loaded into memory at the same time. Then, `G.nodes` and `G.edges` are called on all of them without intermediate garbage collect, further increasing memory footprint (this is where we hit a `MemoryError` on a 64GB machine after some iterations in the `compose_all` loops).
This rewrite:
- still allows the user to pass a list of graphs
- now also allows a generator that loads graphs into memory just-in-time (what we use to avoid `MemoryError`)
- allows garbage collector to deallocate and …

Make all.py generator friendly

---

.github/workflows/pytest-randomly.yml

Prevents this job from running on forks, which should prevent email notifications being sent to fork owners when the job fails. Thanks @mjschwenne for pointing this out.
I grabbed the syntax for this from: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif

Only run scheduled pytest-randomly job in main repo.

---

networkx/algorithms/approximation/tests/test_steinertree.py

The weight in the true test result should match the weight in the graph defined on line 24.

Fix steiner tree test

---

doc/reference/utils.rst
networkx/algorithms/dag.py
networkx/utils/mapped_queue.py
networkx/utils/tests/test_mapped_queue.py

- Added Tests
- test __gt__ in _HeapElement when priorities are tied.
- test dictionary input in MappedQueue
- test tied priorities
- verify exception is raised for incomparable elements
- tests for the `pop` method when dictionaries are the input.
- Fixed `__gt__` bug
- Added the exception for incomparable elements. Include a helpful error message.
- Added Examples
- show that incomparable elements will fail
- show how to fix incomparable elements by assigning priorities via a dict.
- Update the doc_string descriptions to explain assigning priorities via a dict.
- Added a reference to `MappedQueue` in the `networkx/reference/utils.rst` file.  
I needed to check the formatting of the doc_string. This was the only way I 
knew to get `numpydocs` to format the doc_string. I can take it back …

Bugfix /docfix for MappedQueue, issue 5681

---

networkx/drawing/tests/test_pylab.py
networkx/generators/tests/test_expanders.py

A few minor fixups to the test suite. I noticed these from a few warnings that were popping up when running the test suite in random order.
- 68144a9 cleans up a `.A` call on a sparse array that was missed during the general sparse cleanup (though the fact that this warning is only raised when the test suite is run in random order means we probably need to take a closer look and ensure the tests in this file are all being run!)
- 7978bad fixes crosstalk between pylab tests from the fact that a axis object created when using the `pyplot` interface for matplotlib persists across tests, since the default axis object for most of the nx drawing commands is `plt.gca`. Many of these had been fixed previously.

Fix warnings from running tests in randomized order

---

doc/release/release_dev.rst
networkx/algorithms/shortest_paths/generic.py
networkx/algorithms/shortest_paths/tests/test_generic.py

The code for `average_shortest_path_length()` contains a mathematical error: it computes a value for directed graphs that are just weakly connected instead of strongly connected. This approach has no mathematical sense: for example, the current code in the case of the directed graph 0 → 1 returns 1/2, because it adds a single distance $d(0,1)=1$ but then divides by the number of possible distances (2).
In other words, the current code adds $k$ lengths (where $k$ is the number of reachable pairs) and then divides by $n(n-1)$. It is not an average in any possible mathematical sense when $k\neq n(n-1)$.
This fix simply change the wrong test for weak connectivity to a test for strong connectivity, updating the documentation.
A sensible notion of diameter for directed graphs that are not …

Fixed test for average shortest path in the case of directed graphs

---

networkx/generators/tests/test_expanders.py

The main update is splitting the margulis_galil_gabber test into two: one that doesn't depend on numpy/scipy and one that does. In principle this is a minor improvement as previously the entire test was skipped if the dependencies were not installed.
There are some other minor tweaks, like using functions from the `nx` namespace (so this now doubles as a test of the public API); and parametrizing the tests.
IMO this (along with some other testing, see [here](https://github.com/networkx/networkx/issues/6026#issuecomment-1273627062)) is sufficient to close #6026

Minor updates to expanders generator tests

---

networkx/algorithms/flow/maxflow.py
networkx/algorithms/flow/tests/test_maxflow.py

In maxflow.py, I changed ``` flow_funcs ``` to ``` flow_funcs_without_cutoff  ``` and also updated the flow functions that support *cutoff*. In text_maxflow.py, I added  ``` flow_funcs_without_cutoff  ```. 
This was discussed in https://github.com/networkx/networkx/issues/6081. 
Closes #6081

issue #6081: allow cutoff functionality for flow functions

---

networkx/readwrite/gml.py
networkx/readwrite/tests/test_gml.py

Updates the "stringization" functionality in `gml.py` to allow storing empty lists or tuples as node attributes.
This was formerly disallowed, but AFAICT there's nothing in the GML standard (pdf only) that prohibits empty lists/tuples from being used. This would fix the issue raised in #4953 directly, without having to use the deprecated `literal_stringizer` function.

Update GML parsing/writing to allow empty lists/tuples as node attributes

---

examples/drawing/plot_eigenvalues.py

Fixes up the `plot_eigenvalues` example to use best-practices when creating a dense array from a sparse array.

Replace .A call with .toarray for sparse array in example.

---

networkx/algorithms/tests/test_richclub.py

Added more tests to improve test coverage for algorithms in richclub.py. Specifically added tests to ensure the right exception is raised when calculating rich club coefficients for self-loop graphs.

Improve test coverage for algorithms/richclub.py

---

networkx/drawing/nx_pylab.py
networkx/drawing/tests/test_pylab.py

Closes #5857 and #5694
`draw_networkx_edges` has a few keyword arguments that only apply when FancyArrowPatch (FAP) objects are used to represent the edges (as opposed to a LineCollection (LC)). The tricky part is that the logic for determining which object is used is not immediately clear to the user. By default, LCs are used when the input graph `G` is undirected, and FAPs are used when `G` is directed. The reason for this is that LC are *much* faster to draw than FAPs, so using LCs where possible greatly enhances the ability to visualize graphs with many edges. The default behavior can be overridden with the `arrows` kwarg: `arrows=True` will force `draw_networkx_edges` to use FAPs even if `G` is undirected. This may make the visualization much slower, especially if there are a lot of …

Warn on unused visualization kwargs that only apply to FancyArrowPatch edges

---

networkx/algorithms/dag.py
networkx/algorithms/tests/test_dag.py

Fixes #5987 
Personally, I would find it useful to return the edge that was calculated to be the best in addition to the node to avoid having to recalculate it again whenever traversing the path, but that would break backwards compatibility with code that is using MultiDiGraphs for unweighted longest pathing by changing the return type, so I have not included it in my fix. A potential other fix would be to create separate functions for MultiDiGraphs and add a warning to dag_longest_path and dag_longest_path_length when a MultiDiGraph is supplied—preserving backwards compatibility while notifying developers about the function's inability to compute with weights.

Fix weighted MultiDiGraphs in DAG longest path algorithms + add additional tests

---

CONTRIBUTING.rst

Update the new contributor documentation to branch off from main. This will make sure people are creating branches from their local copy of main instead of the current working branch.

DOC: Specifically branch off main, instead of current branch

---

networkx/algorithms/connectivity/connectivity.py
networkx/algorithms/connectivity/disjoint_paths.py

In `local_edge_connectivity` and `local_node_connectivity` from **connectivity.py** the cutoff description implies that only `edmonds_karp()` and `shortest_augmenting_path()` support cutoff. That is not true. Now those algorithms are given as examples of flow functions that allow cutoff. I tried to keep the description as general as possible and reference to [Flow](https://networkx.org/documentation/stable/reference/algorithms/flow.html) as the source of truth so in the future, if new flow algorithms are added there's no need to change this. 
Also changed the cutoff description in `edge_connectivity` from **connectivity.py** to match `local_edge_connectivity` and `local_node_connectivity` cutoff description. 
Finally in **disjoint_paths.py** added a reference to …

Fix doc inconsistencies related to cutoff in connectivity.py and disjoint_paths.py

---

networkx/algorithms/approximation/traveling_salesman.py
networkx/algorithms/matching.py
networkx/algorithms/tests/test_matching.py

Another deprecation removal for 3.0 - the `maxcardinality` parameter of `min_weight_matching` in this case.

Remove deprecated maxcardinality parameter from min_weight_matching

---

doc/release/report_functions_without_rst_generated.py
networkx/algorithms/core.py

It looks like we missed the `find_cores` function when removing deprecated code for NetworkX 3.0. The likely reason it was missed is that we (I) *also* forgot to add the deprecation to the NX 2.7 release notes.
Fortunately, the deprecation warning was being raised, so hopefully any users who were relying on it at least got some notification when running their code. There are a couple things we could do here:
1) Just go ahead an remove it (as proposed here) even though we missed it in the release notes
2) Add the deprecation to the release notes for 3.0 and push back the actual deprecation to 3.2
3) Remove it now, but update the module `__getattr__` for the top-level `__init__.py` to advise users to use `core_number` instead.
1 is the least work, but I'm happy to update the module …

Remove deprecated `find_cores`

---

networkx/algorithms/tests/test_matching.py

Black ran. Added some tests in test_matching.py to hit some untested conditionals. Should get coverage up to around 97 from 94.

Increased test coverage algorithms/matching.py

---

networkx/algorithms/tests/test_lowest_common_ancestors.py

This pull request will fix issue #5863.
The method names of the test classes have been modified to depict what the method is testing.
The modifications are for networkx/algorithms/tests/test_lowest_common_ancestors.py

Renamed test functions in test_lowest_common_ancestors

---

networkx/linalg/algebraicconnectivity.py

I added an example for `fiedler_vector` in `algebraicconnectivity.py`. In the example, I use the Fiedler vector to partition a connected graph.

Add example for fiedler_vector

---

networkx/algorithms/tests/test_cycles.py

Added test for cycle_basis for graphs with self loops.

Improve test coverage for cycles.py

---

networkx/algorithms/approximation/connectivity.py
networkx/algorithms/connectivity/kcutsets.py

In all_pairs_node_connectivity added an example. 
Also in `all_node_cuts` added a missed link to `edmonds_karp`.

Added an example in all_pairs_node_connectivity 

---

networkx/algorithms/tests/test_swap.py

Added tests in test_swap, hitting edge cases when self loops or small cycles are hit, or when no edges are available to be swapped.

Swap.py coverage to 100

---

networkx/algorithms/centrality/tests/test_current_flow_betweenness_centrality.py

Hi @MridulS, please review. I also did not explicitly create an issue for it.

Improve test for algorithms in current-flow-betweenness.py

---

networkx/generators/tests/test_community.py

Adds testing coverage in community.py. Only branch not tested is the return statement of a nested function, which I do not know how to test. Couple of best practice questions. 
1. When testing internal functions, is it OK to simply call them directly, or should they be covered exclusively by forcing another function to call them? 
2. When forcing an ImportError, what is the best practice, I used sys.modules, but am unsure of other (better) ways.
Let me know of any other issues
#6184

Completed Testing in community.py resolves issue #6184

---

networkx/classes/multidigraph.py
networkx/classes/multigraph.py

This PR is for https://github.com/networkx/networkx/issues/5854

Add ThinGraph example to Multi*Graph doc_strings

---

networkx/linalg/spectrum.py

Added an example where the laplacian_spectrum is used to get the number of eigenvalues of the Laplacian matrix that are zero to count the number of connected components of a graph. 
Also added a missed link to to_numpy_array

add laplacian_spectrum example

---

networkx/algorithms/bipartite/redundancy.py

Use dict.keys() for set operations rather than explicitly creating sets, as recommended in the comment.

Minor Python 2 cleanup

---

networkx/algorithms/tests/test_swap.py

There is a valid edge swap between (0, 1) and (2, 3) for this case.
Closes #6220

Rm incorrect test case for connected edge swap

---

networkx/algorithms/swap.py

Inside `connected_double_edge_swap`, one call to `nx.utils.discrete_sequence` does not give the `seed` as input which will mess up trying to make it deterministic by providing a seed.  
This PR adds `seed` to that function call. 
I haven't been able to make this into a test -- and I spotted it while going through the code... not due to a behavior I didn't expect.

add missing `seed` to function called by `connected_double_edge_swap`

---

networkx/algorithms/shortest_paths/astar.py
networkx/algorithms/shortest_paths/tests/test_astar.py
networkx/algorithms/shortest_paths/weighted.py

This matches the Dijkstra's weight interface, which ignores edges with a weight of `None`.
https://github.com/networkx/networkx/blob/d2ceeb69ab0580a84a3b13266e6bd32e99da0232/networkx/algorithms/shortest_paths/weighted.py#L838
Documentation for this feature is copied from `dijkstra_path`.
https://github.com/networkx/networkx/blob/d2ceeb69ab0580a84a3b13266e6bd32e99da0232/networkx/algorithms/shortest_paths/weighted.py#L134

Hide edges with a weight of None in A*.

---

networkx/algorithms/traversal/depth_first_search.py
networkx/algorithms/traversal/tests/test_dfs.py

Fixes #6239
The new reporting of edges labels them as "reverse-depth_limit" rather than simply "reverse" to make clear that they exist due to cutting off the exploration due to reaching the depth_limit.

Add dfs_labeled_edges reporting of reverse edges due to depth_limit.

---

networkx/generators/classic.py

As we discussed last summer, some surprising results can occur if you input duplicate nodes in functions that use the nodes_or_number decorator. We decided to leave them in the code (some people might rely on them and they don't seem to be a problem for users).
For example:  nx.complete_graph([1, 1]) returns a graph with a self-loop.  nx.complete_graph([1, 2, 2, 3, 3, 3]) is the usual complete_graph on 3 nodes with selfloops added for node 2 and 3. 
This PR adds a warning to the doc_strings for these functions just so the users have a hint that duplicate nodes in the list of nodes can cause unusual results.

Warn users about duplicate nodes in generator function input

---

networkx/drawing/nx_pylab.py

This inconsistency between the docs and actual behaviour came up in two StackOverflow questions:
https://stackoverflow.com/a/74106862/20148180
https://stackoverflow.com/q/74622898/10693596

doc: clarify allowed `alpha` when using nx.draw_networkx_edges

---

networkx/algorithms/lowest_common_ancestors.py
networkx/algorithms/tests/test_lowest_common_ancestors.py

Fixes #5209 by checking that LCA and tree_LCA work for MultiDiGraphs.
Removes NotImplementedFor exception in these cases. Adds tests.

Allow MultiDiGraphs for LCA

---

requirements/developer.txt
requirements/doc.txt
requirements/release.txt

and update release requirements
TODO: math roles aren't rendered with sphinx 5.3
See https://github.com/sphinx-doc/sphinx/issues/10944 for example.

Pin to sphinx 5.2.3

---

networkx/algorithms/simple_paths.py
networkx/algorithms/tests/test_simple_paths.py

Current version of `is_simple_path` fails with `KeyError` if the first element of the node list is not in the graph.
Resolves https://github.com/networkx/networkx/issues/6271, by returning `False` if any node in the provided path is outside the graph.

Update simple_paths.py: consistent behaviour for `is_simple_path` when path contains nodes not in the graph.

---

doc/release/release_2.8.8.rst

Fixes https://github.com/networkx/networkx/issues/6297

Correctly point towards 2.8.8 in release notes

---

networkx/algorithms/centrality/katz.py

The formula mentioned in this comment (`y^T = Alpha * x^T A - Beta`) is incorrect as the formula in the code has a `+` sign instead!

Fix typo in Katz.py

---

networkx/algorithms/clique.py
networkx/algorithms/isomorphism/isomorph.py
networkx/algorithms/tests/test_clique.py

This is a proposal in two parts:
1. Update the `find_cliques` docstring with examples of how to compute various quantities from the returned maximal cliques, and
2. deprecate the four helper functions that wrap these examples.
I've lumped this all into one PR just to keep the discussion all in one place, but I'm happy to split out the docstring example (commit 8602796) from the other commits which deprecate the helper functions.
There was only one internal usage of one of the helpers in `could_be_isomorphic`.
Closes #6180

Add clique examples and deprecate helper funtions

---

doc/release/release_3.0.rst

@jim22k and I both contributed code via #6000. I'm guessing squash merges hid our contributions.

Update release_3.0 authors (add Jim and Erik)

---

CONTRIBUTING.rst
doc/conf.py
doc/developer/new_contributor_faq.rst
doc/developer/nxeps/nxep-0004.rst
doc/developer/projects.rst
doc/reference/algorithms/centrality.rst
examples/algorithms/plot_betweenness_centrality.py
networkx/algorithms/approximation/steinertree.py
networkx/algorithms/centrality/laplacian.py
networkx/algorithms/triads.py
networkx/classes/backends.py
networkx/drawing/nx_latex.py
networkx/readwrite/gexf.py
networkx/readwrite/graphml.py

Just some minor doc formatting fixups to get rid of the 25+ sphinx warnings that had accumulated.

DOC: Minor formatting fixups to get rid of doc build warnings.

---

networkx/generators/classic.py
networkx/generators/tests/test_classic.py

switch create_using handling to `isinstance(_, type)` instead of `type(_) is type`
Fixes: #6243

Improve handling of create_using to allow Mixins of type Protocol

---

networkx/algorithms/centrality/betweenness.py

I encountered this DeprecationWarning today. This change was missed in #4602

Remove an instance of random.sample from a set (deprecated in Python 3.9)

---

.pre-commit-config.yaml

I'm seeing a bug in the install of isort with pre-commit. Looks Poetry-related. Bumping the isort version solves it.
```
pre-commit run --all-files
[INFO] Installing environment for https://github.com/pycqa/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/dan/.cache/pre-commit/repo4zn7v0sy/py_env-python3.10/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
Processing /home/dan/.cache/pre-commit/repo4zn7v0sy
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Preparing metadata (pyproject.toml): started …
```

bump pre-commit hooks (and fix CI)

---

.pre-commit-config.yaml

The latest `isort` has a dependency bug that borks development environments with the latest 5.12 isort precommit hooks installed. I just ran into this on Python 3.10 - see pycqa/isort#2083.
Pinning isort to 5.11.5 in the pre-commit config worked for me locally.

Fix pre-commit on Python 3.10

---

networkx/algorithms/approximation/__init__.py
networkx/algorithms/community/__init__.py

On the approximation main page, there was a warning about how to import the functions because they are not part of the `networkx` base namespace. As discussed in another PR, warnings are unsuitable for this purpose. So I change it to delete the warning.

Delete warning in approximation documentation

---

doc/_templates/layout.html

This gives us an anonymous way of tracking usage of our documentation website. By this PR we will only be able to track usage of the latest dev website, which I think is a good start.
This uses the instances hosted by the Scientific Python project.
Should we also put up some disclaimer or note in our README that we are using this?

Add Plausible Analytics to our docs

---

networkx/readwrite/text.py

Very minor tweak to conform to the numpydoc standard and get rid of UserWarnings during the doc build.

Fix docstring heading title.

---

.pre-commit-config.yaml
networkx/algorithms/centrality/betweenness_subset.py
ruff.toml

Use ruff's isort and pyupgrade in the pre-commit pipeline.
All works except there is a ruff-isort change in `networkx/algorithms/centrality/betweenness_subset.py`, not a 100% sure if this is an issue or not. I'm fine either way.

Start using ruff for pyupgrade and isort

---

CONTRIBUTING.rst
doc/Makefile
doc/conf.py

There's currently no info in the contributor guide about how to build/view the documentation locally. This PR adds the minimal instructions to do so.
This also necessitated a minor reorganization of the headings for the contributor guide, which makes the diff look scarier than it actually is. I've regrouped the `Adding tests` and `Image comparison` sections as subsections under `Testing`; and grouped `Adding References` and `Adding Examples` as subsections of the newly added `Documentation` section.

Add documentation building to contributor guide

---

.github/workflows/deploy-docs.yml

Follow-up for #6446 .
According to the warnings in the [deploy action log](https://github.com/networkx/networkx/actions/runs/4254090726), the [parameter names for the gh-pages deploy action](https://github.com/JamesIves/github-pages-deploy-action#optional-choices) changed with the version bump. This PR should fix those and get the deploy job running again.

Reset deploy-action param names for latest version.

---

networkx/algorithms/similarity.py

Made some subjective maintenance changes to similarity.py and fix https://github.com/networkx/networkx/issues/5532
I have also used dataclasses for the 2 classes used in similarity.py as the only usecase here was to store state.

Clean up similarity.py and use dataclasses for storing state

---

.circleci/config.yml
.github/workflows/deploy-docs.yml

This has been discussed before and it's currently a blocker of moving to myst_nb from nb2plots for code block directives in our documentation. Opening this just so we can get the ball rolling on this one and have a decision :)

Remove pdf latex builds of docs

---

networkx/generators/classic.py

Adds a more detailed docstring for this generator, including Parameters, Returns and Examples section. The info in the docstring is derived from a quick scan of referenced paper on arXiv.

Add docstring for dorogovtsev_goltsev_mendes generator

---

networkx/classes/backends.py
networkx/classes/tests/test_backends.py

The `_dispatch` decorator assumes that the first argument is a positional argument.
This PR allows `G` to be provided as a keyword. Note that `G` is still expected to be
the first positional argument. This only affects how people can call it: 
`nx.pagerank(G=G)` and `nx.pagerank(G)` should be the same.
Fixes #6458

tweak _dispatch to allow G keyword. Add test.

---

networkx/algorithms/flow/tests/test_mincost.py
networkx/algorithms/shortest_paths/tests/test_weighted.py
networkx/algorithms/shortest_paths/weighted.py

In reference to #6465, fixed the `negetive_edge_cycle` function by handling an empty graph. Also added `test_negative_cycle_empty` test function in `test_weighted.py`.

Fix negative edge cycle function raising exception for empty graph and added test function

---

networkx/classes/tests/test_graph.py

I started to encounter an error with this when testing `graphblas_algorithms`, b/c it was trying to operate on weakly-reference objects that no longer exist. I have no other context about this, but this change seems "safe" to me.

Ignore weakrefs when testing for memory leak

---

networkx/classes/backends.py

This is a simple follow-up to #6471, and, as in that PR, this fix is short term. We would like to find a more elegant, robust solution (probably after nx 3.1).
I sometimes forget there are two versions of `_dispatch`, and this PR fixes the one that gets used when `NETWORKX_GRAPH_CONVERT` environment variable is set. NetworkX does not yet test `test_override_dispatch`, so it's not easy to add a test, but it gets used by external backends such as `graphblas_algorithms`. Ideally, we should test this in NetworkX, which will require calling subprocess in a test with an environment variable set.
CC @MridulS @jim22k

tweak `test_override_dispatch` to allow G keyword

---

networkx/algorithms/shortest_paths/tests/test_astar.py

I found that the [test coverage for astar.py](https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/algorithms/shortest_paths/astar.py) is currently 91%.
I have added test cases for the two exceptions that can possibly be raised by the astar_path and astar_path_length methods.
The test coverage has now reached 100%.

Improve test coverage for astar.py

---

networkx/algorithms/shortest_paths/weighted.py

Added example in the docstring for computing edges of shortest path in a MultiGraph in `dijkstra_path` method in weighted.py based on the discussion over [here](https://github.com/networkx/networkx/discussions/5818).

Add docstring example to weighted.py

---

networkx/classes/coreviews.py
networkx/classes/tests/test_coreviews.py

The UnionAtlas class was computing `__len__` assuming that the two dicts being unioned have distinct keys. That is not true in general, and certainly not in the case of directed graphs with bidirectional edges.  At the UnionAdjacency level the keys must be the same (one for each node). But inside the UnionAdjacency is a UnionAtlas and for directed graphs it is a union of `_pred[node]` and `_succ[node]` which can have different keys, but it doesn't have to have different keys.
This fix corrects the computation of `__len__` to use the union of the two sets of keys, rather than the sum of the lengths. 
Fixes #6336

Fix len operation of UnionAtlas

---

networkx/algorithms/bipartite/tests/test_edgelist.py

I found that the [test coverage for edgelist.py](https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/algorithms/bipartite/edgelist.py) is currently 86%.
I have added test cases for the various conditions specific to the parse_edgelist() method and the coverage has now reached 100%.

Improve test coverage for edgelist.py

---

networkx/algorithms/tree/mst.py
networkx/algorithms/tree/tests/test_mst.py

Closes #6477 
I have added test cases for Kruskal and Prims algorithms. The test coverage for mst.py has now increased to 98%.
This is my first time writing tests, so I apologize in advance if there are any errors in the code. I am specifically doubtful of the Prims test when ignore_nan = False and an Error is raised.
Edit - This PR also fixes some bugs based on [this discussion](https://github.com/networkx/networkx/pull/6486#discussion_r1136069166). The bug fix introduces new branches to the code, so the test coverage is now 96%.

Improve test coverage for mst.py and bug fix in prim_mst_edges()

---

doc/reference/glossary.rst

I have added examples to the definition of `nbunch` in the glossary section of documentation.
They clarify the behavior when an iterable is passed as nbunch to a method in Networkx.
Reference issues #6509 and #4781

Add examples clarifying ambiguity of nbunch

---

networkx/readwrite/graph6.py

Switching from a list to a generator prevents the allocation of a `num_nodes**2 / 2` list of 2-tuples, which is a blocker for graphs with many nodes (see #6510).
Closes #6510

Use generator to limit memory footprint of read_graph6.

---

networkx/algorithms/boundary.py

I added examples in the docstring for the edge_boundary and node_boundary methods in boundary.py

Add docstring examples to boundary.py

---

networkx/algorithms/bipartite/tests/test_redundancy.py

I found that the [test coverage for redundancy.py](https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/algorithms/bipartite/redundancy.py) is currently 92.31%.
I have added some code that tests an _if_ condition that was previously not covered.
The test coverage has now reached 100%.

Improve test coverage for redundancy.py

---

doc/reference/algorithms/cycles.rst
networkx/algorithms/cycles.py
networkx/algorithms/tests/test_cycles.py

The need to enumerate simple cycles in a graph has come up frequently in my life and it's a common question that people have.  There are two ways of accomplishing this:
1. enumerate all connected sums of cycles in a cycle basis
2. exhaustive search
The first is probably the most efficient way to get all cycles, but filtering down to certain cycle lengths would not be efficient at all.  The code here is reasonably fast given the problem it is solving, but leaves some performance improvements on the table.  The biggest one is that I should probably iterate over 2-edge-connected components to avoid brute-forcing large trees.
This is a work in progress; I have not yet added tests.  And, of course, I'm open to discussion on how best to handle this -- I was unsure whether or not to dispatch …

add simple cycle enumerator for undirected class

---

.github/workflows/test.yml
networkx/algorithms/components/tests/test_connected.py
networkx/algorithms/link_analysis/tests/test_pagerank.py
networkx/algorithms/tests/test_structuralholes.py
networkx/classes/backends.py
networkx/classes/tests/dispatch_interface.py
setup.py

The dispatch functionality is used to delegate graph
computations to a different backend. Because those backends
are not part of NetworkX, testing the dispatching feature
was not originally added, relying instead on the other
backends (e.g. graphblas-algorithms) to verify the dispatch
functionality is working.
This change creates a "loopback" backend where NetworkX dispatches
to itself for the sole purpose of exercising the dispatching
machinery.
In one incarnation, various tests are augmented to use the
LoopbackGraph family and force loopback dispatching to occur
as normal usage would (see nx.algorithms.components.tests.test_connected:64).
A second incarnation forces *all* tests to run in dispatch mode
but use of a different `_dispatch` decorator. This mode is triggered
for all of …

Test dispatching via nx-loopback backend

---

networkx/algorithms/shortest_paths/weighted.py

Reference issue #6527 
Fixed the return type inconsistencies in the following methods of weighted.py - 
1. `all_pairs_dijkstra_path`
2. `all_pairs_bellman_ford_path`
3. `single_source_bellman_ford_path_length`

Fixed return type inconsistencies in weighted.py

---

networkx/algorithms/graph_hashing.py

mistakenly the docstrings reference the diameter of the subgraphs rather than the radius, and I've rephrased the docstrings to make more sense.

corrections to docstring of `weisfeiler_lehman_subgraph_hashes`

---

networkx/readwrite/gexf.py
networkx/readwrite/tests/test_gexf.py

Closes #6443 with @dschult 's fix. The added test should make clear the motivation for this change - this test fails on `main` due to `'None'` being given as the default.

Better default alpha value for viz attributes in gexf writer

---

doc/reference/algorithms/isomorphism.ismags.rst
networkx/algorithms/isomorphism/ismags.py

Closes #6547 
Improperly formatted Notes/References sections was causing a sphinx parsing error which led to a very poorly formatted html page.
Fixing the numpydoc formatting for the module docstring + minor munging of the heading levels should fix the issue.

Fix module docstring format for ismags reference article.

---

doc/developer/nxeps/nxep-0004.rst

Adds some text to the discussion section of NXEP4 to capture the conversations at the last several community meetings.
To summarize: I propose *not* to implement NXEP4 as described, as NetworkX would lose strict stream-compatibility using the new `np.random.Generator` as the default in the `nx.random_state` decorators.

Resolve NXEP4 with justification for not implementing it.

---

networkx/algorithms/centrality/laplacian.py
networkx/linalg/laplacianmatrix.py

Fixed the links in the `See Also` section for [laplacian_centrality](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.centrality.laplacian_centrality.html) and [laplacian_matrix](https://networkx.org/documentation/stable/reference/generated/networkx.linalg.laplacianmatrix.laplacian_matrix.html) that were not working

Fix links in laplacian_centrality and laplacian_matrix

---

networkx/drawing/nx_agraph.py
networkx/drawing/tests/test_agraph.py

Fixes: #6049 
First, I replicated the issue discussed in #6049 and found that it still persists.
The output of the out.dot file is given below which is in the format pos="(0,0)"
As discussed in the issue, I made changes to the to_agraph() method so that the DOT format is pos="0,0". Now the code executes without any warnings as expected.
The contents of the file out.dot are also as expected.

Fixing DOT format for to_agraph()

---

.github/workflows/coverage.yml
requirements/test.txt

The `codecov` CLI has been yanked from PyPI, so we need to update how we upload the coverage results to codecov.io.
See: https://github.com/networkx/networkx/pull/6634#issuecomment-1507376906

Replacing codecov Python CLI with gh action.

---

ruff.toml

I was curious to see if there were any language features that pyupgrade would automagically update for us now that Python 3.9 is the minimum supported version. How I tested: both `ruff .` and `pre-commit run --all-files` with this updated config.

Bump pyupgrade minimum Python version to 3.9.

---

.circleci/config.yml
.github/workflows/lint.yml
.github/workflows/mypy.yml
.github/workflows/pytest-randomly.yml
.github/workflows/test.yml

Sorry for the multiple CI PRs. The main thrust of this one is dropping Python 3.8 from CI, along with a few other minor changes:
- Drop Python 3.8 from the testing workflows
- Bump the pypy version from 3.8 -> 3.9
- Generally bump the Python version used in all other workflows up to 3.10
Note that all of our CI will continue to fail until #6635 is in, so marking this as draft for now.

Remove Python 3.8 from CI

---

networkx/algorithms/centrality/eigenvector.py
networkx/algorithms/centrality/katz.py

Fixed the <b>pagerank, hits</b> links in the <b><i> See Also</i></b> section that weren't working for these:- 
1. [eigenvector_centrality](https://networkx.org/documentation/latest/reference/algorithms/generated/networkx.algorithms.centrality.eigenvector_centrality.html#networkx.algorithms.centrality.eigenvector_centrality) 
2. [eigenvector_centrality_numpy](https://networkx.org/documentation/latest/reference/algorithms/generated/networkx.algorithms.centrality.eigenvector_centrality_numpy.html)
3. [katz_centrality](https://networkx.org/documentation/latest/reference/algorithms/generated/networkx.algorithms.centrality.katz_centrality.html#networkx.algorithms.centrality.katz_centrality)
4.  [katz_centrality_numpy](https://networkx.org/documentation/latest/reference/algorithms/generated/netwo …

Fix links in eigenvector.py and katz_centrality.py 

---

networkx/algorithms/community/centrality.py

Users won't be able to run the example code just by doing copy and paste with the current examples. And the first guess of doing `nx.girvan_newman` will also be wrong. We should try to be explicit about the namespaces (something I got from the user survey).

Use the correct namespace for girvan_newman examples

---

networkx/drawing/layout.py

This PR changes the code in `bipartite_layout` to preserve the specified node order.
The original code converted the nodes to sets, which are unordered in Python. This resulted in the nodes being returned in any order. But for bipartite graphs, we often want to be able to specify the order of the nodes on each side, rather than letting the layout function do it arbitrarily.
For example, code:
```
G = nx.bipartite.gnmk_random_graph(3, 5, 10, seed=123)
G_nodes = [0,1,2,5,4,3,7,6]
top = [2,0,1]
pos = nx.bipartite_layout(G_nodes, top)
nx.draw(G, pos=pos, with_labels=True)
```
before this PR:
after:

Preserve node order in bipartite_layout

---

networkx/algorithms/cluster.py
networkx/algorithms/operators/binary.py
networkx/algorithms/operators/tests/test_binary.py
networkx/classes/backends.py

A new `graphs` keyword is added. For the case of two graphs named `G` and `H` as the first to arguments in `foo`, the new spelling is 
```python
@nx._dispatch(graphs="G,H")
def foo(G, H, other_arg, **kwargs):
...
```

Allow multiple graphs for `@nx._dispatch`

---

networkx/algorithms/approximation/connectivity.py

Fixes #6572 
There are input validation checks in the internal `_bidirectional_shortest_path` function within the `approximation/connectivity` module that are not possible to hit without calling the private functions directly.
The internal function is called in `local_node_connectivity` which raises exceptions for `source=None` or `target=None` and `source == target`. Therefore I vote for removing these validation checks from the private function.

Rm unreachable code for validating input

---

examples/algorithms/plot_greedy_coloring.py

I've written a python script to visualize greedy coloring on the given dodecahedral graph . The visualization is as follows:-

Add Greedy Coloring Example to Gallery 

---

networkx/drawing/nx_pylab.py

Added doc examples for draw_circular, draw_kamada_kawai, draw_random, draw_spectral, draw_spring, draw_shell, and draw_planar functions.

Added docstring examples for nx_pylab.py

---

networkx/algorithms/centrality/tests/test_reaching.py

I have increased test coverage for reaching.py according to here :- https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/algorithms/centrality/reaching.py

Improve test coverage for reaching.py

---

requirements/doc.txt

It turns out the failures in the circleci job are because we're picking up sphinx 7 which was recently released.
This is a temporary fix to get the circleci job green again.

Pin sphinx<7 as temporary fix for doc CI failures

---

doc/release/release_dev.rst
networkx/algorithms/components/semiconnected.py

This PR proposes to remove the `topo_order` kwarg from `is_semiconnected` *without* a deprecation period. This represents the most aggressive potential solution to the problem identified in #6645 .
The rationale for removing without a deprecation period is that using the `topo_order` kwarg results in silently incorrect results more often than not. A quick example:
```python
>>> G = nx.DiGraph([(0, 1), (1, 2)])  # directed path graph
>>> nx.is_semiconnected(G)  # correct
True
>>> nx.is_semiconnected(G, topo_order=[0, 1, 2])  # Wrong result, even though topo_order is valid!
False
```
Therefore, the `topo_order` kwarg itself can be considered a bug rather than a feature, and should be fixed without a deprecation. The main downside of this approach is that any users who are currently using …

Remove `topo_order` kwarg from `is_semiconnected` without deprecation.

---

networkx/algorithms/operators/tests/test_binary.py
networkx/classes/backends.py

This handles `ego_graph`, which I just implemented in `graphblas-algorithms` here: https://github.com/python-graphblas/graphblas-algorithms/pull/61
This `dispatch` function is only used when testing, and it automatically converts graph inputs to the backend specified in an environment variable (it also converts Graph outputs back to networkx graphs). To convert correctly, it needs to know which weight to use for each algorithm. To date, this has worked fairly well by using a small set of rules. As done in this PR, these rules will likely need to be updated as more and more algorithms support dispatch. Some thoughts:
- Perhaps we don't need to do this; instead, can we rely on every backend to properly handle networkx Graphs as inputs?
- Or, instead, perhaps we add e.g. …

Handle weights as `distance=` in testing dispatch

---

networkx/generators/tests/test_random_graphs.py

An example of improving granularity in the `test_random_graphs` module. This PR extracts the tests related to `watts_strogatz` from the top-level test function, and breaks them down into their own individual tests.

Example of improving test granularity related to #5092

---

CONTRIBUTING.rst

Closes #6691 
The contributor guide was a little sparse on info wrt addressing issues in CI with linting. The recommendation is still "use pre-commit", but situations can arise where things are not properly installed/configured in local dev envs, leading to annoying red x's in CI.
The best way (that I know of at least) to deal with this situation is to use `pre-commit` to run all the lint hooks over the entire codebase.

Add linting to contributor guide.

---

doc/reference/functions.rst
networkx/classes/__init__.py
networkx/classes/digraph.py
networkx/classes/function.py
networkx/classes/graph.py
networkx/classes/multidigraph.py
networkx/classes/tests/test_coreviews.py
networkx/classes/tests/test_graphviews.py
networkx/classes/tests/test_subgraphviews.py

Currently `subgraph_view` and `reverse_view` are available in the global `nx` namespace but they are exposed via a redirect in `functions.py`. This was added in https://github.com/networkx/networkx/pull/3627 and I'm not a 100% sure why it is done this way.
Also made changes to some other places where `subgraph_view` and `reverse_view` where being imported via `networkx.graphviews` and not via the `nx` namespace.

MAINT: Add subgraph_view and reverse_view to nx namespace directly through graphviews

---

networkx/classes/graphviews.py

Added the docstring although the function is mainly used by the base classes.

Added doctrings for generic_graph_view

---

networkx/algorithms/node_classification.py

It just emits a warning, but it's one less warning.

Doc: wrong underline length

---

networkx/algorithms/traversal/depth_first_search.py

The stack in dfs can have only parent and children, the depth can be controlled from the outside of it, making the function slightly better in terms of time and space, but also readibility in my opinion :-)

simplify stack in dfs

---

networkx/algorithms/traversal/breadth_first_search.py

Another bfs which could be updated. Here it is the table of comparison of performance between the current implementation vs. the new one:
```
+--------------------------------------------------------+--------------------+---------------+--------------+
|                         graph                          | time: current main | time: this pr | times faster |
+--------------------------------------------------------+--------------------+---------------+--------------+
|     nx.random_regular_graph(d=1, n=10, seed=4241)      |        0.0         |      0.0      |     1.56     |
|     nx.random_regular_graph(d=9, n=10, seed=4241)      |        0.0         |      0.0      |     3.77     |
|    nx.random_regular_graph(d=10, n=100, seed=4241)     |        0.01        |      0.0      | …
```

optimize generic_bfs_edges function

---

networkx/algorithms/components/connected.py
networkx/algorithms/components/weakly_connected.py

Optimization of _plain_bfs for undirected graphs through the same principles described in #6299 and #6337.
This is a table which summarizes the new times in relation to the old ones for some graphs, as you can see there are some huge improvements in performance :-)
```
+--------------------------------------------------------+--------------------+---------------+--------------+
|                         graph                          | time: current main | time: this pr | times faster |
+--------------------------------------------------------+--------------------+---------------+--------------+
|     nx.random_regular_graph(d=1, n=10, seed=4241)      |        0.0         |      0.0      |     2.91     |
|     nx.random_regular_graph(d=9, n=10, seed=4241)      |        0.03        | …
```

Optimize _plain_bfs functions

---

networkx/algorithms/approximation/tests/test_kcomponents.py

There are Sporadic test failures when testing connected components of `AntiGraph` in `test_kcomponents.py`.
The tests checks whether ccs of G and AntiGraph(G) are the same.
But that is not true for graphs with isolated nodes or with nodes that connect to every other node.
One of the graphs being tested is generated using `gnp_random_graph` without a seed.
So occasionally it will construct a graph with a node connected to every other node.
Fix: Assign a seed to make sure the random graph doesn't produce such a node

Stabilize test of approximation.connected_components

---

INSTALL.rst
setup.py

Follow-up to #6636  also getting ready for the move to `pyproject.toml`.  See https://scientific-python.org/specs/spec-0000/

Drop support for Python 3.8 per SPEC0

---

networkx/algorithms/shortest_paths/tests/test_weighted.py
networkx/algorithms/shortest_paths/weighted.py

Closes #6749 
Modified the behavior of the code to match the docstring for Johnson's shortest path method.
Now the unweighted edges in a graph are assumed to have weight 1.

Fix Johnson method for unweighted graphs

---

requirements/default.txt

Should we just keep this pin till scipy 1.11+ becomes the min supported scipy version for networkx?

MAINT: Ignore SciPy v1.11 in requirements

---

networkx/drawing/nx_pylab.py

The method `numpy.alltrue` has been deprecated in 1.25 and will be removed in numpy 2.0. See https://github.com/numpy/numpy/pull/23314

Replace deprecated numpy.alltrue method

---

requirements/default.txt

Scipy released 1.11.1 without waiting for the fix we need to be able to use superLU.

keep out scipy 1.11.1

---

networkx/algorithms/matching.py

I ran into the recursion limit using `max_weight_matching` on a large graph.  This algorithm has some rather large recursive subroutines, so I have not exercised my typical performance-oriented rigor for fear of breaking things and making it completely unreadable.
Instead, I used a trampoline pattern for its simplicity and at-a-glance correctness.
```python
def original_f(*args):
...
original_f(*r_args)
...
def new_f(*args):
def _recurse(*args):
...
yield r_args
...
stack = [_recurse(*args)]
while stack:
top = stack[-1]
for r_args in top:
stack.append(_recurse(*r_args))
break
else:
stack.pop()
```

modified max_weight_matching to be non-recursive

---

CONTRIBUTING.rst

There was a missing backtick causing an extra one to appear after `sp` in the contributing page.

Fix typo in contributing page

---

networkx/algorithms/cycles.py
networkx/algorithms/tests/test_cycles.py

Fixes #6787 
Fixes #6783
This does change the output of this function from a set to a list. 
But given that it was returning wrong results and sets that were not very useful, I'd argue we should just fix this instead of deprecating.
@mbr085 I think this will fix both of your problems. You can install from the branch for this PR, but it might be easier to download the changed `cycles.py` file and then install it in your `site-packages/networkx/algorithms/cycles.py`.
Sorry for the broken code. I hope this fixes it. 
I think the code is easier to read this way too, but I wish I could avoid the 2-pass process to remove extra edges based on multiplicity. I managed to convince myself that you had to do 2 passes. But I wish I didn't. :)

Fix minimum_cycle_basis and change to return cycle instead of set

---

networkx/algorithms/community/louvain.py
networkx/algorithms/community/tests/test_louvain.py

I fixed the Zero division error for the Louvain algorithm when running it with an empty and added a test for it.

Fix empty graph zero division error  for louvain

---

networkx/algorithms/cycles.py
networkx/algorithms/tests/test_cycles.py
networkx/convert_matrix.py

Follow-up testing from #6788 showed a number of interesting bugs and deficiencies.
- My error using `any` instead of `sum` followed by `% 2` in one line. This led to the returned "basis" being not independent in some cases.
- The tests don't check non-uniformly weighted graphs sufficiently to catch the above error. So add tests.
- One reported example from @mbr085 raised a ValueError which was caused because an edge was added as `np.int32` instead of python `int`. I chased this down to `convert_matrix.py` and the handling of conversion from sparse matrices. More below if you are interested.
This PR makes 3 commits to fix these issues. The first adds tests to show the errors reported in #6788. The second adds the sum/modulo term to enable passing those tests. The third corrects the sparse …

Refix minimum_cycle_basis and scipy.sparse conversions and add tests

---

.github/workflows/label-check.yml

As discussed in the developer meeting today, I've updated the labels to include:
https://github.com/networkx/networkx/labels?q=type
```
type: Maintenance
type: Enhancements
type: Documentation
type: Highlights
type: API
type: Bug fix 
```
This is in preparation for switching to https://github.com/scientific-python/changelist/ after the upcoming 3.2 release.

Add label-check workflow

---

.github/workflows/milestone-merged-prs.yaml

This will attach the next milestone to PRs when they are merged into main. I've created the TOKEN, so this should work.
I also enabled `Fine-grained personal access tokens` in the process:
https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github/
We are already using them for scientific-python and scikit-image.

Attach milestone to merged PRs

---

doc/developer/deprecations.rst
doc/release/release_dev.rst
networkx/algorithms/tree/branchings.py
networkx/algorithms/tree/tests/test_branchings.py
networkx/conftest.py

As discussed in #6743, the original implementation of Edmond's algorithm for finding maximum branchings, and by extension minimum branchings as well as minimum and maximum arborescences was a class with only one method (`find_optimum`). This API structure is not common throughout NetworkX, in fact it is the only instance where a class is used to implement a network algorithm that I'm aware of. Since all of these algorithms were recently refactored and no longer depend on the class itself, it is now safe to remove the class. 
Additionally, the `MultiDiGraph` subclass `MultiDiGraph_EdgeKey` is also no longer needed. It was not used in any other algorithms in the library and doesn't extend the original class in a manner which is not easily replicated with an additional helper function.

deprecate Edmonds class

---

networkx/algorithms/tests/test_walks.py
networkx/algorithms/walks.py

number_of_walks might use a weighted edge attribute if that graph has any edge attributes not equal to 1.
That will make it compute the number of walks incorrectly since it uses a power of the adjacency matrix.
This fix simply changes the call to adjacency_matrix to have `weight=None` explicitly set. Test added too.

number_of_walks might use a weighted edge attribute

---

networkx/algorithms/centrality/second_order.py
networkx/algorithms/centrality/tests/test_second_order_centrality.py
networkx/algorithms/minors/contraction.py
networkx/algorithms/minors/tests/test_contraction.py
networkx/algorithms/similarity.py
networkx/algorithms/tests/test_similarity.py
networkx/algorithms/walks.py

As part of https://github.com/networkx/networkx/pull/6688, we found some functions were making assumptions about the `weight` parameter. It was not user programmable and it was defaulting to `weight` the string.
This implements https://github.com/networkx/networkx/issues/6753 and exposes `weight` as part of the API.

Make weight part of the API for functions which had default assumptions

---

networkx/algorithms/tests/test_threshold.py

This allows backends such as `cugraph_nx` to implement `betweenness_centrality` with float32.

Relax threshold in test of `betweenness_centrality`

---

.github/workflows/nightly.yml

Following discussion in https://github.com/scientific-python/upload-nightly-action/pull/27#pullrequestreview-1557811090 this PR adds the mentioned checks to the nightly wheel upload CI.
Use 'twine check' to verify distribution and list the contents of the dist and wheel for visual inspection of distribution content in the logs.

ci: Add distribution verification checks to nightly wheel upload

---

networkx/readwrite/gml.py
networkx/readwrite/tests/test_gml.py

This PR adds support for reading GML files with multiline entries. Currently NetworkX fails reading those files. The multiple lines are concatenated by space. This is achieved by introducing a buffer called `multilines`.
Fixes #6836

GML: added support for reading multi-line values

---

.github/workflows/nightly-release-test.yml

We are failing on the nightly wheel builds b/c of numpy 2 (see #6846). This let's us test on the other wheels without the known numpy 2 failure. After merging this, I will make a PR to revert it and we can work on fixing the issue there.

Don't test numpy2 nightlies

---

networkx/linalg/laplacianmatrix.py
networkx/tests/test_lazy_imports.py

Future versions of scipy are removing the symbols from scipy namespace that are simply aliases to numpy objects
This PR removes these aliases for future compatibility.
Note that the `sp.pi` was used in the testing of the lazy importing system. I went ahead and changed it to `sp.special.erf`... I *believe* this covers the same semantics, but please double-check that I'm not changing the test semantics too much!

MAINT: replace numpy aliases in scipy namespace.

---

networkx/algorithms/approximation/steinertree.py
networkx/algorithms/shortest_paths/generic.py
networkx/drawing/nx_pydot.py
networkx/generators/line.py

Some messages are not properly separated by spaces.
E.g., when the following code (`main.py`) is run by `python main.py`,
```python
import matplotlib.pyplot as plt
def main():
G = nx.complete_graph(4)
pos = nx.nx_pydot.graphviz_layout(G)
nx.draw(G, pos=pos)
plt.savefig("main.png")
if __name__ == "__main__":
main()
```
the execution result look like below.
```
/home/user/main.py:6: DeprecationWarning: nx.nx_pydot.graphviz_layout depends on the pydot package, which hasknown issues and is not actively maintained. Consider usingnx.nx_agraph.graphviz_layout instead.
See https://github.com/networkx/networkx/issues/5723
pos = nx.nx_pydot.graphviz_layout(G)
```
However, this should look like below. Spaces are inserted between "has" and "known", and "using" and …

fix: make messages readable

---

networkx/algorithms/traversal/depth_first_search.py

Add to the doc_strings for `source` input argument of `dfs_predecessors` and `dfs_successors`.
Fixes #6795

add docs for source input of dfs_predecessor and dfs_successor

---

networkx/linalg/laplacianmatrix.py

Fixes #6865 
Uses `np.abs` before `np.sqrt` to force round-off that switches sign to stay positive.
That avoids creating nans via sqrt.
I'd like to add tests for this -- but the example from the OP is 407 lines long. So I'm still looking for a test.

Avoid directed_laplacian_matrix causing nans in some cases.

---

.github/workflows/test.yml
networkx/algorithms/operators/tests/test_binary.py
networkx/classes/tests/dispatch_interface.py
networkx/classes/tests/test_backends.py
networkx/conftest.py
networkx/utils/backends.py

This PR supersedes #6828 and #6829, and it implements one of the "future" items from #6804:
- change `_dispatch` to be a class instead of a closure
- fallback to original networkx function when testing if `fallback_to_nx` is set when backend raises `NotImplementedError` (also done in #6828)
- don't dispatch to backend when testing until tests are set up (also done in #6828)
- add `--backend=whatever` option to `pytest` to choose backend w/o environment variable (also done in #6829)
- add `--fallback-to-nx` option to `pytest` to run test with networkx graph is backend does not implement it
- rename `NETWORKX_GRAPH_CONVERT` environment variable to `NETWORKX_TEST_BACKEND`
- rename `NETWORKX_BACKEND_TEST_EXHAUSTIVE` environment variable to `NETWORKX_FALLBACK_TO_NX`
- add `**backend_kwargs` to …

Change `_dispatch` to a class instead of a closure

---

networkx/drawing/layout.py

modified:   networkx/drawing/layout.py
- Replaced for-loops in :function:`rescale_layout` with numpy vectorized methods.
- No new tests as output should not have changed and no new features were introduced.
- Tested specifically with :method:`TestLayout.test_rescale_layout_dict` in drawing/tests/test_layout.py.
- All other tests ran per contributor guide.

ENH -- Replaced for-loops in :function:`rescale_layout` with numpy vectorized methods.

---

networkx/algorithms/approximation/clustering_coefficient.py
networkx/algorithms/approximation/distance_measures.py
networkx/algorithms/approximation/maxcut.py
networkx/algorithms/approximation/traveling_salesman.py
networkx/algorithms/centrality/betweenness.py
networkx/algorithms/centrality/current_flow_betweenness.py
networkx/algorithms/coloring/greedy_coloring.py
networkx/algorithms/community/asyn_fluid.py
networkx/algorithms/community/kernighan_lin.py
networkx/algorithms/community/label_propagation.py
networkx/algorithms/community/louvain.py
networkx/algorithms/community/quality.py
networkx/algorithms/connectivity/edge_augmentation.py
networkx/algorithms/mis.py
networkx/algorithms/smallworld.py
networkx/algorithms/sparsifiers.py
networkx/algorithms/swap.py
networkx/algorithms/tree/branchings.py
networkx/algorithms/tree/mst.py
networkx/algorithms/triads.py
networkx/generators/spectral_graph_forge.py
networkx/linalg/algebraicconnectivity.py

When I first tried to have `@py_random_state` and `@np_random_state` come before `@nx._dispatch` in #6688, I encountered an error. I don't recall what, but @dschult expected it to "just work" and was surprised there was an error (and it's possible I did something wrong). Anyway, I thought I would check to see if this would work now after #6840... and it does!

Move random_state decorators before `@nx._dispatch`

---

networkx/algorithms/cycles.py

I added the **bold** part in
> A basis for cycles of a network is a minimal collection of cycles such that any **simple** cycle in the network can be written as a sum of cycles in the basis. Here summation of cycles is defined as "exclusive or" of the edges. Cycle bases are useful, e.g. when deriving equations for electric circuits using Kirchhoff's Laws.
because in the graph below, the cycle basis is `[[L1, L2, L3], [R1, R2, R3]]`, but neither of the (non-simple) cycles `[L1, L2, L3, L1, C, L1]` and `[L1, L2, L3, L1, C, R1, R2, R3, R1, C, L1]` is a sum of the basis cycles.
---
It appears that text in docstrings is justified. I read the contributing guidelines and installed the pre-commit hooks, but those did not automatically justify the docstring, so I added whitespace manually.

Clarify that basis generates simple cycles only

---

examples/drawing/plot_tsp.py

Hello, I just found a small typo in the example docs for the traveling salesman problem.
I was also wondering what's the best way to add a hyperlink for christofides with this link:(https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.approximation.traveling_salesman.christofides.html#christofides), does sphinx docs support markdown in the python comments? and is there a shortcut for the link?

updating TSP example docs

---

doc/release/release_dev.rst
networkx/algorithms/shortest_paths/tests/test_weighted.py
networkx/algorithms/shortest_paths/weighted.py

Fixes #6874 
The NetworkX shortest path algorithm Goldberg-Radzik handles negative edge weights. It finds negative weight cycles and raises in this case. But it incorrectly identifies zero-weight cycles as negative cycles.  But zero weight cycles do not make the shortest path unbounded. The path found is not unique, but it exists and has a finite length. (Bellman-Ford in NX correctly reports these paths.) 
This PR corrects Goldberg-Radzik to report shortest paths in the presence of zero-weight cycles. It adds a test of g-r and b-f algorithms. And it adds a short note in the doc_string of goldberg-radzik that the behavior has changed as of NX v3.2.
I don't think we need to deprecate since it was an incorrect result. But I thought a note in the doc_string would help people who find that …

Add test about zero weight cycles and fix goldberg-radzik

---

doc/release/release_dev.rst
networkx/classes/function.py
networkx/classes/tests/test_function.py

Currently it's not possible to get a dictionary with a default value if someone uses the `get_(node/edge)_attributes` methods. If a user passes an attribute name which is set by only a subset of nodes/edges they need to augment the return dictionary manually if they want to set a default value.
The implementation in this PR should be backward compatible so if someone is only expecting to get the nodes/edges which has these attributes it will keep on working.
This came up while trying to come up with a fix for https://github.com/networkx/networkx/issues/6886

ENH: let users set a default value in get_attr methods

---

doc/developer/deprecations.rst
doc/release/release_dev.rst
networkx/algorithms/smetric.py
networkx/algorithms/tests/test_smetric.py
networkx/conftest.py

Currently, the `nx.s_metric` function raises a `NetworkXException` when called with the default keyword argument values because normalization is not implmented:
```python
>>> G = nx.cycle_graph(4)
>>> nx.s_metric(G)
Traceback (most recent call last)
...
NetworkXError: Normalization not implemented
```
I think it's safe to say this function is not frequently used :upside_down_face: Nevertheless, I propose to change the default to `normalization=False`. I don't think the deprecation/futurewarning policy really applies in this case since the default is broken; however, if there are other suggestions for how to handle this (e.g. remove the kwarg outright) LMK!
fixes https://github.com/networkx/networkx/issues/5906

Modify `s_metric` `normalized` default so function doesn't raise

---

networkx/readwrite/gexf.py
networkx/readwrite/graphml.py
networkx/readwrite/tests/test_graphml.py

Nightly tests are failing with numpy 2.0 as numpy has removed `np.float_` https://github.com/networkx/networkx/actions/runs/6061305343/job/16446362472
I think this change should be backward compatible (?) as GEXF and graphml the format don't have a concept of numpy floats (?).

MAINT: Make GEXF and graphml writer work with numpy 2.0

---

networkx/algorithms/tree/coding.py

This pull request is meant for fixing #6420. the author of the issue passes the prufer sequence `[7,5,5,3,1]` to the function `from_prufer_sequence` and expects a valid output (tree). The conflict happens due to the difference in indexing styles; networkx uses the zero-indexing , on the other hand , mathematicians (graph theorists ) use one as the first label/index . Adopting zero-indexing style, every element in the sequence has to obey the following constraint: 
$$0 \le sequence[i] \le length(sequence) + 1   \ \ \ \  ,  \ \ \ \ such \  that  \ \ \  0 \le i < length(sequence)$$
If not the case a `NetworkXError` is raised .
Hope this is thoughtful  
Closes #6420

Error handling for invalid prufer sequence `from_prufer_sequence`: issue #6420

---

networkx/algorithms/tree/operations.py
networkx/algorithms/tree/tests/test_operations.py

Fixes #6488 and fixes #6490 
@MridulS 
Modified join operation to store label_attributes and handled the case when label_attribute argument is provided.
Added test cases for join operation to check label_attributes.
Could you please check the PR and suggest any changes if needed to be done.
https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.tree.operations.join.html
In the documentation its written that Input has to be list of trees but this function works for graphs as well. Should I change the documentation by replacing trees with graphs or modify the join function to not accept list of graphs as input?

Added test cases for join operation and fixed join operation to handle label_attributes

---

networkx/algorithms/polynomials.py

Simple backticks have sphinx trying to guess what this refers to instead of double backtick for verbatim.
The stray backtick just messes up parsing

DOC: stray backtick and double instead of simple backtick.

---

networkx/algorithms/minors/contraction.py

Add an example to explain for multidigraphs while contracting nodes with self loops in the original graph.
An example to resolve https://github.com/networkx/networkx/issues/6739
@Diarmuid-ODonoghue do you think this accurately covers the case?

DOC: Add example for self loop multidigraph in contraction

---

doc/conf.py
networkx/utils/backends.py

@MridulS noticed the online docs no longer render properly for dispatched functions now that `_dispatch` is a class: https://github.com/networkx/networkx/pull/6840#issuecomment-1700779731
I'm not a Sphinx expert, but here is one way to fix the problem. It also allows the dispatch machinery to update the docstring. The signature of dispatched functions is unchanged in the online docs--that is, `backend=None, **backend_kwargs` is not shown.

Fix sphinx docs rendering of dispatched functions

---

doc/developer/deprecations.rst
doc/reference/algorithms/tree.rst
networkx/algorithms/tree/operations.py
networkx/algorithms/tree/tests/test_operations.py

Closes #6906 
Rename `algorithms.tree.operations.join` to `algorithms.tree.operations.join_trees`. Deprecate old function name.
I kept the old function name in the docs with a message stating the deprecation and pointing to the new name. 
Added note to deprecations.rst and updated tests.

Rename function `join` as `join_trees`

---

networkx/classes/function.py
networkx/classes/graph.py
networkx/classes/graphviews.py
networkx/classes/tests/test_coreviews.py
networkx/classes/tests/test_subgraphviews.py
networkx/utils/decorators.py

[Scikit-learn has a decorator](https://github.com/scikit-learn/scikit-learn/blob/8ed0270b99344cee9bb253cbfa1d986561ea6cd7/sklearn/utils/validation.py#L37C1-L90C44) which took care of the deprecation cycle for moving to keyword args from positional args. I have vendored that in as a networkx decorator.
This should resolve https://github.com/networkx/networkx/issues/4845.

 API: Add a decorator to deprecate positional args 

---

networkx/algorithms/centrality/percolation.py
networkx/algorithms/centrality/tests/test_percolation_centrality.py

Closes #6886 (we could raise an error instead)
If the default attribute (`percolation`) is not present for every node it will default to 1. This will also add defaults to nodes if the node attribute is only present for a subset of nodes. This shouldn't break any old code as anyone using this with the node attribute not set for every node would have been getting a `KeyError`.
~This depends on https://github.com/networkx/networkx/pull/6887~

FIX: Better default behaviour for percolation centrality with no node attrs

---

doc/reference/generators.rst
examples/graph/plot_visibility_graph.py
networkx/generators/__init__.py
networkx/generators/tests/test_time_series.py
networkx/generators/time_series.py

Return a Visibility Graph of an input Time Series.
It converts a time series into a graph. The constructed graph inherits several properties of the series in its
structure. Thereby, periodic series convert into regular graphs, and random series do so into random graphs.
Moreover, fractal series convert into scale-free networks.
-- https://www.pnas.org/doi/10.1073/pnas.0709247105
Parameters
----------
series: Iterable[float]
Time Series iterable of float values
Returns
-------
NetworkX graph
The Visibility Graph of series
Examples
--------
>>> import networkx as nx
>>> from matplotlib import pyplot
>>>
>>> series_list = [range(10), [2, 1, 3, 2, 1, 3, 2, 1, 3, 2, 1, 3]]
>>>
>>> for s in series_list:
...     g = nx.visibility_graph(s)
...     print(g)
...     # Uncomment the following lines …

Add time series Visibility Graph generator

---

doc/release/release_dev.rst
networkx/conftest.py

I forgot to update `conftest.py` and `release_dev.rst` for the renaming `join` deprecation in #6908 
This adds them.

add missing `join` deprecation stuff to release_dev and conftest

---

networkx/readwrite/json_graph/adjacency.py
networkx/readwrite/json_graph/tests/test_adjacency.py

- Deserialised Serialised Graph should be equal to Graph
- Deserialisation should not modify serialised object
Fixes #5980

Remove serialisation artifacts on adjacency_graph

---

doc/developer/deprecations.rst
networkx/conftest.py
networkx/readwrite/json_graph/node_link.py
networkx/readwrite/json_graph/tests/test_node_link.py

Removes the deprecated `attrs` kwarg from the `node_link_graph` and `node_link_data` functions in preparation for the v3.2 release.

Expire deprecation for `attrs` kwarg in node_link module

---

networkx/algorithms/graphical.py

added more examples on graphical degree sequence

---

networkx/algorithms/flow/tests/test_maxflow_large_graph.py
networkx/algorithms/flow/tests/test_mincost.py
networkx/algorithms/flow/tests/test_networksimplex.py
networkx/algorithms/isomorphism/tests/test_isomorphvf2.py
networkx/generators/atlas.py

This should fix https://github.com/networkx/networkx/issues/3929
I'm not too sure if there is a better way of doing this. I don't really like writing down the paths explicitly.

MAINT: Use importlib.resources instead of file dunder to access files

---

CONTRIBUTING.rst
doc/README.rst

Condense documentation building instructions to a single location in doc/README.rst and include that directly in the contributor guide.
This resolves some fragmentation of the contributor documentation, ensuring new contributors see the same information both in the html docs and in the source READMEs.
Closes #6770

DOC, MAINT: Deduplicate docs instructions.

---

doc/reference/algorithms/traversal.rst
networkx/algorithms/traversal/breadth_first_search.py

A minor follow-up to #5925 - just something I noticed while reviewing the deprecations list.
* Add back the docstring with the .. deprecated:: directive
* Make clear in the message that removal is slated for v3.4

Minor touchup to the sort_neighbors deprecation.

---

doc/developer/deprecations.rst
networkx/conftest.py
networkx/generators/directed.py
networkx/generators/tests/test_directed.py

Expires the deprecation of create_using (replaced by initial_graph) in `scale_free_graph` in preparation for v3.2.

Rm deprecated `create_using` kwarg from scale_free_graph

---

networkx/algorithms/centrality/betweenness.py

Both equality and unequality comparison of distances in at least `_single_source_dijkstra_path_basic` produce wrong results on some graphs because limited machine precision might produce overflow and roundoff errors.
I have added a warning comment for this.

Warning comment for float weights in betweenness.py

---

networkx/readwrite/gml.py
networkx/readwrite/tests/test_gml.py

Minor followup to #6943 - while `literal_(de)stringizer` is still necessary for the nested-sequence corner case, this PR adds support to the default stringizer for nodes which are tuples.

Add support for tuple-nodes to default gml parser

---

networkx/linalg/graphmatrix.py

Followup to #6725 . Proposal to make the newly added (in v3.2) `dtype` parameter to `incidence_matrix` keyword-only.

Make new dtype param for incidence_matrix kwarg-only.

---

networkx/algorithms/community/label_propagation.py

Followup to #6843 . Proposal to explicitly make the `weight` and `seed` parameters of `fast_label_propagation_communities` keyword-only.

Make weight and seed for `fast_label_propagation_communities` kwarg only

---

doc/reference/linalg.rst
networkx/algorithms/operators/product.py
networkx/linalg/algebraicconnectivity.py

Interpreted text don't like trailing text (unless it is some limited set of character. It renders incorrectly in docs.
Also a too long underline that triggers a Numpydoc warning
And `spectral_bisection` to `doc/reference/linalg.rst`

DOC: Misc typos.

---

networkx/algorithms/shortest_paths/tests/test_weighted.py
networkx/algorithms/shortest_paths/weighted.py

This should fix https://github.com/networkx/networkx/issues/6921
The `_weight_function` assumes that the key of a multigraph is also passed in the data dictionary but `nx.selfloop_edges` only returns the keys when explicitly asked.

FIX: MultiDiGraphs keys got lost in weighted shortest paths

---

networkx/algorithms/structuralholes.py

Fixing very small typo in the explanation of `effective_size`

Fixing typo in effective_size documentation

---

networkx/algorithms/tournament.py

This PR closes #6924. It fixes the example in the docstring for `tournament.is_strongly_connected` and checks whether other example graphs in `tournament.py` are actually tournaments using method `is_tournament`.

fix examples in tournament.py

---

networkx/algorithms/distance_measures.py

Nightly build was failing as `errstate` alias isn't available in scipy anymore https://github.com/networkx/networkx/pull/6857

MAINT: Scipy nightly failing with np alias

---

networkx/generators/classic.py

Fix a reference from `dorogovtsev_goltsev_mendes_graph`.
Fixes a spelling error in one of the author's names and now refers to published article instead of arXiv.

Fix a reference

---

networkx/algorithms/operators/all.py

[DOC]:
Added docstring example for `union_all` in algorithms/operators/all.py

feat: docstring examples for algorithms/operators/all.py

---

doc/developer/deprecations.rst

I added a link to the removal in the commit message for each documentation update.
The only remaining issue is what to do about pydot. For now, I just moved the note to the next release and we can discuss it later.

Update developer deprecation todo list

---

networkx/algorithms/tests/test_time_dependent.py
networkx/algorithms/time_dependent.py

I'd like to propose a change to the `cd_index` API: removing the default value for `time_delta`. The current default of 5 years as a `timedelta` object feels arbitrary, and I can't think of a strong reason why a default value makes sense here. Furthermore, providing a `datetime.timedelta` object suggests that the `time` node attribute must be `datetime.datetime` objects by default, which feels like too strong a recommendation IMO.

API: Rm default value from time_delta for cd_index.

---

doc/developer/deprecations.rst
doc/release/release_dev.rst
networkx/algorithms/components/strongly_connected.py
networkx/algorithms/components/tests/test_strongly_connected.py
networkx/conftest.py

Alternative to #6898 , see https://github.com/networkx/networkx/pull/6898#issuecomment-1734207080.
Deprecates the `strongly_connected_components_recursive` function in favor of the non-recursive implementation.
Closes #6897

Deprecate strongly_connected_components_recursive

---

networkx/algorithms/centrality/laplacian.py
networkx/algorithms/centrality/tests/test_laplacian_centrality.py

Re-submission of #6664 from an editable branch. Original PR description below. All attribution
---
This code handles a few edge cases of the Laplacian centrality with empty, single-node, and unconnected (edgeless) graphs.
Following changes have been made to the laplacian_centrality calculation
NetworkXPointlessConcept is raised for empty and single node graphs
NetworkXPointlessConcept is raised for graphs without edges and normalized=True (we can't normalize to 0.0)
Test cases are provided. The code has been reviewed, and review comments have been processed.
fixes https://github.com/networkx/networkx/issues/6571, fixes https://github.com/networkx/networkx/issues/6626

Handle edge cases in Laplacian centrality

---

.github/workflows/release.yml
doc/developer/release.rst

I enabled GH as a trusted publisher for PyPI:

Use trusted publisher

---

.github/workflows/nightly.yml

The [`scientific-python/upload-nightly-action`](https://github.com/scientific-python/upload-nightly-action/) action has received stability updates in [`0.2.0`](https://github.com/scientific-python/upload-nightly-action/releases/tag/0.2.0) that provide a reproducible runtime environment for the action, which should mitigate issues with stability.
Using stable known releases provides additional protection from service disruption incidents (like https://github.com/scientific-python/upload-nightly-action/issues/43). Future releases will get picked up automatically by Dependabot
https://github.com/networkx/networkx/blob/364e20eca8f270b9d364fab7f73ea63338790d98/.github/dependabot.yml#L2-L8

CI: Pin scientific-python/upload-nightly-action to 0.2.0

---

doc/release/release_dev.rst

This was generated via:
```
export VERSION=3.2rc0
export PREVIOUS=3.1
export ORG="networkx"
export REPO="networkx"
changelist ${ORG}/${REPO} networkx-${PREVIOUS} main --version ${VERSION}  --out doc/release/release_dev.rst --format rst
```
If we want to change something in the release notes, we should update the relevant GH PR.

Add 3.2rc0 release notes

---

networkx/algorithms/community/quality.py

Hello!
The docstring for the `modularity` function (`networkx/algorithms/community/quality.py`) states that:
>  $m$ is the number of edges
This is incorrect, as the function itself defines `m` as:
```python
out_degree = in_degree = dict(G.degree(weight=weight))
deg_sum = sum(out_degree.values()) # Sum of all weights in G!
m = deg_sum / 2 # Divide by two to account for mirrors
```
in the undirected case (same goes for the directed case, except because it uses `G.in_degrees`/`G.out_degrees`).
I therefore corrected the docstring and cited [this paper](https://arxiv.org/abs/cond-mat/0408187) exactly as it appears in `networkx/algorithms/community/louvain.py`.

Fix definition of $m$ parameter in docstring of `modularity` function

---

networkx/algorithms/clique.py
networkx/algorithms/tests/test_clique.py

Removes the 4 deprecated functions from the clique module: `graph_clique_number`, `graph_number_of_cliques`, `number_of_cliques` and `cliques_containing_node`.
@MridulS I know you have a preference for *not* removing helper functions, so just one final check with you :).
One thing I was thinking we could do: in each of these cases, the helper function is replaced by a one-liner[^1]. In order to further reduce the disruption of removing these functions, we could add the four names to the package `__getattr__` and have it raise an exception which includes the recommended one-liner in the message. This seems like the best of both worlds IMO: the confusing function names are removed (and we don't add them to `__dir__` so they are not discoverable), but any code that was relying on them and …

Rm deprecated clique helper functions

---

networkx/algorithms/connectivity/edge_augmentation.py
networkx/algorithms/connectivity/tests/test_edge_augmentation.py

Add call to ```is_connected``` in addition to ```has_bridges``` for k=2, to catch multi-component graphs without bridges, which are not not 2-edge-connected.
Fixes #7023

Fix ```is_k_edge_connected``` for case of k=2

---

doc/release/index.rst

This was inadvertently broken in #7005, by omitting the :glob: flag. However since globbing in sphinx currently only supports lexicographical ordering (https://github.com/sphinx-doc/sphinx/issues/3828), this is not really suited for version numbers anyways. Thus, revert back to manually listing versions.

Fix listing of release notes on Releases page

---

.github/workflows/deploy-docs.yml
.github/workflows/nightly-release-test.yml
.github/workflows/test.yml
INSTALL.rst
benchmarks/asv.conf.json
networkx/algorithms/link_analysis/hits_alg.py
networkx/algorithms/lowest_common_ancestors.py
networkx/conftest.py
networkx/convert.py
networkx/convert_matrix.py
networkx/drawing/nx_latex.py
networkx/readwrite/gml.py
networkx/readwrite/json_graph/node_link.py
networkx/readwrite/text.py
networkx/relabel.py
networkx/utils/backends.py
networkx/utils/misc.py
networkx/utils/tests/test_decorators.py
pyproject.toml

See https://scientific-python.org/specs/spec-0000/

Drop Python 3.9 support

---

networkx/algorithms/cluster.py
networkx/algorithms/similarity.py

Fixes #7038 
Using `n is not node` compares whether n and node are the same object, not whether they are equal.
Thanks to a bug report in #7038 we discovered that the string "46" can sometimes be created twice and not [interned](http://guilload.com/python-string-interning/)so that `n is not node` returns True even though both are equal to "46".
The error occurs in `triangles` when ensuring that a node in not included in its list of neighbors (ruling out self-loops).
`n` is the neighbor in question and `node` is the node being checked.  This only goes to prove that "46" is not always the same object as "46". They are the same object if they are interned.
Unfortunately figuring out when interning occurs is quite complicated and it may change. So I could not think of a good test to write for …

Fix triangles to avoid using `is` to compare nodes

---

networkx/convert_matrix.py

[comment reference](https://github.com/networkx/networkx/pull/6259#discussion_r1280916514) in #6259

fix: Explicitly check for None/False in edge_attr during import from np

---

doc/reference/algorithms/bipartite.rst

fix extendability function name in bipartite.rst
The name of the function maximal_extendability in the bipartite docs was not updated from `find_extendability` during PR review. So, the function doesn't show in current docs and creates quiet failures for documentation builds when looking for `find_extendbability`.
This might help e.g. #7040 successfully build the docs, but I am not sure. It should be fixed in any case.

fix extendability function name in bipartite.rst

---

doc/reference/algorithms/clique.rst
doc/release/index.rst
networkx/algorithms/bipartite/extendability.py

Similar to #7042 
* remove the expired clique functions from the refguide to fix the doc build.
* Fix reference formatting in maximal_extendability docstring
* Rm `release_dev` from release notes autosummary

Minor doc cleanups to remove doc build warnings

---

networkx/generators/small.py

I noticed the  names of these small graphs aren't like all the other small graph names--one is a tuple, and one uses "graph" instead of "Graph".

Fix names of small graphs

---

networkx/generators/classic.py
networkx/generators/tests/test_classic.py

I doubt the current behavior with negative integer inputs to `complete_multipartite_graph` is intended or used anywhere, so let's raise instead.
Adding this check makes my life (and the job of other backend developers) easier, b/c I don't want to reproduce this behavior, nor do I want to handle this as a special case in my otherwise nice test fixture.

Disallow negative number of nodes in `complete_multipartite_graph`

---

networkx/conftest.py
networkx/lazy_imports.py

Fixes #7047 
Allow pytest to run even when `nx-loopback` is not available resulting in 5 failed nx-loopback tests, but other tests run OK.
I put a warning message into this version for the PR, but we could instead have no message (no one should ever be in this situation except maybe our future selves). And we could raise an exception instead of a warning.
These error s create a ModuleNotFoundError which is handled by our lazy_loading code. The error message in that code tries to provide information about the `context` of the error, but in this case the context's value is `None`. So I added a hack to handle the None allowing the error message to be created in cases where the context is None.

Improve error messages for misconfigured backend treatment

---

networkx/algorithms/traversal/breadth_first_search.py

Updates the `generic_bfs_edges` docstring examples to better demonstrate the parameters.

DOC: Add example to generic_bfs_edges to demonstrate the `neighbors` param

---

networkx/generators/classic.py
networkx/generators/tests/test_classic.py

A very minor followup to #6999. All of the test suite changes are in 2aa6953 - I'm happy to break that out into a separate PR if they need a closer look!

MAINT: Minor touchups to tadpole and lollipop graph

---

networkx/algorithms/components/connected.py

Previously, it was relying on a call to `connected_components` to check the graph type, but this doesn't work well when dispatching to a backend. Also, fix an exception message.

Add `@not_implemented_for("directed")` to `number_connected_components`

---

networkx/algorithms/distance_measures.py

#6925 improved the `resistance_distance`.
I already removed some old code in #7053, but this PR removes a no-longer-used auxiliary function.

remove unused code

---

doc/developer/deprecations.rst
networkx/algorithms/tests/test_triads.py
networkx/algorithms/triads.py
networkx/conftest.py

Proposal to remove the `triads.all_triplets` function, which is simply an alias for `itertools.combinations(G, 3)`.
`all_triplets` is not even used internally in the `triads` module, so AFAICT there is no special meaning attached to the term "graph triplets" - please correct me if I'm wrong!

DEP: Deprecate the all_triplets one-liner.

---

networkx/algorithms/traversal/beamsearch.py
networkx/algorithms/traversal/tests/test_beamsearch.py

A few minor changes to the beamsearch module and test suite. The biggest change is the addition of the note to the docstring which attempts to explain the difference between `bfs_beam_edges` and `bfs_edges`.

Minor touchups to the beamsearch module

---

examples/drawing/plot_clusters.py

An alternative to #6923 - adds an example to the gallery with a recipe for visualizing node clusters. This is just a slightly more polished version of [the example I left in #6923](https://github.com/networkx/networkx/pull/6923#issuecomment-1716292391).
The advantage of this approach is that it generalizes to multiple layers of clustering. The example only shows one layer, but if it's preferred I can make sub-clusters within the three communities instead (at the expense of a bit more complexity in the example).
Also, if anyone has suggestions for a better example graph for finding communities, let me know!

Hierarchical clustering layout gallery example

---

networkx/algorithms/centrality/katz.py

Issue  #6279 reported a sentence in the documentation of the method stating
>  When $\alpha = 1/\lambda_{\max}$ and $\beta=0$, Katz centrality is the same 
>      as eigenvector centrality. 
I replaced $\beta=0$ with $\beta=1$, according to the issue's suggestion (and fixed a small typo along the way).

Fixed an error in the documentation of the katz centrality

---

pyproject.toml
requirements/doc.txt

This upper pin is no longer needed, see #7082.

Remove nbconvert upper pin (revert #6984)

---

.github/workflows/test.yml

Related to #7064 and #7032.
This PR adds a minimal step to the `default` testing job to check for warnings raised at import time. I'm still not able to reproduce #7064 / #7032 locally, so I suspect that they are specific to Python config/environment management systems. Nevertheless, this is a relatively lightweight check that will hopefully help catch any user-facing import warnings prior to releases.
If anyone has ideas how this can be made more robust, please chime in!

Add a step to CI to check for warnings at import time.

---

networkx/algorithms/shortest_paths/astar.py
networkx/algorithms/shortest_paths/tests/test_astar.py

Added a cutoff to limit the exploration of a large, potentially disconnected graph. The use-case is highlighted in https://github.com/networkx/networkx/discussions/7026.
Reasoning for implementing this in A-star:
It is not directly mentioned in papers that a cutoff can be added. However, since it's not an unknown concept (as also implemented in Dijkstra), I think the [original paper on A-star](https://sci-hub.se/10.1109/TSSC.1968.300136) highlights it the best. Going by the definition of the evaluation function f:
$f(n) = g(n) + h(n)$
where $g(n)$ is the actual cost from source to $n$ and $h(n)$ is the actual cost of an optimal path from $n$ to the target.
It is then given for A* to be admissible that our heuristic $h'(n)$ must be $h'(n) <= h(n)$. I.e. when $g(n) + h'(n) > cutoff$, we are …

[A-star] Added expansion pruning via cutoff if cutoff is provided

---

networkx/algorithms/link_analysis/hits_alg.py
networkx/algorithms/link_analysis/tests/test_hits.py

Specifically, instead of raising `ValueError` or `sp.sparse.linalg.ArpackNoConvergence`, change `nx.hits` to raise `nx.PowerIterationFailedConvergence` just like other algorithms that have power iterations. This makes it easier for backends to raise consistent exceptions (`ArpackNoConvergence` is particularly awkward to match).

Make HITS raise exceptions consistent with power iterations

---

networkx/algorithms/community/modularity_max.py
networkx/algorithms/community/tests/test_modularity_max.py

Hi, This fork addresses issue https://github.com/networkx/networkx/issues/5562 using the solution proposed by [dschult](https://github.com/dschult) in the issue discussion. But like [j-hap](https://github.com/j-hap) mentions the error still gets thrown by any downstream functions like `networkx.algorithms.community.quality.modularity` that the result gets passed to.
If there are any changes that need to be made, I'd be happy to add those to my PR
Closes #5562

Handle edge cases for greedy_modularity_communities

---

networkx/classes/filters.py

DOC: Add docstrings to filter view functions  

---

networkx/classes/coreviews.py

DOC: Add docstrings to Filter mapping views

---

.github/workflows/test.yml

Python 3.13.0-alpha1 was made available recently:
https://github.com/actions/python-versions/releases/tag/3.13.0-alpha.1-6531259803
See #7089.

Test on Python 3.13-dev

---

doc/developer/deprecations.rst
networkx/algorithms/tests/test_triads.py
networkx/algorithms/triads.py
networkx/conftest.py

Another proposal for deprecation in the `triads` module. This is another one-liner "helper function". It doesn't appear to have any special meaning w.r.t triadic analysis and isn't used at all internally. The one caveat here though is that unlike "triplets" (see #7060), triads are only defined for directed graphs. In other words, if a user did `nx.subgraph(G, random.sample(list(G), 3))` and `G` *wasn't* a directed graph, then this would technically not be a triad (at least given the current definitions - see #4386 for related discussion).

DEP: Deprecate random_triad

---

networkx/algorithms/operators/binary.py
networkx/algorithms/operators/tests/test_binary.py

As pointed out by @eriknw in https://github.com/networkx/networkx/pull/7066#discussion_r1374017287, we weren't following our own docs :)

FIX: Match the doc description while copying over data

---

networkx/algorithms/approximation/traveling_salesman.py

Closes #6748
Added the following note in the docstring of `traveling_salesman_problem()` function:
```
(Note: If the graph contains any triangle inequalities then it might return a minimal 
approximate cycle with repeating nodes(other than the starting node).)
```
should we also put a warning message here? because TSP makes sense only for valid graphs, without triangle inequalities. Please let me know what you think.
Thank you :)

added note for the triangle inequality case in TSP

---

doc/developer/new_contributor_faq.rst

Adds a blurb to the "new algorithm policy" question of the new contributor FAQ.

Add note about importance of testing to contributor guide

---

doc/developer/projects.rst

Per discussions at this week's [community meeting](https://github.com/networkx/archive/blob/main/meetings/2023-11-08.md).

Proposal to add centrality overview to mentored projects.

---

networkx/readwrite/graphml.py

Changed arguments list of GraphMLWriterLxml.dump to be consistent with the type of GraphMLWriter.dump. Otherwise, if we have some GraphMLWriterLxml A, and some user calls A.dump(stream) (maybe in the context of a function which takes a GraphMLWriter) then it will throw an error.
This also makes static analysis tools happier, which reduces the amount of things to look at when debugging.

Changed arguments list of GraphMLWriterLxml.dump()

---

doc/reference/readwrite/dot.rst
doc/reference/readwrite/index.rst

Addresses #4311, though probably doesn't close it.
[One of the suggestions](https://github.com/networkx/networkx/issues/4311#issuecomment-720019303) is to add NetworkX's functionality related to I/O from DOT files to the `readwrite` section of the refguide. This will make the DOT I/O functionality more discoverable for users who are interested in reading/writing graphs in DOT format.

Add dot io to readwrite

---

networkx/readwrite/graphml.py

Fixes a small issue when calling `networkx.write_graphml` on a graph with invalid attribute types (e.g., a `list`).
The exception message raised by networkx currently displays an unhelpful error message, which reads:
```
TypeError: GraphML does not support type <class 'type'> as data values.
```
This PR simply fixes it to display the object type that is causing the exception, such as in:
```
TypeError: GraphML does not support type <class 'list'> as data values.
```

`write_graphml`: Small fix for object type description on `TypeError` exception

---

networkx/algorithms/core.py
networkx/algorithms/tests/test_core.py

1. Added examples for `core_number(G)` and `k_core(G, k)` algorithms.
2. <strike>Added `@not_implemented_for("multigraph")` to `k_core()` , `k_shell()` , `k_crust()` and `k_corona()`</strike>

updated functions in `core.py`

---

networkx/classes/function.py

This links the functions.py docstrings to the base Graph class, should resolve https://github.com/networkx/networkx/issues/7124

DOC: Link methods in functions to base Graph methods/properties

---

networkx/algorithms/shortest_paths/tests/test_generic.py
networkx/algorithms/simple_paths.py
networkx/algorithms/tests/test_cycles.py
networkx/algorithms/tests/test_simple_paths.py

The source being one of the targets shouldn't automatically exclude all other solutions.
Closes #6690, closes #6732

fix: Include singleton/trivial paths in all_simple_paths & other functions

---

.github/workflows/label-check.yml

Make label check activate on each push
(currently red x disappears after first run because not rerun on push)
I also renamed the label check so it hopefully makes it clear that a reviewer gives the label.
Other name suggestions welcome. I tried to keep it under 20 chars.

label check on push and change check name

---

doc/developer/deprecations.rst
networkx/algorithms/core.py
networkx/algorithms/tests/test_core.py
networkx/conftest.py

In the first commit, I have deprecated the behavior of the above four `k_` functions to not take a `MultiGraph` object as an argument. 
The above four functions are not defined for a multigraph so it would be appropriate to add a `not_implemented_for("multigraph”)` decorator and strictly not allow a `MultiGraph` object to avoid any confusion about multigraph and `MultiGraph` class. 
Also, when the `core_number` dictionary is not passed as an argument in these functions and a `MultiGraph` object is passed, then a `NetworkXNotImplemented` exception is raised. But, when the `core_number` dictionary is given then the same `MultiGraph` graph won't raise any exceptions. So, to avoid this kind of inconsistent behavior we should add the decorator. 
In the second commit, I have just added some …

DEP : adding `not_implemented_for("multigraph”)` to `k_core`, `k_shell`, `k_crust` and `k_corona` 

---

.github/workflows/label-check.yml

the push trigger occurs even if it is not a pull_request.
So we need to use a pull request action rather than push.
This PR tries to add the pull_request type `edited` instead of push.

Add label check when pull request is edited instead of push

---

doc/reference/linalg.rst

Following #7065
Add missing link in documentation to `total_spanning_tree_weight`.

Add doc total_spanning_tree_weight

---

networkx/algorithms/triads.py

With this contribution I have updated the documentation for triadic census to handle directed graphs. 
The update is in the Notes section of the triadic_census and the text added is as follows: 
For undirected graphs, the triadic census can be computed by first converting
the graph into a directed graph using the ``G.to_directed()`` method. Afther this conversion,
only the triad types 003, 102, 201 and 300 will be present in the undirected scenario.
Closes #4386

update triadic_census documentation for undirected graphs - issue 4386

---

networkx/algorithms/flow/dinitz_alg.py

[Edited by dschult: text added from email to the NetworkX-discuss list from @YVWX ]
just made a PR (#6968). I find the current implementation of Dinitz's algorithm is actually an Edmonds-Karp algorithm, so I try to make a change.
The second issue is about the documentation. There is a shortest_augmenting_path algorithm. As I see, the core part of the algorithm is the same as Edmonds_Karp. However, its time complexity mentioned in the user guide differs from Edmonds_Karp (O(n^2m) and O(nm^2)). Could you help check this problem?
Thank you in advance!

Dinitz correction

---

networkx/algorithms/bipartite/generators.py
networkx/algorithms/operators/binary.py
networkx/algorithms/operators/product.py
networkx/algorithms/regular.py
networkx/algorithms/triads.py
networkx/classes/tests/test_backends.py
networkx/generators/classic.py
networkx/generators/ego.py
networkx/generators/lattice.py
networkx/utils/backends.py

This is an alternative to #7063 and is much more general.
The backend testing infrastructure can call backend graph generator functions such as `circular_ladder_graph`, and it converts the backend Graph to a networkx Graph. This is a great way to test backend generators! However, sometimes iteration order is different when using the converted backend graph. So, our solution here is to *also* call the original networkx function when the return type is a Graph, compare results, then use the result from networkx to allow tests to pass. We use a series of assertions to help backend implementers identify differences.

Compare graphs for generator functions when running tests with backend

---

doc/reference/algorithms/dag.rst
networkx/algorithms/cycles.py
networkx/algorithms/dag.py

This should fix https://github.com/networkx/networkx/issues/7150 atleast in networkx docs (not the root cause in sphinx). I also found that `compute_v_structures` wasn't properly listed in the reference docs.

DOC: fix URL econded links and doc references

---

networkx/algorithms/centrality/reaching.py
networkx/algorithms/shortest_paths/generic.py
networkx/algorithms/shortest_paths/tests/test_generic.py
networkx/algorithms/shortest_paths/tests/test_unweighted.py
networkx/algorithms/shortest_paths/unweighted.py

Fixes: #6527 
Deprecation warnings for this added in #6567   This should be merged in v3.3
Changed the output of `single_target_shortest_path_length` to dictionary, and of `shortest_path` to iterator. The test cases have also been modified accordingly.
This makes the shortest path methods more consistent.

Changed return types of shortest path methods to improve consistency

---

networkx/algorithms/isomorphism/tests/test_isomorphism.py

Adding some basic test coverage while looking at Networkx. First time contributing to nx so let me know if there's anything I missed in the guidelines and I'll fix it!

adding test coverage for isomorphism when using digraphs

---

networkx/algorithms/approximation/treewidth.py
networkx/algorithms/centrality/voterank_alg.py
networkx/algorithms/cluster.py
networkx/algorithms/coloring/greedy_coloring.py
networkx/algorithms/coloring/tests/test_coloring.py
networkx/algorithms/community/asyn_fluid.py
networkx/algorithms/community/label_propagation.py
networkx/algorithms/community/louvain.py
networkx/algorithms/core.py
networkx/algorithms/dominating.py
networkx/algorithms/graph_hashing.py
networkx/algorithms/isomorphism/ismags.py
networkx/algorithms/isomorphism/vf2pp.py
networkx/algorithms/matching.py
networkx/algorithms/planar_drawing.py
networkx/algorithms/similarity.py
networkx/algorithms/sparsifiers.py
networkx/algorithms/summarization.py
networkx/algorithms/tests/test_mis.py
networkx/classes/graph.py
networkx/generators/duplication.py
networkx/generators/line.py
networkx/generators/random_graphs.py

This addresses the comment by @dschult https://github.com/networkx/networkx/pull/4308#issuecomment-730305251 and also builds on top of https://github.com/networkx/networkx/pull/4309

 DOC: consistent spelling of neighbor and rename vars 

---

.pre-commit-config.yaml
networkx/algorithms/assortativity/correlation.py
networkx/algorithms/isomorphism/ismags.py
networkx/algorithms/isomorphism/tests/test_vf2pp_helpers.py
networkx/algorithms/shortest_paths/generic.py
networkx/algorithms/tests/test_bridges.py
networkx/utils/tests/test_misc.py

The [ruff formatter ](https://docs.astral.sh/ruff/formatter/)is in "production-ready beta" now, and it's supposed to be a [99% drop in replacement for black](https://docs.astral.sh/ruff/formatter/#black-compatibility).
I ran our codebase with the ruff formatter and it makes minimal changes to our black formatted codebase and it's much faster than the black formatter (it still follows the black spec).
We still will depend on blacken-docs for now. They are still finialising support for formatting code inside docstrings (https://github.com/astral-sh/ruff/issues/8908).

MAINT: use ruff format instead of black

---

networkx/readwrite/tests/test_gml.py

Modify GML test to fix invalid octal character warning.

---

doc/developer/deprecations.rst
networkx/algorithms/shortest_paths/generic.py
networkx/algorithms/shortest_paths/unweighted.py
networkx/conftest.py

As discussed in the community meeting, this PR ensures[^1] that visible warnings will be raised notifying users of proposed changes to the return type of `shortest_path` and `single_target_shortest_path_length`.
I also went ahead and made a couple additional changes to the warning:
- I changed the type from `DeprecationWarning` -> `FutureWarning` since the only thing changing is the return type rather than something being removed from the API
- I reset the deprecation cycle to the current release; i.e. the warning will be raised for 2 cycles (3.3 and 3.4) then the behavior change implemented in 3.5
- Finally, I beefed up the text for the `shortest_path` warning. I wanted to illustrate that it's possible to future proof your code now by wrapping `shortest_path` in `dict` (since …

Ensure warnings related to changes in shortest_path returns are visible to users

---

networkx/algorithms/chordal.py
networkx/algorithms/components/tests/test_strongly_connected.py
networkx/algorithms/components/tests/test_weakly_connected.py
networkx/algorithms/dag.py
networkx/algorithms/distance_regular.py
networkx/algorithms/regular.py
networkx/algorithms/tests/test_dag.py
networkx/algorithms/tests/test_distance_regular.py
networkx/algorithms/tests/test_euler.py
networkx/algorithms/tests/test_regular.py
networkx/algorithms/tree/tests/test_recognition.py

Currently we get very different answers if we use a `nx.is_something()` method with an empty graph. This PR tries to sync them up. It's still not synced up, we should probably decide on one behavior.
Current:
- `is_aperiodic` -> StopIteration (empty digraph)
- `is_arborescence` -> NetworkXPointlessConcept: G has no nodes.
- `is_branching` -> NetworkXPointlessConcept: G has no nodes.
- `is_chordal` -> StopIteration
- `is_connected` -> NetworkXPointlessConcept: ('Connectivity is undefined ', 'for the null graph.')
- `is_distance_regular` -> StopIteration
- `is_eulerian` -> NetworkXPointlessConcept: ('Connectivity is undefined ', 'for the null graph.')
- `is_forest` -> NetworkXPointlessConcept: G has no nodes.
- `is_regular` -> StopIteration
- ` is_semiconnected` -> NetworkXPointlessConcept: …

Sync up behavior of is_{type} for empty graphs

---

doc/conf.py
networkx/generators/classic.py

Builds on top of https://github.com/networkx/networkx/pull/6401
I have added a seed and removed the links to download script/png/pdf from the doc build. IMO we should be using this to just quickly show how the graph looks like, we don't need to worry about making this reproducible on a pixel level.

DOC: Add plots to classic graph generators docs

---

networkx/algorithms/approximation/maxcut.py
networkx/algorithms/approximation/tests/test_maxcut.py
networkx/algorithms/community/asyn_fluid.py
networkx/algorithms/community/tests/test_asyn_fluid.py
networkx/algorithms/distance_regular.py
networkx/algorithms/isomorphism/tests/test_tree_isomorphism.py
networkx/algorithms/isomorphism/tree_isomorphism.py
networkx/algorithms/tests/test_distance_regular.py

Fix not_implemented_for decorator for is_regular and related functions

---

networkx/algorithms/connectivity/kcutsets.py
networkx/algorithms/connectivity/tests/test_kcutsets.py

Closes #6533 
I modified the special condition for complete graphs in `all_node_cuts` to return an empty generator and also changed the test cases accordingly.

Fix all_node_cuts output for complete graphs

---

networkx/algorithms/structuralholes.py

To fix a tiny typo in `structuralholes.py::local_constraint` docstring.

Fix a tiny typo in `structuralholes.py::local_constraint` docstring

---

networkx/utils/backends.py

I had to move the class docstring to the docstring of the `__new__` method, because we define `__doc__` property later in the class.

Fix online docs for `_dispatch`

---

networkx/utils/backends.py

Use `"networkx.backends"` and `"networkx.backend_info"` instead. Version 3.2 supports both options. The next release can drop "plugin".
I forgot to do this in #7157, which made a similar change.

Remove `"networkx.plugins"` and `"networkx.plugin_info"` entry-points

---

networkx/algorithms/components/tests/test_strongly_connected.py
networkx/drawing/tests/test_agraph.py

There is a release candidate for Pytest v8 for which two of NX's tests were failing. This PR makes the necessary updates to be pytest-8 compatible:
- f537f0b removes a `pytest.deprecated_call` check from a test which raises an exception. It turns out this never raised the warning as it hits the exception first, it's just that pytest v7 never caught this case. 
- 7fe9c50 replaces the deprecated `pytest.warns(None)` pattern with the recommended `warnings.catch_warnings()` context manager.

Update test suite for Pytest v8

---

networkx/algorithms/centrality/group.py
networkx/conftest.py
networkx/generators/expanders.py

This PR fixes the warnings seen in the test suite from the nightly wheels of the default dependencies. Other improvements include:
- A fix to one of the warning filters in the test config
- Seeding a doctest to avoid intermittent failures

Future-proofing and improve tests

---

networkx/generators/tests/test_geometric.py

#6858 added the `geometric_soft_configuration_model` generator, which included several tests that generated graphs with >1k nodes. These tests were quite slow:
```bash
$ pytest --durations 4 networkx/generators/tests/test_geometric.py
...
4.07s call     networkx/generators/tests/test_geometric.py::test_mean_degree_S1
4.06s call     networkx/generators/tests/test_geometric.py::test_mean_kappas_S1
1.34s call     networkx/generators/tests/test_geometric.py::test_compare_mean_kappas_different_gammas_S1
0.18s call     networkx/generators/tests/test_geometric.py::test_dict_kappas_S1
```
These could be decorated with `pytest.mark.slow`, but then they'd still be running in the coverage job in CI. Since the tests are pseudo-stochastic anyways (i.e. they test average properties of graphs created …

Refactor geometric_soft_configuration_model tests for performance

---

networkx/algorithms/planar_drawing.py
networkx/algorithms/planarity.py
networkx/algorithms/tests/test_planarity.py

The use of a node attribute called `"first_nbr"` makes it impossible to represent a valid PlanarEmbedding with a dict_of_dicts. This complicates the creation of valid and invalid embeddings for testing purposes, particularly if the changes in the PR to solve issue #6798 (which forbids the use of `PlanarEmbedding.add_edge*`) are merged.
The attribute `"first_nbr"` seems to be relevant only to `LRPlanarity.lr_planarity()` and the way the methods `add_half_edge_first()` and `add_half_edge_ccw()` update that attribute are quite unintuitive and undocumented. This means I doubt there is someone out there relying on this attribute
This PR introduces a new method `add_half_edge()`, which covers the functionality of `add_half_edge_cw()`, `add_half_edge_ccw()` and `add_half_edge_first()` while …

feat: drop the use of node attribute "first_nbr" in PlanarEmbedding

---

networkx/algorithms/tree/mst.py
networkx/algorithms/tree/tests/test_mst.py

Partial fix for issue #6920 for random_spanning_tree() by checking explicitly for empty and single node graphs. Earlier, the main for loop was the only return path, and these edge cases would cause an Exception meant for trees with less edges.

Fix random_spanning_tree() for single node and empty graphs

---

.circleci/config.yml
.github/workflows/deploy-docs.yml

This should let us add information about nx-parallel implementation in the main networkx.org doc website. https://github.com/networkx/nx-parallel/pull/27 adds the `backend_info` entry point for nx-parallel.

DOC: build with nx-parallel extra documentation information

---

networkx/algorithms/bipartite/tests/test_edgelist.py
networkx/drawing/tests/test_agraph.py
networkx/drawing/tests/test_pydot.py
networkx/readwrite/tests/test_adjlist.py
networkx/readwrite/tests/test_edgelist.py
networkx/readwrite/tests/test_gml.py
networkx/readwrite/tests/test_graph6.py
networkx/readwrite/tests/test_graphml.py
networkx/readwrite/tests/test_pajek.py
networkx/readwrite/tests/test_sparse6.py

An alternative to #6554 which removes `tempfile` entirely in favor of the [`tmp_path` fixture](https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html#the-tmp-path-fixture) in the test suite.

Replace tempfile with tmp_path fixture in test suite.

---

LICENSE.txt
README.rst

2024 version of the basic copyright bumping chore (#6322). If anyone knows of an action or linting rule that handles this automatically LMK!

Bump copyright year for 2024.

---

networkx/algorithms/tests/test_swap.py

Fixes #7236 
One of the test graphs is currently random graphs and that sometimes affects the `max_tries` count needed for the `directed_edge_swap` to be successful.  I added seed to the graph creation call so the tests become deterministic.
[Edited -- only one graph creation routine needed seed added: `random_tree`]

add seed to graph creation

---

networkx/algorithms/community/tests/test_label_propagation.py

Add seed to tests of `fast_label_propatation_communities`
These tests were sometimes failing.
Fixes #7240

add seed to tests of fast_label_propatation_communities

---

networkx/algorithms/connectivity/edge_kcomponents.py

Minor updates to docstring:
* Adds a parameters section
* `Returns` -> `Yields` and update wording to clarify that graphs are yielded, not node sets
* Fix format of links to references
* Update example to use comprehension instead of `map`
Closes #7253

Update general_k_edge_subgraphs docstring.

---

networkx/generators/tests/test_small.py

I have increased test coverage for small.py according to here :- 
https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/generators/small.py
I would love a review on this and do any changes if required!

Improving test coverage for Small.py

---

networkx/algorithms/richclub.py
networkx/algorithms/tests/test_richclub.py
networkx/classes/function.py
networkx/classes/tests/test_function.py

Partial fix for issue #6920 rich_club_coefficient() bugs
For the empty graph, degree_histogram() errors out when using max() on an empty collections.Counter. This is fixed by explicitly checking the condition of non-empty counter
For the single node graph, _compute_rc() errors out where edge_degrees is popped just before the for loop. This assumes that there is at least 1 edge in the graph. For edgeless graphs, rich club coefficient dictionary should probably be empty since it is defined only for non-negative degree values d where there exist at least 2 nodes of degree > d. In an edgeless graph, there are no such nodes for any non-negative d. This is fixed by explicitly checking the edge count before the pop

Fix rich_club_coefficient() for single node and empty graphs

---

networkx/algorithms/community/tests/test_divisive.py

closes https://github.com/networkx/nx-parallel/issues/36

Test for symmetric edge flow betweenness partition

---

networkx/algorithms/community/tests/test_label_propagation.py

ref. https://github.com/networkx/nx-parallel/actions/runs/7741216722/job/21107789475?pr=32
<details>
<summary>Error msg </summary>
```
=========================== short test summary info ===========================
FAILED algorithms/community/tests/test_label_propagation.py::TestFastLabelPropagationCommunities::test_random_graph - assert {frozenset({2...13, 14, ...})} == {frozenset({0..., 4, 5, ...})}
Extra items in the left set:
frozenset({2, 3, 6, 7, 8, 9, ...})
frozenset({0, 1, 4, 5, 13, 14, ...})
Extra items in the right set:
frozenset({0, 1, 2, 3, 4, 5, ...})
Full diff:
{
frozenset({
-         0,
-         1,
2,
3,
-         4,
-         5,
6,
7,
8,
9,
10,
11,
12,
-         13,
-         14,
-         15,
16,
-         17,
-         18,
19,
-         20,
21,
-         22,
23,
- …
```

MAINT : added `seed` to `gnm_random_graph` in `community/tests/test_label_propagation.py`

---

benchmarks/benchmarks/benchmark_neighbors.py
networkx/algorithms/link_prediction.py
networkx/classes/function.py
networkx/classes/tests/test_function.py

I'm not sure why we should not use direct set operations on the `_adj` dictionary to find common neighbors. This will require a deprecation probably as we will change the behavior of the return type (`generator` to `set`).
This was spurred by https://github.com/networkx/networkx/discussions/7243.

ENH: Speed up common/non_neighbors by using _adj dict operations

---

networkx/generators/nonisomorphic_trees.py

Update docstring of nonisomorphic_trees.

---

networkx/algorithms/cycles.py

Minor doc improvement related to #7272 - adds `minimum_cycle_basis` to the `See Also` section of `cycle_basis` (thanks @boothby !)

Add minimum_cycle_basis to cycle_basis See Also.

---

examples/3d_drawing/plot_3d_rotation_animation.py
networkx/algorithms/operators/product.py
networkx/generators/nonisomorphic_trees.py

Fix all sphinx warnings related specifically to formatting issues in docstrings. There are still a lot of extraneous warnings from plotting, but those are covered in issue #7284 and should be handled separately.

Fix all sphinx warnings during doc build.

---

networkx/generators/tests/test_random_clustered.py

I have increased test coverage for random_clustered.py according to here at 93.55%:-
https://app.codecov.io/gh/networkx/networkx/blob/main/networkx%2Fgenerators%2Frandom_clustered.py
It is now at a 100% as seen below :- 
I have also renamed functions to follow better coding practices.

Improve test coverage for random_clustered and update function names

---

networkx/algorithms/tree/branchings.py
networkx/algorithms/tree/tests/test_branchings.py

Attempts to fix https://github.com/networkx/networkx/issues/7279
It looks like the code for `minimal_branching` and a bunch of other algorithms access the weight attribute `attr` directrly from node or edge data `d` via `d[attr]` and does not respect the specified `default` value provided in the signature.
This PR does fix the issue by replacing these with `d.get(attr, default)`, but I'm not sure it does it correctly. Looking at the code, I'm not sure the algorithm structures ever used something like `d.get(attr, default)`, instead it looks like the "dispatch" decorator is ensuring the graph structure is ammenable to this sort of direct lookup (perhaps for efficiency?). I don't understand the dispatch structure well enough to say for sure. Advice and / or pointers to docs would be …

Fix minimum_spanning_arborescence regression

---

networkx/drawing/nx_pylab.py
networkx/drawing/tests/test_pylab.py

Fixes #7284 
A UserWarning is raised on the value of arrowstyle, but the value
is modified internally before this validation is performed.
Move the modification *after* the validation step to suppress the
spurious warnings.

 Move arrowstyle input munging after intput validation. 

---

networkx/algorithms/bipartite/tests/test_extendability.py

I have increased test coverage for extendability.py according to here at 92.59% :-
https://app.codecov.io/gh/networkx/networkx/blob/main/networkx%2Falgorithms%2Fbipartite%2Fextendability.py
I would love a review on this and do any changes if required!

Improve test coverage for bipartite extendability

---

.github/workflows/nightly.yml

* Update the scientific-python/upload-nightly-action to v0.4.0 to avoid issues with uploading wheels of the same name to Anaconda Cloud where the project being uploaded to only contains one wheel (the one being replaced).
- c.f. https://github.com/scientific-python/upload-nightly-action/releases/tag/0.4.0
I know that Dependabot maanges the GitHub Actions updates, but this release was made specifically to try to fix the issues that `networkx` has been having
so I wanted to try to fix this rather than waiting a month.

CI: Update scientific-python/upload-nightly-action from 0.3.0 to 0.4.0

---

networkx/classes/tests/test_backends.py
networkx/utils/backends.py
networkx/utils/decorators.py

`_dispatchable` objects don't look good in REPRs and they make it really awkward for type checkers. This PR uses `argmap` to transmogrify `_dispatchable` objects into functions. I hope to someday understand `argmap`.
@rossbar, this is as discussed in #7185 and the meeting today. Everything looks good in REPRs to me. This PR supercedes #7185.
CC @rlratzel

Transmogrify `_dispatchable` objects into functions

---

networkx/utils/backends.py

Changes made : 
- added `url` : if we would want to link to the function's webpage page(in the future) or source code, right now in nx-parallel I've put the link to the function header(https://github.com/networkx/nx-parallel/pull/47)
-  renamed`extra_parameters` to `additional_parameters`: bcoz "extra" gives a sense that they are not necessary but "additional" gives a sense that they are an added functionality, anyways we can keep it if it's not that big of a change
- renamed `extra_docstring` to `additional_docs` for the similar reason as above
- removed an unused import

renaming backend `func_info` dictionary's keys

---

doc/developer/deprecations.rst
networkx/conftest.py
networkx/generators/nonisomorphic_trees.py
networkx/generators/tests/test_nonisomorphic_trees.py

Deprecate the `create` argument of `nonisomorphic_trees`

---

networkx/algorithms/planarity.py

closes #7223
`PlanarEmbedding` inherits the method `copy()` from `nx.Graph`. However, the current implementation uses the method `add_edges_from()` which was made forbidden by PR #6798.
```python
embedding = nx.PlanarEmbedding({1: {2: {"cw": 2, "ccw": 2}},
2: {1: {"cw": 1, "ccw": 1}}})
emb2 = embedding.copy()
```
```
NotImplementedError: Use `add_half_edge` method to add edges to a PlanarEmbedding.
```

fix: make `PlanarEmbedding.copy()` use `add_edges_from()` from parent (closes #7223)

---

networkx/readwrite/graphml.py
networkx/readwrite/tests/test_graphml.py

Fixes https://github.com/networkx/networkx/issues/7291
networkx does not parse GraphML attributes that are empty.
As a result, they will not be added to the graph.
This fix will create the attribute with an empty string.

Fix empty GraphML attribute is not parsed

---

networkx/algorithms/bipartite/tests/test_matrix.py

I have increased test coverage for matrix.py according to here at 95.12% :-
https://app.codecov.io/gh/networkx/networkx/blob/main/networkx%2Falgorithms%2Fbipartite%2Fmatrix.py
I would love a review on this and do any changes if required!

Improve test coverage for bipartite matrix.py

---

networkx/algorithms/coloring/greedy_coloring.py

Closes #7153 
Removes dispatch decorator from the `strategy_` generators in the greedy-coloring module.

Un-dispatch coloring strategies.

---

networkx/algorithms/shortest_paths/tests/test_unweighted.py
networkx/algorithms/shortest_paths/unweighted.py

Fixes #7315 by reverting the change in return type until the FutureWarning has expired (scheduled for 3.5).
The other possible solution would be to remove the FutureWarning and implement the change now. I don't recall from previous discussions which was the desired course of action, so if I got this wrong please LMK! Either way - the behavior needs to be consistent with the warning (or lack thereof).

Undo change in return type of `single_target_shortest_path_length`

---

networkx/convert_matrix.py

Fixes the test failure from the pandas-3.0 nightly wheel by replacing an assignment to `df.values` (which is becoming read-only) with index assignment via `df.iloc`. This should work both on pandas 2 and 3 - I've tested locally against the pandas-3.0dev nightly and it works as expected. I'm certainly no pandas expert so if there's a better/more idiomatic way to do this please push/suggest!
I also made minor adjustments to the example, including adding a second node with self-loop edges to make the adjacency matrix more interpretable in the repr.
Finally, I went ahead and opened pandas-dev/pandas#57687 to raise awareness about the fact that the behavior change associated with assigning to `.values` does not have an accompanying warning.

Update docstring example with future-proof pandas assignment.

---

doc/conf.py
examples/algorithms/plot_image_segmentation_spectral_graph_partiion.py

Closes #7235 
Removes 3D animation from the image segmentation via spectral clustering gallery example, reducing the runtime by more than 100x so that it is no longer a bottleneck in the doc build (either locally or in CI).
Adds xrefs to the other 3D drawing examples so that users have a recipe for creating animations.

Remove animation from spectral clustering example to improve performance

---

networkx/algorithms/approximation/tests/test_traveling_salesman.py
networkx/algorithms/approximation/traveling_salesman.py

Fixes #5913 
(I hope, since I can't reproduce the bug)

Add new test result to `test_asadpour_tsp` and change `linprog` method

---

networkx/algorithms/approximation/steinertree.py

It looks like a FutureWarning related to changing the default `steiner_tree` method from "kou" -> "mehlhorn" had slipped through the cracks. This PR expires that `FutureWarning` and switches the default (the warning said this would happen in 3.2, but oh well). I also couldn't resist a cosmetic change to remove a local variable.

Expire steinertree mehlhorn futurewarning

---

networkx/generators/small.py

Use numpydoc docstring standard and fixup formatting/examples.

Update `LCF_graph` docstring

---

networkx/algorithms/community/tests/test_louvain.py

Closes #6823 
I'm no expert in community detection, but from reading through the Louvain description (and thinking about the various floating-point issues associated with the modularity calculation) I think using `<=` for this comparison is correct, since equivalence is also "not increasing".

Update louvain test modularity comparison to leq.

---

networkx/algorithms/graph_hashing.py
networkx/algorithms/tests/test_graph_hashing.py

Apologies for the spam folks, I thought I had caught the mistakes in #6598  but had to correct some things further down too - good catch from @dschult in the PR comments.
I've read the whole docstring through a couple of times now and it looks right.

Option to include initial labels in `weisfeiler_lehman_subgraph_hashes`

---

networkx/algorithms/approximation/steinertree.py
networkx/algorithms/approximation/tests/test_steinertree.py

I have increased test coverage for  Steinertree.py according to here :-
https://app.codecov.io/gh/networkx/networkx/blob/main/networkx%2Falgorithms%2Fapproximation%2Fsteinertree.py
It is now at 100% as seen below:- 
I have also added Raises to docstrings and changed the default from kou to mehlhorn according to recent changes.

Improve test coverage for Steiner Tree & Docs

---

networkx/utils/backends.py

This at least partially addresses the errors in #7354. In particular, this fixes the pydot errors.
I don't know how to fix the `agraph` segfaults you see in #7354 @rossbar. You can work around them by removing `pygraphviz` from your environment.
Also, I don't think `pytest-xdist` has anything to do with these errors, but I like the idea of running the dispatch tests with `pytest-xdist` if it makes them faster.

Fix pydot tests when testing backends

---

networkx/classes/function.py

This function may be useful for backends (and _is_ useful for `nx-cugraph`).
We may want to dispatch more functions in `nx.classes.function` after version 3.3 is released. `is_negatively_weighted` and other functions in this file are often plenty fast with the NetworkX implementation, but I think making these dispatchable becomes much more feasible and desirable once we have `should_run` (already in) and caching (coming soon 🤞).
CC @rlratzel

Make `is_negatively_weighted` dispatchable

---

networkx/readwrite/graphml.py

As of Python 3.12, the lxml tree parser raises a warning about evaluating truthiness of elements directly, instead recommending an is not None or len() test. For an example of the warnings, see the warning logs on any of the Python 3.12 tests in actions, e.g. https://github.com/networkx/networkx/actions/runs/8349137374/job/22852640690

Future proof xml parsing in graphml.

---

networkx/drawing/nx_pylab.py
networkx/drawing/tests/test_pylab.py

This PR adds a flag `hide_ticks` to drawing functions so tick labels can be shown. This can be useful for debugging or spatial networks, for example. The default is `hide_ticks=True` to ensure functionality does not change.
*Edit*: I'm not sure why the Circle CI test fails.
*Edit*: It seemed that Circle CI was failing because I hadn't updated my default branch from `master` to `main` yet.

Add option to hide or show tick labels.

---

networkx/drawing/tests/test_pylab.py

Prevents too-many-figures-open warning from the test suite with the matplotlib nightlies. Ultimately the figure handling (i.e. setup/teardown) should be handled in a fixture, but that's an improvement for another PR!

Close figures on test cleanup.

---

networkx/algorithms/approximation/tests/test_traveling_salesman.py
networkx/algorithms/approximation/traveling_salesman.py
networkx/tests/test_all_random_functions.py

The current interface for `traveling_salesman_problem` requires currying, creating a lambda to create a partial application of the fixed arguments for the method. This by itself is totally fine, and very commonly seen in functional programming, but as far as I know this is the only time that behavior appears in NetworkX. 
This PR adds a `**kwargs` to `traveling_salesman_problem` to remove the currying requirement. I've designed it so that existing code shouldn't break, although this does require the extra check for `init_cycle` to remain compatible with the threshold accepting and simulated annealing TSP methods. I thought about changing those methods to have a default argument, which has been considered numerous times, but decided against changing the API. The points raised in the doc …

add **kwargs to traveling_salesman_problem

---

networkx/utils/backends.py

Fixes #7354 
excludes `nx_agraph.read_dot` from backend equivalence checks.
algorithms that accept `TextIOWrapper` arguments ignore this check.
FYI @rossbar @MridulS @eriknw

Fix pygraphviz tests causing segmentation faults in backend test

---

networkx/drawing/layout.py

Handling a new deprecation from the NumPy 2.1 nightlies.
On an unrelated note, matplotlib has released v3.8.4 with support for numpy 2.0. This release (along with the latest mpl 3.9.0dev nightly wheel) fixes the test failures that had been cropping up in `test_pylab` with numpy 2.0. In other words, NX is now green across the board with numpy 2.0, scipy 1.13, and matplotlib 3.8.4!

Rm deprecated np.row_stack in favor of vstack.

---

networkx/utils/configs.py
networkx/utils/tests/test_config.py

Also, make `cfg.__setitem__` (a little) faster.
I forgot to update `__delitem__` when I enabled `strict=False` option for configs.

Fix exception for `del config[key]`

---

doc/reference/algorithms/shortest_paths.rst
doc/release/release_3.3.rst

Follow-up to #5959 - adds `all_pairs_all_shortest_paths` and `single_source_all_shortest_paths` to the reference guide.
I also added a minor rst formatting nit to fixup a few sphinx warnings during doc building.

Document missing shortest_path functions

---

networkx/conftest.py

Followup to #7388 
Additional test-suite config to skip doctests when dependencies aren't installed. The main change is that the docstrings of the `generators/classic.py` graph creation functions now depend on matplotlib with the addition of the `.. plot` directive. IMO this is totally fine and straightforward to skip (see below).
The other two changes are:
- nx_latex docstring depends on numpy
- alphabetizing the `needs_numpy` list.

A few more doctest skips for mpl/np dependencies.

---

networkx/classes/coreviews.py
networkx/classes/filters.py
networkx/classes/graphviews.py

__len__ result is being stored for FilterAdjacency and FilterAtlas
Fixes #7377 
Impacts of dynamic computation of len
---
The class FilterAdjacency is only used in views and therefore only works on frozen sets of edges and nodes. Despite that its __len__ function is recalculated each time it is called instead of it being calculated and stored once upon its first call.
__len__ of FilterAdjacency is recalculated unnecessarily upon each call using up 80% of runtime for my application.
__len__ of FilterAdjacency should calculated and stored once upon its first call. For all other calls the stored value is returned.
Any use of nx.subgraph_view shows this behaviour. Very poor performance shows in my case for number of nodes > 100.000.
Should be completely independent of env.
Python version: …

FilterAdjacency: __len__ is recalculated unnecessarily #7377

---

networkx/convert_matrix.py
networkx/tests/test_convert_numpy.py
networkx/tests/test_convert_pandas.py

Adds a kwarg to allow users to specify a sequence of nodes which map to the dimensions of the adjacency matrix. The mapping implicitly relies on the ordering of the nodes in the adjacency matrix, i.e. `node_labels[0] -> row 0`, `node_labels[1] -> row 1`, etc.
I'm not sure about the name of the kwarg. One motivating factor for this proposal is it fixes #7407 in an efficient way. I've added that change in a1a17ac7, but I'm happy to break that into a separate PR in order to focus on the new feature proposal!

Add a `nodelist` feature to `from_numpy_array`

---

doc/developer/deprecations.rst
networkx/conftest.py
networkx/readwrite/tests/test_text.py
networkx/readwrite/text.py

This was supposed to make it into 3.3 (oops), but better late than never! Removes `forest_str` in favor of `generate_network_text` as the deprecation message specifies.
I went ahead and updated the `forest_str` tests to use `generate_network_text` (rather than delete them) to verify that `generate_network_text` works as expected as a replacement for those use-cases. For tests that probed features/exceptions specific to `forest_str`, I went ahead and removed them. I also snuck in a commit to rm remaining extraneous print statements from the readwrite test suite.

Expires the `forest_str` deprecation

---

networkx/algorithms/hierarchy.py
networkx/algorithms/tests/test_hierarchy.py

The following snippet produces a division by zero error due to the lack of null graph catching condition, I just added it and updated the tests :) 
```py
G = nx.DiGraph()
G.add_node(1)
print(nx.flow_hierarchy(G))
```

Add check for empty graphs in `flow_hierarchy`

---

networkx/convert.py

Fixes #7401
This replaces the ImportWarnings with `pass` in the case when the environment doesn't have pandas or numpy or scipy installed. The idea is that this removes unwanted warnings without causing any surprises (the user could not be using an input that is a pandas/numpy/scipy object type because they library isn't installed).
Further improvements involve changing the order of consideration in `to_networkx_graph` so that common cases are caught first. That is a separate PR #7424

Remove import warnings during to_networkx_graph conversion

---

networkx/algorithms/approximation/tests/test_traveling_salesman.py

Minor follow-up to #7412, which added the `nodelist` kwarg to `from_numpy_array`. I did a quick grep through the library to see if there were any opportunities to apply it internally and these are the only instances I found.

Use nodelist feature of from_numpy_array.

---

examples/algorithms/plot_lca.py
networkx/algorithms/tests/test_cycles.py
networkx/algorithms/tests/test_swap.py
networkx/tests/test_all_random_functions.py

Replaces the remaining usages of the deprecated `random_tree` with `random_labeled_tree`.

Cleanup remaining usages of deprecated `random_tree` in package

---

benchmarks/benchmarks/benchmark_to_networkx_graph.py
networkx/classes/reportviews.py
networkx/classes/tests/test_reportviews.py
networkx/convert.py

This PR was originally motivated by #7401. The main issue there is the extraneous `ImportWarning` s that are raised by `to_networkx_graph` (often via the graph constructors) when creating graphs in an environment without the default dependencies (numpy, scipy, pandas). This is the case because converting from these data structures is actually attempted *before* attempting to interpret the input as an edgelist. However, creating a graph from an edge list (or edgelist-like, such as an EdgeView or generator of edges) is a very common operation - certainly much more so than from numpy/scipy/pandas objects within NetworkX itself. This latter point can be demonstrated relatively simply: see https://github.com/networkx/networkx/pull/7402#issuecomment-2048157399.
I wanted to investigate whether …

Prioritize edgelist representations in `to_networkx_graph`

---

networkx/classes/digraph.py
networkx/classes/graph.py
networkx/classes/tests/dispatch_interface.py
networkx/utils/backends.py

This rewrites the copy functionality within nx-loopback to ensure that the neighbor order is the same in the copy. Instead of copying edges, this copies adjacencies (careful to ensure opposite representations of an edge point to the same datadict).
The result is that the incoming PR for fixing colliders and v-structures passes its tests.
Also, dfs_labeled_edges test passes. In fact all the topological sort functions that were excluded pass the tests as well, though I'm not sure whether we should still exclude them from the nx-loopback tests because I don't know what the issue was regarding the function changing the original graph. E.g. maybe we shouldn't be copying the graph at all since it needs to be changed.
~~This also seems to fix the long time for the nx-loopback tests. It is still …

retain adjacency order in nx-loopback copy of networkx graph

---

.gitignore

Very minor improvements to the development workflow related to benchmarking.
Running `asv` locally to do comparison benchmarks ends up generating files/dirs in the `benchmarks/` folder. This PR adds those generated files to `.gitignore`. I've only captured the files generated from local workflows (e.g. `asv run`, `asv continuous` and `asv compare`). There may be others for other workflows, in which case please feel free to add them here (@MridulS ).

DEV: Add files generated by benchmarking to .gitignore.

---

networkx/algorithms/bridges.py

Remove redundant graph copy in `algorithms.bridges.bridges()`

---

.github/workflows/release.yml

* Add generation of GitHub artifact attestations to built sdist and wheel before upload. c.f.:
- https://github.blog/2024-05-02-introducing-artifact-attestations-now-in-public-beta/
- https://docs.github.com/en/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds
This PR is related to https://github.com/scientific-python/summit-2024/issues/9 so cc @MridulS and @jarrodmillman for review.

CI: Add GitHub artifact attestations to package distribution

---

doc/conf.py
pyproject.toml
requirements/doc.txt

Makes use of the centralized intersphinx db provided/maintained by [intersphinx_registry](https://pypi.org/project/intersphinx_registry/). IMO this is a nice convenience!

Use intersphinx_registry to manage intersphinx mapping.

---

networkx/classes/tests/dispatch_interface.py
networkx/utils/tests/test_backends.py
pyproject.toml

from PR https://github.com/networkx/networkx/pull/7404
(ref. [review comment](https://github.com/networkx/networkx/pull/7404#discussion_r1610816636))

MAINT: Renaming `LoopbackDispatcher` to `LoopbackBackendInterface` and `dispatcher` to `backend_interface`

---

.github/workflows/test.yml

See discussion in https://github.com/networkx/networkx/pull/7495,
This is failing on main, but the error is just swallowed. Split int two step to see if we can actually see the failure in CI
See for example https://github.com/networkx/networkx/actions/runs/9584451708/job/26428116613 (current main), which is green but says:
ERROR: Could not build wheels for pygraphviz, which is required to install pyproject.toml-based projects
Failed to build pygraphviz

Fix pygraphviz install on Windows

---

doc/developer/deprecations.rst
doc/reference/algorithms/dag.rst
networkx/algorithms/__init__.py
networkx/algorithms/dag.py
networkx/algorithms/tests/test_dag.py
networkx/conftest.py

closes https://github.com/networkx/networkx/issues/7385
<strike>
previously `compute_v_structures` was computing colliders. Now, I've renamed `compute_v_structures` to `compute_colliders`(and updated its implementation too) and added the correct implementation for `compute_v_structures`. Also, updated and added the relevant docs and tests.
</strike>
Thank you :)

[ENH, BUG]: added `colliders` and `v_structures` and deprecated `compute_v_structures` in `dag.py`

---

networkx/generators/classic.py
networkx/generators/tests/test_classic.py

Clarifies the meaning of the generation number in DGM graphs, as discussed in #7472.
Also contains additional tests based on average clustering and average shortest path length in the original paper, as well as minor changes to wording.
Fixes #7472.

Clarify generation number in `dorogovtsev_goltsev_mendes_graph()`

---

networkx/readwrite/json_graph/node_link.py

Fixes #7531 
It is now possible to provide a keyword to replace the default `nodes` key for reading/writing `json`.

add: nodes attribute is modifiable

---

doc/developer/deprecations.rst
doc/reference/algorithms/component.rst
networkx/algorithms/components/strongly_connected.py
networkx/algorithms/components/tests/test_strongly_connected.py
networkx/conftest.py

Completes removal of `strongly_connected_components_recursive`.

Expire deprecation for strongly_connected_components_recursive.

---

.github/workflows/coverage.yml

The [actions log](https://github.com/networkx/networkx/actions/workflows/coverage.yml) shows we recently had a coverage workflow hang until it was killed at the maximum timeout limit, which defaults to 360 minutes. I propose to add a more stringent timeout limit so that if a coverage job goes awry, it will be terminated sooner and free up the GH runners for other jobs.
I also bumped the coverage workflow Python version from 3.10 -> 3.12, though if there is a preference for keeping it pinned to the minimum-supported Python version, please go ahead and ignore!

CI: Add timeout limit to coverage job

---

.circleci/config.yml

Bump the images used to build the docs from oldest supported Python (3.10) to 3.12.

Update images used in docs build workflow.

---

doc/developer/deprecations.rst
networkx/algorithms/traversal/breadth_first_search.py
networkx/algorithms/traversal/tests/test_bfs.py

Removes the `sort_neighbors` param per the deprecation in #5925 .
This is ready for review, but will mark as draft until we're sure there's no need for a 3.3 patch release!

Expire deprecated `sort_neighbors` param in `generic_bfs_edges`

---

doc/developer/deprecations.rst
networkx/algorithms/smetric.py
networkx/algorithms/tests/test_smetric.py

Removes the deprecated `normalized` parameter from `s_metric`. I also snuck in a cleanup of the one existing test for this function, but I'm happy to back that out if it complicates review (the test itself is unchanged, only formatting updates).
Like other dep PRs - draft for now, but this is ready for review.

Rm deprecated normalized param from s_metric.

---

networkx/algorithms/centrality/flow_matrix.py

Our nightlies are broken right now https://github.com/networkx/networkx/actions/workflows/nightly-release-test.yml and my hunch is something happened after https://github.com/scipy/scipy/pull/20120
I am not sure if this is expected behavior @dschult ?

FIX: scipy 1d indexing tripped up numpy?

---

doc/developer/deprecations.rst
doc/reference/algorithms/tree.rst
networkx/algorithms/tree/operations.py
networkx/conftest.py

Completes removal of `join` in favor of `join_trees`.

Expire deprecated nx.join in favor of join_trees.

---

networkx/readwrite/json_graph/node_link.py

A quick follow-up to #7532 ...
There are two proposed changes:
- 6347e0f removes `_attrs` dict from the node_link module which is both private and no longer used internally
- 0b68182 adds `pprint`-ing to the node_link docstring examples to make the dictionaries easier to read.
The first should be uncontroversial; the second is subjective, so if anyone prefers to back it out I'm happy to do so!

Minor touchups to node_link functions

---

networkx/algorithms/tests/test_dag.py
networkx/conftest.py

A very minor update to the warnings filter for `compute_v_structures` to prevent it showing up in test logs.
I also took the liberty to parametrize the colliders/v_structures tests. These refactors are very subjective - IMO they make the test body more readable, but the test setup less so :shrug: . WDYT @Schefflera-Arboricola ? NBD either way - I'm happy to back those last two commits out!

Minor updates to colliders v_structures tests

---

doc/conf.py
networkx/conftest.py

Somewhere in the Sphinx 7.3.X series, sphinx-build began emitting warnings about unpickleable values in the sphinx env:
```
pickling environment... WARNING: cannot cache unpickable configuration value: 'sphinx_gallery_conf' (because it contains a function, class, or module object)
done
```
Fortunately this has already been fixed in sphinx-gallery, cf. sphinx-gallery/sphinx-gallery#1289. These changes were part of the sphinx-gallery 0.16 release, which we're already pinned above. Due to the sphinx-gallery devs' hard work, the fix is very simple :tada: . Note to review whether this patch worked, you'd have to view the sphinx build log from circleci and verify there are no more unpickleable warnings. FWIW I've built the docs and verified this locally.
Finally, I also snuck in a tiny tweak to …

Update sphinx gallery config to enable sphinx build caching

---

networkx/algorithms/shortest_paths/astar.py
networkx/algorithms/shortest_paths/tests/test_unweighted.py
networkx/algorithms/shortest_paths/unweighted.py
networkx/algorithms/shortest_paths/weighted.py

I find the exception `Either source {source} or target {target} is not in G` to be not really helpful because the exception should really tell you which of the two it is that is not in G.
I separated the cases to raise individually on a missing source or target node. If necessary, I can also add a case when *both* are not in G.

More accurate NodeNotFound error message.

---

.pre-commit-config.yaml
pyproject.toml

This PR is mainly to get the ruff configuration in sync with other repos. It adds more rules, but doesn't require changing anything. I plan to make future PRs to uncomment and fix the commented out rules in `extend-select` in order of importance / usefulness.

Update ruff config

---

networkx/utils/configs.py

Enable cache by default as discussed during the dispatch meeting yesterday.
#7497 is a companion PR that will make caching UX even nicer.
CC @rlratzel

Enable caching by default

---

.circleci/config.yml
.github/workflows/deploy-docs.yml

This is a follow-up to #7538 to install pre-release of `nx-cugraph` when building docs.
Failure was noticed https://github.com/networkx/networkx/pull/7498#issuecomment-2221133236.
Since this channel is for nightly wheels, we need `--pre`. It's curious that this worked before.
If connectivity to this repo is too flaky, we could increase the retries/timeout, and/or we could add the channel for regular releases `--extra-index-url https://pypi.nvidia.com nx-cugraph-cu11`.
CC @rlratzel

Fix installing nx-cugraph in deploy docs CI

---

networkx/drawing/nx_pydot.py

Hi. Tiny PR to fix in the docstring of nx_pydot.pydot_layout().
Given Pydot recent breaking changes wrt to node names (https://github.com/pydot/pydot/pull/363), the provided code snippet to convert node name to integers was super useful. Thanks.

DOC: Fix typo in the code snippet provided in the docstring of nx_pydot.pydot_layout().

---

README.rst

The user guide prescribes installing 
```
$ pip install networkx[default]
```
- https://networkx.org/documentation/stable/install.html#install-the-released-version
This matches the optional dependencies listed at
https://github.com/networkx/networkx/blob/7d195ae20c9f043da680a25f437e328aada0055b/pyproject.toml#L56-L62
It seems like the README, which is also published to PyPI (https://pypi.org/project/networkx/3.3/), should use the same instructions.
Further, when trying to use the README instructions:
```
$ python -m pip install "networkx[all]"
Collecting networkx[all]
Using cached networkx-3.3-py3-none-any.whl.metadata (5.1 kB)
WARNING: networkx 3.3 does not provide the extra 'all'
```

Fix installation instructions for `default` extras in README

---

networkx/algorithms/components/connected.py
networkx/algorithms/components/weakly_connected.py

Description
========
weakly_connected_components() calls len(G) inside a loop, resulting in poor performance on graph views.
suggested pull request moves len(G) to outside the loop.
Reproduction:
=========
```
import datetime
import os.path
import sys
sys.path.insert(0, os.path.dirname(__file__))
from networkx import DiGraph, weakly_connected_components, subgraph_view
g = DiGraph()
for i in range(10_000):
g.add_node(i)
view = subgraph_view(g, filter_node=lambda n: True, filter_edge=lambda u, v: True)
for i in range(10):
start = datetime.datetime.now()
for c in weakly_connected_components(view):
pass
end = datetime.datetime.now()
tmp = None
print(f'{(end - start).total_seconds():.9f}')
```
Evaluation results:
===========
* before fix: ~15.4sec per iteration
* after fix: 0.064sec per …

Fix weakly_connected_components() performance on graph view

---

networkx/drawing/nx_pydot.py
networkx/drawing/tests/test_pydot.py

Fixes https://github.com/networkx/networkx/issues/7581 and https://github.com/pydot/pydot/issues/396
Explanation of the problem:
1. In new versions of Pydot, node names are stored unchanged. They are NOT quoted/escaped on creation.
2. They are quoted/escaped if necessary when output to a `.dot` file. This is to follow the DOT grammar. Example: `Node("a\nb")` must be saved in the .dot file as `"a\nb"` (quoted and escaped), not `a(actual new line)b`.
3. Combining 1. and 2. means that saving a node in `.dot` and reading it back may result in a node with a different name. Example: `Node("a\nb")` -> saved to `.dot` as `"a\nb"` -> read back into a `Node("a\\nb")`.
4. `nx.drawing.nx_pydot.graphviz_layout` doesn't expect this.
This PR fixes the issue by explicitly using …

Fix `nx_pydot.graphviz_layout` for nodes with quoted/escaped chars

---

doc/release/release_3.3.rst

Compared to recent releases, v3.3 was missing
- release date (taken from PyPI)
- supported python versions (taken from pyproject.toml)
- high level project description (taken from previous release)

Add missing metadata to v3.3 release notes

---

doc/developer/teams.inc

The docs don't show all the members of the steering council. This adds @boothby to the list of steering council members which matches the permissions and teams as shown by github permissions. Note that this does not require changes in any github permissions -- just the docs.

Correct the members of steering council

---

.github/workflows/nightly-release-test.yml

Add Python 3.13 to the nightly wheel test matrix, to get an overview of the state of the ecosystem and find any remaining missing dependencies.
Python 3.13 is now in release candidate phase and is ABI stable.

CI: Include Python 3.13 in nightly wheel tests

---

networkx/algorithms/simple_paths.py
networkx/algorithms/tests/test_simple_paths.py

Commit d82815dba6 for issue #5945 added the ability for A* weight functions to return None, in which case that edge is ignored. This was done for consistency with Dijkstra.
The simple_paths() algorithms would benefit from the same ability.

Hide edges with a weight of None in simple_paths

---

benchmarks/benchmarks/benchmark_harmonic_centrality.py
networkx/algorithms/centrality/harmonic.py
networkx/algorithms/centrality/tests/test_harmonic_centrality.py

Computing the harmonic centrality was unnecessarily slow in many cases, for instance when computing the harmonic centrality for just a single vertex and all vertices as sources. This was due to a shortest path search starting from each vertex in `sources`. If `sources` is larger than `nbunch`, it is faster to do a shortest path search on the reversed graph starting from each vertex in `nbunch`. I implemented the graph reversal for this case, and a test case.

Improved running time for harmonic centrality

---

networkx/classes/function.py
networkx/classes/tests/test_function.py

With the addition of attribute based visualization, users may want to be able to remove visualization related attributes. I was a bit surprised that this functionality didn't already exist, but these are a pair of convenience functions to help with that.

Add remove attribute functions

---

.github/workflows/benchmark.yml
.github/workflows/coverage.yml
.github/workflows/deploy-docs.yml
.github/workflows/lint.yml
.github/workflows/mypy.yml
.github/workflows/nightly-release-test.yml
.github/workflows/pytest-randomly.yml
.github/workflows/test.yml

Removing them seem to be controversial for good reasons (see #7490), but we can already start by not using them in github action to see the effect on the build steps. This may alleviate some concerns later on.

Do not use requirements file in github workflow.

---

networkx/drawing/nx_pylab.py
networkx/drawing/tests/test_pylab.py

A set of improvements to the existing visualization suite aimed to align the current functionality with what will be implemented after the refactor. 
Some attributes can only have one value per visualization, such as node font color or arrow style for directed graphs, but if attributes are read from the graph, we should allow individual values for all of these. 
While I haven't broken any of the existing tests, I'm not sure that I fully understand the testing infrastructure for the visualization module. Tests will need to be added, but I'm still working on it. 
Below are some examples on the karate club graph. 
```python
nx.draw_networkx(G, pos=pos, ax=ax, node_shape='o', 
font_size={n: int(n / (34/15) + 5) for n in G.nodes()}, 
font_color={n: 'k' if n % 2 == 0 else 'r' for n in …
```

Individualize drawing attributes

---

doc/developer/deprecations.rst
networkx/conftest.py
networkx/readwrite/json_graph/node_link.py
networkx/readwrite/json_graph/tests/test_node_link.py

Following the discussion in #7532, this PR does the following:
- New keyword argument `edges` is introduced to JSON reading/writing functions
- Previous keyword argument `link` is deprecated
- Functions raise `ValueError` if both are provided
- Functions raise `DeprecationWarning` if `link` is provided
In the second commit, the actual default value for `edges` is set to `"edges"` instead of `"links"`.
I am not sure if the idea was to chage it now or maintain backwards compatibility of scripts that might use default values.

Add `edges` keyword/deprecate `link` keyword arguments in `JSON` input-output

---

networkx/algorithms/centrality/reaching.py
networkx/algorithms/centrality/tests/test_reaching.py

This PR partially solves #6914
I have just added a check for single node with self loops, this behavior is meaningless and should raise ``NetworkXPointlessConcept``.
Also, I have added the corresponding test cases.

Add single node with self loop check to local and global reaching centrality

---

benchmarks/benchmarks/benchmark_algorithms.py
networkx/algorithms/centrality/eigenvector.py
networkx/algorithms/centrality/tests/test_eigenvector_centrality.py

Fixes #6888.
As discussed in #6888, the SciPy solver does not handle disconnected graphs well, leading to inconsistent results. The proposed solution was to add a check that `G` is connected, as long as that didn't make the algorithm much slower (for reference, the execution time was usually around 1-2% longer with the check).
This PR:
- Changes `eigenvector_centrality_numpy` to only accept connected graphs (strongly connected for directed graphs)
- Updates the docstring to clearly mention the reason for this choice (i.e. the inconsistency, and its explanation by @dschult)
- Adds two tests to verify that the function properly raises when given a disconnected graph as input
- Reorganises the arguments in the docstring to match the arguments of the function
- Has other very minor changes …

Only allow connected graphs in `eigenvector_centrality_numpy`

---

.github/workflows/nightly-release-test.yml

Nightly tests are broken https://github.com/networkx/networkx/actions/workflows/nightly-release-test.yml because of a typo in the pip install command.

CI: Fix typo in nightly run pip install

---

doc/developer/deprecations.rst
networkx/readwrite/json_graph/node_link.py
networkx/readwrite/json_graph/tests/test_node_link.py

Follow-up to #7565 
One of the changes in #7565 was to change the default value for the `edges` (cf. `link`) parameter from `"links"` to the more networkx-y `"edges"`. At the time of the discussion, this was recognized as a breaking change, but the consensus (including my own opinion) was that it was better to get all of the changes in now rather than have multiple deprecation cycles.
However, this change did lead to a break downstream in `nx-guides`, which can be interpreted as a proxy for how disruptive any change might be in user-code. Essentially, changing the default without warning will affect any user attempting to read saved graphs saved in `node_link` format with the default edge values. Given this, I *do* now think a deprecation cycle is a good idea - not only does it avoid …

Revert breaking change to `node_link_*` link defaults

---

networkx/generators/social.py

Added the following lines to the `karate_club_graph()` docstring in `networkx/generators/social.py`:
```
The dataset is derived from the 'Club After Split From Data' column of Table 3 in the source paper.
This was in turn derived from the 'Club After Fission' column of Table 1 in the same paper.
Note that the nodes are 0-indexed in NetworkX, but 1-indexed in the paper
(the 'Individual Number in Matrix C' column of Table 3 starts at 1).
This means, for example, that G.nodes[9]["club"] returns 'Officer',
which corresponds to row 10 of Table 3 in the paper.
```
Closes #7519 #7515

Updated docstring for generators/karate_club_graph()

---

networkx/algorithms/operators/product.py
networkx/algorithms/operators/tests/test_product.py

Addressing #7486 , I have modified the product.py file and test_product.py file to raise the NodeNotFound Exception instead of 
NetworkXError when root is not in H.

modified product.py to raise NodeNotFound when 'root is not in H'

---

networkx/__init__.py
networkx/utils/__init__.py
networkx/utils/backends.py
networkx/utils/configs.py

Fixes #7671 
Delays updating backend_info and setting up configs until the end of the import process so that backends which import networkx inside their backend_info function don't run into a circular import issue.
We should test this locally with nx-cugraph installed just to make sure nothing strange occurs.

MAINT: delay loading of backend_info to after imports

---

networkx/__init__.py
networkx/utils/backends.py

This may not fix when building the docs; let's experiment!
For backends to show up in docs, we need to load `backend_info` before we decorate functions with `_dispatchable`.
This fixes #7675 and attempts to fix #7677, and is a follow-up to #7672. Let's see if #7671 remains fixed with this PR.
@Schefflera-Arboricola will this work for nx-parallel?

Fix docstrings of dispatchable functions

---

doc/backends.md
doc/tutorial.md
networkx/utils/configs.py

Minor formatting touchups to get rid of sphinx warnings in the doc build

Fix doc warnings from recently added docs

---

networkx/drawing/nx_pylab.py
networkx/drawing/tests/test_pylab.py

This PR addresses #7684 by returning the collection object rather than axis object in `draw_networkx_nodes`. Additional tests are added to check that the return types of `draw_networkx_nodes` and `draw_networkx_edges` return expected types.

Fix draw_networkx_nodes return type

---

networkx/algorithms/tests/test_link_prediction.py

Done to get rid of the following `FutureWarning` when using Python 3.13
```
/home/runner/work/networkx/networkx/networkx/algorithms/tests/test_link_prediction.py:91: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in staticmethod() if you want to preserve the old behavior
```
Thank you :)

MAINT: wrapping `partial` with `staticmethod()` in `test_link_prediction.py`

---

doc/backends.md

Updates the `nx-arangodb` link in Backends Gallery
Github Page has a video, which IMO is nicer to have vs. the RTD page

set nx-arangodb link to github

---

networkx/drawing/tests/test_pylab.py
networkx/generators/small.py
networkx/generators/tests/test_small.py

This decorator is only used by the "small" graph generators. We could update this to use `argmap`, but probably not worth the effort since all functions have create_using as the first positional argument.
If we were creating these functions today, we might make create_using keyword-only, but that would be a breaking change.
I came across this when running networkx tests with nx-cugraph with networkx 3.4.2. The test added in #7685 was failing for nx-cugraph, because `cubical_graph` isn't supposed to work with directed graphs and we were raising.

Update `_raise_on_directed` to work with `create_using` pos arg

---

networkx/generators/directed.py
networkx/generators/tests/test_directed.py

I found this generator to be particularly slow, so I dug into it and made several optimizations. The main bottleneck I found was the re-computation of out-degrees at every single step. Updating their values at every step already allowed for a ~20x performance improvement for `nx.random_k_out_graph(1000, 100, 0.1)`. I then introduced numpy to optimize further to reach a ~60x improvement for this same set of parameters (from 2 minutes down to 2 seconds). There are more lines of code but not really more complexity, as most lines are for variable initialisations and updates.

perf: optimise `random_k_out_graph`

---

networkx/algorithms/centrality/tests/test_trophic.py
networkx/algorithms/centrality/trophic.py

trophic_levels now checks for paths from each node to a basal node

---

networkx/classes/coreviews.py
networkx/classes/tests/test_subgraphviews.py

Fixes #7724: `MultiGraph` views return inconsistent `has_edge` results.
___
Minimum working example:
```python
G = nx.MultiDiGraph()
G.add_edges_from([("a", "b"),
("a", "c"),       # <-- to be filtered out
("c", "b")])
H = nx.edge_subgraph(G, [("a", "b", 0), ("c", "b", 0)])
print(f"{H.edges()}\n\n"
f"{H.has_edge('a', 'c')} \t H.has_edge('a', 'c')\n"
f"{('a', 'c') in H.edges()} \t ('a', 'c') in H.edges()\n\n"
f"{'c' in H['a']} \t 'c' in H['a']\n"
f"{'c' in list(H['a'])} \t 'c' in list(H['a'])")
```
Output **before** the PR:
```
#
#
```
Output **after** the PR:
```
```

Fix for filtered MultiGraph views from `edge_subgraph` (#7724).

---

networkx/algorithms/asteroidal.py

The current version of `find_asteroidal_triple` builds the complement of the graph and stores all its edges, which causes performance and memory usage issues for large graphs. This is easily fixed by iterating over non-edges in the graph.

`find_asteroidal_triple` improvement

---

networkx/algorithms/bipartite/generators.py
networkx/algorithms/centrality/subgraph_alg.py
networkx/generators/geometric.py
networkx/readwrite/leda.py

Some `Examples` sections in the docs aren't being displayed correctly. These are the ones I was able to catch at a quick glance:
- https://networkx.org/documentation/latest/reference/algorithms/generated/networkx.algorithms.centrality.subgraph_centrality_exp.html#networkx.algorithms.centrality.subgraph_centrality_exp
- https://networkx.org/documentation/latest/reference/algorithms/generated/networkx.algorithms.centrality.subgraph_centrality.html
- https://networkx.org/documentation/latest/reference/generated/networkx.generators.geometric.thresholded_random_geometric_graph.html#networkx.generators.geometric.thresholded_random_geometric_graph
- https://networkx.org/documentation/latest/reference/generated/networkx.generators.geometric.soft_random_geometric_graph.html
- …

Fix code formatting of some examples

---

networkx/algorithms/community/local.py

Very minor cleanup of recently-introduced docstring parsing warnings.

Fix sphinx warnings from numpydoc parsing.

---

doc/developer/deprecations.rst
networkx/algorithms/centrality/reaching.py
networkx/algorithms/shortest_paths/generic.py
networkx/algorithms/shortest_paths/tests/test_generic.py
networkx/algorithms/shortest_paths/tests/test_unweighted.py
networkx/algorithms/shortest_paths/unweighted.py
networkx/conftest.py

These have been deprecated and are slated to change in NetworkX 3.5
See: #6527

Update `shortest_path` and `single_target_shortest_path_length` for 3.5

---

examples/algorithms/plot_bipartite_motif_abcore.py

An alternative to #7728 presenting the computation of "alpha-beta-core" motifs in bipartite graphs as a gallery example instead of a function.

Gallery example: bipartite a/b-core motif

---

networkx/algorithms/shortest_paths/generic.py

Currently, the function `single_source_all_shortest_paths` contains this line:
```python
for n in G:
```
Which might be a significant waste of time if most nodes aren't reachable from the given source.
Merely looping on the keys of `pred` could lead to a significant improvement for large very sparse graphs.
```python
for n in pred:
```
And I guess the `try`-`except` in the loop is then no longer necessary.
Here's an example that shows the performance issue. The more nodes in the graph, the slower, even if they are unreachable. Even though it might not be an issue for a single call to that function, when calling it on several sources, it quickly adds up. (See **Additional context** below.)
```python
>>> import networkx as nx
>>> g = nx.DiGraph()
>>> g.add_edges_from((n, n+1) for n in …
```

single_source_all_shortest_paths: don't loop over all nodes

---

networkx/conftest.py

There are four LOBPCG convergence warnings in current test suite so add warnings filters to filter them. Details are seen in issue [7755](https://github.com/networkx/networkx/issues/7755). Please add a reviewer label for this PR otherwise the checks are not successful. Thanks.

Add filters for LOBPCG convergence warnings

---

networkx/algorithms/isomorphism/isomorphvf2.py

This pull request resolves a documentation issue in the NetworkX isomorphism module, where the functionality of `subgraph_is_monomorphic` was incorrectly described as checking for subgraph isomorphism.
Current Documentation :
The current example incorrectly implies that `subgraph_is_monomorphic` is used to check for isomorphism:
```python
Check whether a subgraph of H is isomorphic to G:
>>> isomatcher = nx.isomorphism.GraphMatcher(H, G)
>>> isomatcher.subgraph_is_monomorphic()
True
```
Expected Documentation Update :
The example should describe the functionality accurately as checking for monomorphism:
``` python
Check whether a subgraph of H is monomorphic to G:
>>> isomatcher = nx.isomorphism.GraphMatcher(H, G)
>>> isomatcher.subgraph_is_monomorphic()
True
```

Correcting the example given under subgraph_is_monomorphic.py

---

networkx/drawing/tests/test_pylab.py

The test in https://github.com/networkx/networkx/pull/7739 added some flakiness to our [pytest-randomly runs](https://github.com/networkx/networkx/actions/workflows/pytest-randomly.yml). This should hopefully clean it up :)

MAINT: Close mpl figures in tests to clear up test env

---

networkx/drawing/layout.py
networkx/drawing/tests/test_layout.py

When pos_arr includes a node at 0, 0, after normalization, a NaN occurs in the gravity calculation for that node, which propagates through the code to return NaNs for most values.

Fixed a divide by zero error in forceatlas2

---

networkx/classes/graph.py
networkx/classes/tests/test_graph.py

This closes https://github.com/networkx/networkx/issues/7740
Changes :
Error message changed to include what nbunch is instead of just 'nbunch'
Tests changed accordingly to look for new error message.
Small improvement in documentation && documentation changed accordingly.

Error message improvement for nbunch_iter ( NetworkXError raised with specific message on TypeError with "iter" in msg )

---

networkx/algorithms/centrality/laplacian.py

Major performance improvement when computing Laplacian centrality. Simply followed theorem 1 of the original paper (the one cited in the documentation: https://math.wvu.edu/~cqzhang/Publication-files/my-paper/INS-2012-Laplacian-W.pdf) which implies simply summing the squares of the entries of the matrix instead of computing a ton of eigenvalues.
The change is very simple (just two lines). Should give exactly the same result now due to the theorem mentioned. Preliminary testing showed it did work.
Note: it should be possible to make this even faster by only summing over the values that change when going from the big to the small matrix (the whole diagonal and respective row and column). I don't have time to do the computations for this now, though.

Faster computation of energy in Laplacian centrality

---

networkx/algorithms/approximation/steinertree.py

In follow up to issue #5889  I implemented a backward compatible enhancement by only changing the _kou_steiner_tree function in  steinertree.py. So far it passed all tests and shows significant speed up. 
This is my first ever time using GitHub, I am not sure if I am contributing correctly.
There is also a possibe improvement in the for loop on line 98, where it currently adds edges (u, v) and (v, u), although one may argue that it adds a generalization to directed graphs.
PS: It may also be considered to change the documentation of steinertree to reflect that time complexity of Kou algorithm is O(|S|(|E|+|V|log|V|)), the reason why in original paper the time complexity was shown as O(|S||V|^2) is because back when Kou's paper was published the more efficient Dijkstra implementation was …

Steinertree kou enhancement in response to issue 5889 type:Enhancements

---

benchmarks/README.md
benchmarks/benchmarks/benchmark_many_components.py

Adds a benchmark that uses `atlas6` (i.e. the set of all connected graphs with at most 6 nodes and at least one edge that are not isomorphic to one another) to provide an evaluation point for algorithm performance whose variance depends on the number of components.
Inspired by #7762 - note this PR doesn't implement the suggestion from that issue, but it should be useful in evaluating the performance gains!
I also took the opportunity to add a bit more detail to the benchmarking readme - specifically, I added the recipe for running only a subset of the full benchmarking suite.

Benchmarking: graph atlas

---

networkx/algorithms/tests/test_cluster.py

The test originally only checks the square clustering coefficient for a single node - this PR expands the test to check the square clustering coefficient of all nodes in the example graph. I came across this while doing some background research for #7810 !

Improve square clustering test derived from Zhang paper (reference 2)

---

networkx/utils/backends.py

#7690 enabled backend-only functions, and we did a small refactor of dispatch `__call__` in #7761. When #7690 was merged into #7761 from the main branch ([here](https://github.com/networkx/networkx/pull/7761/commits/f714e178af0fd5d687743d44984b61ce9ebaa0fd)), the new error message was put in the wrong call function and recreated a block of code that was deleted.
Anyway, this PR fixes things.

Fix exception for backend-only functions

---

networkx/utils/configs.py
networkx/utils/tests/test_config.py

Previously, it didn't restore the original values
Thanks @rlratzel who discovered this.

Fix `with nx.config(backend_priority=backends):`

---

networkx/drawing/tests/test_pylab.py

Follow up to #7783 - add a fixture for creating figure/axis objects for the pylab tests which uses `yield` statements to [automatically clean up the tests](https://docs.pytest.org/en/stable/how-to/fixtures.html#yield-fixtures-recommended) afterwards. This will hopefully help prevent issues like this with adding new visualization tests in the future!

Add a subplot fixture to automate test cleanup.

---

networkx/drawing/nx_pylab.py

A purely cosmetic change: removes the importation of specific layout functions in `nx_pylab` and instead calls them from the `nx.` namespace. Essentially just an (opinionated) lint - the main motivation is getting rid of the big import statement.

MAINT: use nx.layout instead of importing layouts.

---

networkx/utils/tests/test_backends.py

pytest-randomly seems to be tripping up on this https://github.com/networkx/networkx/actions/workflows/pytest-randomly.yml
Closes #7808

MAINT: Move stub func in the correct scope for pickle test

---

.pre-commit-config.yaml
doc/conf.py
doc/reference/randomness.rst
examples/algorithms/plot_blockmodel.py
examples/drawing/plot_eigenvalues.py
examples/graph/plot_visibility_graph.py
networkx/algorithms/approximation/traveling_salesman.py
networkx/algorithms/tests/test_regular.py
networkx/classes/tests/test_digraph_historical.py
networkx/classes/tests/test_graph_historical.py
networkx/conftest.py
networkx/convert.py
networkx/generators/expanders.py
networkx/generators/tests/test_directed.py
networkx/utils/misc.py

I was poking around open issues and saw #4426, which referenced #4401. So, I took a minute to explore whether these conventions are actually used. Linting tools such as flake8-import-conventions can also do something similar to the simple pre-commit pygrep hook I added.

Ensure standard import conventions are used

---

.pre-commit-config.yaml

This is a quick follow-up to #7821.
The last commit in #7821 added `"^ *"` to the regex string to avoid false-positives by only matching lines that begin with spaces (optional) and "import". Without this regex, we would get the following:
```
Check import conventions; see CONTRIBUTING.rst#guidelines.......................Failed
- hook id: check-import-conventions
- exit code: 1
CONTRIBUTING.rst:288:  ``import scipy.sparse.linalg as spla``.
doc/release/api_0.99.rst:290:>>> import networkx # e.g. centrality functions available as networkx.fcn()
doc/release/old_release_log.rst:730:     >>> import networkx
doc/release/old_release_log.rst:1036: - import networkx
doc/release/old_release_log.rst:1037: - import networkx as NX
networkx/lazy_imports.py:117:    The workaround is to import numpy …
```

Clean up pygrep pre-commit for import convention checks

---

doc/reference/drawing.rst
networkx/drawing/layout.py
networkx/drawing/nx_pylab.py
networkx/drawing/tests/test_layout.py
networkx/drawing/tests/test_pylab.py

A feature proposal to make the `nodes` parameter of `bipartite_layout` optional, with the default behavior to compute the nodesets with `nx.bipartite.sets`.
This is intended to be a minor convenience enhancement so users don't have to explicitly create partitions just to visualize the graph. This is only a proposal to add a feature and should be completely backwards compatible - including preserving the order of the nodes in the `pos` dict. I wasn't sure how important that was, but it's straightforward not to break!
I also added a `draw_bipartite` convenience function in 9196501 to match the pattern used for the other layout functions. I did so only for consistency and am completely happy to leave it out if preferred!

Bipartite layout nodes optional

---

doc/developer/deprecations.rst
networkx/algorithms/d_separation.py
networkx/algorithms/tests/test_d_separation.py
networkx/conftest.py

Expire deprecations of `d_separated` and `minimum_d_separator`, which are scheduled for removal in 3.5

Expire d_separated and minimum_d_separator functions.

---

doc/developer/deprecations.rst
doc/reference/algorithms/triads.rst
networkx/algorithms/tests/test_triads.py
networkx/algorithms/triads.py
networkx/conftest.py

Expires the `all_triplets` deprecation, which is scheduled to be removed in 3.5

Expire all_triplets deprecation.

---

doc/developer/deprecations.rst
doc/reference/algorithms/triads.rst
networkx/algorithms/tests/test_triads.py
networkx/algorithms/triads.py
networkx/conftest.py
networkx/tests/test_all_random_functions.py

Expires the `random_triad` deprecation, which is scheduled for removal in version 3.5

Expire random_triad deprecation.

---

doc/developer/deprecations.rst
networkx/algorithms/isomorphism/isomorph.py
networkx/algorithms/isomorphism/tests/test_isomorphism.py
networkx/algorithms/tests/test_threshold.py
networkx/generators/tests/test_classic.py
networkx/generators/tests/test_small.py

`graph_could_be_isomorphic` (and friends `fast_` and `faster_`) are aliases for `could_be_isomorphic` that is not exported outside of the `isomorph` module, so this should be a relatively undisruptive deprecation (the only way to access the alias is to import from `nx.algorithms.isomorphism.isomorph` - see e.g. the removed examples in the test suite).
There were some internal usages in the test suite which are easily replaced with the (newly) recommended function.

Deprecate graph_could_be_isomorphic

---

networkx/algorithms/tests/test_link_prediction.py
networkx/algorithms/tests/test_threshold.py

Using `assert` with `pytest.raises` is unnecessary.
Tiny stylistic fix to encourage better practice. Some linter may check for this (not sure), but this was trivial to search-and-replace.

Don't use `assert` when using `pytest.raises`

---

examples/drawing/plot_chess_masters.py
networkx/algorithms/bipartite/edgelist.py
networkx/drawing/nx_agraph.py
networkx/drawing/nx_latex.py
networkx/drawing/nx_pydot.py
networkx/readwrite/adjlist.py
networkx/readwrite/edgelist.py
networkx/readwrite/gexf.py
networkx/readwrite/gml.py
networkx/readwrite/graph6.py
networkx/readwrite/graphml.py
networkx/readwrite/leda.py
networkx/readwrite/multiline_adjlist.py
networkx/readwrite/p2g.py
networkx/readwrite/pajek.py
networkx/readwrite/sparse6.py

Some read functions said "write", and some didn't describe the ability to compress or decompress. Also, I prefer "decompressed" over "uncompressed".

Update readwrite docstrings for the `path` parameter

---

networkx/algorithms/similarity.py

As discovered in https://github.com/networkx/networkx/pull/7817#issuecomment-2635286426, the docstring example with using `index_map` is incorrect, because it was trying to index into a generator.
This argument is a little awkward to use since this function is a generator and `index_map` will be updated incrementally, but I believe the updated docstring example is what was intended.

Fix docstring example of `nx.generate_random_paths(index_map=...)`

---

doc/developer/deprecations.rst
doc/reference/linalg.rst
networkx/algorithms/approximation/traveling_salesman.py
networkx/algorithms/tree/mst.py
networkx/conftest.py
networkx/linalg/laplacianmatrix.py

Removes `total_spanning_tree_weight` and replaces internal usages with `number_of_spanning_trees`. `total_spanning_tree_weight` is scheduled for removal in v3.5

Expire total_spanning_tree_weight deprecation

---

networkx/classes/function.py
networkx/utils/backends.py

I think it would be useful to dispatch `{get,set}_{node,edge}_attributes` when using backends such as nx-cugraph and nx-arangodb (CC @aMahanna), and I went ahead and made a few other (but not all) functions from this file dispatchable.

Dispatch `get_node_attributes` and a few more from `nx.classes.function`

---

networkx/algorithms/d_separation.py
networkx/convert_matrix.py

I noticed the docstring for `from_pandas_edgelist` was not rendering a code block correctly because it used triple backticks <code>```</code>, so I did a quick grep to fix their use in docstrings. See incorrect docs here:
- https://networkx.org/documentation/stable/reference/generated/networkx.convert_matrix.from_pandas_edgelist.html
- https://networkx.org/documentation/stable/reference/generated/networkx.convert_matrix.from_pandas_adjacency.html
- https://networkx.org/documentation/stable/reference/algorithms/d_separation.html

Fix use of triple backticks in docstrings

---

doc/developer/projects.rst

We've talked about adding to the mentored projects page a paragraph that makes suggestions to people who are running university courses with NetworkX projects. 
Here's an attempt at such a paragraph. I want it to tread the fine line of being welcoming while also making suggestions for how they do it. The big ideas are:
- consider improving what is already there rather than creating new.
- work with the class on a separate fork and the PR to that fork is ready, then make the PR to NetworkX.
Is this too discouraging? too encouraging? :)

Add paragraph about university classes to mentored projects

---

doc/developer/deprecations.rst
networkx/conftest.py
networkx/generators/nonisomorphic_trees.py
networkx/generators/tests/test_nonisomorphic_trees.py

Expires the last deprecation scheduled for 3.5: removing the `create=` kwarg to `nonisomorphic_trees`.
During the removal it seemed to me there is also an opportunity to remove some redundancy in the conditionals by restructuring the loop, but that's for a separate PR!

Expire deprecation of create kwarg in nonisomorphic_trees.

---

.mailmap

I may have missed a few but I tried to catch all the ones for committers with a fair amount of activity, as well as some obvious ones for single commits each with a different address.
The file can be later updated if anyone notices any I missed.

Add .mailmap file to consilidate contributors.

---

networkx/algorithms/clique.py
networkx/algorithms/isomorphism/isomorph.py

When looking at #7852, @rossbar noticed `could_be_isomorphic` could be made much faster by counting cliques faster. Same change applies to `number_of_cliques` too, and I updated the recipe in the docstring of `find_cliques` to avoid the slow recipe.
Additional changes that could be made (preferably in other PR(s)):
- Recipe in `find_cliques` could be replaced by `number_of_cliques` (or at least mention it)
- `could_be_isomorphic` could also use `number_of_cliques`, but used simple one-liner for performance
- Docstring of `number_of_cliques` doesn't describe parameters or return types, and incorrectly says returns a list

Faster `could_be_isomorphic` and `number_of_cliques`

---

networkx/algorithms/flow/networksimplex.py
networkx/algorithms/flow/tests/test_networksimplex.py

I've looked into the issue and implemented a potential fix. While I have a general understanding of the high-level idea, I have not studied the network-simplex algorithm in full detail.
From my understanding, the purpose of the `faux_inf value` is to create dummy edges and assign them a "practical infinity" value, rather than using actual infinity. This "practical infinity" is intended to be sufficiently large compared to all other "real" weights and capacities.
Change made:
1. Implemented a new calculation for `faux_inf`: 
`faux_inf = (sum(c for c in DEAF.edge_capacities if c < inf) +
sum(abs(w) for w in DEAF.edge_weights) +
sum(abs(d) for d in DEAF.node_demands)) * 10 or 1`
2. Added the three sample cases discussed in the issue as tests (for illustration):
- Verified that these tests …

Fix handling of faux_infinite values in network_simplex

---

networkx/algorithms/flow/tests/test_networksimplex.py

Follow-up to #7796 
Just a refactor of the test for the `faux_infinity` bound that was added in #7796. The tests themselves should be the same, I've just modified the organization to:
1) move the modifications of weight/demand/capacity into the test itself to make it more clear how the base example is being modified, and
2) Use stacked fixtures to simplify the generation of test cases.

Refactor network_simplex test of faux_infinity.

---

networkx/algorithms/graph_hashing.py

Just a minor fix of the documentation of `weisfeiler_lehman_graph_hash`: it takes a number of **bytes**, passed to blake2b, as size parameter.
I also added an explicit mention of how this translates to the size of the output, for anyone no familiar with `hashlib`.

doc: hash size are in bytes

---

networkx/algorithms/bipartite/tests/test_matrix.py

Caught a couple remaining instances of `csc_matrix` while combing over code for #7859 !

Rm stray instances of sparse matrices from test suite.

---

doc/release/contribs.py
networkx/algorithms/cycles.py
networkx/algorithms/flow/tests/test_maxflow_large_graph.py
networkx/algorithms/flow/tests/test_mincost.py
networkx/algorithms/flow/tests/test_networksimplex.py
networkx/algorithms/isomorphism/tests/test_isomorphvf2.py
networkx/algorithms/link_analysis/pagerank_alg.py
networkx/algorithms/matching.py
networkx/algorithms/operators/tests/test_binary.py
networkx/algorithms/shortest_paths/generic.py
networkx/algorithms/shortest_paths/unweighted.py
networkx/algorithms/tests/test_smallworld.py
networkx/conftest.py
networkx/convert.py
networkx/drawing/nx_agraph.py
networkx/drawing/nx_latex.py
networkx/generators/atlas.py
networkx/generators/trees.py
networkx/linalg/algebraicconnectivity.py
networkx/readwrite/gml.py
networkx/readwrite/text.py
networkx/tests/test_lazy_imports.py
networkx/utils/configs.py
networkx/utils/decorators.py
networkx/utils/misc.py

Some more cleanup since we're in the mood for linting.
I did this by adding
```yaml
- repo: https://github.com/PyCQA/autoflake
rev: 0544741e2b4a22b472d9d93e37d4ea9153820bb1 # frozen: v2.3.1
hooks:
- id: autoflake
args: [--in-place]
```
to `.pre-commit-config.yaml` locally.
I'll let somebody else decide whether we want to add this check to `.pre-commit-config.yaml`. Ideally, it would probably be best if `ruff` could take care of this to have it run faster and not add another tool that we need to update, but I haven't tried to do this.
Like a lot of other linting, I think it would be fine to run this every couple of years or so.

Remove unused imports

---

benchmarks/benchmarks/benchmark_algorithms.py

This one was easy - I just plugged it directly into the existing algorithm benchmarks. Note however that I chose the test cases that excluded the drug interaction network, as the existing implementation can be quite expensive!
Here's an example incantation and some results:
```bash
$ asv continuous --bench AlgorithmBenchmarksConnectedGraphsOnly.time_square_clustering 2d1ad6b1 main
$ asv compare 2d1ad6b1 main
```
<details>
<summary>Benchmarking results</summary>
<pre>
All benchmarks:
| Change   | Before [2d1ad6b1] <faster_square_clustering>   | After [f87c3611] <main>   |   Ratio | Benchmark (Parameter)                                                                                        |
|----------|------------------------------------------------|---------------------------|---------|-- …

Add square_clustering to algorithm benchmarks.

---

examples/basic/plot_properties.py
examples/drawing/plot_random_geometric_graph.py
networkx/algorithms/flow/maxflow.py
networkx/algorithms/shortest_paths/tests/test_generic.py
networkx/algorithms/shortest_paths/tests/test_weighted.py
networkx/algorithms/tests/test_dominance.py
networkx/generators/ego.py
networkx/utils/rcm.py

When reviewing #7877, I noticed a call to `nx.single_source_shortest_path_length` was wrapped with `dict(...)`, which is now unnecessary (and to me was confusing/surprising). So, a quick `git grep` revealed where this pattern is occurring.
I updated tests too, which I think is helpful to ensure return types are correct for backends that implement these.

Remove unnecessary `dict(...)` for SSSP algos that return dicts

---

doc/developer/projects.rst

This moves the visualization project to the completed section.
It seems to be orthogonal to the new projects PR (no conflicts with it).

DOC: Clean up mentored projects page: move visualization project to completed section

---

networkx/algorithms/centrality/group.py

% `ruff check --select=NPY,PD --statistics`
```
18	PD901 	[ ] pandas-df-variable-name
3	NPY002	[ ] numpy-legacy-random
2	PD002 	[*] pandas-use-of-inplace-argument
1	PD011 	[ ] pandas-use-of-dot-values
[*] fixable with `ruff check --fix`
```
% `ruff check --select=PD002 --fix --unsafe-fixes ` # These are ___unsafe-fixes___ so careful review please!
```
Found 2 errors (2 fixed, 0 remaining).
```
As a followup, someone with more NumPy and Pandas expertise than I should try to close the remaining issues.
* https://docs.astral.sh/ruff/rules/#numpy-specific-rules-npy

ruff check --select=PD002 --fix --unsafe-fixes

---

networkx/algorithms/distance_measures.py

Adds missing `usebounds` parameter description to the docstrings for the relevant distance measures. Addresses at least the documentation part of #7687, though it may be worth keeping that open in case there's any other discussion.
Wording suggestions welcome!

Add missing usebounds param descr to distance docstrings.

---

networkx/algorithms/structuralholes.py
networkx/algorithms/tests/test_structuralholes.py

Handles the corner-case of isolated nodes that contain self-edges. Currently, isolated nodes are treated as having undefined `effective_size`:
```python
>>> G = nx.Graph()
>>> G.add_node(0)
>>> nx.effective_size(G)
{0: nan}
```
However, the current behavior for isolated nodes with self-loops is inconsistent, resulting in `ZeroDivisionError` for the undirected case and `0.0` for directed graphs::
```python
>>> G = nx.Graph([(0, 0)])
>>> nx.effective_size(G)
Traceback (most recent call last)
...
ZeroDivisionError: division by zero
>>> G = nx.DiGraph([(0, 0)])
>>> nx.effective_size(G)
{0: 0.0}
```
This discrepancy is due to the ambiguity of the direction of a self-edge.
Based on the current behavior and Borgatti's formula, I think the thing that makes the most sense is to have …

`effective_size` of nodes with only self-loop edges is undefined

---

networkx/generators/atlas.py

I often find myself searching for [the graph atlas gallery example](https://networkx.org/documentation/stable/auto_examples/graphviz_layout/plot_atlas.html#sphx-glr-auto-examples-graphviz-layout-plot-atlas-py) as a reminder for how to partition the graph atlas to get all graphs of *n* nodes. Therefore, I thought it might be worthwhile to put that info in the `graph_atlas_g` docstring itself.
I've elected to do so with `Examples`, though it could perhaps be done more concisely in a bulleted list somewhere in the docstring summary. I'm open to ideas/suggestions!

Add examples to graph_atlas_g docstring.

---

networkx/drawing/layout.py

Closes #7912 
Small PR that adds the missing docstring description for the `weight` and `gravity` arg. Followed wording convention from similar functions.

Add missing `weight` and `gravity` attribute to `forceatlas2_layout` docstring

---

networkx/algorithms/connectivity/cuts.py
networkx/algorithms/connectivity/tests/test_cuts.py

Addressing issues #7909 
This PR involves the suggested changes : 
1. fix the typo {} -> set()
2. Adding documentation text under the Returns section about when an empty set is returned.
Additional Changes : 
1. Fix test assertion `tests_minimum_st_node_cut()` by using set() instead of {} for empty set comparison.

Fixed the return type from an empty dict to an empty set

---

networkx/drawing/layout.py

This is a follow up to #7794 and #7915. The `weight=` parameter wasn't documented when `@nx._dispatchable` was added to FA2, so I/we completely missed its use. Anyway, this change makes sure the edge attribute is preserved if necessary when converting to a different backend.
Also, the default weight is None, not "weight".
CC @nv-rliu @rlratzel

Add `edge_attrs="weight"` to `forceatlas2_layout` dispatch decorator

---

networkx/algorithms/graph_hashing.py
networkx/algorithms/tests/test_graph_hashing.py

Fixes #7806 
Includes bugfixes for the issues discussed.
Does not cover the potential extension to ```MultiGraph```s.
Extended testing, but note that a lot of the test in this module in depend on randomly generated graphs. We continued that here. However, that does not necessarily mean all edge-cases are covered (as the original bug showed).
Note that subgraph hashing requires hashing of initial labels for digest size testing. This is not necessarily (and thus omitted) for general graph hashing.
~~A small optimisation is also made to the original graph hashing method. It used to collect _all_ labels calculated during execution in a counter, and hashed that to get the final graph hash. However, the WL algorithm only relies on the colouring (labels) calculated at the last iteration, so the …

Fix graph_hash iteration counts and DiGraph handling

---

networkx/algorithms/approximation/treewidth.py
networkx/convert.py
networkx/linalg/attrmatrix.py

This finishes up Issue #6804 to follow-up on warts found during the `_dispatch` code audit. 
Fixes #6804
It includes:
- changing the input name `graph` to `graph_dict` in `min_fill_in_heuristic` as it needs to be a dict-of-neighbor-sets rather than a networkx graph.
- updated the doc-strings of `to_dict_of_dicts()` to explain that input `edge_data` is a scalar value, that it should not be a container, and that it's default is the full edgedata dict from the graph (which is not a scalar value). 
- updated the doc-string of `attr_matrix()` and `attr_sparse_matrix` -- but I left the code requiring that every node/edge must have the requested attribute (no default for missing values).
I decided not to change some of the items -- they will still be warts (and are still unchecked in that …

DOC: docstring changes to `to_dict_of_dicts` and `attr_matrix` and input name change in `min_fill_in_heuristic`

---

networkx/generators/nonisomorphic_trees.py
networkx/generators/tests/test_nonisomorphic_trees.py

The current implementation of number_of_nonisomorphic_trees() constructs all trees and output the amount of trees created, which is exponential. The proposed implementation computes directly the number, using an O(n**3) formula.

Improve runtime of number_of_nonisomorphic_trees().

---

networkx/algorithms/cycles.py
networkx/algorithms/tests/test_cycles.py

This PR addresses an issue in the `chordless_cycles` function where multigraphs with self-loops were not being correctly handled. Added test cases under `test_chordless_cycles_multigraph_self_loops` that verify :
1. Self-loops as single-node chordless cycles.
2. Parallel edges in a multigraph as two-node chordless cycles.
```
def test_chordless_cycles_multigraph_self_loops(self):
G = nx.MultiGraph([(1, 1), (2, 2), (1, 2), (1, 2)])
expected = [[1], [2]]  
self.check_cycle_algorithm(G, expected, chordless=True)
G.add_edges_from([(2, 3), (3, 4), (3, 4), (1, 3)])
expected = [[1], [2], (3, 4)] 
self.check_cycle_algorithm(G, expected, chordless=True)
```
Changes made include : 
1. Interpretation of self-loops to be chordless cycles, except in multigraphs with multiple loops in parallel.
2. …

Refactored the working of chordless_cycles to handle self loops

---

networkx/readwrite/json_graph/cytoscape.py

Update the examples section for cytoscape_data
1. Modifies the original example so that it is not doctest-able (i.e. add `pprint` and remove the `doctest: +SKIP`)
2. Adds an example of using `json` (with StringIO) to simulate serializing to a file.
Closes #7913

DOC: Update first docstring example and add a serialization example.

---

networkx/readwrite/gexf.py
networkx/readwrite/tests/test_gexf.py

When using write_gexf on a Graph containing start/end attributes, the Graph timeformat parameter was not set, breaking compatibility with the [gexf draft](https://gexf.net/1.2draft/gexf-12draft-primer.pdf). This ensures that the timeformat parameter is set in the .gexf <graph> tag.
Before this fix, the .gexf file obtained when using write_gexf on a dynamic graph would not contain a timeformat attribute in the graph tag. This made read_gexf unable to parse the Graph.
After this fix, the timeformat argument for the graph tag is saved on line 6 of the gexf file, ensuring that a dynamic Graph exported through write_gexf can then be loaded again through read_gexf.

Fix write_gexf timeformat for dynamic Graphs

---

networkx/utils/backends.py
networkx/utils/tests/test_backends.py

I took a dive into some of `backends.py` and came up with these suggestions for notes and code tweaks to ease readability of some parts. Push back on any of this, and/or push up corrections, reversions, additions. 
None of these changes should be changing behavior of the code **except** that `_fallback_to_nx` seems to be due for deprecation (v3.5) so I removed it and the test of the deprecation warning. If there are other steps needed for deprecation of backend features, I can revert these or add those (or you can).

Tweaks and notes from a dive into backends.py

---

networkx/algorithms/isomorphism/isomorph.py
networkx/algorithms/isomorphism/tests/test_isomorphism.py

This is a left-over idea from the summit that I thought I'd write up for further discussion!
NetworkX has a function `could_be_isomorphic` to check various properties of two graphs to determine whether or not they, well, could be isomorphic. `could_be_isomorphic` checks three properties: 1) degree sequences, 2) sequences of triangles, and 3) sequences of number-of-cliques.
There also exist two other functions, `fast_could_be_isomorphic` and `faster_could_be_isomorphic` that check degree+triangles and just degree, respectively. IMO, the name of these functions doesn't do a whole lot to illuminate what they are checking. There is also a lot of code duplication between these three functions as all of them check degree, two check triangles, etc.
Therefore I thought it might be worth trying to …

Consolidate could_be_isomorphic

---

networkx/algorithms/centrality/betweenness.py
networkx/algorithms/centrality/tests/test_betweenness_centrality.py

This is a follow up to #7908 and specifically @dschult's question from https://github.com/networkx/networkx/pull/7908#pullrequestreview-2711295366:
> The case with k < n and endpoints is False still confuses me. It seems like the number of valid (s, t) node pairs that could have a path through v where s != t should depend on whether node v was in the sample or not in the sample. The largest possible count for nodes in the sample (when endpoints is False) is (k-1)*(n-2), but for nodes not in the sample the count can be k*(n-2). Why are we using k*(n-2) for all the nodes?
After investigating this, I think source nodes and non-source nodes do indeed need to scale differently when `k` is given and `endpoints=False`.
I added a test that exercises this. I don't fully grok the test results, but …

Fix BC scaling for source nodes with k and endpoints=False

---

networkx/algorithms/isomorphism/tests/test_tree_isomorphism.py
networkx/algorithms/isomorphism/tree_isomorphism.py

I was looking at tree isomorphism logic when reviewing https://github.com/networkx/networkx/pull/7929 and realized implementation was using a recursive approach to compute the node mapping. This can be problematic with deep trees because it can lead to `RecursionError` exceptions.
@rossbar since you are already working on this module please let me know if you are already working on this particular improvement. Happy to drop this PR!
This PR refactors the `generate_isomorphism` function to replace its recursive implementation with an iterative approach using an explicit stack. The change is intended to prevent potential stack overflow issues when dealing with deeply nested trees (e.g., long path graphs).  
- Converted `generate_isomorphism` from a recursive function to an iterative one …

Improving rooted_tree_isomorphism for deep trees

---

networkx/algorithms/isomorphism/tests/test_tree_isomorphism.py

Something I noticed while reviewing other related work.
The `test_tree_isomorphism.py` bit of the test suite had a lot of helper functions that IMO made the tests harder to follow than they could be.
The biggest change hereis captured in the first commit 1f3b75f which replaces the custom isomorphism checking functionality with a simpler check: essential relabel the nodes with the given isomorphism and check `nx.utils.graphs_equal`.
The other big-ish change is refactoring the two tests which check *all* nonisomorphic trees for various numbers of nodes. There are two tests:
- one that tests that all nonisomorphic trees are isomorphic with themselves, with their nodes
relabeled, and
- one that tests that all pairs of nonisomorphic trees are not isomorphic with one another.
In practice I …

Some light refactoring to make the tree isomorphism tests more readable

---

networkx/algorithms/distance_measures.py
networkx/algorithms/tests/test_distance_measures.py

Did a random sample comparison of the output of `nx.diameter` function when passing `usebounds=True` and I ended up finding instances where both algorithms don't match when they are expected to compute the same result (See https://github.com/networkx/networkx/issues/7948)
```python
def test_ale(self):
import numpy as np
seed = 1
rng = np.random.RandomState(seed=seed)
G = nx.erdos_renyi_graph(10, 0.25, seed=seed)
for u, v in G.edges():
G[u][v]['w'] = rng.randint(0, 1000)
assert nx.diameter(G, weight='w') == nx.diameter(G, usebounds=True, weight='w')
```
Besides this issue, we should incorporate these types of randomized tests for certain algorithms/optimizations where they apply.
```
def test_ale(self):
import numpy as np
seed = 1
rng = np.random.RandomState(seed=seed)
G = …
```

Fixing nx.diameter inconsistent results with usebounds=True

---

networkx/drawing/layout.py

As the docstring suggests, the argument should be `distributed_attraction` instead of `distributed_action`.

Fix typo in forceatlas2_layout

---

doc/reference/algorithms/tournament.rst
networkx/algorithms/tournament.py

Also adding to `__all__`, which doesn't have much of an effect since everything is kept within `tournament` module anyway.
It's a shame to keep such a pretty doc from the world!

Add `tournament_matrix` to docs

---

networkx/algorithms/similarity.py

Something I came across while looking at more linting outputs. I think the `debug_print` statement should definitely be removed - if other folks want to keep the comments the commented asserts I think that's fine!

MAINT: rm debug print from similarity module.

---

networkx/algorithms/flow/utils.py
networkx/algorithms/minors/contraction.py
networkx/generators/spectral_graph_forge.py
networkx/utils/backends.py

These changes are intended to unblock #7902 (CC @rossbar) and to try to make dispatch tests more maintainable (see #7904).
This actually took _a lot_ of experimentation, and I suspect there's even more debt we could pay off, but I think this is a nice increment. To summarize:
We are more methodological about when we create two different arguments to run with the backend and with networkx. As before, we run with networkx and compare results when the _result_ is a graph. In this case, we check that the output graphs match _exactly_, and return the networkx graph in order to preserve iteration order (b/c some tests are sensitive). We are more careful about doing this when functions _mutate_ input graphs--we now ensure that input graphs are _different_ when calling the function with both the …

Improve special cases in dispatch testing (paying off tech debt)

---

networkx/convert_matrix.py

This is a single line modification - it just removes a no longer used import.

Remove unused import in convert_matrix.py (networkx.utils.not_implemented_for)

---

examples/drawing/plot_clusters.py

The `superpos` positions should be computed using `supergraph`, not the original graph `G`.

bugfix: use supergraph to compute superpos in plot_clusters example

---

networkx/algorithms/bipartite/edgelist.py
networkx/readwrite/adjlist.py
networkx/readwrite/edgelist.py
networkx/readwrite/gml.py
networkx/readwrite/multiline_adjlist.py
networkx/readwrite/pajek.py

When running tests in parallel, the test filenames should be unique or they overwrite each other.
Fixes #7995 
hopefully... :)  But for sure this could be a problem anyway.
There was talk about making these all tempfile examples, but the point of the examples is to show the various ways you can save to files -- so we would lose the point of the examples. There still might be a solution there, but I'm putting this out there as a way to avoid the intermittent failures.

Make test file names unique to be threadsafe

---

networkx/algorithms/similarity.py

Follow-up to #7832 
Incorporates @Schefflera-Arboricola 's suggestions and then extends them further. The main changes are:
1. The original wording in the first example implied that `generate_random_paths` is a function. I've reworded to make it clear that it's a generator, and extended the example to illustrate this more clearly.
2. Seeded the second example per @Schefflera-Arboricola 's suggestion, but also changed the example so that there is at least one output path that *doesn't* contain node 0 to better illustrate the usage of `index_map`.

More `random_paths` docstring improvements

---

networkx/algorithms/similarity.py
networkx/algorithms/tests/test_similarity.py

Small modification to allow the user to specify an initial node to begin all walks from.

Added "initial_node" param to generate_random_paths() to allow a starting node to be specified for generated walks

---

networkx/algorithms/traversal/breadth_first_search.py
networkx/algorithms/traversal/tests/test_bfs.py

This addresses the issue reported in #8009.
It makes sense to me to ensure the function works correctly for generators as well; especially since the fix is as simple as this.
I also thought it was more reasonable to gracefully handle duplicate nodes in the `sources` argument; at every depth other than 0, nodes never appear multiple times (because of the `visited` set), and I see no convincing reason to have the sources be handled any differently.
List of changes:
* Avoid silent failure when `sources` is a generator
* Only handle duplicate nodes once
* Add test cases where `sources` is a generator and list with duplicate elements
* Minor clarifications in docstring
Fixes gh-8009.

Fix behavior for iterable `sources` argument in `bfs_layers`

---

networkx/algorithms/components/connected.py
networkx/algorithms/components/weakly_connected.py

This PR introduces lightweight optimizations to several connectivity-checking functions by adding early returns based on simple graph invariants. These heuristics help short-circuit computation in cases where connectivity can be ruled out without traversing the graph.
- Adjusted BFS calls in `connected_components` and `weakly_connected_components` to reduce traversal overhead when many nodes have already been seen.
These changes preserve correctness while reducing unnecessary work, especially on dense graphs.
The optimization shows the most significant gains on disconnected graphs with large components, achieving up to a 367× speed-up for n=1000. This case is artificially generated to make current version need to visit the same nodes in a connected component multiple times. These are the …

Speed up `connected_components` and `weakly_connected_components`

---

networkx/algorithms/tests/test_similarity.py

I was late reviewing #8002 (apologies!) but did eventually get a chance to look at it and just turned my comments into a PR :). Not at all important, just a minor followup!
There are two main proposals:
- 98d5074 refactors the test added in #8002 to check properties of the generated paths (i.e. that they all start with `source`, rather than doing an exact-match on a seeded example. IMO this is a minor improvement as it's slightly more flexible and removes the dependence of the test on the random number system (in principle also increasing robustness). It's clear that the test was inspired by the one below it, so it made perfect sense but I thought it was a nice opportunity to add some flexibility!
- 558f4d2 adds an additional test for when the `source` is not in `G`.

Minor follow-up to gh-8002 tests

---

.gitignore

When running the `make` command to build the docs locally, the file `sg_execution_times.rst` is created. I've added it to the `.gitignore` for convenience/QoL.

Add sg_execution_times.rst to gitignore

---

networkx/drawing/nx_pydot.py

Closes #8026 
I think it's relatively straightforward to deal with the signature difference between pydot v3 and v4 for `get_strict`.
My personal vote would be to support both for nx 3.5, then bump the pydot minimum version to 4.0 in nx 3.6.

Support both pydot v3 and pydot v4.

---

doc/reference/backends.rst

This PR is a follow-up from discussion https://github.com/networkx/networkx/issues/8030. It makes two changes to the backend interface documentation:
1. Fixes a typo in the description of the BackendInterface object
2. Clarifies backend graph interface requirements: Adds an explanation that backend graph objects are required to implement the `is_directed()` and `is_multigraph()` methods and its relation with `@not_implemented_for` decorator.

Clarifying backend graph class interface is_directed+is_multigraph

---

LICENSE.txt
README.rst

Changes license formatting to match the 3-clause BSD pattern.
Updates copyright license years for 2025.

Update copyright license years

---

doc/reference/backends.rst
doc/release/release_dev.rst
networkx/drawing/nx_pylab.py
networkx/readwrite/graph6.py

A little activity from my recent flight without internet. I'm loathe to add to the PR queue but it might be nice to have a clean doc build for the release (though certainly not critical).
In principle we could add a CI job to fail on sphinx warnings to prevent these from getting in. Personally, I don't think these should be blockers for PRs so my vote would be to keep things the way they are. Open to other opinions though!

Fix all sphinx build warnings

---

networkx/algorithms/isomorphism/isomorphvf2.py
networkx/algorithms/isomorphism/tests/test_isomorphvf2.py

Fixes #7964.
Check that both graphs have the correct directedness in `(Multi-)(Di-)GraphMatcher` initialization.
@dschult, you mentioned switching to a function-oriented interface in the linked issue. Is this something that has been discussed previously/is there some kind of consensus on what that should look like? I feel the graph matching subsection of the codebase could use a revamp (there are still untouched lines of code from 2007 in there! :) ). I'd give it a shot, but it would entail some significant, opinionated API changes, and I'm curious what people think about that.

Enforce correct graph types for graph matchers

---

networkx/generators/expanders.py
networkx/generators/tests/test_expanders.py

Fixes gh-8046.
This adds an explicit seed to the `maybe_regular_expander` and `random_regular_expander_graph` (is there a reason for the inconsistency in appending `_graph` to generator names?) tests which avoids stochastic failures when the maximum number of iterations gets exceeded.
Since this is a simple fix and the linked issue has a discussion surrounding _how_ it should be fixed, this can also be left as a good first issue imo.

Fix intermittent test failures in expander graph generator tests

---

networkx/algorithms/isomorphism/tree_isomorphism.py

A few more minor improvements while working my way through the tree_isomorphism module (fun!)
There are two main bits in this PR where I've attempted to replace custom code with built-in functions:
1. `tree_isomorphism` essentially implements the `faster_could_be_isomorphic` check before it actually begins searching for tree isomorphisms. I've replaced it with an explicit call to `faster_could_be_isomorphic`.
2. `rooted_tree_isomorphism` relied on two helper functions `assign_levels` and `group_by_levels` to set up the algorithm. Upon closer inspection, I think these two functions are equivalent to grouping nodes by their shortest path length to the root node - so I've replaced them with the 3-liner to do this grouping (using `defaultdict(list)`). Technically these functions are "public", …

Refactor tree_isomorphism to improve code reuse and readability

---

networkx/algorithms/dag.py
networkx/algorithms/tests/test_dag.py

This is a minimal fix for `is_aperiodic`. See #8021 .
Description: The original logic of `is_aperiodic` can be used to calculate period of a graph, so it is moved to `_period`, with an extra check to make sure it do not go outside the current strongly connected component. `is_aperiodic` now simply returns `_period(G) == 1`.

A minimal fix for `is_aperiodic`

---

networkx/drawing/layout.py
networkx/drawing/tests/test_layout.py

Dear NetworkX maintainers,
I am Hiroki Hamaguchi, a contributor to NetworkX and the author of [this previous pull request](https://github.com/networkx/networkx/pull/7889).
I sincerely apologize, but I have discovered a bug introduced in that PR. Specifically, when `method="auto"` is specified, the `nx.spring_layout` function does not use the new `_energy_fruchterman_reingold` function as intended.
The fix is trivial, and I would appreciate it if you could kindly review and merge the proposed correction.
Thank you very much for your time and consideration.
---
**Added based on discussion (details in comments below)**
I believe the try/except block [using ValueError as a signal to try a different branch of code] is unnecessary.
A ValueError can occur in the following situations:
pos is a …

fix bug of _sparse_fruchterman_reingold and remove try/except idiom

---

networkx/algorithms/centrality/betweenness.py
networkx/algorithms/shortest_paths/astar.py
networkx/algorithms/shortest_paths/weighted.py
networkx/algorithms/simple_paths.py
networkx/algorithms/tree/mst.py
networkx/utils/heaps.py

There is a consistent pattern in the codebase where `heappush` and `heappop` are renamed to `push` and `pop` in the functions where they are used. IMO this indirection makes the code less readable; especially in diffs, where the renaming often occurs in one of the unchanged bits of code and is therefore not immediately obvious.
This PR replaces all of the `push = heappush` and `pop = heappop` with just calling `heappush` and `heappop` directly. IMO this is a (very minor) readability improvement[^1]; however, it's so minor that I'm also happy just to close if others think it's not worth the code churn!
[^1]: explicit is better than implicit

STY: Rm local variable remapping of heappush and heappop.

---

networkx/algorithms/isomorphism/ismags.py
networkx/algorithms/isomorphism/tests/test_ismags.py

Fixes #4915.
Paraphrasing the original issue (#4915): there is an error in the ISMAGS implementation. For some specific cases it trips an `AssertionError`. This happens for graphs of this shape, where all nodes and edges are equivalent.
```
5 - 4 \     / 12 - 13
0 - 3
9 - 8 /     \ 16 - 17
```
During symmetry detection/analysis, nodes 0 and 3 are coupled and no longer equivalent. At that point, {4, 8} and {12, 16} are no longer equivalent, and neither are {5, 9} and {13, 17}. Coupling 4 then refining results in 5 and 9 getting their own partitions, but not 13 and 17.
This results in tripping the following `assert`: https://github.com/networkx/networkx/blob/679191810fc962e282b606622c90355f2e6f58ad/networkx/algorithms/isomorphism/ismags.py#L1090-L1092
The good news is that this case cannot …

Fix edge case in ISMAGS symmetry detection

---

networkx/algorithms/tests/test_matching.py

A few test suite improvements from having read the code while reviewing #8062.
This PR essentially contains 3 unrelated proposals, and might be easier to digest commit-by-commit:
- 942193a is the big one: it removes a layer of indirection in the tests by getting rid of the consistent calls to `matching_dict_to_set` for munging the "expected" answers. IMO it's much more straightforward to compare to the expected edge sets explicitly. This is possible because `nx.utils.edges_equal` already handles arbitrary edge ordering, so there's no need to do so twice.
- af4aef3 converts all the instances of `pytest.raises` from function calls to the context manager pattern, and adds the `match=` kwarg better ensure that the expected exception is being raised.
- Finally, 2ba9698 and e01171d factor out …

Minor refactor to cleanup/improve matching test suite

---

networkx/algorithms/covering.py

Came across this while hunting down test failures in #8074.

Fix typo in `min_edge_cover` docstring

---

networkx/algorithms/matching.py
networkx/algorithms/tests/test_matching.py

The current `min_weight_matching` claims to compute a minimum-weight maximal matching, but it is actually computing a minimum-weighted maximum-cardinality matching.
The minimum-weight maximal matching, which it claims to solve, is NP-hard. See the [paper](https://arxiv.org/abs/1811.08506):
> As we know since 1961, all natural variants of perfect matchings and maximum matchings can be found in polynomial time, even in general graphs. Here we study a different problem — Minimum Maximal Matching (MMM). The task is — given graph G, to find an inclusion-wise maximal matching M with the smallest cardinality (or weight in the weighted version).
>
> The MMM problem was studied as early as 1980, when Yannakakis and Gavril showed, that it is NP-hard even in some restricted cases.
Changes include:
- …

Fix `min_weight_matching`

---

networkx/drawing/nx_pylab.py

I'm trying out `nx.display` in an nx-guide I'm working on and noticed that some attributes are printed during drawing.

Rm extraneous print from nx.display.

---

networkx/drawing/tests/test_image_comparison_pylab_mpl.py
networkx/drawing/tests/test_pylab.py

Alternative to #8094 for closing #8090 . The main difference between the two is that this PR leaves the CI footprint (i.e. which workflows run the mpl tests) unchanged.
All this PR does is move the 6 `mpl_image_comparison` tests out of `nx_pylab` to their own test file. The "fixing CI" part is then just adding `pytest.importorskip("pytest_mpl")` to the new test file.
Even aside from the pytest/plugin dependency issues, I think moving these tests to their own file makes sense as they are quite different from all of the other nx_pylab tests.

Refactor image comparison tests.

---

.github/workflows/test.yml
networkx/generators/lattice.py

Inspired by #8091 - adds Python 3.14 to the testing matrix in CI. Specifically, it adds 3.14 testing *only* to the `base` jobs, i.e. the ones without dependencies. This is to avoid conflicts for default dependencies that do not yet supply 3.14 wheels (it looks like only NumPy does so at this point).
Also includes a fix for #8091 which fails on Pythoon 3.14. I'm happy to break this out in a follow-up PR if folks prefer to keep the CI config/code changes separate.
Fizes #8091
Finally - I arbitrarily chose to include 3.14 both with and without free-threaded support (the `3.14t-dev`). In principle this shouldn't affect networkx at all (i.e. networkx without dependencies) so we could remove it.

Add Python 3.14 to testing matrix

---

.github/workflows/deploy-docs.yml

I'm not sure what the big-scale implications are of changing this. So please check if it makes sense.
nx-parallel is used when deploying the docs in a yml file that runs with Python 3.11. We just shifted the python version requirements of nx-parallel to Python 3.12+ so we could use `itertools.batched` (which was added in 3.12).  We could of course write our own version of that tools and include it in nx-parallel and then remove it again after the Python 3.14 release.  But we'd prefer to just up  the requirements-- it is unlikely we will have a release of nx-parallel before October anyway.
Is there a reason the docs are deployed using Python 3.11?
We are using the latest github `main` branch for nx-parallel and nx-cugraph when building our docs. Is it OK to make the docs with a newer …

Update deploy-docs yml to use Python 3.12 when deploying the docs

---

.github/workflows/deploy-docs.yml

With #8101 getting closed, this pulls out the change to the extra name in the doc deploy action.
This fixes the following warning/error hidden in the logs.
> WARNING: networkx 3.5 does not provide the extra 'tests'

Fix typo in extra name

---

pyproject.toml

While building the wheel, the warning pops up multiple times. Hopefully the setuptools bump shouldn't be consequential.

MAINT: Support PEP 639 for license metadata

---

networkx/drawing/layout.py

This PR replaces `@np_random_state(10)` with `@np_random_state("seed")` in the `spring_layout` function to ensure correct handling of the seed argument. Using a positional index assumes that seed is always passed as the 11th positional argument, which is fragile and fails when seed is passed as a keyword (the common case).
By switching to the argument name "seed", we make the decorator robust to both positional and keyword usage, aligning with best practices and preventing subtle bugs in layout reproducibility.
We ran into an issue when parallelizing our tests with networks.

pass numpy seed by value not index

---

networkx/algorithms/cuts.py

This PR improves the documentation for the `boundary_expansion` function by:
- Adding practical examples.
- Clarifying the calculation and the concept of node boundary.
- Adding a note about the potential generalization for two sets (related to the TODO).
- Formatting the documentation to follow NetworkX standards.

Improved documentation for boundary_expansion function

---

networkx/algorithms/link_analysis/hits_alg.py

This is a small PR to address a couple of issues I found in the references section of the HITS algorithm documentation.
1. The link for the first reference was broken. I've updated it to point to a live webpage with a pdf of the paper.
2. The link for the second reference was not being rendered by sphinx as a url. I reordered it with the doi information to get sphinx to recognize it as a link.
3. Lastly, I switch both urls to use `https`.

Fix issues with urls in HITS reference docs

---

networkx/algorithms/centrality/harmonic.py

In the current implementation of harmonic centrality, we compute `nbunch.intersection(dist)` for every source node. This creates a temporary set at each iteration, which is unnecessary and slightly inefficient since we can achieve the same logic with a conditional check during iteration over `dist.items()`.
I replaced:
```py
for v in sources:
dist = spl(v)
for u in nbunch.intersection(dist):
d = dist[u]
if d == 0:  # handle u == v and edges with 0 weight
continue
centrality[v if transposed else u] += 1 / d
```
with:
```py
for v in sources:
dist = spl(v)
for u, d_uv in dist.items():
if u in nbunch and d_uv != 0:
centrality[v if transposed else u] += 1 / d_uv
```
I ran the following benchmark command to compare performance:
```sh
asv compare f750ce5b a9371f78
```
[EDIT]: 
The most notable …

Optimise harmonic centrality

---

doc/reference/backends.rst
networkx/utils/backends.py

In #8115, a user encountered an error when a backend name was not a valid Python identifier.
@amcandio suggested we guard against this https://github.com/networkx/networkx/issues/8115#issuecomment-3092681130.
Notably, it's possible for users to encounter this when e.g. `networkx.egg-info/entry_points.txt` file has an *old* entry for `nx-loopback` instead of `nx_loopback`, as may have happened in #8115.
This PR ignores backends that are not valid identifiers, displays a warning when this happens, and updates documentation to indicate that backends must be valid Python identifiers.
Instead of checking when creating the config as suggested in https://github.com/networkx/networkx/issues/8115#issuecomment-3094631390, this PR checks when loading the entry points for backends.
If an invalidly …

Ensure that backend names are valid Python identifiers

---

benchmarks/benchmarks/benchmark_shortest_path.py

Adds another benchmark for #8023 
One of the concerns I expressed there (after reviewing the original benchmark results) was degradation in performance when computing shortest paths over many small graphs. Therefore, I decided to add an explicit benchmark for this case! The idea is to compute dijkstra multisource over all connected graphs of 7 nodes (drawn from `graph_atlas_g`) with various weighting schemes.
The good news: according to these benchmarks, there is no performance degradation in #8023 for the looping-over-many-small-graphs case!

Add benchmarks for multisrc_dijkstra over many small graphs.

---

networkx/generators/classic.py
networkx/generators/tests/test_classic.py

While working on #8148, directed star graphs would have been useful to easily created directed graphs with many "leaf nodes" in their DFS tree. This PR implements adds that possibility and adds a test for it.

feat: add directed star graph

---

networkx/algorithms/tests/test_link_prediction.py

This PR ensures that exceptions are raised inside the `pytest.raises` block, so that pytest can catch them instead of the exception being raised *before* the test starts monitoring for it.
In nx-parallel, the `_apply_prediction` function is run across multiple cores. Unlike NetworkX’s standard implementation, we cannot return a generator expression because generators are not picklable and cannot be transferred between processes — that is, we cannot return the generator from the child process back to the parent process.
To handle this, `_apply_prediction` returns a fully consumed chunk instead of a generator expression.
In the test below, if `self.func` raises an exception, it means the exception occurs when the function is called, not when the result is consumed:
```py
G = …
```

Use `pytest.raises` as a context

---

networkx/algorithms/regular.py
networkx/algorithms/tests/test_regular.py

This PR adds a small performance improvement, allowing `is_regular` to avoid checking all in-/outdegrees when a directed graph has nodes with different out-/indegrees. I've also slightly tweaked the docstring and added/refactored a few tests to check everything works as it should.

enh: short-circuit in `is_regular` for directed graphs

---

networkx/algorithms/planarity.py

Fixes #8185
Trying to `pickle.loads(pickle.dumps(PlanarEmbedding()))` raises: AttributeError: 'PlanarEmbedding' object has no attribute '__forbidden'

fix: resolve failure to pickle.loads(pickle.dumps(PlanarEmbedding()))

---

tools/generate_requirements.py

With the minimum supported Python version being 3.11, this is no longer necessary.

MAINT: remove `try except` for `tomllib` in `generate_requirements`

---

networkx/algorithms/shortest_paths/weighted.py

This is a completely cosmetic change, i.e. a proposal to rename some internal variables. Just something I noticed while reviewing #8206. There are two independent proposals in this PR:
1. Rename `dir` -> `direction` (32ba3ff). This is more descriptive *and* has the added benefit that it doesn't mask the builtin `dir` (which is extra annoying while reading due to syntax highlighting)
2. Rename `neighs` to `neighbors` (ee306b7). IMO this goes especially well with change 1, which transforms `neighs[dir]` to `neighbors[direction]`.
Please feel free to consider these separately - happy to back out the second if desired (I feel more strongly about `dir`!)

STY: Variable rename proposal in bidirectional_dijkstra

---

networkx/algorithms/clique.py
networkx/algorithms/tests/test_clique.py

Fixes #8209.
This PR adds the `not_implemented_for("directed")` decorator to `nx.find_cliques_recursive`, similarly to `nx.find_cliques`. It also adds a test (for both functions) that directed graphs now raise `nx.NetworkXNotImplemented`.

BUG: Raise on directed graphs in `nx.find_cliques_recursive`

---

doc/reference/algorithms/shortest_paths.rst

After working on https://github.com/networkx/networkx/pull/8169 I realized that the whole Shortest Path section lacked some introduction and context.
In this PR I extend the docs with some definitions, examples and time-complexity of the different supported algorithms.
Follow-up sections I was thinking we can add:
- Notes on negative weights and cylces
- Translating path from list of nodes into list of edges

Adding shortest-paths documentation

---

networkx/generators/tests/test_cographs.py

Towards #8223.
This test would sometimes fail to hit one of these branches.
https://github.com/networkx/networkx/blob/main/networkx/generators/cographs.py#L63-L66
Adding a fixed seed of 42 resolves the spurious coverage misses.

TST: add seed for `random_cograph` test

---

README.rst

While we're looking at badges - it looks to me like the testing badge on the README has a broken link. This will hopefully fix it!

Update links for broken testing badge in README.

---

networkx/algorithms/minors/contraction.py

Adds a more extensive examples section to contracted_nodes to highlight behavior in a myriad of cases:
- Highlights the handling of contracted nodes, the `"contraction"` attribute, and any edges that result from the contraction (and their attributes). Includes explicit examples for both non-multigraphs and multigraphs.
- More detail on `self_loops` and how self-loops in the original graph are handled by contraction
Closes #7781
Closes #7660

DOC: Add examples to contracted_nodes.

---

networkx/drawing/tests/test_pylab.py

Towards #8223.
This PR is an attempt to find out more about why the `draw` method of `CurvedArrowText` sometimes gets hit, and sometimes doesn't.
https://github.com/networkx/networkx/blob/6fad2d34112d5d860ef9f3dd997936c77d454b09/networkx/drawing/nx_pylab.py#L248-L254
In #8223 for example, running only the non-`slow` tests covered these lines, whereas running all tests didn't (as such, I guess this doesn't strictly belong in #8223, but it'd be good to fix this anyways).
I can confirm this is _not_ an issue with `pytest-cov`; adding an `assert False` in the `draw` method sometimes fails, and sometimes doesn't. Perhaps even more surprisingly, it's not immediately obvious to me where the randomness is coming from, here. `draw_planar` is one of the functions for which we hit the failing …

TST: ensure determinism in `nx_pylab` drawing tests

---

networkx/algorithms/shortest_paths/tests/test_weighted.py
networkx/algorithms/shortest_paths/weighted.py

Closes #8223.
The branch
https://github.com/networkx/networkx/blob/e8a8c1944440bd8cf216381366df40a8210a0743/networkx/algorithms/shortest_paths/weighted.py#L2079-L2081
was not reliably being entered because iterating over `relabeled` is not deterministic.
This PR adds a test that guarantees the branch would have been entered/the set difference is doing something.

TST: test `topo_sort` skips visited nodes in `goldberg_radzik`

---

doc/developer/deprecations.rst
doc/reference/algorithms/dag.rst
networkx/algorithms/dag.py
networkx/algorithms/tests/test_dag.py
networkx/conftest.py

With the NX 3.6 release on the horizon, I wanted to make sure we get the scheduled deprication expirations in. This is the first of 2 removals slated for 3.6: removing the `compute_v_structures` fn.

Expire deprecation of compute_v_structures.

---

doc/developer/deprecations.rst
examples/external/javascript_force.py
networkx/conftest.py
networkx/readwrite/json_graph/node_link.py
networkx/readwrite/json_graph/tests/test_node_link.py

... and the 2nd of 2 deprication expirations for 3.6 - see also #8281 
This one's a little trickier as it involves removing a kwarg named `link` from `node_link_graph` and `node_link_data`, and replacing it with the more NetworkX-y `edges`. Note that most of the changes to the test suite involve removing a context manager that was ensuring a `FutureWarning` was being raised - the underlying tested code remains the same.

Expire deprecation of link kwarg in node_link fns.

---

doc/reference/drawing.rst
examples/external/plot_iplotx.py
pyproject.toml
requirements/example.txt

After previous communication with @dschult and @tacaswell , the `iplotx` library (https://iplotx.readthedocs.org) was recently developed (by myself) to offer seamless network visualisation from both NetworkX and igraph:
- working with native data structures, with no need for file export/import
- expanding the range of styling options compared to internal NetworkX functions
- using well behaved matplotlib artists that can be animated or edited after the fact
- ensuring correct behaviour across backends, DPI resolutions, zoom/pan operations
This draft PR proposes to add specific mentions and examples of `iplotx` into NetworkX's documentation to let users know that option for network visualisation is available.
For starters, I added a mention in the drawing reference docs and an example in …

Add iplotx to network drawing documentation

---

doc/reference/algorithms/shortest_paths.rst
networkx/algorithms/centrality/betweenness.py
networkx/algorithms/centrality/betweenness_subset.py

A couple new sphinx errors from a detailed look at the build logs.
The first is related to the whole mess of how rst handles headers. It didn't like `~~~~` as that hadn't been used yet (and therefore was assigned `h4`) while the preceding header was an `h1`. There are basically two options - force this to an `h1` (which I opted for in 8d28fe9), or change this to an `h3` (which maps to `^^^^^`) then modify the Example heading below to use `~~~~~`.
The second is related to missing references after the betweenness centrality docstring updates in #8256 .

Fix sphinx build errors

---

CONTRIBUTING.rst
doc/developer/deprecations.rst

A minor doc refactor that reorganizes where the deprecation procedure is found. Currently it lives in [step 7 of the development workflow in the contributor guide](https://networkx.org/documentation/latest/developer/contribute.html#development-workflow). I have trouble finding it every time I look for it.
This PR moves it to the [Deprecations](https://networkx.org/documentation/latest/developer/deprecations.html) article which has a top-level heading in the developer guide (see the left side-bar on the linked page). Placing it here will also provide an anchor link to the section, making it easier to refer/link to elsewhere.
Note I didn't change the text of the deprecation procedure at all, just where it lives!

DOC: Move deprecation procedure from contributing->dev guide.

---

examples/algorithms/plot_metric_closure.py

This PR updates the new gallery example for the metric closure.
- Clarifies the definition of the metric closure for both weighted and unweighted graphs:
- For weighted graphs, edge weights in the closure correspond to the minimum total
weight along any path between two nodes.
- For unweighted graphs, all edges are assumed to have weight 1, so closure weights
correspond to the minimum number of hops.
- Adjusts the example to demonstrate the *unweighted* version using
:func:`networkx.all_pairs_shortest_path_length`.
- Notes in the docstring that the weighted version can be obtained by using
:func:`networkx.all_pairs_dijkstra_path_length` instead.
The goal is to reduce potential confusion around whether "shortest path" refers to hop
count or weighted distance, and to provide a clear …

DOC: add gallery example for metric_closure

---

networkx/generators/small.py

Minor doc improvement based on my own inability to remember all 5 Platonic solids off the top of my head!
Adds a `See Also` section to each of the 5 Platonic graphs linking to the other 4.

Cross-link Platonic graphs in See Also section

---

networkx/generators/lattice.py

Very similar to #8307 - I was recently looking at the 2D grid for building mazes and thought it would be useful to cross-link to the other lattice graphs in each others' docstrings. For my particular use-case I was interested in all the available 2D lattice graphs so I grouped the See Also section. I don't feel strongly about this though so if folks prefer just a general listing (with no grouping) I'd be perfectly happy with that too!

Add seealso crosslinks between lattice graphs.
